### ISSUE TITLE
Adapter is no longer starting after debug session

### ISSUE THREAD

**Issue by kuumaur** [ioBroker/ioBroker.zigbee#1038]
Hi Guys,
i had to shutdown iobroker.zigbee and iobroker itself for a debuggung session with zigbee2mqtt.
I have installed zigbee2mqtt and start with the debugging. After that a stopped zigbee2mqtt and started iobroker.
(yes, that was all on the same machine)
Now the adapter iobroker.zigbee adapter is no longer starting, even after reboot.
What can i do to bring the adapter back to life?

zigbee.0 | 2021-03-21 15:59:19.472 | warn | (873) Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
zigbee.0 | 2021-03-21 15:59:19.472 | info | (873) terminating
zigbee.0 | 2021-03-21 15:59:19.472 | warn | (873) Failed to stop zigbee during startup
zigbee.0 | 2021-03-21 15:59:19.471 | info | (873) Zigbee: disabling joining new devices.
zigbee.0 | 2021-03-21 15:59:19.470 | info | (873) cleaned everything up...
zigbee.0 | 2021-03-21 15:59:19.462 | error | (873) Cannot read property 'getEntries' of null
zigbee.0 | 2021-03-21 15:59:19.462 | error | (873) TypeError: Cannot read property 'getEntries' of null     at Function.loadFromDatabaseIfNecessary (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/device.js:220:55)     at Functi
zigbee.0 | 2021-03-21 15:59:19.461 | error | (873) unhandled promise rejection: Cannot read property 'getEntries' of null
zigbee.0 | 2021-03-21 15:59:19.461 | error | (873)  Unhandled promise rejection. This error originated either by throwing  inside of an async function without a catch block, or by rejecting a  promise which was not handled with .catch().
zigbee.0 | 2021-03-21 15:58:51.271 | info | (873) Installed Version: iobroker.zigbee@1.4.4
zigbee.0 | 2021-03-21 15:58:51.077 | info | (873) Starting Zigbee  npm ...
zigbee.0 | 2021-03-21 15:58:51.029 | info | (873) starting. Version 1.4.4 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.21.0, js-controller: 3.2.16
zigbee.0 | 2021-03-21 15:58:19.473 | warn | (854) Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee.0 | 2021-03-21 15:58:19.473 | info | (854) terminating
zigbee.0 | 2021-03-21 15:58:19.472 | warn | (854) Failed to stop zigbee during startup
zigbee.0 | 2021-03-21 15:58:19.471 | info | (854) Zigbee: disabling joining new devices.
zigbee.0 | 2021-03-21 15:58:19.470 | info | (854) cleaned everything up...
zigbee.0 | 2021-03-21 15:58:19.465 | error | (854) Cannot read property 'getEntries' of null
zigbee.0 | 2021-03-21 15:58:19.465 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
zigbee.0 | 2021-03-21 15:58:19.465 | error | at StatesController.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:158:14)
zigbee.0 | 2021-03-21 15:58:19.465 | error | at StatesController.emit (events.js:314:20)
zigbee.0 | 2021-03-21 15:58:19.465 | error | at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:419:48)
zigbee.0 | 2021-03-21 15:58:19.465 | error | at ZigbeeController.resolveEntity (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:239:52)
zigbee.0 | 2021-03-21 15:58:19.465 | error | at Controller.getDeviceByIeeeAddr (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/controller.js:285:31)
zigbee.0 | 2021-03-21 15:58:19.465 | error | at Function.byIeeeAddr (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/device.js:228:16)
zigbee.0 | 2021-03-21 15:58:19.465 | error | at Function.loadFromDatabaseIfNecessary (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/device.js:220:55)
zigbee.0 | 2021-03-21 15:58:19.465 | error | (854) TypeError: Cannot read property 'getEntries' of null
zigbee.0 | 2021-03-21 15:58:19.464 | error | (854) unhandled promise rejection: Cannot read property 'getEntries' of null
zigbee.0 | 2021-03-21 15:58:19.463 | error | (854) Unhandled promise rejection. This error originated either by  throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-03-21 15:57:51.563 | info | (854) Installed Version: iobroker.zigbee@1.4.4
zigbee.0 | 2021-03-21 15:57:51.368 | info | (854) Starting Zigbee  npm ...
zigbee.0 | 2021-03-21 15:57:51.315 | info | (854) starting. Version 1.4.4 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.21.0, js-controller: 3.2.16
zigbee.0 | 2021-03-21 15:57:19.474 | warn | (554) Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee.0 | 2021-03-21 15:57:19.473 | info | (554) terminating
zigbee.0 | 2021-03-21 15:57:19.473 | warn | (554) Failed to stop zigbee during startup
zigbee.0 | 2021-03-21 15:57:19.472 | info | (554) Zigbee: disabling joining new devices.
zigbee.0 | 2021-03-21 15:57:19.472 | info | (554) cleaned everything up...
zigbee.0 | 2021-03-21 15:57:19.470 | error | (554) Cannot read property 'mapped' of undefined
zigbee.0 | 2021-03-21 15:57:19.470 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
zigbee.0 | 2021-03-21 15:57:19.470 | error | at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:421:36)
zigbee.0 | 2021-03-21 15:57:19.470 | error | (554) TypeError: Cannot read property 'mapped' of undefined
zigbee.0 | 2021-03-21 15:57:19.470 | error | (554) unhandled promise rejection: Cannot read property 'mapped' of undefined
zigbee.0 | 2021-03-21 15:57:19.470 | error | (554) Unhandled promise rejection. This error originated either by  throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-03-21 15:57:19.459 | error | (554) Cannot read property 'getEntries' of null
zigbee.0 | 2021-03-21 15:57:19.459 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
zigbee.0 | 2021-03-21 15:57:19.459 | error | at StatesController.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:158:14)
zigbee.0 | 2021-03-21 15:57:19.459 | error | at StatesController.emit (events.js:314:20)
zigbee.0 | 2021-03-21 15:57:19.459 | error | at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:419:48)
zigbee.0 | 2021-03-21 15:57:19.459 | error | at ZigbeeController.resolveEntity (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:239:52)
zigbee.0 | 2021-03-21 15:57:19.459 | error | at Controller.getDeviceByIeeeAddr (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/controller.js:285:31)
zigbee.0 | 2021-03-21 15:57:19.459 | error | at Function.byIeeeAddr (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/device.js:228:16)
zigbee.0 | 2021-03-21 15:57:19.459 | error | at Function.loadFromDatabaseIfNecessary (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/device.js:220:55)
zigbee.0 | 2021-03-21 15:57:19.459 | error | (554) TypeError: Cannot read property 'getEntries' of null
zigbee.0 | 2021-03-21 15:57:19.458 | error | (554) unhandled promise rejection: Cannot read property 'getEntries' of null
zigbee.0 | 2021-03-21 15:57:19.457 | error | (554) Unhandled promise rejection. This error originated either by  throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch().

**Comment by kuumaur** [comment]
This is interesting:
zigbee.0 | 2021-03-21 16:15:16.399 | error | (1059) Error: Coordinator failed to start, probably the panID is already in use, try a different panID or channel     at /opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/startZn
-- | -- | -- | --

was it my fault?

**Comment by kuumaur** [comment]
This entry seems to help, at least to bring back the Adapter.
https://forum.iobroker.net/topic/29671/gel%C3%B6st-zigbee-kaputt-panid-already-in-use/3?_=1616438963588
