### ISSUE TITLE
[v1.4.6] unhandled promise rejection: The id is empty! Please provide a valid id.

### ISSUE THREAD

**Issue by o0shojo0o** [ioBroker/ioBroker.zigbee#1055]
Hi, I have tested the new 1.4.6 and I noticed the Unhandled promise rejection.

![image](https://user-images.githubusercontent.com/19333515/114504293-f226f480-9c2e-11eb-8454-878d1645a84a.png)

```js
 Error: The id is empty! Please provide a valid id. at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:496:19) at Zigbee.setState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5925:17) at Commands.onMessage (/opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js:87:38) at Zigbee.emit (events.js:326:22) at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5483:34) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:234:37) at processImmediate (internal/timers.js:461:21)
```

**Comment by kirovilya** [comment]
can you try now?

**Comment by o0shojo0o** [comment]
Thanks the fix has fixed the problem, great job thanks :)
