### ISSUE TITLE
zzh! Stick Link quality 0

### ISSUE THREAD

**Issue by Claus1985** [ioBroker/ioBroker.zigbee#1063]
Hi Guys,

after I got my zzh! Stick working I got an odd error.
When the stick is part of the network more than 1 day the link quality is  sometimes shown as 0:
![image](https://user-images.githubusercontent.com/69499563/115154487-658b9480-a07b-11eb-976c-f2555a1590e2.png)
![image](https://user-images.githubusercontent.com/69499563/115154506-75a37400-a07b-11eb-927d-ac92b8ca573e.png)

Funny thing is that its still active part of the network (at least following the network map and the signal strength of nearby devices).

After 10 Minutes and a few forced state cleanups its back on with a signal strength of 54.
![image](https://user-images.githubusercontent.com/69499563/115154739-b18b0900-a07c-11eb-95a1-385f5a2a9022.png)

Besides that I get a lot of errors since the update to 1.5.1:

I belive this is because of a hue motion sensor (0x0017880104b76a78) which gets kicked out of the network even though it sits directly beside my coordinator. Do you have a tip for me on what I can do to fix this problem?

`zigbee.0 | 2021-04-18 19:29:03.266 | error | (6785) Device 0x0017880104b76a78 "undefined" not described in statesMapping.
-- | -- | -- | --
host.Schaltzentrale2 | 2021-04-18 17:32:09.615 | info | Restart adapter system.adapter.zigbee.0 because enabled
-- | -- | -- | --
host.Schaltzentrale2 | 2021-04-18 17:32:09.614 | error | instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
zigbee.0 | 2021-04-18 17:32:08.962 | warn | (3103) Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee.0 | 2021-04-18 17:32:08.961 | info | (3103) terminating
zigbee.0 | 2021-04-18 17:32:08.461 | info | (3103) Zigbee: disabling joining new devices.
zigbee.0 | 2021-04-18 17:32:08.459 | info | (3103) cleaned everything up...
zigbee.0 | 2021-04-18 17:32:08.362 | warn | (3103) Blocked interview for 'undefined' because the network is closed
host.Schaltzentrale2-Server | 2021-04-18 17:32:08.168 | warn | Objects 127.0.0.1:57768 Error from InMemDB: Error: Not exists
host.Schaltzentrale2-Server | 2021-04-18 17:32:08.074 | warn | Objects 127.0.0.1:57768 Error from InMemDB: Error: Not exists
zigbee.0 | 2021-04-18 17:32:07.948 | error | (3103) Error Not exists
zigbee.0 | 2021-04-18 17:32:07.948 | error | at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
zigbee.0 | 2021-04-18 17:32:07.948 | error | at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)
zigbee.0 | 2021-04-18 17:32:07.948 | error | (3103) ReplyError: Error Not exists
zigbee.0 | 2021-04-18 17:32:07.948 | error | (3103) unhandled promise rejection: Error Not exists
zigbee.0 | 2021-04-18 17:32:07.947 | error | (3103) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-04-18 17:32:07.947 | error | (3103) Error Not exists
zigbee.0 | 2021-04-18 17:32:07.947 | error | at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
zigbee.0 | 2021-04-18 17:32:07.947 | error | at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)
zigbee.0 | 2021-04-18 17:32:07.947 | error | (3103) ReplyError: Error Not exists
zigbee.0 | 2021-04-18 17:32:07.947 | error | (3103) unhandled promise rejection: Error Not exists
zigbee.0 | 2021-04-18 17:32:07.946 | error | (3103) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-04-18 17:32:07.946 | error | (3103) Error Not exists
zigbee.0 | 2021-04-18 17:32:07.946 | error | at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
zigbee.0 | 2021-04-18 17:32:07.946 | error | at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)
zigbee.0 | 2021-04-18 17:32:07.946 | error | (3103) ReplyError: Error Not exists
zigbee.0 | 2021-04-18 17:32:07.945 | error | (3103) unhandled promise rejection: Error Not exists
zigbee.0 | 2021-04-18 17:32:07.945 | error | (3103) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-04-18 17:32:07.945 | error | (3103) Error Not exists
zigbee.0 | 2021-04-18 17:32:07.944 | error | at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
zigbee.0 | 2021-04-18 17:32:07.944 | error | at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)
zigbee.0 | 2021-04-18 17:32:07.944 | error | (3103) ReplyError: Error Not exists
zigbee.0 | 2021-04-18 17:32:07.944 | error | (3103) unhandled promise rejection: Error Not exists
zigbee.0 | 2021-04-18 17:32:07.944 | error | (3103) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-04-18 17:32:07.944 | error | (3103) Error Not exists
zigbee.0 | 2021-04-18 17:32:07.943 | error | at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
zigbee.0 | 2021-04-18 17:32:07.943 | error | at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)
zigbee.0 | 2021-04-18 17:32:07.943 | error | (3103) ReplyError: Error Not exists
zigbee.0 | 2021-04-18 17:32:07.943 | error | (3103) unhandled promise rejection: Error Not exists
zigbee.0 | 2021-04-18 17:32:07.943 | error | (3103) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-04-18 17:32:07.942 | error | (3103) Error Not exists
zigbee.0 | 2021-04-18 17:32:07.942 | error | at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
zigbee.0 | 2021-04-18 17:32:07.942 | error | at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)
zigbee.0 | 2021-04-18 17:32:07.942 | error | (3103) ReplyError: Error Not exists
zigbee.0 | 2021-04-18 17:32:07.942 | error | (3103) unhandled promise rejection: Error Not exists
zigbee.0 | 2021-04-18 17:32:07.941 | error | (3103) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-04-18 17:32:07.941 | error | (3103) Error Not exists
zigbee.0 | 2021-04-18 17:32:07.940 | error | at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
zigbee.0 | 2021-04-18 17:32:07.940 | error | at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)
zigbee.0 | 2021-04-18 17:32:07.940 | error | (3103) ReplyError: Error Not exists
zigbee.0 | 2021-04-18 17:32:07.940 | error | (3103) unhandled promise rejection: Error Not exists
zigbee.0 | 2021-04-18 17:32:07.940 | error | (3103) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-04-18 17:32:07.939 | error | (3103) Error Not exists
zigbee.0 | 2021-04-18 17:32:07.939 | error | at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
zigbee.0 | 2021-04-18 17:32:07.939 | error | at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)
zigbee.0 | 2021-04-18 17:32:07.939 | error | (3103) ReplyError: Error Not exists
zigbee.0 | 2021-04-18 17:32:07.939 | error | (3103) unhandled promise rejection: Error Not exists
zigbee.0 | 2021-04-18 17:32:07.938 | error | (3103) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
mqtt.0 | 2021-04-18 17:32:07.941 | warn | (21752) Cannot resolve topic name for ID: zigbee.0.0017880104b76a78.battery (object not found)
zigbee.0 | 2021-04-18 17:32:07.934 | error | (3103) Error Not exists
zigbee.0 | 2021-04-18 17:32:07.933 | error | at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
zigbee.0 | 2021-04-18 17:32:07.933 | error | at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)
zigbee.0 | 2021-04-18 17:32:07.933 | error | (3103) ReplyError: Error Not exists
zigbee.0 | 2021-04-18 17:32:07.933 | error | (3103) unhandled promise rejection: Error Not exists
zigbee.0 | 2021-04-18 17:32:07.933 | error | (3103) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-04-18 17:32:07.932 | error | (3103) Error Not exists
zigbee.0 | 2021-04-18 17:32:07.932 | error | at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
zigbee.0 | 2021-04-18 17:32:07.932 | error | at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)
zigbee.0 | 2021-04-18 17:32:07.932 | error | (3103) ReplyError: Error Not exists
zigbee.0 | 2021-04-18 17:32:07.932 | error | (3103) unhandled promise rejection: Error Not exists
zigbee.0 | 2021-04-18 17:32:07.932 | error | (3103) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-04-18 17:32:07.931 | error | (3103) Error Not exists
zigbee.0 | 2021-04-18 17:32:07.931 | error | at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
zigbee.0 | 2021-04-18 17:32:07.931 | error | at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)
zigbee.0 | 2021-04-18 17:32:07.931 | error | (3103) ReplyError: Error Not exists
zigbee.0 | 2021-04-18 17:32:07.931 | error | (3103) unhandled promise rejection: Error Not exists
zigbee.0 | 2021-04-18 17:32:07.930 | error | (3103) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-04-18 17:32:07.930 | error | (3103) Error Not exists
zigbee.0 | 2021-04-18 17:32:07.929 | error | at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
zigbee.0 | 2021-04-18 17:32:07.929 | error | at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)
zigbee.0 | 2021-04-18 17:32:07.929 | error | (3103) ReplyError: Error Not exists
zigbee.0 | 2021-04-18 17:32:07.929 | error | (3103) unhandled promise rejection: Error Not exists
zigbee.0 | 2021-04-18 17:32:07.928 | error | (3103) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-04-18 17:32:07.928 | error | (3103) Error Not exists
zigbee.0 | 2021-04-18 17:32:07.927 | error | at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
zigbee.0 | 2021-04-18 17:32:07.927 | error | at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)
zigbee.0 | 2021-04-18 17:32:07.927 | error | (3103) ReplyError: Error Not exists
zigbee.0 | 2021-04-18 17:32:07.927 | error | (3103) unhandled promise rejection: Error Not exists
zigbee.0 | 2021-04-18 17:32:07.927 | error | (3103) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-04-18 17:32:07.926 | error | (3103) Error Not exists
zigbee.0 | 2021-04-18 17:32:07.926 | error | at parseType (/opt/iobroker/node_modules/redis-parser/lib/parser.js:302:14)
zigbee.0 | 2021-04-18 17:32:07.926 | error | at parseError (/opt/iobroker/node_modules/redis-parser/lib/parser.js:179:12)
zigbee.0 | 2021-04-18 17:32:07.926 | error | (3103) ReplyError: Error Not exists
zigbee.0 | 2021-04-18 17:32:07.926 | error | (3103) unhandled promise rejection: Error Not exists
zigbee.0 | 2021-04-18 17:32:07.925 | error | (3103) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-04-18 17:32:07.925 | error | (3103) Error Not exists`

**Comment by asgothian** [comment]
Please run the adapter in debug mode to see where the error is coming from.

A.

**Comment by Claus1985** [comment]
Do you mean the zigbee herdsman debug option in the options menu?
![FE13224C-4594-43A8-9BB7-716BC65872E3](https://user-images.githubusercontent.com/69499563/115157909-008c6a80-a08c-11eb-95c1-be35dd124f9d.jpeg)

**Comment by asgothian** [comment]
Initially the "normal" debug info (activated from the instance list) is enough

A.

**Comment by Claus1985** [comment]
`2021-04-20 07:22:07.882  - [34mdebug[39m: zigbee.0 (15643) handleMessage. {"type":"attributeReport","device":{"ID":24,"_type":"EndDevice","_ieeeAddr":"0x00158d0002d68105","_networkAddress":61488,"_manufacturerID":4151,"_endpoints":[{"ID":1,"inputClusters":[],"outputClusters":[],"deviceNetworkAddress":61488,"deviceIeeeAddress":"0x00158d0002d68105","clusters":{"genBasic":{"attributes":{"65282":[{"elmType":16,"elmVal":0},{"elmType":33,"elmVal":2975},{"elmType":33,"elmVal":5032},{"elmType":36,"elmVal":[0,1]},{"elmType":33,"elmVal":87},{"elmType":32,"elmVal":86}],"modelId":"lumi.sensor_magnet","appVersion":10}},"genOnOff":{"attributes":{"onOff":0}}},"_binds":[],"_configuredReportings":[],"meta":{}}],"_manufacturerName":"LUMI","_powerSource":"Battery","_modelID":"lumi.sensor_magnet","_applicationVersion":10,"_interviewCompleted":true,"_interviewing":false,"_skipDefaultResponse":false,"meta":{},"_lastSeen":1618896127881,"_linkquality":102},"endpoint":"[Circular]","data":{"65282":"[Circular]"},"linkquality":102,"groupID":0,"cluster":"genBasic","meta":{"zclTransactionSequenceNumber":56,"manufacturerCode":4660,"frameControl":{"frameType":0,"manufacturerSpecific":true,"direction":1,"disableDefaultResponse":true,"reservedBits":0}}}
2021-04-20 07:22:07.883  - [34mdebug[39m: zigbee.0 (15643) Received Zigbee message from '0x00158d0002d68105', type 'attributeReport', cluster 'genBasic', data '{"65282":[{"elmType":16,"elmVal":0},{"elmType":33,"elmVal":2975},{"elmType":33,"elmVal":5032},{"elmType":36,"elmVal":[0,1]},{"elmType":33,"elmVal":87},{"elmType":32,"elmVal":86}]}' from endpoint 1 with groupID 0
2021-04-20 07:22:07.884  - [34mdebug[39m: zigbee.0 (15643) Type attributeReport device {"type":"device","device":{"ID":24,"_type":"EndDevice","_ieeeAddr":"0x00158d0002d68105","_networkAddress":61488,"_manufacturerID":4151,"_endpoints":[{"ID":1,"inputClusters":[],"outputClusters":[],"deviceNetworkAddress":61488,"deviceIeeeAddress":"0x00158d0002d68105","clusters":{"genBasic":{"attributes":{"65282":[{"elmType":16,"elmVal":0},{"elmType":33,"elmVal":2975},{"elmType":33,"elmVal":5032},{"elmType":36,"elmVal":[0,1]},{"elmType":33,"elmVal":87},{"elmType":32,"elmVal":86}],"modelId":"lumi.sensor_magnet","appVersion":10}},"genOnOff":{"attributes":{"onOff":0}}},"_binds":[],"_configuredReportings":[],"meta":{}}],"_manufacturerName":"LUMI","_powerSource":"Battery","_modelID":"lumi.sensor_magnet","_applicationVersion":10,"_interviewCompleted":true,"_interviewing":false,"_skipDefaultResponse":false,"meta":{},"_lastSeen":1618896127881,"_linkquality":102},"mapped":{"zigbeeModel":["lumi.sensor_magnet"],"model":"MCCGQ01LM","vendor":"Xiaomi","description":"MiJia door & window contact sensor","meta":{"battery":{"voltageToPercentage":"3V_2100"}},"fromZigbee":[{"cluster":"genBasic","type":["attributeReport","readResponse"]},{"cluster":"genOnOff","type":["attributeReport","readResponse"]}],"toZigbee":[],"exposes":[{"type":"numeric","name":"battery","property":"battery","access":1,"unit":"%","description":"Remaining battery in %","value_min":0,"value_max":100},{"type":"binary","name":"contact","property":"contact","access":1,"value_on":false,"value_off":true,"description":"Indicates if the contact is closed (= true) or open (= false)"},{"type":"numeric","name":"voltage","property":"voltage","access":1,"unit":"mV","description":"Voltage of the battery in millivolts"},{"type":"numeric","name":"linkquality","property":"linkquality","access":1,"unit":"lqi","description":"Link quality (signal strength)","value_min":0,"value_max":255}]},"name":"0x00158d0002d68105"} incoming event: {"type":"attributeReport","device":{"ID":24,"_type":"EndDevice","_ieeeAddr":"0x00158d0002d68105","_networkAddress":61488,"_manufacturerID":4151,"_endpoints":[{"ID":1,"inputClusters":[],"outputClusters":[],"deviceNetworkAddress":61488,"deviceIeeeAddress":"0x00158d0002d68105","clusters":{"genBasic":{"attributes":{"65282":[{"elmType":16,"elmVal":0},{"elmType":33,"elmVal":2975},{"elmType":33,"elmVal":5032},{"elmType":36,"elmVal":[0,1]},{"elmType":33,"elmVal":87},{"elmType":32,"elmVal":86}],"modelId":"lumi.sensor_magnet","appVersion":10}},"genOnOff":{"attributes":{"onOff":0}}},"_binds":[],"_configuredReportings":[],"meta":{}}],"_manufacturerName":"LUMI","_powerSource":"Battery","_modelID":"lumi.sensor_magnet","_applicationVersion":10,"_interviewCompleted":true,"_interviewing":false,"_skipDefaultResponse":false,"meta":{},"_lastSeen":1618896127881,"_linkquality":102},"endpoint":"[Circular]","data":{"65282":"[Circular]"},"linkquality":102,"groupID":0,"cluster":"genBasic","meta":{"zclTransactionSequenceNumber":56,"manufacturerCode":4660,"frameControl":{"frameType":0,"manufacturerSpecific":true,"direction":1,"disableDefaultResponse":true,"reservedBits":0}}}
2021-04-20 07:22:07.893  - [34mdebug[39m: zigbee.0 (15643) Publish {"voltage":2975,"battery":86} to "00158d0002d68105"
2021-04-20 07:22:08.368  - [34mdebug[39m: zigbee.0 (15643) handleDeviceAnnounce. {"device":{"ID":19,"_type":"EndDevice","_ieeeAddr":"0x001788010645950f","_networkAddress":33216,"_manufacturerID":4107,"_endpoints":[{"ID":1,"profileID":49246,"deviceID":2128,"inputClusters":[0],"outputClusters":[0,3,4,6,8,768,5],"deviceNetworkAddress":33216,"deviceIeeeAddress":"0x001788010645950f","clusters":{"genBasic":{"attributes":{"modelId":"SML002","manufacturerName":"Philips","powerSource":3,"zclVersion":1,"appVersion":2,"stackVersion":1,"hwVersion":1,"dateCode":"20190219","swBuildId":"6.1.1.27575"}}},"_binds":[],"_configuredReportings":[],"meta":{}},{"ID":2,"profileID":260,"deviceID":263,"inputClusters":[0,1,3,1030,1024,1026],"outputClusters":[25],"deviceNetworkAddress":33216,"deviceIeeeAddress":"0x001788010645950f","clusters":{"genPowerCfg":{"attributes":{"batteryPercentageRemaining":131}},"msOccupancySensing":{"attributes":{"48":2,"pirOToUDelay":0,"occupancy":0}},"msTemperatureMeasurement":{"attributes":{"measuredValue":-104}},"msIlluminanceMeasurement":{"attributes":{"measuredValue":32321}}},"_binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b001ca1b3ab","endpointID":1},{"cluster":1024,"type":"endpoint","deviceIeeeAddress":"0x00124b001ca1b3ab","endpointID":1},{"cluster":1026,"type":"endpoint","deviceIeeeAddress":"0x00124b001ca1b3ab","endpointID":1},{"cluster":1030,"type":"endpoint","deviceIeeeAddress":"0x00124b001ca1b3ab","endpointID":1}],"_configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0},{"cluster":1030,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0},{"cluster":1026,"attrId":0,"minRepIntval":10,"maxRepIntval":3600,"repChange":100},{"cluster":1024,"attrId":0,"minRepIntval":10,"maxRepIntval":3600,"repChange":5}],"meta":{}}],"_manufacturerName":"Philips","_powerSource":"Battery","_modelID":"SML002","_applicationVersion":2,"_stackVersion":1,"_zclVersion":1,"_hardwareVersion":1,"_dateCode":"20190219","_softwareBuildID":"6.1.1.27575","_interviewCompleted":true,"_interviewing":false,"_skipDefaultResponse":false,"meta":{"configured":2},"_lastSeen":1618896128367,"_linkquality":69}}
2021-04-20 07:22:08.369  - [33mwarn[39m: zigbee.0 (15643) Device '0x001788010645950f' announced itself
2021-04-20 07:22:08.370  - [34mdebug[39m: zigbee.0 (15643) New device event: {"type":"device","device":{"ID":19,"_type":"EndDevice","_ieeeAddr":"0x001788010645950f","_networkAddress":33216,"_manufacturerID":4107,"_endpoints":[{"ID":1,"profileID":49246,"deviceID":2128,"inputClusters":[0],"outputClusters":[0,3,4,6,8,768,5],"deviceNetworkAddress":33216,"deviceIeeeAddress":"0x001788010645950f","clusters":{"genBasic":{"attributes":{"modelId":"SML002","manufacturerName":"Philips","powerSource":3,"zclVersion":1,"appVersion":2,"stackVersion":1,"hwVersion":1,"dateCode":"20190219","swBuildId":"6.1.1.27575"}}},"_binds":[],"_configuredReportings":[],"meta":{}},{"ID":2,"profileID":260,"deviceID":263,"inputClusters":[0,1,3,1030,1024,1026],"outputClusters":[25],"deviceNetworkAddress":33216,"deviceIeeeAddress":"0x001788010645950f","clusters":{"genPowerCfg":{"attributes":{"batteryPercentageRemaining":131}},"msOccupancySensing":{"attributes":{"48":2,"pirOToUDelay":0,"occupancy":0}},"msTemperatureMeasurement":{"attributes":{"measuredValue":-104}},"msIlluminanceMeasurement":{"attributes":{"measuredValue":32321}}},"_binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b001ca1b3ab","endpointID":1},{"cluster":1024,"type":"endpoint","deviceIeeeAddress":"0x00124b001ca1b3ab","endpointID":1},{"cluster":1026,"type":"endpoint","deviceIeeeAddress":"0x00124b001ca1b3ab","endpointID":1},{"cluster":1030,"type":"endpoint","deviceIeeeAddress":"0x00124b001ca1b3ab","endpointID":1}],"_configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0},{"cluster":1030,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0},{"cluster":1026,"attrId":0,"minRepIntval":10,"maxRepIntval":3600,"repChange":100},{"cluster":1024,"attrId":0,"minRepIntval":10,"maxRepIntval":3600,"repChange":5}],"meta":{}}],"_manufacturerName":"Philips","_powerSource":"Battery","_modelID":"SML002","_applicationVersion":2,"_stackVersion":1,"_zclVersion":1,"_hardwareVersion":1,"_dateCode":"20190219","_softwareBuildID":"6.1.1.27575","_interviewCompleted":true,"_interviewing":false,"_skipDefaultResponse":false,"meta":{"configured":2},"_lastSeen":1618896128367,"_linkquality":69},"mapped":{"zigbeeModel":["SML002"],"model":"9290019758","vendor":"Philips","description":"Hue motion outdoor sensor","fromZigbee":[{"cluster":"genPowerCfg","type":["attributeReport","readResponse"]},{"cluster":"msOccupancySensing","type":["attributeReport","readResponse"]},{"cluster":"msTemperatureMeasurement","type":["attributeReport","readResponse"]},{"cluster":"msIlluminanceMeasurement","type":["attributeReport","readResponse"]},{"cluster":"msOccupancySensing","type":["attributeReport","readResponse"]},{"cluster":"msOccupancySensing","type":["attributeReport","readResponse"]},{"cluster":"genBasic","type":["attributeReport","readResponse"]}],"exposes":[{"type":"numeric","name":"temperature","property":"temperature","access":1,"unit":"°C","description":"Measured temperature value"},{"type":"binary","name":"occupancy","property":"occupancy","access":1,"value_on":true,"value_off":false,"description":"Indicates whether the device detected occupancy"},{"type":"numeric","name":"battery","property":"battery","access":1,"unit":"%","description":"Remaining battery in %","value_min":0,"value_max":100},{"type":"numeric","name":"illuminance_lux","property":"illuminance_lux","access":1,"unit":"lx","description":"Measured illuminance in lux"},{"type":"numeric","name":"illuminance","property":"illuminance","access":1,"description":"Raw measured illuminance"},{"type":"enum","name":"motion_sensitivity","property":"motion_sensitivity","access":7,"values":["low","medium","high"]},{"type":"binary","name":"led_indication","property":"led_indication","access":7,"value_on":true,"value_off":false,"description":"Blink green LED on motion detection"},{"type":"numeric","name":"occupancy_timeout","property":"occupancy_timeout","access":7,"unit":"second","value_min":0,"value_max":65535},{"type":"numeric","name":"linkquality","property":"linkquality","access":1,"unit":"lqi","description":"Link quality (signal strength)","value_min":0,"value_max":255}],"toZigbee":[{"key":["occupancy_timeout"]},{"key":["motion_sensitivity"]},{"key":["led_indication"]},{"key":["scene_store"]},{"key":["scene_recall"]},{"key":["scene_add"]},{"key":["scene_remove"]},{"key":["scene_remove_all"]},{"key":["read"]},{"key":["write"]}],"meta":{"configureKey":2},"ota":{}},"name":"0x001788010645950f"}
2021-04-20 07:22:08.376  - [31merror[39m: zigbee.0 (15643) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-04-20 07:22:08.376  - [31merror[39m: zigbee.0 (15643) unhandled promise rejection: SREQ '--> ZDO - extRouteDisc - {"dstAddr":33216,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)')
2021-04-20 07:22:08.377  - [31merror[39m: zigbee.0 (15643) Error: SREQ '--> ZDO - extRouteDisc - {"dstAddr":33216,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)')
    at Znp.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:291:27)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:24:58)
2021-04-20 07:22:08.378  - [31merror[39m: zigbee.0 (15643) SREQ '--> ZDO - extRouteDisc - {"dstAddr":33216,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)')
2021-04-20 07:22:08.396  - [32minfo[39m: zigbee.0 (15643) cleaned everything up...
2021-04-20 07:22:08.401  - [32minfo[39m: zigbee.0 (15643) Zigbee: disabling joining new devices.`

**Comment by asgothian** [comment]
Please have a look at your zigbee and Wifi network load. Your log contains an error message with
NWK_TABLE_FULL
which according to https://www.zigbee2mqtt.io/information/FAQ is a sign of wireless network issues.

A.
