### ISSUE TITLE
Crash on starting Admin UI

### ISSUE THREAD

**Issue by kurt4160** [ioBroker/ioBroker.zigbee#1070]
Hi,

everytime I start die Admin UI the zigbee adapter crashes and restarts. Then I can pair, set properties, etc.
Here the debug log around the crash time:

```
2021-04-25 18:47:23.618  - [34mdebug[39m: zigbee.0 (15890) Publish available for 0x00158d0002c978db = false
2021-04-25 18:47:23.619  - [34mdebug[39m: zigbee.0 (15890) Publish LQ for 0x00158d0002c978db = 0
2021-04-25 18:47:23.662  - [34mdebug[39m: zigbee.0 (15890) LQI succeeded for 'Coordinator'
2021-04-25 18:47:23.670  - [34mdebug[39m: zigbee.0 (15890) Routing for 'Coordinator': {"table":[]}
2021-04-25 18:47:23.670  - [34mdebug[39m: zigbee.0 (15890) Routing table succeeded for 'Coordinator'
2021-04-25 18:47:23.762  - [31merror[39m: zigbee.0 (15890) getDevices error: TypeError: Cannot read property 'resolveEntity' of undefined
    at adapter.getEnumsAsync.then.then.then.then.then (/opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js:220:64)
2021-04-25 18:47:23.927  - [34mdebug[39m: zigbee.0 (15890) LQI succeeded for '0x000d6ffffea26433'
2021-04-25 18:47:23.996  - [32minfo[39m: zigbee.0 (15890) terminating
2021-04-25 18:47:23.996  - [33mwarn[39m: zigbee.0 (15890) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-04-25 18:47:24.542  - [31merror[39m: host.cd7d67278839 instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-04-25 18:47:24.543  - [32minfo[39m: host.cd7d67278839 Restart adapter system.adapter.zigbee.0 because enabled
2021-04-25 18:47:54.556  - [32minfo[39m: host.cd7d67278839 instance system.adapter.zigbee.0 started with pid 18249
2021-04-25 18:47:55.389  - [34mdebug[39m: zigbee.0 (18249) Redis Objects: Use Redis connection: 0.0.0.0:9001
2021-04-25 18:47:55.407  - [34mdebug[39m: zigbee.0 (18249) Objects client ready ... initialize now
2021-04-25 18:47:55.409  - [34mdebug[39m: zigbee.0 (18249) Objects create System PubSub Client
2021-04-25 18:47:55.409  - [34mdebug[39m: zigbee.0 (18249) Objects create User PubSub Client
2021-04-25 18:47:55.409  - [34mdebug[39m: zigbee.0 (18249) Objects client initialize lua scripts
2021-04-25 18:47:55.417  - [34mdebug[39m: zigbee.0 (18249) Objects connected to redis: 0.0.0.0:9001
2021-04-25 18:47:55.424  - [34mdebug[39m: zigbee.0 (18249) objectDB connected
2021-04-25 18:47:55.425  - [34mdebug[39m: zigbee.0 (18249) Redis States: Use Redis connection: 0.0.0.0:9000
2021-04-25 18:47:55.429  - [34mdebug[39m: zigbee.0 (18249) States create System PubSub Client
2021-04-25 18:47:55.430  - [34mdebug[39m: zigbee.0 (18249) States create User PubSub Client
2021-04-25 18:47:55.480  - [34mdebug[39m: zigbee.0 (18249) States connected to redis: 0.0.0.0:9000
2021-04-25 18:47:55.481  - [34mdebug[39m: zigbee.0 (18249) statesDB connected
2021-04-25 18:47:55.699  - [32minfo[39m: zigbee.0 (18249) starting. Version 1.4.4 in /opt/iobroker/node_modules/iobroker.zigbee, node: v10.17.0, js-controller: 3.2.16
2021-04-25 18:47:55.715  - [34mdebug[39m: zigbee.0 (18249) Using zigbee-herdsman with settings: {"network":{"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11],"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13]},"databasePath":"/opt/iobroker/iobroker-data/zigbee_0/shepherd.db","backupPath":"/opt/iobroker/iobroker-data/zigbee_0/nvbackup.json","serialPort":{"baudRate":115200,"rtscts":false,"path":"/dev/ttyUSB1","adapter":"zstack"}}
2021-04-25 18:47:55.740  - [32minfo[39m: zigbee.0 (18249) Starting Zigbee  npm ...
2021-04-25 18:47:55.740  - [34mdebug[39m: zigbee.0 (18249) Starting zigbee-herdsman...
2021-04-25 18:47:55.960  - [32minfo[39m: zigbee.0 (18249) Installed Version: iobroker.zigbee@1.4.4
```
Ist this a known Problem?
Kurt

**Comment by asgothian** [comment]
Please update to the current latest version (1.5.1) and verify if the error is still present.

A.

**Comment by kurt4160** [comment]
Installed 1.5.1 with npm an have the same problem. Also groups are not working - after closing the settings and opening again all groups are gone (perhaps related to error?)


```
2021-04-26 08:47:06.622 - debug: zigbee.0 (2571) Publish LQ for 0x00158d00022f1f3d = 0
--
2021-04-26 08:47:06.959 - info: zigbee.0 (2571) terminating
2021-04-26 08:47:06.960 - warn: zigbee.0 (2571) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-04-26 08:47:07.504 - error: host.cd7d67278839 instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-04-26 08:47:07.504 - info: host.cd7d67278839 Restart adapter system.adapter.zigbee.0 because enabled
2021-04-26 08:47:07.504 - warn: host.cd7d67278839 Do not restart adapter system.adapter.zigbee.0 because restart loop detected
2021-04-26 08:47:55.875 - info: host.cd7d67278839 instance system.adapter.zigbee.0 started with pid 3820
2021-04-26 08:47:56.660 - debug: zigbee.0 (3820) Redis Objects: Use Redis connection: 0.0.0.0:9001
2021-04-26 08:47:56.678 - debug: zigbee.0 (3820) Objects client ready ... initialize now
2021-04-26 08:47:56.680 - debug: zigbee.0 (3820) Objects create System PubSub Client
2021-04-26 08:47:56.680 - debug: zigbee.0 (3820) Objects create User PubSub Client
2021-04-26 08:47:56.680 - debug: zigbee.0 (3820) Objects client initialize lua scripts
2021-04-26 08:47:56.688 - debug: zigbee.0 (3820) Objects connected to redis: 0.0.0.0:9001
2021-04-26 08:47:56.694 - debug: zigbee.0 (3820) objectDB connected
2021-04-26 08:47:56.696 - debug: zigbee.0 (3820) Redis States: Use Redis connection: 0.0.0.0:9000
2021-04-26 08:47:56.701 - debug: zigbee.0 (3820) States create System PubSub Client
2021-04-26 08:47:56.702 - debug: zigbee.0 (3820) States create User PubSub Client
2021-04-26 08:47:56.748 - debug: zigbee.0 (3820) States connected to redis: 0.0.0.0:9000
2021-04-26 08:47:56.749 - debug: zigbee.0 (3820) statesDB connected
2021-04-26 08:47:56.961 - info: zigbee.0 (3820) starting. Version 1.5.1 in /opt/iobroker/node_modules/iobroker.zigbee, node: v10.17.0, js-controller: 3.2.16
2021-04-26 08:47:56.981 - debug: zigbee.0 (3820) Using zigbee-herdsman with settings: {"network":{"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11],"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13]},"databasePath":"/opt/iobroker/iobroker-data/zigbee_0/shepherd.db","backupPath":"/opt/iobroker/iobroker-data/zigbee_0/nvbackup.json","serialPort":{"baudRate":115200,"rtscts":false,"path":"/dev/ttyUSB1","adapter":"zstack"}}
2021-04-26 08:47:57.013 - info: zigbee.0 (3820) Starting Zigbee npm ...
2021-04-26 08:47:57.014 - debug: zigbee.0 (3820) Starting zigbee-herdsman...
2021-04-26 08:47:57.168 - info: zigbee.0 (3820) Installed Version: undefined
2021-04-26 08:47:57.173 - debug: zigbee.0 (3820) Backup /opt/iobroker/iobroker-data/zigbee_0/backup_2021_04_26-08_47_56.tar.gz success
2021-04-26 08:48:07.632 - debug: zigbee.0 (3820) zigbee-herdsman started
2021-04-26 08:48:07.632 - info: zigbee.0 (3820) Coordinator firmware version: {"type":"zStack3x0","meta":{"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20210120}}
2021-04-26 08:48:07.638 - debug: zigbee.0 (3820) Zigbee network parameters: {"panID":6754,"extendedPanID":"0xdddddddddddddddd","channel":11}
2021-04-26 08:48:07.638 - info: zigbee.0 (3820) Unable to disable LED, unsupported function.
2021-04-26 08:48:07.638 - info: zigbee.0 (3820) --> transmitPower : normal
2021-04-26 08:48:07.645 - info: zigbee.0 (3820) Currently 20 devices are joined:
2021-04-26 08:48:07.645 - debug: zigbee.0 (3820) DeviceConfigure 0x000d6ffffea26433 TRADFRI signal repeater not needed
2021-04-26 08:48:07.645 - debug: zigbee.0 (3820) DeviceConfigure 0x00158d000246504c lumi.sensor_ht not needed
2021-04-26 08:48:07.646 - debug: zigbee.0 (3820) DeviceConfigure 0x00158d00023e80d2 lumi.sensor_motion.aq2 not needed
2021-04-26 08:48:07.646 - debug: zigbee.0 (3820) DeviceConfigure 0x00158d000237afcd lumi.sensor_ht not needed
2021-04-26 08:48:07.646 - debug: zigbee.0 (3820) DeviceConfigure 0x00158d000236fa33 lumi.sensor_magnet.aq2 not needed
2021-04-26 08:48:07.646 - debug: zigbee.0 (3820) DeviceConfigure 0x000d6ffffe9a6d2b TRADFRI signal repeater not needed
2021-04-26 08:48:07.646 - debug: zigbee.0 (3820) DeviceConfigure 0x00158d00020ea68e lumi.sensor_ht not needed
2021-04-26 08:48:07.646 - debug: zigbee.0 (3820) DeviceConfigure 0x00158d000315e79e lumi.sensor_ht not needed
2021-04-26 08:48:07.647 - debug: zigbee.0 (3820) DeviceConfigure 0x00158d000321f1e1 lumi.sensor_ht not needed
2021-04-26 08:48:07.647 - debug: zigbee.0 (3820) DeviceConfigure 0x00158d0002434b5a lumi.sensor_magnet.aq2 not needed
2021-04-26 08:48:07.647 - debug: zigbee.0 (3820) DeviceConfigure 0x5c0272fffef6f62c TRADFRI bulb E27 WS opal 1000lm not needed
2021-04-26 08:48:07.647 - debug: zigbee.0 (3820) DeviceConfigure 0x000b57fffed8cb0b TRADFRI bulb E27 W opal 1000lm not needed
2021-04-26 08:48:07.647 - debug: zigbee.0 (3820) DeviceConfigure 0x00158d00022ac5da lumi.sensor_switch not needed
2021-04-26 08:48:07.647 - debug: zigbee.0 (3820) DeviceConfigure 0x00158d00026eba56 lumi.sensor_86sw2 not needed
2021-04-26 08:48:07.647 - debug: zigbee.0 (3820) DeviceConfigure 0xd0cf5efffe24aac1 TRADFRI bulb E27 CWS opal 600lm not needed
2021-04-26 08:48:07.648 - debug: zigbee.0 (3820) DeviceConfigure 0x00158d0002ec8348 lumi.remote.b286acn01 not needed
2021-04-26 08:48:07.651 - debug: zigbee.0 (3820) DeviceConfigure 0x000d6ffffefb11ad TRADFRI bulb E27 W opal 1000lm not needed
2021-04-26 08:48:07.651 - debug: zigbee.0 (3820) DeviceConfigure 0xd0cf5efffecb548a TRADFRI bulb E27 W opal 1000lm not needed
2021-04-26 08:48:07.651 - debug: zigbee.0 (3820) DeviceConfigure 0x00158d0002c978db lumi.remote.b186acn01 not needed
2021-04-26 08:48:07.651 - debug: zigbee.0 (3820) DeviceConfigure 0x00158d00022f1f3d lumi.sensor_86sw1 not needed

```

**Comment by kurt4160** [comment]
Here some logging with Admin Logging set to debug:


```
2021-04-26 08:55:07.225 - debug: admin.0 (8001) Subscribe STATES: zigbee.0.*
--
2021-04-26 08:55:07.225 - debug: admin.0 (8001) Subscribes: zigbee.0.*
2021-04-26 08:55:07.247 - debug: admin.0 (8001) Subscribe OBJECTS: zigbee.0.*
2021-04-26 08:55:07.266 - debug: admin.0 (8001) sendTo "listUart" to system.adapter.zigbee.0 from system.adapter.admin.0
2021-04-26 08:55:07.274 - error: zigbee.0 (9093) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-04-26 08:55:07.274 - error: zigbee.0 (9093) unhandled promise rejection: spawn udevadm ENOENT
2021-04-26 08:55:07.274 - error: zigbee.0 (9093) Error: spawn udevadm ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
at onErrorNT (internal/child_process.js:415:16)
at process._tickCallback (internal/process/next_tick.js:63:19)
2021-04-26 08:55:07.274 - error: zigbee.0 (9093) Exception-Code: ENOENT: spawn udevadm ENOENT
2021-04-26 08:55:07.279 - info: zigbee.0 (9093) cleaned everything up...
2021-04-26 08:55:07.282 - debug: admin.0 (8001) sendTo "getCoordinatorInfo" to system.adapter.zigbee.0 from system.adapter.admin.0
2021-04-26 08:55:07.284 - debug: admin.0 (8001) sendTo "getDevices" to system.adapter.zigbee.0 from system.adapter.admin.0
2021-04-26 08:55:07.286 - debug: admin.0 (8001) sendTo "getMap" to system.adapter.zigbee.0 from system.adapter.admin.0
2021-04-26 08:55:07.287 - debug: admin.0 (8001) sendTo "getGroups" to system.adapter.zigbee.0 from system.adapter.admin.0
2021-04-26 08:55:07.288 - debug: admin.0 (8001) sendTo "getLibData" to system.adapter.zigbee.0 from system.adapter.admin.0
2021-04-26 08:55:07.281 - info: zigbee.0 (9093) Zigbee: disabling joining new devices.
2021-04-26 08:55:07.749 - info: zigbee.0 (9093) terminating
2021-04-26 08:55:07.749 - warn: zigbee.0 (9093) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-04-26 08:55:08.328 - error: host.cd7d67278839 instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-04-26 08:55:08.328 - info: host.cd7d67278839 Restart adapter system.adapter.zigbee.0 because enabled
2021-04-26 08:55:38.343 - info: host.cd7d67278839 instance system.adapter.zigbee.0 started with pid 10034
2021-04-26 08:55:39.487 - info: zigbee.0 (10034) starting. Version 1.5.1 in /opt/iobroker/node_modules/iobroker.zigbee, node: v10.17.0, js-controller: 3.2.16
2021-04-26 08:55:39.538 - info: zigbee.0 (10034) Starting Zigbee npm ...
2021-04-26 08:55:39.686 - info: zigbee.0 (10034) Installed Version: undefined
2021-04-26 08:55:50.173 - info: zigbee.0 (10034) Coordinator firmware version: {"type":"zStack3x0","meta":{"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20210120}}
2021-04-26 08:55:50.178 - info: zigbee.0 (10034) Unable to disable LED, unsupported function.
2021-04-26 08:55:50.178 - info: zigbee.0 (10034) --> transmitPower : normal
2021-04-26 08:55:50.183 - info: zigbee.0 (10034) Currently 20 devices are joined:

```

**Comment by asgothian** [comment]
It seems that your system does not allow for Query of the serial ports. (The error message "ENOENT" is an indication that a call is made to a program / a directory is attempted to query which does not exist. Please verify that the zigbee-herdsman was correctly installed and only exists once in your node_module tree (via npm list zigbee-herdsman and/or npm list zigbee-herdsman-converters)

Also, please clarify "groups are not working". Did the group states in the objects vanish, or are the groups not displayed in the admin page ?

A.

**Comment by Apollon77** [comment]
Please run "iobroker fix"

**Comment by kurt4160** [comment]
I did a "iobroker fix" and checked zigbee-herdsman

```
iobroker.inst@2.0.3 /opt/iobroker
└─┬ iobroker.zigbee@1.5.1
  ├── zigbee-herdsman@0.13.91
  └─┬ zigbee-herdsman-converters@14.0.120
    └── zigbee-herdsman@0.13.91  deduped
```

```
iobroker.inst@2.0.3 /opt/iobroker
└─┬ iobroker.zigbee@1.5.1
  └── zigbee-herdsman-converters@14.0.120
```

But nothing changed:


```
2021-04-26 10:18:01.788 - error: zigbee.0 (11758) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
--
2021-04-26 10:18:01.789 - error: zigbee.0 (11758) unhandled promise rejection: spawn udevadm ENOENT
2021-04-26 10:18:01.789 - error: zigbee.0 (11758) Error: spawn udevadm ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
at onErrorNT (internal/child_process.js:415:16)
at process._tickCallback (internal/process/next_tick.js:63:19)
2021-04-26 10:18:01.789 - error: zigbee.0 (11758) Exception-Code: ENOENT: spawn udevadm ENOENT
2021-04-26 10:18:01.796 - info: zigbee.0 (11758) cleaned everything up...
2021-04-26 10:18:01.798 - info: zigbee.0 (11758) Zigbee: disabling joining new devices.
2021-04-26 10:18:02.115 - error: zwave2.0 (11616) Node 10 interview failed: The node is dead
2021-04-26 10:18:02.271 - info: zigbee.0 (11758) terminating
```

If it is a permission problem reading the serial port, why is it working after the restart of the adapter?

To the groups: I add a group and asign it. When I close settings, the nodes for the new group are added. After opening settings again the group is missing from the "Groups" Tab and the asignment to the two lamps are gone.
I then deleted the nodes for these groups and after opening the settings again, all of the nodes are created again, but none of the groups is shown in settings.

I am using Slaesh's CC2652RB stick on /dev/ttyUSB1.

**Comment by asgothian** [comment]
- Please check if the program 'udevadm' exists and is executable on your system.
- Please check on the groups side:
-- are the states for the group present in the states tree (zigbee.0.group_<id>). If so, can the members be controlled via these states.
-- is the group listed and named under zigbee.0.info.groups
-- on the devices added to the group: do they have a state "group" or "groups" with any content ? If so, which ?

A.

**Comment by kurt4160** [comment]
Thanks for your quick answers.
I am running iobroker under debian inside a docker container. On trying to check for udevadm I restartet the container and now all is working. No crash on opening the settings and all defined groups are listed and are working.
Sorry for not trying this earlyer and bothering you.
Kurt

**Comment by Tombra1889** [comment]
I have the same Error:

> Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms) at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31) at Generator.throw (<anonymous>) at rejected (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)

> Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port' at Znp.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:136:32) at Generator.next (<anonymous>) at /opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:27:71 at new Promise (<anonymous>) at __awaiter (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:23:12) at SerialPort.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:134:49) at SerialPort._error (/opt/iobroker/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14) at /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12

> pi@raspberrypi:/opt/iobroker $ npm list zigbee-herdsman
iobroker.inst@2.0.3 /opt/iobroker
└─┬ iobroker.zigbee@1.5.1
  ├── zigbee-herdsman@0.13.92 
  └─┬ zigbee-herdsman-converters@14.0.125
    └── zigbee-herdsman@0.13.91 

> pi@raspberrypi:/opt/iobroker $ npm list zigbee-herdsman-converters
iobroker.inst@2.0.3 /opt/iobroker
└─┬ iobroker.zigbee@1.5.1
  └── zigbee-herdsman-converters@14.0.125
