### ISSUE TITLE
After detecting unknown device, Adapter will not start anymore ("SRSP - ZDO - activeEpReq after 6000ms")

### ISSUE THREAD

**Issue by MiWoBln** [ioBroker/ioBroker.zigbee#1131]
After a new unknown device was detected, the adapter will not start anymore.

What i tried:
* unplug the adapter
* remove instance from iobroker
* remove adapter from iobroker
* change COM Port from /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B000BE6755E-if00 to /dev/ttyACM0

Any Help would be appreciated

Best Mirko

```

<!--StartFragment-->
zigbee.0 | 2021-06-12 00:36:24.423 | silly | States user redis pmessage zigbee.0.*/zigbee.0.info.connection:{"val":false,"ack":true,"ts":1623450984417,"q":0,"from":"system.adapter.zigbee.0","user":"system.user.admin","lc":1623450730401}
-- | -- | -- | --
zigbee.0 | 2021-06-12 00:36:24.413 | silly | States user redis pmessage zigbee.0.*/zigbee.0.info.pairingMessage:{"val":"Error: Starting zigbee-herdsman problem : \"Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'\". undefined","ack":true,"ts":1623450984407,"q":0,"from":"system.adapter.zigbee.0","user":"system.user.admin","lc":1623450984407}
zigbee.0 | 2021-06-12 00:36:24.397 | error | Error herdsman start
zigbee.0 | 2021-06-12 00:36:24.396 | error | Failed to start Zigbee
zigbee.0 | 2021-06-12 00:36:24.394 | error | Starting zigbee-herdsman problem : "Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'"
zigbee.0 | 2021-06-12 00:36:19.378 | debug | zigbee-herdsman:adapter:zStack:znp:log Opening SerialPort with /dev/ttyACM0 and {"baudRate":115200,"rtscts":false,"autoOpen":false}
zigbee.0 | 2021-06-12 00:36:19.374 | debug | zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11],"extenedPanID":[221,221,221,221,221,221,221,221]},"serialPort":{"baudRate":115200,"rtscts":false,"path":"/dev/ttyACM0","adapter":"zstack"},"databasePath":"/opt/iobroker/iobroker-data/zigbee_0/shepherd.db","databaseBackupPath":null,"backupPath":"/opt/iobroker/iobroker-data/zigbee_0/nvbackup.json","adapter":{"disableLED":false},"acceptJoiningDeviceHandler":null}'
zigbee.0 | 2021-06-12 00:36:19.373 | debug | zigbee-herdsman:adapter Path '/dev/ttyACM0' is valid for 'ZStackAdapter'
zigbee.0 | 2021-06-12 00:36:19.127 | info | Installed Version: iobroker.zigbee@1.5.6
zigbee.0 | 2021-06-12 00:36:19.089 | debug | Starting zigbee-herdsman...
zigbee.0 | 2021-06-12 00:36:19.088 | info | Starting Zigbee npm ...
zigbee.0 | 2021-06-12 00:36:19.086 | info | Try to reconnect. 1 attempts left
zigbee.0 | 2021-06-12 00:36:09.097 | silly | States user redis pmessage zigbee.0.*/zigbee.0.info.connection:{"val":false,"ack":true,"ts":1623450969092,"q":0,"from":"system.adapter.zigbee.0","user":"system.user.admin","lc":1623450730401}
zigbee.0 | 2021-06-12 00:36:09.094 | silly | States user redis pmessage zigbee.0.*/zigbee.0.info.pairingMessage:{"val":"Error: Starting zigbee-herdsman problem : \"Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)\". undefined","ack":true,"ts":1623450969091,"q":0,"from":"system.adapter.zigbee.0","user":"system.user.admin","lc":1623450969091}
zigbee.0 | 2021-06-12 00:36:09.086 | error | Error herdsman start
zigbee.0 | 2021-06-12 00:36:09.085 | error | Failed to start Zigbee
zigbee.0 | 2021-06-12 00:36:09.084 | error | Starting zigbee-herdsman problem : "Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)"
zigbee.0 | 2021-06-12 00:36:03.083 | debug | zigbee-herdsman:adapter:zStack:unpi:writer --&gt; frame [254,0,33,1,32]
zigbee.0 | 2021-06-12 00:36:03.082 | debug | zigbee-herdsman:adapter:zStack:znp:SREQ --&gt; SYS - ping - {"capabilities":1}
zigbee.0 | 2021-06-12 00:35:57.079 | debug | zigbee-herdsman:adapter:zStack:unpi:writer --&gt; frame [254,0,33,1,32]
zigbee.0 | 2021-06-12 00:35:57.078 | debug | zigbee-herdsman:adapter:zStack:znp:SREQ --&gt; SYS - ping - {"capabilities":1}
zigbee.0 | 2021-06-12 00:35:51.075 | debug | zigbee-herdsman:adapter:zStack:unpi:writer --&gt; frame [254,0,33,1,32]
zigbee.0 | 2021-06-12 00:35:51.073 | debug | zigbee-herdsman:adapter:zStack:znp:SREQ --&gt; SYS - ping - {"capabilities":1}
zigbee.0 | 2021-06-12 00:35:50.067 | debug | zigbee-herdsman:adapter:zStack:unpi:writer --&gt; buffer [239]
zigbee.0 | 2021-06-12 00:35:50.064 | debug | zigbee-herdsman:adapter:zStack:znp:log Writing skip bootloader payload
zigbee.0 | 2021-06-12 00:35:34.475 | debug | zigbee-herdsman:adapter:zStack:znp:log Serialport opened
zigbee.0 | 2021-06-12 00:35:29.395 | debug | zigbee-herdsman:adapter:zStack:znp:log Opening SerialPort with /dev/ttyACM0 and {"baudRate":115200,"rtscts":false,"autoOpen":false}
zigbee.0 | 2021-06-12 00:35:29.389 | debug | zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11],"extenedPanID":[221,221,221,221,221,221,221,221]},"serialPort":{"baudRate":115200,"rtscts":false,"path":"/dev/ttyACM0","adapter":"zstack"},"databasePath":"/opt/iobroker/iobroker-data/zigbee_0/shepherd.db","databaseBackupPath":null,"backupPath":"/opt/iobroker/iobroker-data/zigbee_0/nvbackup.json","adapter":{"disableLED":false},"acceptJoiningDeviceHandler":null}'
zigbee.0 | 2021-06-12 00:35:29.387 | debug | zigbee-herdsman:adapter Path '/dev/ttyACM0' is valid for 'ZStackAdapter'
zigbee.0 | 2021-06-12 00:35:29.265 | silly | States user redis pmessage zigbee.0.*/zigbee.0.info.connection:{"val":false,"ack":true,"ts":1623450929257,"q":0,"from":"system.adapter.zigbee.0","user":"system.user.admin","lc":1623450730401}
zigbee.0 | 2021-06-12 00:35:29.261 | debug | Backup /opt/iobroker/iobroker-data/zigbee_0/backup_2021_06_12-00_35_28.tar.gz success
zigbee.0 | 2021-06-12 00:35:29.253 | info | Installed Version: iobroker.zigbee@1.5.6
zigbee.0 | 2021-06-12 00:35:29.230 | silly | States system redis pmessage system.adapter.zigbee.0.logLevel/system.adapter.zigbee.0.logLevel:{"val":"silly","ack":true,"ts":1623450929153,"q":0,"from":"system.adapter.zigbee.0","lc":1623450247250}
zigbee.0 | 2021-06-12 00:35:28.951 | debug | Starting zigbee-herdsman...
zigbee.0 | 2021-06-12 00:35:28.950 | info | Starting Zigbee npm ...
zigbee.0 | 2021-06-12 00:35:28.892 | debug | Using zigbee-herdsman with settings: {"network":{"panID":6754,"channelList":[11],"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"extenedPanID":[221,221,221,221,221,221,221,221]},"databasePath":"/opt/iobroker/iobroker-data/zigbee_0/shepherd.db","backupPath":"/opt/iobroker/iobroker-data/zigbee_0/nvbackup.json","serialPort":{"baudRate":115200,"rtscts":false,"path":"/dev/ttyACM0","adapter":"zstack"}}
zigbee.0 | 2021-06-12 00:35:28.846 | info | starting. Version 1.5.6 in /opt/iobroker/node_modules/iobroker.zigbee, node: v15.14.0, js-controller: 3.3.12
zigbee.0 | 2021-06-12 00:35:28.540 | debug | statesDB connected
zigbee.0 | 2021-06-12 00:35:28.539 | debug | States connected to redis: 127.0.0.1:9000
zigbee.0 | 2021-06-12 00:35:28.530 | debug | States create User PubSub Client
zigbee.0 | 2021-06-12 00:35:28.528 | debug | States create System PubSub Client
zigbee.0 | 2021-06-12 00:35:28.510 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
zigbee.0 | 2021-06-12 00:35:28.507 | debug | objectDB connected
zigbee.0 | 2021-06-12 00:35:28.499 | silly | redis psubscribe cfg.o.system.user.*
zigbee.0 | 2021-06-12 00:35:28.495 | debug | Objects connected to redis: 127.0.0.1:9001
zigbee.0 | 2021-06-12 00:35:28.463 | debug | Objects client initialize lua scripts
zigbee.0 | 2021-06-12 00:35:28.462 | debug | Objects create User PubSub Client
zigbee.0 | 2021-06-12 00:35:28.460 | debug | Objects create System PubSub Client
zigbee.0 | 2021-06-12 00:35:28.458 | debug | Objects client ready ... initialize now
zigbee.0 | 2021-06-12 00:35:28.419 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
zigbee.0 | 2021-06-12 00:34:55.486 | warn | Terminated (ADAPTER_ALREADY_RUNNING): Without reason
zigbee.0 | 2021-06-12 00:34:55.485 | error | zigbee.0 already running
zigbee.0 | 2021-06-12 00:34:55.478 | debug | statesDB connected
zigbee.0 | 2021-06-12 00:34:55.477 | debug | States connected to redis: 127.0.0.1:9000
zigbee.0 | 2021-06-12 00:34:55.460 | debug | States create User PubSub Client
zigbee.0 | 2021-06-12 00:34:55.458 | debug | States create System PubSub Client
zigbee.0 | 2021-06-12 00:34:55.445 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
zigbee.0 | 2021-06-12 00:34:55.442 | debug | objectDB connected
zigbee.0 | 2021-06-12 00:34:55.434 | silly | redis psubscribe cfg.o.system.user.*
zigbee.0 | 2021-06-12 00:34:55.430 | debug | Objects connected to redis: 127.0.0.1:9001
zigbee.0 | 2021-06-12 00:34:55.408 | debug | Objects client initialize lua scripts
zigbee.0 | 2021-06-12 00:34:55.407 | debug | Objects create User PubSub Client
zigbee.0 | 2021-06-12 00:34:55.405 | debug | Objects create System PubSub Client
zigbee.0 | 2021-06-12 00:34:55.403 | debug | Objects client ready ... initialize now
zigbee.0 | 2021-06-12 00:34:55.356 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
zigbee.0 | 2021-06-12 00:34:50.017 | error | Cannot read property 'getEntries' of null
zigbee.0 | 2021-06-12 00:34:50.017 | error | TypeError: Cannot read property 'getEntries' of null at Function.loadFromDatabaseIfNecessary (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/device.js:220:55) at Function.all (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/device.js:240:16) at Controller.getDevices (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/controller.js:303:31) at ZigbeeController.getClients (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:228:49) at DeviceAvailability.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceAvailability.js:222:43) at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:214:42) at ZigbeeController.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:385:20) at Zigbee.onUnload (/opt/iobroker/node_modules/iobroker.zigbee/main.js:696:41) at processTicksAndRejections (node:internal/process/task_queues:94:5)
zigbee.0 | 2021-06-12 00:34:50.015 | error | unhandled promise rejection: Cannot read property 'getEntries' of null
zigbee.0 | 2021-06-12 00:34:50.014 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-06-12 00:34:50.013 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
zigbee.0 | 2021-06-12 00:34:50.011 | info | terminating
zigbee.0 | 2021-06-12 00:34:50.010 | warn | Failed to stop zigbee during startup
zigbee.0 | 2021-06-12 00:34:50.008 | info | Zigbee: disabling joining new devices.
zigbee.0 | 2021-06-12 00:34:50.003 | info | cleaned everything up...
zigbee.0 | 2021-06-12 00:34:50.002 | info | Got terminate signal TERMINATE_YOURSELF
zigbee.0 | 2021-06-12 00:34:50.001 | silly | States system redis pmessage system.adapter.zigbee.0.sigKill/system.adapter.zigbee.0.sigKill:{"val":-1,"ack":false,"ts":1623450889999,"q":0,"from":"system.host.raspberrypi","lc":1623450889999}
zigbee.0 | 2021-06-12 00:34:28.691 | debug | sendTo "listUart" to system.adapter.admin.0 from system.adapter.zigbee.0
zigbee.0 | 2021-06-12 00:34:28.690 | debug | List of ports: [{"comName":"/dev/ttyACM0"},{"comName":"/dev/ttyS0"}]
zigbee.0 | 2021-06-12 00:34:28.550 | debug | sendTo "getGroups" to system.adapter.admin.0 from system.adapter.zigbee.0
zigbee.0 | 2021-06-12 00:34:28.550 | error | getGroups: caught error: TypeError: Cannot read property 'getGroups' of undefined
zigbee.0 | 2021-06-12 00:34:28.541 | debug | sendTo "getLibData" to system.adapter.admin.0 from system.adapter.zigbee.0
zigbee.0 | 2021-06-12 00:34:28.540 | silly | States system redis pmessage io.messagebox.system.adapter.zigbee.0/io.messagebox.system.adapter.zigbee.0:{"command":"getLibData","message":{"key":"cidList"},"from":"system.adapter.admin.0","callback":{"message":{"key":"cidList"},"id":29,"ack":false,"time":1623450868517},"_id":92587216}
zigbee.0 | 2021-06-12 00:34:28.539 | silly | States system redis pmessage io.messagebox.system.adapter.zigbee.0/io.messagebox.system.adapter.zigbee.0:{"command":"getGroups","message":{},"from":"system.adapter.admin.0","callback":{"message":{},"id":28,"ack":false,"time":1623450868516},"_id":92587215}
zigbee.0 | 2021-06-12 00:34:28.538 | silly | States system redis pmessage io.messagebox.system.adapter.zigbee.0/io.messagebox.system.adapter.zigbee.0:{"command":"getMap","message":{},"from":"system.adapter.admin.0","callback":{"message":{},"id":27,"ack":false,"time":1623450868515},"_id":92587214}
zigbee.0 | 2021-06-12 00:34:28.536 | debug | sendTo "getDevices" to system.adapter.admin.0 from system.adapter.zigbee.0
zigbee.0 | 2021-06-12 00:34:28.535 | silly | States system redis pmessage io.messagebox.system.adapter.zigbee.0/io.messagebox.system.adapter.zigbee.0:{"command":"getDevices","message":{},"from":"system.adapter.admin.0","callback":{"message":{},"id":26,"ack":false,"time":1623450868515},"_id":92587213}
zigbee.0 | 2021-06-12 00:34:28.534 | debug | sendTo "getCoordinatorInfo" to system.adapter.admin.0 from system.adapter.zigbee.0
zigbee.0 | 2021-06-12 00:34:28.532 | silly | States system redis pmessage io.messagebox.system.adapter.zigbee.0/io.messagebox.system.adapter.zigbee.0:{"command":"getCoordinatorInfo","message":{},"from":"system.adapter.admin.0","callback":{"message":{},"id":25,"ack":false,"time":1623450868514},"_id":92587212}
zigbee.0 | 2021-06-12 00:34:28.515 | silly | States system redis pmessage io.messagebox.system.adapter.zigbee.0/io.messagebox.system.adapter.zigbee.0:{"command":"listUart","message":null,"from":"system.adapter.admin.0","callback":{"message":null,"id":24,"ack":false,"time":1623450868513},"_id":92587211}
zigbee.0 | 2021-06-12 00:34:19.319 | debug | sendTo "listUart" to system.adapter.admin.0 from system.adapter.zigbee.0
zigbee.0 | 2021-06-12 00:34:19.318 | debug | List of ports: [{"comName":"/dev/ttyACM0"},{"comName":"/dev/ttyS0"}]
zigbee.0 | 2021-06-12 00:34:19.153 | debug | sendTo "getGroups" to system.adapter.admin.0 from system.adapter.zigbee.0
zigbee.0 | 2021-06-12 00:34:19.152 | error | getGroups: caught error: TypeError: Cannot read property 'getGroups' of undefined
zigbee.0 | 2021-06-12 00:34:19.143 | debug | sendTo "getLibData" to system.adapter.admin.0 from system.adapter.zigbee.0
zigbee.0 | 2021-06-12 00:34:19.141 | silly | States system redis pmessage io.messagebox.system.adapter.zigbee.0/io.messagebox.system.adapter.zigbee.0:{"command":"getLibData","message":{"key":"cidList"},"from":"system.adapter.admin.0","callback":{"message":{"key":"cidList"},"id":22,"ack":false,"time":1623450859112},"_id":92587209}
zigbee.0 | 2021-06-12 00:34:19.140 | silly | States system redis pmessage io.messagebox.system.adapter.zigbee.0/io.messagebox.system.adapter.zigbee.0:{"command":"getGroups","message":{},"from":"system.adapter.admin.0","callback":{"message":{},"id":21,"ack":false,"time":1623450859111},"_id":92587208}
zigbee.0 | 2021-06-12 00:34:19.138 | silly | States system redis pmessage io.messagebox.system.adapter.zigbee.0/io.messagebox.system.adapter.zigbee.0:{"command":"getMap","message":{},"from":"system.adapter.admin.0","callback":{"message":{},"id":20,"ack":false,"time":1623450859111},"_id":92587207}
zigbee.0 | 2021-06-12 00:34:19.137 | debug | sendTo "getDevices" to system.adapter.admin.0 from system.adapter.zigbee.0
zigbee.0 | 2021-06-12 00:34:19.134 | silly | States system redis pmessage io.messagebox.system.adapter.zigbee.0/io.messagebox.system.adapter.zigbee.0:{"command":"getDevices","message":{},"from":"system.adapter.admin.0","callback":{"message":{},"id":19,"ack":false,"time":1623450859110},"_id":92587206}
zigbee.0 | 2021-06-12 00:34:19.132 | debug | sendTo "getCoordinatorInfo" to system.adapter.admin.0 from system.adapter.zigbee.0
zigbee.0 | 2021-06-12 00:34:19.129 | silly | States system redis pmessage io.messagebox.system.adapter.zigbee.0/io.messagebox.system.adapter.zigbee.0:{"command":"getCoordinatorInfo","message":{},"from":"system.adapter.admin.0","callback":{"message":{},"id":18,"ack":false,"time":1623450859110},"_id":92587205}
zigbee.0 | 2021-06-12 00:34:19.111 | silly | States system redis pmessage io.messagebox.system.adapter.zigbee.0/io.messagebox.system.adapter.zigbee.0:{"command":"listUart","message":null,"from":"system.adapter.admin.0","callback":{"message":null,"id":17,"ack":false,"time":1623450859109},"_id":92587204}

<!--EndFragment-->





```

dmesg respond with

```
[  625.052669] usb 1-1.3: New USB device found, idVendor=0451, idProduct=16a8, bcdDevice= 0.09
[  625.052692] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  625.052710] usb 1-1.3: Product: TI CC2531 USB CDC
[  625.052728] usb 1-1.3: Manufacturer: Texas Instruments
[  625.052745] usb 1-1.3: SerialNumber: __0X00124B000BE6755E
[  625.057833] cdc_acm 1-1.3:1.0: ttyACM0: USB ACM device
[  905.366984] cdc_acm 1-1.3:1.0: failed to set dtr/rts
[  913.607047] cdc_acm 1-1.3:1.0: failed to set dtr/rts
[  923.687421] cdc_acm 1-1.3:1.0: failed to set dtr/rts

```

**Comment by asgothian** [comment]
It seems that the adapter is unable to establish connection to your coordinator. Please try to refresh the firmware on the coordinator.

**Comment by MiWoBln** [comment]
It seesm that the stick is broken.. with a new one it works instantly.
