### ISSUE TITLE
adapter crashes since rpi update

### ISSUE THREAD

**Issue by softwarecrash** [ioBroker/ioBroker.zigbee#1139]
hello,
after i updatet the npm, node, and other for the backitup adapter the zigbee adapter crashes at start, version 1.5.6 any idea what going wrong?

here the log
```
<html><body>
<!--StartFragment-->

zigbee.0 | 2021-06-23 19:17:25.106 | error | (4446) Error herdsman start
-- | -- | -- | --
zigbee.0 | 2021-06-23 19:17:25.105 | error | (4446) Failed to start Zigbee
zigbee.0 | 2021-06-23 19:17:25.103 | error | (4446)  Starting zigbee-herdsman problem : "Error while opening serialport  'Error: Error Resource temporarily unavailable Cannot lock port'"
zigbee.0 | 2021-06-23 19:17:24.672 | info | (4446) Installed Version: ioBroker/ioBroker.zigbee#master
zigbee.0 | 2021-06-23 19:17:24.626 | info | (4446) Starting Zigbee  npm ...
zigbee.0 | 2021-06-23 19:17:24.624 | info | (4446) Try to reconnect. 1 attempts left
zigbee.0 | 2021-06-23 19:17:14.621 | error | (4446) Error herdsman start
zigbee.0 | 2021-06-23 19:17:14.620 | error | (4446) Failed to start Zigbee
zigbee.0 | 2021-06-23 19:17:14.619 | error | (4446)  Starting zigbee-herdsman problem : "startup failed -  configuration-adapter mismatch - see logs above for more information"
zigbee.0 | 2021-06-23 19:17:14.617 | error | (4446) Re-commissioning your network will require re-pairing of all devices!
zigbee.0 | 2021-06-23 19:17:14.616 | error | (4446)  If you wish to re-commission your network, please remove coordinator  backup at /opt/iobroker/iobroker-data/zigbee_0/nvbackup.json.
zigbee.0 | 2021-06-23 19:17:14.615 | error | (4446) Please update configuration to prevent further issues.
zigbee.0 | 2021-06-23 19:17:14.614 | error | (4446) - Channel List: configured=20, adapter=20
zigbee.0 | 2021-06-23 19:17:14.614 | error | (4446) - Network Key: configured=01030507090b0d0f00020406080a0c0a, adapter=01030507090b0d0f00020406080a0c0a
zigbee.0 | 2021-06-23 19:17:14.612 | error | (4446) - Extended PAN ID: configured=dadddddddddddddd, adapter=00124b0014b8889a
zigbee.0 | 2021-06-23 19:17:14.611 | error | (4446) - PAN ID: configured=6754, adapter=6754
zigbee.0 | 2021-06-23 19:17:14.610 | error | (4446) Configuration is not consistent with adapter state/backup!
zigbee.0 | 2021-06-23 19:17:12.563 | info | (4446) Installed Version: ioBroker/ioBroker.zigbee#master
zigbee.0 | 2021-06-23 19:17:11.796 | info | (4446) Starting Zigbee  npm ...
zigbee.0 | 2021-06-23 19:17:11.563 | info | (4446) starting. Version 1.5.6 in /opt/iobroker/node_modules/iobroker.zigbee, node: v14.17.0, js-controller: 3.2.16
host.iobroker | 2021-06-23 19:17:05.335 | info | instance system.adapter.zigbee.0 started with pid 4446
host.iobroker | 2021-06-23 19:17:03.013 | info | instance system.adapter.zigbee.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
zigbee.0 | 2021-06-23 19:17:02.293 | error | (4220) Cannot read property 'getEntries' of null
zigbee.0 | 2021-06-23 19:17:02.292 | error | at processTicksAndRejections (internal/process/task_queues.js:95:5)
zigbee.0 | 2021-06-23 19:17:02.292 | error | at Zigbee.onUnload (/opt/iobroker/node_modules/iobroker.zigbee/main.js:696:41)
zigbee.0 | 2021-06-23 19:17:02.292 | error | at ZigbeeController.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:385:20)
zigbee.0 | 2021-06-23 19:17:02.292 | error | at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:214:42)
zigbee.0 | 2021-06-23 19:17:02.292 | error | at DeviceAvailability.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceAvailability.js:222:43)
zigbee.0 | 2021-06-23 19:17:02.292 | error | at ZigbeeController.getClients (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:228:49)
zigbee.0 | 2021-06-23 19:17:02.292 | error | at Controller.getDevices  (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/controller.js:303:31)
zigbee.0 | 2021-06-23 19:17:02.292 | error | at Function.all  (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/device.js:240:16)
zigbee.0 | 2021-06-23 19:17:02.292 | error | at Function.loadFromDatabaseIfNecessary  (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/device.js:220:55)
zigbee.0 | 2021-06-23 19:17:02.292 | error | (4220) TypeError: Cannot read property 'getEntries' of null
zigbee.0 | 2021-06-23 19:17:02.289 | error | (4220) unhandled promise rejection: Cannot read property 'getEntries' of null
zigbee.0 | 2021-06-23 19:17:02.288 | error | (4220) Unhandled promise rejection. This error originated either by  throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-06-23 19:17:02.286 | info | (4220) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
zigbee.0 | 2021-06-23 19:17:02.283 | info | (4220) terminating
zigbee.0 | 2021-06-23 19:17:02.281 | warn | (4220) Failed to stop zigbee during startup

<!--EndFragment-->
</body>
</html>
```

after a complete reinstall of zigbee adapter and delete all data from it i got this

```
<html><body>
<!--StartFragment-->

zigbee.0 | 2021-06-23 19:48:45.709 | error | (3016) Error herdsman start
-- | -- | -- | --
zigbee.0 | 2021-06-23 19:48:45.708 | error | (3016) Failed to start Zigbee
zigbee.0 | 2021-06-23 19:48:45.706 | error | (3016)  Starting zigbee-herdsman problem : "Error while opening serialport  'Error: Error Resource temporarily unavailable Cannot lock port'"
zigbee.0 | 2021-06-23 19:48:45.271 | info | (3016) Installed Version: iobroker.zigbee@1.5.6
zigbee.0 | 2021-06-23 19:48:45.228 | info | (3016) Starting Zigbee  npm ...
zigbee.0 | 2021-06-23 19:48:45.226 | info | (3016) Try to reconnect. 1 attempts left
zigbee.0 | 2021-06-23 19:48:35.224 | error | (3016) Error herdsman start
zigbee.0 | 2021-06-23 19:48:35.222 | error | (3016) Failed to start Zigbee
zigbee.0 | 2021-06-23 19:48:35.220 | error | (3016) Starting zigbee-herdsman problem : "network commissioning failed - panId collision detected (expected=6754, actual=6755)"
zigbee.0 | 2021-06-23 19:48:24.625 | info | (3016) Installed Version: iobroker.zigbee@1.5.6
zigbee.0 | 2021-06-23 19:48:23.965 | info | (3016) Starting Zigbee  npm ...
zigbee.0 | 2021-06-23 19:48:23.856 | info | (3016) starting. Version 1.5.6 in /opt/iobroker/node_modules/iobroker.zigbee, node: v14.17.0, js-controller: 3.2.16
host.iobroker | 2021-06-23 19:48:17.542 | info | instance system.adapter.zigbee.0 started with pid 3016
host.iobroker | 2021-06-23 19:48:15.684 | info | instance system.adapter.zigbee.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
host.iobroker | 2021-06-23 19:48:15.498 | info | stopInstance system.adapter.zigbee.0 killing pid 2955

<!--EndFragment-->
</body>
</html>
```

after install it from git it got a struct error

```
<html><body>
<!--StartFragment-->

zigbee.0 | 2021-06-23 19:57:08.851 | error | (3590) Error herdsman start
-- | -- | -- | --
zigbee.0 | 2021-06-23 19:57:08.850 | error | (3590) Failed to start Zigbee
zigbee.0 | 2021-06-23 19:57:08.848 | error | (3590)  Starting zigbee-herdsman problem : "Error while opening serialport  'Error: Error Resource temporarily unavailable Cannot lock port'"
zigbee.0 | 2021-06-23 19:57:08.362 | info | (3590) Installed Version: ioBroker/ioBroker.zigbee#a06b80be5f5d62e67b89c716a077352529526121
zigbee.0 | 2021-06-23 19:57:08.309 | info | (3590) Starting Zigbee  npm ...
zigbee.0 | 2021-06-23 19:57:08.307 | info | (3590) Try to reconnect. 1 attempts left
zigbee.0 | 2021-06-23 19:56:58.304 | error | (3590) Error herdsman start
zigbee.0 | 2021-06-23 19:56:58.303 | error | (3590) Failed to start Zigbee
zigbee.0 | 2021-06-23 19:56:58.301 | error | (3590) Starting zigbee-herdsman problem : "Struct length mismatch (expected=16/16, got=32)"
zigbee.0 | 2021-06-23 19:56:45.911 | info | (3590) Installed Version: ioBroker/ioBroker.zigbee#a06b80be5f5d62e67b89c716a077352529526121
zigbee.0 | 2021-06-23 19:56:45.224 | info | (3590) Starting Zigbee  npm ...
zigbee.0 | 2021-06-23 19:56:45.116 | info | (3590) starting. Version 1.5.6 in /opt/iobroker/node_modules/iobroker.zigbee, node: v14.17.0, js-controller: 3.2.16

<!--EndFragment-->
</body>
</html>
```

mod edit - better code tags for readability (A)

**Comment by Apollon77** [comment]
try "Iobroker fix" ad a reboot. something is blocking the serial device of your raspi

**Comment by softwarecrash** [comment]
> 
> 
> try "Iobroker fix" ad a reboot. something is blocking the serial device of your raspi

done, without success. can i test what is accessing the serial port?

**Comment by asgothian** [comment]
- which hardware are you using
- can you do a soft reset on the zigbee hardware (unplug the stick from the system if it is connected with USB)

A.

**Comment by softwarecrash** [comment]
> * which hardware are you using
> * can you do a soft reset on the zigbee hardware (unplug the stick from the system if it is connected with USB)
> 
> A.

a cc2531 usb stick
soft reset i have tried without any changes

**Comment by softwarecrash** [comment]
i think i have found it, my cc2531 runs on the 3.0 firmware, after flashing the 1.2 home firmware, the adapter starts without error

**Comment by MrThreesome** [comment]
Some problem with CC2531. After unplug and plug again several times it works.

<html>
<body>


(1571) Coordinator firmware version: {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}
--


<br class="Apple-interchange-newline">
</body>
</html>

Should I upgrade my CC2531?
