### ISSUE TITLE
Nach jedem Neustart des iobrokers muß zigbee "rebuilded" werden?

### ISSUE THREAD

**Issue by weindler** [ioBroker/ioBroker.zigbee#1148]
Folgende Meldung kommt im Log.

```
<html><body>
<!--StartFragment-->

2021-07-06 17:05:45.696  - warn: host.raspberrypi adapter "zigbee" seems to be installed for a different version of Node.js. Trying to rebuild it... 1 attempt
--
2021-07-06 17:05:45.696  - info: host.raspberrypi iobroker rebuild zigbee
2021-07-06 17:05:46.659  - info:  host.raspberrypi iobroker npm-rebuild: npm rebuild --loglevel error  (System call) in "/opt/iobroker/node_modules/iobroker.zigbee"
2021-07-06 17:05:47.936  - info: host.raspberrypi iobroker npm-rebuild: Rebuild zigbee done
2021-07-06 17:05:48.948  - info: host.raspberrypi iobroker npm-rebuild: exit 0
2021-07-06 17:05:49.000  - info: host.raspberrypi instance system.adapter.zigbee.0 started with pid 1774
2021-07-06 17:05:50.132  - error: host.raspberrypi Caught by controller[0]: /opt/iobroker/node_modules/zigbee-herdsman/node_modules/bindings/bindings.js:121
2021-07-06 17:05:50.133  - error: host.raspberrypi Caught by controller[0]:         throw e;
2021-07-06 17:05:50.133  - error: host.raspberrypi Caught by controller[0]:         ^
2021-07-06 17:05:50.133  - error:  host.raspberrypi Caught by controller[0]: Error: The module  '/opt/iobroker/node_modules/zigbee-herdsman/node_modules/@serialport/bindings/build/Release/bindings.node'
2021-07-06 17:05:50.133  - error: host.raspberrypi Caught by controller[0]: was compiled against a different Node.js version using
2021-07-06 17:05:50.134  - error: host.raspberrypi Caught by controller[0]: NODE_MODULE_VERSION 64. This version of Node.js requires
2021-07-06 17:05:50.134  - error: host.raspberrypi Caught by controller[0]: NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
2021-07-06 17:05:50.134  - error: host.raspberrypi Caught by controller[0]: the module (for instance, using `npm rebuild` or `npm install`).
2021-07-06 17:05:50.134  - error: host.raspberrypi Caught by controller[0]:     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
2021-07-06 17:05:50.135  - error: host.raspberrypi Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:863:32)
2021-07-06 17:05:50.135  - error: host.raspberrypi Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2021-07-06 17:05:50.135  - error: host.raspberrypi Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:887:19)
2021-07-06 17:05:50.135  - error: host.raspberrypi Caught by controller[0]:     at require (internal/modules/cjs/helpers.js:74:18)
2021-07-06 17:05:50.136  - error:  host.raspberrypi Caught by controller[0]:     at bindings  (/opt/iobroker/node_modules/zigbee-herdsman/node_modules/bindings/bindings.js:112:48)
2021-07-06 17:05:50.136  - error: host.raspberrypi Caught by controller[0]:     at Object. (/opt/iobroker/node_modules/zigbee-herdsman/node_modules/@serialport/bindings/lib/linux.js:2:36)
2021-07-06 17:05:50.136  - error: host.raspberrypi Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
2021-07-06 17:05:50.136  - error: host.raspberrypi Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2021-07-06 17:05:50.136  - error: host.raspberrypi Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:863:32)
2021-07-06 17:05:50.137  - error: host.raspberrypi instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2021-07-06 17:05:50.137  - info: host.raspberrypi Adapter system.adapter.zigbee.0 needs rebuild and will be restarted afterwards.
```

Das macht er 3 mal und dann geht die INstanz auf grün und es läuft wieder alles.

Node.js
    v12.22.2
NPM
    6.14.13

Was kann das sein?

Gruß Weindler

Mod edit: proper code tags (A)

**Comment by asgothian** [comment]
- please post logs in code tags (<>) in the future.
- Please check if you have the serial port library installed multiple times.
A

**Comment by weindler** [comment]
Hi, thanks for your answer, how can i check this?
i have on 1 usb2 the conbee stick for zigbee with this com name /dev/ttyACM0
on the other usb 2 i have a usv seaton ellipse
and on the usb 3 i have a samsung ssd (this i have it only for 2 days long)
the errors i have for connect to the ssd over usb 3

**Comment by weindler** [comment]
Ich habe gesehen daß in den Einstellungen die 2 gleichen Ports auszuwählen waren, vielleicht lags an dem, habe aber jetzt folgendes reingeschrieben.

/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2255974-if00

Habe dann den iobroker gestoppt ein weilchen gewartet und dann wieder gestartet und dann hat es ohne rebuilden geklappt, cool danke. Habe eigentlich nicht auf die Einstellung geachtet, daß man das serial direkt angeben muß.

Naja wer lesen kann ist klar im Vorteil. 

Keine Fehler mehr im Log.

Damit ist das Problem behoben.
