### ISSUE TITLE
All devices disconnected

### ISSUE THREAD

**Issue by Flacedoo** [ioBroker/ioBroker.zigbee#1177]
Hi everyone,

I was happily using the Zigbee adapter for the last few months, but today somehow my devices won’t connect anymore. In the devices tab, only the zigbee coordinator shows up, and in the network map all my devices are displayed, but are marked as disconnected. I already checked that it’s not just a range issue by placing some devices directly on top of my zigbee usb dongle. Any ideas what could be the reason for this, or how I could fix it?Here’s the log:

> 2021-08-12 15:53:29.172 - info: zigbee.0 (2002) starting. Version 1.5.6 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.22.1, js-controller: 3.3.15
2021-08-12 15:53:29.461 - info: zigbee.0 (2002) Starting Zigbee npm ...
2021-08-12 15:53:30.492 - info: zigbee.0 (2002) Installed Version: iobroker.zigbee@1.5.6
2021-08-12 15:53:32.763 - info: zigbee.0 (2002) Coordinator firmware version: {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20201127}}
2021-08-12 15:53:32.794 - info: zigbee.0 (2002) --> transmitPower : normal
2021-08-12 15:53:32.810 - info: zigbee.0 (2002) Currently no devices.
2021-08-12 15:53:32.814 - info: zigbee.0 (2002) Zigbee started
2021-08-12 15:55:28.369 - info: zigbee.0 (2002) Zigbee: allowing new devices to join.
2021-08-12 15:56:29.680 - info: zigbee.0 (2002) Zigbee: stop joining
2021-08-12 15:57:28.241 - info: host.musicpi-tv iobroker upgrade discovery@2.7.0
2021-08-12 15:57:33.953 - info: host.musicpi-tv iobroker Update discovery from @2.6.2 to @2.7.0
2021-08-12 15:57:35.870 - info: host.musicpi-tv iobroker NPM version: 6.14.12
2021-08-12 15:57:35.882 - info: host.musicpi-tv iobroker npm install iobroker.discovery@2.7.0 --loglevel error --prefix "/opt/iobroker" (System call)
2021-08-12 15:59:06.956 - info: zigbee.0 (2002) Zigbee: allowing new devices to join.
2021-08-12 16:00:08.239 - info: zigbee.0 (2002) Zigbee: stop joining
2021-08-12 16:01:32.099 - error: zigbee.0 (2002) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-08-12 16:01:32.101 - error: zigbee.0 (2002) unhandled promise rejection: Cannot read property 'mapped' of undefined
2021-08-12 16:01:32.104 - error: zigbee.0 (2002) TypeError: Cannot read property 'mapped' of undefined
at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:449:36)
2021-08-12 16:01:32.106 - error: zigbee.0 (2002) Cannot read property 'mapped' of undefined
2021-08-12 16:01:32.155 - info: zigbee.0 (2002) cleaned everything up...
2021-08-12 16:01:32.162 - info: zigbee.0 (2002) Zigbee: disabling joining new devices.
2021-08-12 16:01:32.426 - info: zigbee.0 (2002) terminating
2021-08-12 16:01:32.428 - warn: zigbee.0 (2002) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-08-12 16:01:33.169 - error: host.musicpi-tv instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-08-12 16:01:33.185 - info: host.musicpi-tv Restart adapter system.adapter.zigbee.0 because enabled
2021-08-12 16:02:03.278 - info: host.musicpi-tv instance system.adapter.zigbee.0 started with pid 2088
2021-08-12 16:02:06.501 - info: host.musicpi-tv iobroker upload [6] discovery.admin /opt/iobroker/node_modules/iobroker.discovery/admin/words.js words.js application/javascript
2021-08-12 16:02:06.726 - info: host.musicpi-tv iobroker Update "system.adapter.discovery.0"
2021-08-12 16:02:06.947 - info: host.musicpi-tv iobroker upload [5] discovery.admin /opt/iobroker/node_modules/iobroker.discovery/admin/translateTools.js translateTools.js application/javascript
2021-08-12 16:02:07.185 - info: host.musicpi-tv iobroker upload [4] discovery.admin /opt/iobroker/node_modules/iobroker.discovery/admin/settings_m.html settings_m.html text/html
2021-08-12 16:02:07.306 - info: host.musicpi-tv iobroker upload [3] discovery.admin /opt/iobroker/node_modules/iobroker.discovery/admin/settings.html settings.html text/html
2021-08-12 16:02:07.429 - info: host.musicpi-tv iobroker upload [2] discovery.admin /opt/iobroker/node_modules/iobroker.discovery/admin/index_m.html index_m.html text/html
2021-08-12 16:02:07.550 - info: host.musicpi-tv iobroker upload [1] discovery.admin /opt/iobroker/node_modules/iobroker.discovery/admin/index.html index.html text/html
2021-08-12 16:02:07.737 - info: host.musicpi-tv iobroker upload [0] discovery.admin /opt/iobroker/node_modules/iobroker.discovery/admin/discovery.png discovery.png image/png
2021-08-12 16:02:07.848 - info: host.musicpi-tv iobroker Adapter "discovery" updated
2021-08-12 16:02:08.918 - info: host.musicpi-tv iobroker exit 0
2021-08-12 16:02:12.681 - info: zigbee.0 (2088) starting. Version 1.5.6 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.22.1, js-controller: 3.3.15
2021-08-12 16:02:12.989 - info: zigbee.0 (2088) Starting Zigbee npm ...
2021-08-12 16:02:14.006 - info: zigbee.0 (2088) Installed Version: iobroker.zigbee@1.5.6
2021-08-12 16:02:16.261 - info: zigbee.0 (2088) Coordinator firmware version: {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20201127}}
2021-08-12 16:02:16.289 - info: zigbee.0 (2088) --> transmitPower : normal
2021-08-12 16:02:16.306 - info: zigbee.0 (2088) Currently no devices.
2021-08-12 16:02:16.310 - info: zigbee.0 (2088) Zigbee started

**Comment by Flacedoo** [comment]
Any alternative ideas? That actually worked for a few days now, but today everything was back to disconnected again. Unfortunately the exact same backup I used last time didn‘t change anything.. Here’s the log again:

> 2021-08-17 18:43:09.813 - info: host.musicpi-tv instance system.adapter.zigbee.0 started with pid 1356
2021-08-17 18:43:16.060 - info: zigbee.0 (1356) starting. Version 1.5.6 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.22.1, js-controller: 3.3.15
2021-08-17 18:43:16.251 - info: zigbee.0 (1356) Starting Zigbee npm ...
2021-08-17 18:43:16.964 - info: zigbee.0 (1356) Installed Version: iobroker.zigbee@1.5.6
2021-08-17 18:43:18.905 - info: zigbee.0 (1356) Coordinator firmware version: {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20201127}}
2021-08-17 18:43:18.920 - info: zigbee.0 (1356) --> transmitPower : normal
2021-08-17 18:43:18.938 - info: zigbee.0 (1356) Currently 12 devices are joined:
2021-08-17 18:43:18.999 - info: zigbee.0 (1356) 0x804b50fffe584d1e (addr 43121): BW-SS7_1gang - BlitzWolf Zigbee 3.0 smart light switch module 1 gang (Router)
2021-08-17 18:43:19.006 - info: zigbee.0 (1356) 0x804b50fffe584b87 (addr 34915): BW-SS7_1gang - BlitzWolf Zigbee 3.0 smart light switch module 1 gang (Router)
2021-08-17 18:43:19.009 - info: zigbee.0 (1356) 0x804b50fffe584c2c (addr 55753): BW-SS7_1gang - BlitzWolf Zigbee 3.0 smart light switch module 1 gang (Router)
2021-08-17 18:43:19.013 - info: zigbee.0 (1356) 0x0017880106b2b266 (addr 19431): 8718699673147 - Philips Hue white A60 bulb E27 bluetooth (Router)
2021-08-17 18:43:19.016 - info: zigbee.0 (1356) 0x086bd7fffe5aeafd (addr 38951): HGZB-01 - Nue / 3A Smart Zigbee 3.0 light controller (Router)
2021-08-17 18:43:19.019 - info: zigbee.0 (1356) 0x84fd27fffee27aa6 (addr 55107): BW-SS7_2gang - BlitzWolf Zigbee 3.0 smart light switch module 2 gang (Router)
2021-08-17 18:43:19.022 - info: zigbee.0 (1356) 0x00158d000635e179 (addr 49207): WSDCGQ01LM - Xiaomi MiJia temperature & humidity sensor (EndDevice)
2021-08-17 18:43:19.024 - info: zigbee.0 (1356) 0x00158d0006c47b30 (addr 36209): SJCGQ11LM - Xiaomi Aqara water leak sensor (EndDevice)
2021-08-17 18:43:19.027 - info: zigbee.0 (1356) 0x84fd27fffe5f0e23 (addr 17551): TS0121_plug - TuYa 10A UK or 16A EU smart plug (Router)
2021-08-17 18:43:19.030 - info: zigbee.0 (1356) 0xcc86ecfffef3c0b7 (addr 21037): TS0121_plug - TuYa 10A UK or 16A EU smart plug (Router)
2021-08-17 18:43:19.032 - info: zigbee.0 (1356) 0xcc86ecfffe4ea2e9 (addr 52655): TS0121_plug - TuYa 10A UK or 16A EU smart plug (Router)
2021-08-17 18:43:19.036 - info: zigbee.0 (1356) 0x847127fffe411382 (addr 15216): LED1732G11 - IKEA TRADFRI LED bulb E27 1000 lumen, dimmable, white spectrum, opal white (Router)
2021-08-17 18:43:19.038 - info: zigbee.0 (1356) Zigbee started
2021-08-17 18:44:59.090 - warn: zigbee.0 (1356) Failed to ping 0x804b50fffe584d1e TS0003
2021-08-17 18:44:59.800 - warn: zigbee.0 (1356) Failed to ping 0x804b50fffe584b87 TS0003
2021-08-17 18:45:00.489 - warn: zigbee.0 (1356) Failed to ping 0x0017880106b2b266 LWA001
2021-08-17 18:45:01.121 - warn: zigbee.0 (1356) Failed to ping 0x804b50fffe584c2c TS0003
2021-08-17 18:45:02.784 - warn: zigbee.0 (1356) Failed to ping 0x086bd7fffe5aeafd LXN59-1S7LX1.0
2021-08-17 18:45:03.411 - warn: zigbee.0 (1356) Failed to ping 0x84fd27fffee27aa6 TS0003
2021-08-17 18:45:21.661 - warn: zigbee.0 (1356) Send command to 0x804b50fffe584b87 failed with: Code 205 (No network route)
2021-08-17 18:45:41.912 - warn: zigbee.0 (1356) Send command to 0x804b50fffe584b87 failed with: Code 205 (No network route)
2021-08-17 18:46:02.171 - warn: zigbee.0 (1356) Send command to 0x804b50fffe584b87 failed with: Code 205 (No network route)
2021-08-17 18:46:17.070 - error: zigbee.0 (1356) Failed to remove Error: AREQ - ZDO - mgmtLeaveRsp after 10000ms
at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/dist/utils/waitress.js:37:35)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)
2021-08-17 18:46:17.701 - warn: zigbee.0 (1356) Failed to ping 0xcc86ecfffef3c0b7 TS0121
2021-08-17 18:46:22.716 - warn: zigbee.0 (1356) Send command to 0x804b50fffe584b87 failed with: Code 205 (No network route)
2021-08-17 18:46:27.728 - warn: zigbee.0 (1356) Failed to ping 0x84fd27fffe5f0e23 TS0121
2021-08-17 18:46:28.565 - warn: zigbee.0 (1356) Failed to ping 0xcc86ecfffe4ea2e9 TS0121
2021-08-17 18:46:29.439 - warn: zigbee.0 (1356) Failed to ping 0x847127fffe411382 TRADFRI bulb E27 WS opal 1000lm
2021-08-17 18:46:42.508 - warn: zigbee.0 (1356) Send command to 0x804b50fffe584b87 failed with: Code 205 (No network route)
2021-08-17 18:47:23.226 - warn: zigbee.0 (1356) Send command to 0x0017880106b2b266 failed with: Code 205 (No network route)
2021-08-17 18:47:43.677 - warn: zigbee.0 (1356) Send command to 0x0017880106b2b266 failed with: Code 205 (No network route)

**Comment by kamikazemimmi** [comment]
I am not quite sure, whether we have had the same entries in log, but we have had a simular problem. I try also a new usb device. I tried conbee and with this usb device it works (until one device, but I don't know exactely when the problem really occur there, but the most other things really work fine now.)
