### ISSUE TITLE
Absturz vom Zigbee Adapter

### ISSUE THREAD

**Issue by JogiBarbarski** [ioBroker/ioBroker.zigbee#1192]
Wenn er mal läuft und man ihn neu startet, geht nichts mehr.

zigbee.0 | 2021-08-24 21:36:16.845 | error | Error herdsman start
-- | -- | -- | --
zigbee.0 | 2021-08-24 21:36:16.845 | error | Failed to start Zigbee
zigbee.0 | 2021-08-24 21:36:16.844 | error | Starting zigbee-herdsman problem : "Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'"
zigbee.0 | 2021-08-24 21:36:06.634 | error | Error herdsman start
zigbee.0 | 2021-08-24 21:36:06.634 | error | Failed to start Zigbee
zigbee.0 | 2021-08-24 21:36:06.633 | error | Starting zigbee-herdsman problem : "startup failed - configuration-adapter mismatch - see logs above for more information"
zigbee.0 | 2021-08-24 21:36:06.631 | error | Re-commissioning your network will require re-pairing of all devices!
zigbee.0 | 2021-08-24 21:36:06.630 | error | If you wish to re-commission your network, please remove coordinator backup at /opt/iobroker/iobroker-data/zigbee_0/nvbackup.json.
zigbee.0 | 2021-08-24 21:36:06.630 | error | Please update configuration to prevent further issues.
zigbee.0 | 2021-08-24 21:36:06.629 | error | - Channel List: configured=13, adapter=13
zigbee.0 | 2021-08-24 21:36:06.627 | error | - Network Key: configured=01030507090b0d0f00020406080a0c0a, adapter=01030507090b0d0f00020406080a0c0a
zigbee.0 | 2021-08-24 21:36:06.626 | error | - Extended PAN ID: configured=9fb49f21004b1200, adapter=9fb49f21004b1200
zigbee.0 | 2021-08-24 21:36:06.625 | error | - PAN ID: configured=6755, adapter=6755
zigbee.0 | 2021-08-24 21:36:06.624 | error | Configuration is not consistent with adapter state/backup!
zigbee.0 | 2021-08-24 21:34:21.378 | error | Cannot read property 'getEntries' of null
zigbee.0 | 2021-08-24 21:34:21.377 | error | TypeError: Cannot read property 'getEntries' of null at Function.loadFromDatabaseIfNecessary (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/device.js:220:55) at Function.all (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/device.js:240:16) at Controller.getDevices (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/controller.js:303:31) at ZigbeeController.getClients (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:228:49) at DeviceAvailability.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceAvailability.js:222:43) at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:214:42) at ZigbeeController.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:385:20) at Zigbee.onUnload (/opt/iobroker/node_modules/iobroker.zigbee/main.js:696:41) at processTicksAndRejections (internal/process/task_queues.js:97:5)
zigbee.0 | 2021-08-24 21:34:21.376 | error | unhandled promise rejection: Cannot read property 'getEntries' of null
zigbee.0 | 2021-08-24 21:34:21.376 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

**Comment by JogiBarbarski** [comment]
zigbee.0 | 2021-08-24 21:44:41.562 | error | Running despite adapter configuration mismatch as configured. Please update the adapter to compatible firmware and recreate your network as soon as possible.
-- | -- | -- | --
zigbee.0 | 2021-08-24 21:44:41.562 | error | Re-commissioning your network will require re-pairing of all devices!
zigbee.0 | 2021-08-24 21:44:41.561 | error | If you wish to re-commission your network, please remove coordinator backup at /opt/iobroker/iobroker-data/zigbee_0/nvbackup.json.
zigbee.0 | 2021-08-24 21:44:41.561 | error | Please update configuration to prevent further issues.
zigbee.0 | 2021-08-24 21:44:41.560 | error | - Channel List: configured=13, adapter=13
zigbee.0 | 2021-08-24 21:44:41.559 | error | - Network Key: configured=01030507090b0d0f00020406080a0c0a, adapter=01030507090b0d0f00020406080a0c0a
zigbee.0 | 2021-08-24 21:44:41.558 | error | - Extended PAN ID: configured=9fb49f21004b1200, adapter=9fb49f21004b1200
zigbee.0 | 2021-08-24 21:44:41.558 | error | - PAN ID: configured=6755, adapter=6755
zigbee.0 | 2021-08-24 21:44:41.557 | error | Configuration is not consistent with adapter state/backup!

**Comment by djsirius2410** [comment]
```

 
zigbee.0
4312	2021-08-24 11:02:51.340	info	Installed Version: iobroker.zigbee@1.5.6
 
zigbee.0
4312	2021-08-24 11:02:50.688	debug	Starting zigbee-herdsman...
 
zigbee.0
4312	2021-08-24 11:02:50.686	info	Starting Zigbee npm ...
 
zigbee.0
4312	2021-08-24 11:02:50.679	debug	Using zigbee-herdsman with settings: {"network":{"panID":6755,"channelList":[11],"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"extenedPanID":[221,221,221,221,221,221,221,221]},"databasePath":"/opt/iobroker/iobroker-data/zigbee_0/shepherd.db","backupPath":"/opt/iobroker/iobroker-data/zigbee_0/nvbackup.json","serialPort":{"baudRate":115200,"rtscts":false,"path":"/dev/ttyACM0","adapter":"zstack"}}
 
zigbee.0
4312	2021-08-24 11:02:50.629	info	starting. Version 1.5.6 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.22.1, js-controller: 3.3.15
 
zigbee.0
4246	2021-08-24 11:02:10.759	warn	Got terminate signal. Checking desired PID: 4301 vs own PID 4246
 
zigbee.0
4246	2021-08-24 11:02:10.741	error	Cannot read property 'getEntries' of null
 
zigbee.0
4246	2021-08-24 11:02:10.738	error	TypeError: Cannot read property 'getEntries' of null at Function.loadFromDatabaseIfNecessary (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/device.js:220:55) at Function.all (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/device.js:240:16) at Controller.getDevices (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/controller.js:303:31) at ZigbeeController.getClients (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:228:49) at DeviceAvailability.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceAvailability.js:222:43) at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:214:42) at ZigbeeController.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:385:20) at Zigbee.onUnload (/opt/iobroker/node_modules/iobroker.zigbee/main.js:696:41) at processTicksAndRejections (internal/process/task_queues.js:97:5)
 
zigbee.0
4246	2021-08-24 11:02:10.732	error	unhandled promise rejection: Cannot read property 'getEntries' of null
 
zigbee.0
4246	2021-08-24 11:02:10.729	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
{1}
zigbee.0
4246	2021-08-24 11:02:10.724	info	Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
{1}
zigbee.0
4246	2021-08-24 11:02:10.721	info	terminating
{1}
zigbee.0
4246	2021-08-24 11:02:10.718	warn	Failed to stop zigbee during startup
{1}
zigbee.0
4246	2021-08-24 11:02:10.712	info	Zigbee: disabling joining new devices.
{1}
zigbee.0
4246	2021-08-24 11:02:10.697	info	cleaned everything up...
{1}
zigbee.0
4246	2021-08-24 11:02:10.692	warn	Got terminate signal. Checking desired PID: 0 vs own PID 4246
{1}
zigbee.0
4246	2021-08-24 11:01:45.583	info	Installed Version: iobroker.zigbee@1.5.6
{1}
zigbee.0
4246	2021-08-24 11:01:44.949	debug	Starting zigbee-herdsman...
{1}
zigbee.0
4246	2021-08-24 11:01:44.947	info	Starting Zigbee npm ...
{1}
zigbee.0
4246	2021-08-24 11:01:44.940	debug	Using zigbee-herdsman with settings: {"network":{"panID":6755,"channelList":[11],"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"extenedPanID":[221,221,221,221,221,221,221,221]},"databasePath":"/opt/iobroker/iobroker-data/zigbee_0/shepherd.db","backupPath":"/opt/iobroker/iobroker-data/zigbee_0/nvbackup.json","serialPort":{"baudRate":115200,"rtscts":false,"path":"/dev/ttyACM0","adapter":"zstack"}}
 
zigbee.0
4246	2021-08-24 11:01:44.890	info	starting. Version 1.5.6 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.22.1, js-controller: 3.3.15
 
zigbee.0
4246	2021-08-24 11:01:44.370	debug	statesDB connected
 
zigbee.0
4246	2021-08-24 11:01:44.368	debug	States connected to redis: 192.168.1.16:9000
 
zigbee.0
4246	2021-08-24 11:01:44.312	debug	States create User PubSub Client
 
zigbee.0
4246	2021-08-24 11:01:44.309	debug	States create System PubSub Client
 
zigbee.0
4246	2021-08-24 11:01:44.293	debug	Redis States: Use Redis connection: 192.168.1.16:9000
 
zigbee.0
4246	2021-08-24 11:01:44.288	debug	objectDB connected
 
zigbee.0
4246	2021-08-24 11:01:44.270	debug	Objects connected to redis: 192.168.1.16:9001
 
zigbee.0
4246	2021-08-24 11:01:44.246	debug	Objects client initialize lua scripts
 
zigbee.0
4246	2021-08-24 11:01:44.244	debug	Objects create User PubSub Client
 
zigbee.0
4246	2021-08-24 11:01:44.241	debug	Objects create System PubSub Client
 
zigbee.0
4246	2021-08-24 11:01:44.231	debug	Objects client ready ... initialize now
 
zigbee.0
4246	2021-08-24 11:01:44.172	debug	Redis Objects: Use Redis connection: 192.168.1.16:9001
 
zigbee.0
4235	2021-08-24 11:01:40.166	warn	Got terminate signal. Checking desired PID: 4246 vs own PID 4235
 
zigbee.0
4235	2021-08-24 11:01:40.152	error	Cannot read property 'error' of undefined
 
zigbee.0
4235	2021-08-24 11:01:40.150	error	TypeError: Cannot read property 'error' of undefined at Zigbee.onUnload (/opt/iobroker/node_modules/iobroker.zigbee/main.js:700:22) at Zigbee.emit (events.js:314:20) at stop (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8747:22) at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5539:29) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:234:37) at processImmediate (internal/timers.js:461:21)
 
zigbee.0
4235	2021-08-24 11:01:40.137	error	unhandled promise rejection: Cannot read property 'error' of undefined
 
zigbee.0
4235	2021-08-24 11:01:40.134	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
{1}
zigbee.0
4235	2021-08-24 11:01:40.124	warn	Got terminate signal. Checking desired PID: 0 vs own PID 4235
{1}
zigbee.0
4235	2021-08-24 11:01:39.767	warn	Terminated (NO_ADAPTER_CONFIG_FOUND): Without reason
{1}
zigbee.0
4235	2021-08-24 11:01:39.701	error	adapter disabled
{1}
zigbee.0
4235	2021-08-24 11:01:39.330	debug	statesDB connected
{1}
zigbee.0
4235	2021-08-24 11:01:39.328	debug	States connected to redis: 192.168.1.16:9000
{1}
zigbee.0
4235	2021-08-24 11:01:39.269	debug	States create User PubSub Client
{1}
zigbee.0
4235	2021-08-24 11:01:39.266	debug	States create System PubSub Client
{1}
zigbee.0
4235	2021-08-24 11:01:39.249	debug	Redis States: Use Redis connection: 192.168.1.16:9000
{1}
zigbee.0
4235	2021-08-24 11:01:39.244	debug	objectDB connected
{1}
zigbee.0
4235	2021-08-24 11:01:39.226	debug	Objects connected to redis: 192.168.1.16:9001
{1}
zigbee.0
4235	2021-08-24 11:01:39.201	debug	Objects client initialize lua scripts
{1}
zigbee.0
4235	2021-08-24 11:01:39.199	debug	Objects create User PubSub Client
{1}
zigbee.0
4235	2021-08-24 11:01:39.197	debug	Objects create System PubSub Client
{1}
zigbee.0
4235	2021-08-24 11:01:39.193	debug	Objects client ready ... initialize now
{1}
zigbee.0
4235	2021-08-24 11:01:39.133	debug	Redis Objects: Use Redis connection: 192.168.1.16:9001
{1}
zigbee.0
1427	2021-08-24 11:01:31.692	error	Cannot read property 'getEntries' of null
{1}
zigbee.0
1427	2021-08-24 11:01:31.691	error	TypeError: Cannot read property 'getEntries' of null at Function.loadFromDatabaseIfNecessary (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/device.js:220:55) at Function.all (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/device.js:240:16) at Controller.getDevices (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/controller.js:303:31) at ZigbeeController.getClients (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:228:49) at DeviceAvailability.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceAvailability.js:222:43) at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:214:42) at ZigbeeController.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:385:20) at Zigbee.onUnload (/opt/iobroker/node_modules/iobroker.zigbee/main.js:696:41) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:97:5)
{1}
zigbee.0
1427	2021-08-24 11:01:31.689	error	unhandled promise rejection: Cannot read property 'getEntries' of null
{1}
zigbee.0
1427	2021-08-24 11:01:31.688	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
{1}
zigbee.0
1427	2021-08-24 11:01:31.686	info	Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
{1}
zigbee.0
1427	2021-08-24 11:01:31.684	info	terminating
{1}
zigbee.0
1427	2021-08-24 11:01:31.683	warn	Failed to stop zigbee during startup
{1}
zigbee.0
1427	2021-08-24 11:01:31.680	info	Zigbee: disabling joining new devices.
{1}
zigbee.0
1427	2021-08-24 11:01:31.675	info	cleaned everything up...
{1}
zigbee.0
1427	2021-08-24 11:01:31.673	info	Got terminate signal TERMINATE_YOURSELF
{1}

```

**Comment by djsirius2410** [comment]
Kann mir hier keiner helfen? 
Was kann ich tun, damit ich meinen Stick wieder ans laufen bekomme?
Liegt es vielleicht an dem Update vom JS-Controller? Vielen Dank!

**Comment by arteck** [comment]
es steht alles in den Fehlermeldungen man muss es nur lesen

Starting zigbee-herdsman problem : "startup failed - configuration-adapter mismatch - see logs above for more information"

.....

If you wish to re-commission your network, please remove coordinator backup at /opt/iobroker/iobroker-data/zigbee_0/nvbackup.json.
