### ISSUE TITLE
Probleme mit neuem CC2531

### ISSUE THREAD

**Issue by stmb-100** [ioBroker/ioBroker.zigbee#1195]
Hallo
ich bekomme den CC2531 nicht zum laufen. Hat jemand eine Idee ?

/dev/serial/by-id usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CDE5891-if00

LG
Stefan

```
zigbee.0	2021-08-27 09:24:25.450	info	(17481) Zigbee started
zigbee.0	2021-08-27 09:24:25.448	info	(17481) Currently no devices.
zigbee.0	2021-08-27 09:24:25.438	info	(17481) --> transmitPower : normal
zigbee.0	2021-08-27 09:24:25.429	info	(17481) Coordinator firmware version: {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20201127}}
zigbee.0	2021-08-27 09:24:23.431	info	(17481) Installed Version: iobroker.zigbee@1.6.0
zigbee.0	2021-08-27 09:24:23.060	info	(17481) Starting Zigbee npm ...
zigbee.0	2021-08-27 09:24:22.927	info	(17481) starting. Version 1.6.0 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.22.4, js-controller: 3.3.15
zigbee.0	2021-08-27 09:23:48.341	warn	(17463) Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee.0	2021-08-27 09:23:48.339	info	(17463) terminating
zigbee.0	2021-08-27 09:23:47.851	info	(17463) Zigbee: disabling joining new devices.
zigbee.0	2021-08-27 09:23:47.847	info	(17463) cleaned everything up...
zigbee.0	2021-08-27 09:23:47.816	error	(17463) SRSP - SYS - osalNvRead after 0,2ms
zigbee.0	2021-08-27 09:23:47.815	error	(17463) Error: SRSP - SYS - osalNvRead after 0,2ms at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (internal/timers.js:554:17)
zigbee.0	2021-08-27 09:23:47.785	error	(17463) unhandled promise rejection: SRSP - SYS - osalNvRead after 0,2ms
zigbee.0	2021-08-27 09:23:47.784	error	(17463) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0	2021-08-27 09:23:47.777	info	(17463) Zigbee started
```

**Comment by arteck** [comment]
es ist der neue herdsman .. der ein Problem mit den alten Firmwares hat.. vor allem mit den cc2531 Sticks

empfehlung kauft was Ordentliches.. bitte..
