### ISSUE TITLE
VirtualBox/Ubuntu/Docker/CC2531 not working

### ISSUE THREAD

**Issue by Karatekid2407** [ioBroker/ioBroker.zigbee#121]
Hi,

i have the issue that my stick was working and now it isn't.
I tried really much and did not find a solution.

here the error from iobroker

```
2018-12-13 19:20:58.613 - error: Caught by controller[0]: Thu, 13 Dec 2018 18:20:46 GMT zigbee-shepherd:init zigbee-shepherd booting...
--
2018-12-13 19:20:58.613 - error: Caught by controller[1]: Thu, 13 Dec 2018 18:20:46 GMT cc-znp The serialport /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018ECDFD4-if00 is opened.
2018-12-13 19:20:58.614 - error: Caught by controller[2]: Thu, 13 Dec 2018 18:20:46 GMT zigbee-shepherd:request REQ --> SYS:osalNvRead
2018-12-13 19:20:58.614 - error: Caught by controller[3]: Thu, 13 Dec 2018 18:20:46 GMT cc-znp:SREQ --> SYS:osalNvRead, { id: 3840, offset: 0, len: 1, value: [ 85 ] }
2018-12-13 19:20:58.614 - error: Caught by controller[4]: Thu, 13 Dec 2018 18:20:49 GMT cc-znp:SRSP <-- SYS:osalNvRead, __timeout__
2018-12-13 19:20:58.614 - error: Caught by controller[5]: Thu, 13 Dec 2018 18:20:49 GMT zigbee-shepherd:request RSP <-- SYS:osalNvRead
2018-12-13 19:20:58.614 - error: Caught by controller[6]: Thu, 13 Dec 2018 18:20:49 GMT zigbee-shepherd:init Coordinator initialize had an error: Error: request timeout
2018-12-13 19:20:58.614 - error: Caught by controller[6]: at CcZnp. (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/cc-znp/lib/ccznp.js:254:22)
2018-12-13 19:20:58.614 - error: Caught by controller[6]: at Object.onceWrapper (events.js:315:30)
2018-12-13 19:20:58.614 - error: Caught by controller[6]: at emitOne (events.js:116:13)
2018-12-13 19:20:58.614 - error: Caught by controller[6]: at CcZnp.emit (events.js:211:7)
2018-12-13 19:20:58.614 - error: Caught by controller[6]: at Timeout. (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/cc-znp/lib/ccznp.js:233:18)
2018-12-13 19:20:58.614 - error: Caught by controller[6]: at ontimeout (timers.js:498:11)
2018-12-13 19:20:58.614 - error: Caught by controller[6]: at tryOnTimeout (timers.js:323:5)
2018-12-13 19:20:58.614 - error: Caught by controller[6]: at Timer.listOnTimeout (timers.js:290:5)
2018-12-13 19:20:58.614 - error: Caught by controller[7]: 2018-12-13T18:20:49.209Z zigbee:controller debug Error while starting zigbee-shepherd, attemping to fix... (takes 60 seconds) undefined
2018-12-13 19:20:58.614 - error: Caught by controller[8]: Thu, 13 Dec 2018 18:20:49 GMT cc-znp The serialport /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018ECDFD4-if00 is closed.
2018-12-13 19:20:58.614 - error: Caught by controller[9]: Thu, 13 Dec 2018 18:20:58 GMT zigbee-shepherd zigbee-shepherd is stopping.
2018-12-13 19:20:58.614 - error: Caught by controller[10]: Thu, 13 Dec 2018 18:20:58 GMT zigbee-shepherd zigbee-shepherd is stopped.
2018-12-13 19:20:58.614 - error: Caught by controller[10]: 2018-12-13T18:20:58.595Z zigbee:controller info zigbee-shepherd stopped undefined
```

**Comment by Karatekid2407** [comment]
The questions why?!
Is there a possibility to debug?

I have access in docker to 
- /dev/serial/by-id/usb-....
- /dev/ttyACM0
None of them is working in iobroker
Both have get 777 rights.
What else is needed?

And the thing is that it was working and now it isn't.
The stick is always resetting (hearing the Host-System (Win10) USB-sound of unplugging) because I think he will not used?!

**Comment by Karatekid2407** [comment]
Same problem directly on a raspberry pi with docker?!


```
> zigbee2mqtt@1.0.1 start /app
> node index.js
zigbee2mqtt:info 2018-12-23 22:20:12 Logging to directory: '/app/data/log/2018-12-23.22-20-12'
zigbee2mqtt:info 2018-12-23 22:20:13 Starting zigbee2mqtt version 1.0.1 (commit #84593a5)
zigbee2mqtt:info 2018-12-23 22:20:13 Starting zigbee-shepherd
zigbee2mqtt:info 2018-12-23 22:20:16 Error while starting zigbee-shepherd, attemping to fix... (takes 60 seconds)
zigbee2mqtt:info 2018-12-23 22:21:16 Starting zigbee-shepherd
zigbee2mqtt:error 2018-12-23 22:21:19 Error while starting zigbee-shepherd!
zigbee2mqtt:error 2018-12-23 22:21:19 Press the reset button on the stick (the one closest to the USB) and start again
zigbee2mqtt:error 2018-12-23 22:21:19 Failed to start
{"message":"request timeout","stack":"Error: request timeout\n    at CcZnp.<anonymous> (/app/node_modules/cc-znp/lib/ccznp.js:255:22)\n    at Object.onceWrapper (events.js:315:30)\n    at emitOne (events.js:116:13)\n    at CcZnp.emit (events.js:211:7)\n    at Timeout.<anonymous> (/app/node_modules/cc-znp/lib/ccznp.js:234:18)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)"}
```

**Comment by Karatekid2407** [comment]
Can be closed. Since i updated the SW of CC2531 everything is fine.
