### ISSUE TITLE
Cloud not migrate from zigbee adapter 1.6.0 to 1.6.3

### ISSUE THREAD

**Issue by dp20eic** [ioBroker/ioBroker.zigbee#1236]
Hi,

I have tried to move forwared to zigbee adapter 1.6.3 but after update the adapter is not running anymore, so I go back to 1.6.0 and everything is running again.

My system:
PC with proxmox
Iobroker running as LXC Container:

> PlatformBetriebssystem:linux
Architektur:x64
CPUs:2
Geschwindigkeit:3200 MHz
Modell:AMD Phenom(tm) II X4 955 Processor
RAM:3.5 GB
System-Betriebszeit:02:12:28
Node.js:v12.22.5
NPM:7.5.2
Datenträgergröße:12.0 GB
Festplatte frei:3.0 GB
Adapter-Anzahl:441
Betriebszeit:01:19:29
Aktive Instanzen:26
Pfad:/opt/iobroker/

Iobroker is on "beta" actual all adaper a running without problems only after update to zigbee 1.6.3 this adapter have problems.

`
2021-10-11 11:32:18.141  - error: host.iobroker instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2021-10-11 11:32:48.539  - error: host.iobroker Caught by controller[0]: Error: Cannot find module 'zigbee-herdsman/dist/adapter/serialPortUtils'
2021-10-11 11:32:48.539  - error: host.iobroker Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.zigbee/lib/seriallist.js
2021-10-11 11:32:48.539  - error: host.iobroker Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.zigbee/main.js
2021-10-11 11:32:48.540  - error: host.iobroker Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/lib/seriallist.js:3:25)
2021-10-11 11:32:48.540  - error: host.iobroker Caught by controller[0]:     '/opt/iobroker/node_modules/iobroker.zigbee/lib/seriallist.js',
2021-10-11 11:32:48.540  - error: host.iobroker Caught by controller[0]:     '/opt/iobroker/node_modules/iobroker.zigbee/main.js'
2021-10-11 11:32:48.541  - error: host.iobroker instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2021-10-11 11:33:18.945  - error: host.iobroker Caught by controller[0]: Error: Cannot find module 'zigbee-herdsman/dist/adapter/serialPortUtils'
2021-10-11 11:33:18.945  - error: host.iobroker Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.zigbee/lib/seriallist.js
2021-10-11 11:33:18.945  - error: host.iobroker Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.zigbee/main.js
2021-10-11 11:33:18.946  - error: host.iobroker Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/lib/seriallist.js:3:25)
2021-10-11 11:33:18.946  - error: host.iobroker Caught by controller[0]:     '/opt/iobroker/node_modules/iobroker.zigbee/lib/seriallist.js',
2021-10-11 11:33:18.946  - error: host.iobroker Caught by controller[0]:     '/opt/iobroker/node_modules/iobroker.zigbee/main.js'
2021-10-11 11:37:51.962  - info: host.iobroker iobroker npm rebuild --loglevel error (System call1) in "/opt/iobroker/node_modules/iobroker.zigbee"
`

Did I miss somethin about new "herdsman"?

with kind regards
Bernd

**Comment by dp20eic** [comment]
> > Cannot find module 'zigbee-herdsman/dist/adapter/serialPortUtils'
> 
> this means that the zigbee-herdsman has not been installed... check that the zigbee-herdsman is installed in the node_modules.

Hi,
is there a different between Version 1.6.0 up to 1.6.3?
With 1.6.0 I have no problem!

Actual I have installed zigbee adapter version 1.6.0 and if I checked zigbee-herdsman Iget the following:

`iobroker@iobroker:/opt/iobroker$ npm list zigbee-herdsman`
`iobroker.inst@2.0.3 /opt/iobroker`
`-- iobroker.zigbee@1.6.0`
`  +-- zigbee-herdsman-converters@14.0.217`
  | `-- zigbee-herdsman@0.13.126`
  `-- zigbee-herdsman@0.13.127`

with kind regards
Bernd

p.s.: I'm for the next 5 Dasy "afk"
