### ISSUE TITLE
Adapter does not start after update to Nodejs v14.18.1

### ISSUE THREAD

**Issue by Claus1985** [ioBroker/ioBroker.zigbee#1279]
After Update to Nodejs v14.18.1 the adapter won´t start and I get the following error in log:;

`<html>
<body>

2021-11-24 17:19:54.081 | error | instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | --
| error | Caught by controller[0]: }
| error | Caught by controller[0]: code: 'ERR_DLOPEN_FAILED'
| error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:950:32) {
| error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
| error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1085:14)
| error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/node_modules/@serialport/bindings/lib/linux.js:2:36)
| error | Caught by controller[0]: at bindings (/opt/iobroker/node_modules/zigbee-herdsman/node_modules/bindings/bindings.js:112:48)
| error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:93:18)
| error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:974:19)
| error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:790:12)
| error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:950:32)
| error | Caught by controller[0]: at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
| error | Caught by controller[0]: the module (for instance, using `npm rebuild` or `npm install`).
| error | Caught by controller[0]: NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
| error | Caught by controller[0]: NODE_MODULE_VERSION 72. This version of Node.js requires
| error | Caught by controller[0]: was compiled against a different Node.js version using
| error | Caught by controller[0]: Error: The module '/opt/iobroker/node_modules/zigbee-herdsman/node_modules/@serialport/bindings/build/Release/bindings.node'
| error | Caught by controller[0]: ^
| error | Caught by controller[0]: throw e;
| error | Caught by controller[0]: /opt/iobroker/node_modules/zigbee-herdsman/node_modules/bindings/bindings.js:121

</body>
</html>`

What can I do to get the adapter to start again?

**Comment by Claus1985** [comment]
works after using the rebuild function of iobroker
