### ISSUE TITLE
Lidle HG06467 Absturz Adapter

### ISSUE THREAD

**Issue by jegow** [ioBroker/ioBroker.zigbee#1307]
Nach der Änderung der Helligkeit (die Helligkeit ändert hat sich auch geändert) stürzt der Adapter mit der folgenden Fehlermeldung ab.

```Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
unhandled promise rejection: Cannot read property 'hasOwnProperty' of null
TypeError: Cannot read property 'hasOwnProperty' of null
    at StatesController.publishToState (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:475:59)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Cannot read property 'hasOwnProperty' of null
cleaned everything up...
Zigbee: disabling joining new devices.
terminating
Terminated (UNCAUGHT_EXCEPTION): Without reason
```
Das Verhalten ist reproduzierbar.

Mein System
- zigbee adapter 1.6.6
- iobroker 3.3.21
- node.js 12.16.2

**Comment by asgothian** [comment]
known bug. Is being worked on.

Current workaround: Add the device to the Exclude List (Ausschliessen Tab).

A.

**Comment by asgothian** [comment]
The behavior is fixed in 1.6.11
