### ISSUE TITLE
Failed to add supportet smoke detector SMSZB-120

### ISSUE THREAD

**Issue by rotodt** [ioBroker/ioBroker.zigbee#1317]
Hi,
two new smoke alarms have the same problem. The adapter crashes after adding.
If I remove the battery after adding, the adapter remains stable until I activate the smoke detector again. 
I already have three of these smoke alarms successfully in operation. 
Is there anything I can do about it myself? 
Best regards 
Roland

SONOFF Zigbee 3.0 USB Dongle Plus Cc2652P+CP2102N，Z-Stack 3.x.0

```2021-12-31 15:07:26.154  - info: zigbee.0 (1132) Zigbee: allowing new devices to join.
2021-12-31 15:07:48.390  - info: zigbee.0 (1132) Starting interview of '0x0015bc003100bcd7'
2021-12-31 15:07:49.009  - warn: zigbee.0 (1132) Device '0x0015bc003100bcd7' announced itself
2021-12-31 15:08:01.699  - error: zigbee.0 (1132) Device 0x0015bc003100bcd7 "undefined" not described in statesMapping.
2021-12-31 15:08:01.701  - error: zigbee.0 (1132) Device 0x0015bc003100bcd7 "undefined" not described in statesMapping.
2021-12-31 15:08:17.314  - info: zigbee.0 (1132) Successfully interviewed '0x0015bc003100bcd7', device has succesfully been paired
2021-12-31 15:08:17.315  - info: zigbee.0 (1132) Device '0x0015bc003100bcd7' is supported, identified as: Develco Smoke detector with siren (SMSZB-120)
2021-12-31 15:08:17.318  - info: zigbee.0 (1132) Configuring 0x0015bc003100bcd7 SMSZB-120
2021-12-31 15:08:21.111  - error:  zigbee.0 (1132) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
2021-12-31 15:08:21.111  - error: zigbee.0 (1132) unhandled promise rejection: Cannot set property 'softwareBuildID' of undefined
2021-12-31 15:08:21.114  - error: zigbee.0 (1132) TypeError: Cannot set property 'softwareBuildID' of undefined
at Object.convert (/opt/iobroker/node_modules/zigbee-herdsman-converters/converters/fromZigbee.js:7199:53)
at /opt/iobroker/node_modules/iobroker.zigbee/main.js:462:43
at StatesController.collectOptions (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:132:19)
at runMicrotasks ()
at runNextTicks (internal/process/task_queues.js:62:5)
at processImmediate (internal/timers.js:434:9)
2021-12-31 15:08:21.114  - error: zigbee.0 (1132) Cannot set property 'softwareBuildID' of undefined
2021-12-31 15:08:21.243  - info: zigbee.0 (1132) cleaned everything up...
2021-12-31 15:08:21.247  - info: zigbee.0 (1132) Zigbee: disabling joining new devices.
2021-12-31 15:08:21.746  - info: zigbee.0 (1132) terminating
2021-12-31 15:08:21.747  - warn: zigbee.0 (1132) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-12-31 15:08:22.354  - error: host.raspberrypi instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-12-31 15:08:22.358  - info: host.raspberrypi Restart adapter system.adapter.zigbee.0 because enabled
2021-12-31 15:08:52.390  - info: host.raspberrypi instance system.adapter.zigbee.0 started with pid 13976
2021-12-31 15:08:55.745  - info:  zigbee.0 (13976) Plugin sentry Sentry Plugin disabled for this process  because sending of statistic data is disabled for the system
2021-12-31 15:08:55.761  - info: zigbee.0 (13976) starting. Version 1.6.6 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.22.8, js-controller: 3.3.22
2021-12-31 15:08:55.857  - info: zigbee.0 (13976) Starting Zigbee  npm ...
2021-12-31 15:08:56.390  - info: zigbee.0 (13976) Installed Version: iobroker.zigbee@1.6.6
2021-12-31 15:08:56.731  - info:  zigbee.0 (13976) Coordinator firmware version:  {"type":"zStack3x0","meta":{"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20210120}}
2021-12-31 15:08:56.740  - info: zigbee.0 (13976) Unable to disable LED, unsupported function.
2021-12-31 15:08:56.741  - info: zigbee.0 (13976)   --> transmitPower : high
2021-12-31 15:08:56.752  - info: zigbee.0 (13976) Currently 30 devices are joined:
2021-12-31 15:08:56.860  - info: zigbee.0 (13976) Configuring 0x0015bc003100bcd7 SMSZB-120
2021-12-31 15:08:56.866  - info: zigbee.0 (13976) 0x60a423fffeaeaf09 (addr 48260): TS0121_plug - TuYa 10A UK or 16A EU smart plug (Router)
2021-12-31 15:08:56.871  - info:  zigbee.0 (13976) 0x00158d00029a9b68 (addr 44400): RTCGQ11LM - Xiaomi  Aqara human body movement and illuminance sensor (EndDevice)
2021-12-31 15:08:56.873  - info:  zigbee.0 (13976) 0x00158d0006a03aa3 (addr 62060): WSDCGQ11LM - Xiaomi  Aqara temperature, humidity and pressure sensor (EndDevice)
2021-12-31 15:08:56.875  - info:  zigbee.0 (13976) 0x00158d00051e3b8b (addr 57227): WSDCGQ11LM - Xiaomi  Aqara temperature, humidity and pressure sensor (EndDevice)
2021-12-31 15:08:56.877  - info: zigbee.0 (13976) 0x00158d0006796ffc (addr 16679): DJT11LM - Xiaomi Aqara vibration sensor (EndDevice)
2021-12-31 15:08:56.879  - info: zigbee.0 (13976) 0x5c0272fffe88cf2d (addr 51636): E1603/E1702/E1708 - IKEA TRADFRI control outlet (Router)
2021-12-31 15:08:56.880  - info: zigbee.0 (13976) 0x60a423fffead7a6a (addr 27044): TS0121_plug - TuYa 10A UK or 16A EU smart plug (Router)
2021-12-31 15:08:56.882  - info:  zigbee.0 (13976) 0x00158d000678e259 (addr 26207): WSDCGQ11LM - Xiaomi  Aqara temperature, humidity and pressure sensor (EndDevice)
2021-12-31 15:08:56.883  - info:  zigbee.0 (13976) 0x00158d000423b474 (addr 437): RTCGQ11LM - Xiaomi  Aqara human body movement and illuminance sensor (EndDevice)
2021-12-31 15:08:56.885  - info:  zigbee.0 (13976) 0x00158d00067d9725 (addr 56433): WSDCGQ11LM - Xiaomi  Aqara temperature, humidity and pressure sensor (EndDevice)
2021-12-31 15:08:56.887  - info:  zigbee.0 (13976) 0x00158d000277b1d1 (addr 4584): WSDCGQ11LM - Xiaomi  Aqara temperature, humidity and pressure sensor (EndDevice)
2021-12-31 15:08:56.889  - info:  zigbee.0 (13976) 0x00158d00067ca66a (addr 7672): RTCGQ11LM - Xiaomi  Aqara human body movement and illuminance sensor (EndDevice)
2021-12-31 15:08:56.891  - info:  zigbee.0 (13976) 0x00158d00068ba9d1 (addr 31684): RTCGQ11LM - Xiaomi  Aqara human body movement and illuminance sensor (EndDevice)
2021-12-31 15:08:56.892  - info: zigbee.0 (13976) 0x00158d00067c157b (addr 48487): WXKG11LM - Xiaomi Aqara wireless switch (EndDevice)
2021-12-31 15:08:56.893  - info: zigbee.0 (13976) 0x5c0272fffecbc0de (addr 6198): E1603/E1702/E1708 - IKEA TRADFRI control outlet (Router)
2021-12-31 15:08:56.894  - info: zigbee.0 (13976) 0x00158d00067c3d54 (addr 31122): WXKG11LM - Xiaomi Aqara wireless switch (EndDevice)
2021-12-31 15:08:56.896  - info:  zigbee.0 (13976) 0x00158d0006a07e74 (addr 48920): WSDCGQ11LM - Xiaomi  Aqara temperature, humidity and pressure sensor (EndDevice)
2021-12-31 15:08:56.898  - info: zigbee.0 (13976) 0x847127fffe435023 (addr 24193): E1743 - IKEA TRADFRI ON/OFF switch (EndDevice)
2021-12-31 15:08:56.899  - info: zigbee.0 (13976) 0x5c0272fffe88ca0f (addr 46687): E1603/E1702/E1708 - IKEA TRADFRI control outlet (Router)
2021-12-31 15:08:56.900  - info:  zigbee.0 (13976) 0x00158d00047b4c35 (addr 60971): WSDCGQ11LM - Xiaomi  Aqara temperature, humidity and pressure sensor (EndDevice)
2021-12-31 15:08:56.901  - info: zigbee.0 (13976) 0x00158d0001b148c7 (addr 20949): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
2021-12-31 15:08:56.903  - info:  zigbee.0 (13976) 0x00158d0006f0add9 (addr 5837): WSDCGQ11LM - Xiaomi  Aqara temperature, humidity and pressure sensor (EndDevice)
2021-12-31 15:08:56.904  - info: zigbee.0 (13976) 0x00158d0001ab37d5 (addr 28111): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
2021-12-31 15:08:56.906  - info: zigbee.0 (13976) 0x0015bc003100b1a4 (addr 12480): SMSZB-120 - Develco Smoke detector with siren (EndDevice)
2021-12-31 15:08:56.907  - info: zigbee.0 (13976) 0x0015bc0034000b85 (addr 27258): HESZB-120 - Develco Fire detector with siren (EndDevice)
2021-12-31 15:08:56.909  - info:  zigbee.0 (13976) 0x00158d00073c9bf0 (addr 35517): RTCGQ11LM - Xiaomi  Aqara human body movement and illuminance sensor (EndDevice)
2021-12-31 15:08:56.910  - info:  zigbee.0 (13976) 0x00158d0006ec71b1 (addr 49190): WSDCGQ11LM - Xiaomi  Aqara temperature, humidity and pressure sensor (EndDevice)
2021-12-31 15:08:56.912  - info: zigbee.0 (13976) 0x0015bc003100c5ba (addr 4839): SMSZB-120 - Develco Smoke detector with siren (EndDevice)
2021-12-31 15:08:56.913  - info: zigbee.0 (13976) 0x0015bc003100a339 (addr 59083): SMSZB-120 - Develco Smoke detector with siren (EndDevice)
2021-12-31 15:08:56.915  - info: zigbee.0 (13976) 0x0015bc003100bcd7 (addr 11526): SMSZB-120 - Develco Smoke detector with siren (EndDevice)
2021-12-31 15:08:56.916  - info: zigbee.0 (13976) Zigbee started
2021-12-31 15:09:19.097  - error:  zigbee.0 (13976) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
2021-12-31 15:09:19.097  - error: zigbee.0 (13976) unhandled promise rejection: Cannot set property 'softwareBuildID' of undefined
2021-12-31 15:09:19.100  - error: zigbee.0 (13976) TypeError: Cannot set property 'softwareBuildID' of undefined
at Object.convert (/opt/iobroker/node_modules/zigbee-herdsman-converters/converters/fromZigbee.js:7199:53)
at /opt/iobroker/node_modules/iobroker.zigbee/main.js:462:43
at StatesController.collectOptions (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:132:19)
2021-12-31 15:09:19.101  - error: zigbee.0 (13976) Cannot set property 'softwareBuildID' of undefined
2021-12-31 15:09:19.106  - info: zigbee.0 (13976) cleaned everything up...
2021-12-31 15:09:19.110  - info: zigbee.0 (13976) Zigbee: disabling joining new devices.
2021-12-31 15:09:19.608  - info: zigbee.0 (13976) terminating
2021-12-31 15:09:19.610  - warn: zigbee.0 (13976) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-12-31 15:09:20.268  - error: host.raspberrypi instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)```

**Comment by arteck** [comment]
check 1.6.11 version

**Comment by rotodt** [comment]
thanks, 
but same behavior in 1.6.11

```
2022-01-03 07:38:33.614  - warn: zigbee.0 (31425) Device '0x0015bc003100bab0' announced itself
--
2022-01-03 07:38:33.616  - info: zigbee.0 (31425) Configuring 0x0015bc003100bab0 SMSZB-120
2022-01-03 07:38:38.336  - error:  zigbee.0 (31425) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
2022-01-03 07:38:38.337  - error: zigbee.0 (31425) unhandled promise rejection: Cannot set property 'softwareBuildID' of undefined
2022-01-03 07:38:38.339  - error: zigbee.0 (31425) TypeError: Cannot set property 'softwareBuildID' of undefined
at Object.convert (/opt/iobroker/node_modules/zigbee-herdsman-converters/converters/fromZigbee.js:7303:53)
at /opt/iobroker/node_modules/iobroker.zigbee/main.js:463:43
at StatesController.collectOptions (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:145:19)
2022-01-03 07:38:38.339  - error: zigbee.0 (31425) Cannot set property 'softwareBuildID' of undefined
2022-01-03 07:38:38.342  - info: zigbee.0 (31425) cleaned everything up...
2022-01-03 07:38:38.452  - info: zigbee.0 (31425) Zigbee: disabling joining new devices.
2022-01-03 07:38:38.842  - info: zigbee.0 (31425) terminating
2022-01-03 07:38:38.844  - warn: zigbee.0 (31425) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-01-03 07:38:39.469  - error: host.raspberrypi instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-01-03 07:38:39.473  - info: host.raspberrypi Restart adapter system.adapter.zigbee.0 because enabled
2022-01-03 07:39:09.554  - info: host.raspberrypi instance system.adapter.zigbee.0 started with pid 31582
2022-01-03 07:39:12.583  - info:  zigbee.0 (31582) Plugin sentry Sentry Plugin disabled for this process  because sending of statistic data is disabled for the system
2022-01-03 07:39:12.599  - info: zigbee.0 (31582) starting. Version 1.6.11 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.22.8, js-controller: 3.3.22
2022-01-03 07:39:12.700  - info: zigbee.0 (31582) Starting Zigbee  npm ...
2022-01-03 07:39:12.702  - warn: zigbee.0 (31582) 4  extensions initialized
2022-01-03 07:39:12.703  - warn: zigbee.0 (31582) extension DeviceAvailability
2022-01-03 07:39:12.703  - warn: zigbee.0 (31582) extension DeviceConfigure
2022-01-03 07:39:12.704  - warn: zigbee.0 (31582) extension DeviceEvent
2022-01-03 07:39:12.704  - warn: zigbee.0 (31582) extension DelayedAction
2022-01-03 07:39:13.246  - info: zigbee.0 (31582) Installed Version: ioBroker/ioBroker.zigbee#50ead5d3c2c3533674955e1bf4981e411b143bb9
2022-01-03 07:39:13.590  - info:  zigbee.0 (31582) Coordinator firmware version:  {"type":"zStack3x0","meta":{"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20210120}}
2022-01-03 07:39:13.599  - info: zigbee.0 (31582) Unable to disable LED, unsupported function.
2022-01-03 07:39:13.600  - info: zigbee.0 (31582)   --> transmitPower : high
2022-01-03 07:39:13.611  - info: zigbee.0 (31582) Currently 30 devices are joined:
2022-01-03 07:39:13.724  - info: zigbee.0 (31582) Configuring 0x0015bc003100bab0 SMSZB-120
2022-01-03 07:39:13.728  - info: zigbee.0 (31582) 0x60a423fffeaeaf09 (addr 48260): TS0121_plug - TuYa 10A UK or 16A EU smart plug (Router)
2022-01-03 07:39:13.739  - info:  zigbee.0 (31582) 0x00158d00029a9b68 (addr 44400): RTCGQ11LM - Xiaomi  Aqara human body movement and illuminance sensor (EndDevice)
2022-01-03 07:39:13.741  - info:  zigbee.0 (31582) 0x00158d0006a03aa3 (addr 62060): WSDCGQ11LM - Xiaomi  Aqara temperature, humidity and pressure sensor (EndDevice)
2022-01-03 07:39:13.743  - info:  zigbee.0 (31582) 0x00158d00051e3b8b (addr 57227): WSDCGQ11LM - Xiaomi  Aqara temperature, humidity and pressure sensor (EndDevice)
2022-01-03 07:39:13.744  - info: zigbee.0 (31582) 0x00158d0006796ffc (addr 16679): DJT11LM - Xiaomi Aqara vibration sensor (EndDevice)
2022-01-03 07:39:13.746  - info: zigbee.0 (31582) 0x5c0272fffe88cf2d (addr 51636): E1603/E1702/E1708 - IKEA TRADFRI control outlet (Router)
2022-01-03 07:39:13.748  - info: zigbee.0 (31582) 0x60a423fffead7a6a (addr 27044): TS0121_plug - TuYa 10A UK or 16A EU smart plug (Router)
2022-01-03 07:39:13.749  - info:  zigbee.0 (31582) 0x00158d000678e259 (addr 26207): WSDCGQ11LM - Xiaomi  Aqara temperature, humidity and pressure sensor (EndDevice)
2022-01-03 07:39:13.751  - info:  zigbee.0 (31582) 0x00158d000423b474 (addr 437): RTCGQ11LM - Xiaomi  Aqara human body movement and illuminance sensor (EndDevice)
2022-01-03 07:39:13.753  - info:  zigbee.0 (31582) 0x00158d00067d9725 (addr 56433): WSDCGQ11LM - Xiaomi  Aqara temperature, humidity and pressure sensor (EndDevice)
2022-01-03 07:39:13.755  - info:  zigbee.0 (31582) 0x00158d000277b1d1 (addr 4584): WSDCGQ11LM - Xiaomi  Aqara temperature, humidity and pressure sensor (EndDevice)
2022-01-03 07:39:13.757  - info:  zigbee.0 (31582) 0x00158d00067ca66a (addr 7672): RTCGQ11LM - Xiaomi  Aqara human body movement and illuminance sensor (EndDevice)
2022-01-03 07:39:13.759  - info:  zigbee.0 (31582) 0x00158d00068ba9d1 (addr 31684): RTCGQ11LM - Xiaomi  Aqara human body movement and illuminance sensor (EndDevice)
2022-01-03 07:39:13.761  - info: zigbee.0 (31582) 0x00158d00067c157b (addr 48487): WXKG11LM - Xiaomi Aqara wireless switch (EndDevice)
2022-01-03 07:39:13.764  - info: zigbee.0 (31582) 0x5c0272fffecbc0de (addr 6198): E1603/E1702/E1708 - IKEA TRADFRI control outlet (Router)
2022-01-03 07:39:13.766  - info: zigbee.0 (31582) 0x00158d00067c3d54 (addr 31122): WXKG11LM - Xiaomi Aqara wireless switch (EndDevice)
2022-01-03 07:39:13.768  - info:  zigbee.0 (31582) 0x00158d0006a07e74 (addr 48920): WSDCGQ11LM - Xiaomi  Aqara temperature, humidity and pressure sensor (EndDevice)
2022-01-03 07:39:13.769  - info: zigbee.0 (31582) 0x847127fffe435023 (addr 24193): E1743 - IKEA TRADFRI ON/OFF switch (EndDevice)
2022-01-03 07:39:13.771  - info: zigbee.0 (31582) 0x5c0272fffe88ca0f (addr 46687): E1603/E1702/E1708 - IKEA TRADFRI control outlet (Router)
2022-01-03 07:39:13.773  - info:  zigbee.0 (31582) 0x00158d00047b4c35 (addr 60971): WSDCGQ11LM - Xiaomi  Aqara temperature, humidity and pressure sensor (EndDevice)
2022-01-03 07:39:13.774  - info: zigbee.0 (31582) 0x00158d0001b148c7 (addr 20949): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
2022-01-03 07:39:13.775  - info:  zigbee.0 (31582) 0x00158d0006f0add9 (addr 5837): WSDCGQ11LM - Xiaomi  Aqara temperature, humidity and pressure sensor (EndDevice)
2022-01-03 07:39:13.777  - info: zigbee.0 (31582) 0x00158d0001ab37d5 (addr 28111): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
2022-01-03 07:39:13.778  - info: zigbee.0 (31582) 0x0015bc003100b1a4 (addr 12480): SMSZB-120 - Develco Smoke detector with siren (EndDevice)
2022-01-03 07:39:13.780  - info: zigbee.0 (31582) 0x0015bc0034000b85 (addr 27258): HESZB-120 - Develco Fire detector with siren (EndDevice)
2022-01-03 07:39:13.782  - info:  zigbee.0 (31582) 0x00158d00073c9bf0 (addr 35517): RTCGQ11LM - Xiaomi  Aqara human body movement and illuminance sensor (EndDevice)
2022-01-03 07:39:13.783  - info:  zigbee.0 (31582) 0x00158d0006ec71b1 (addr 49190): WSDCGQ11LM - Xiaomi  Aqara temperature, humidity and pressure sensor (EndDevice)
2022-01-03 07:39:13.785  - info: zigbee.0 (31582) 0x0015bc003100c5ba (addr 4839): SMSZB-120 - Develco Smoke detector with siren (EndDevice)
2022-01-03 07:39:13.788  - info: zigbee.0 (31582) 0x0015bc003100a339 (addr 59083): SMSZB-120 - Develco Smoke detector with siren (EndDevice)
2022-01-03 07:39:13.790  - info: zigbee.0 (31582) 0x0015bc003100bab0 (addr 50730): SMSZB-120 - Develco Smoke detector with siren (EndDevice)
2022-01-03 07:39:13.791  - warn:  zigbee.0 (31582) config  :{"port":"/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0","panID":"2303","extPanID":"dddddddddddddddd","channel":"16","disableLed":false,"precfgkey":"01030507090B0D0F00020406080A0C0D","countDown":"60","adapterType":"zstack","debugHerdsman":false,"disablePing":false,"external":"","transmitPower":"19","extPanIdFix":true,"startWithInconsistent":false}
2022-01-03 07:39:13.792  - info: zigbee.0 (31582) Zigbee started
2022-01-03 07:39:23.877  - warn:  zigbee.0 (31582) DeviceConfigure:DeviceConfigure failed  0x0015bc003100bab0 SMSZB-120, attempt 1 (Error: Bind  0x0015bc003100bab0/35 genPowerCfg from '0x00124b0022810e5f/1' failed  (AREQ - ZDO - bindRsp after 10000ms)
at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/dist/utils/waitress.js:37:35)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7))

**Comment by arteck** [comment]
check now plz

**Comment by rotodt** [comment]
Received an error message but stable

```
2022-01-03 08:28:57.099  - info: zigbee.0 (3160) Configuring 0x0015bc003100bab0 SMSZB-120
--
2022-01-03 08:28:57.525  - warn: zigbee.0 (3160) Device '0x0015bc003100bab0' announced itself
2022-01-03 08:29:04.688  - error:  zigbee.0 (3160) Error collectOptions for 0015bc003100bab0. Error:  TypeError: Cannot set property 'softwareBuildID' of undefined
at Object.convert (/opt/iobroker/node_modules/zigbee-herdsman-converters/converters/fromZigbee.js:7303:53)
at /opt/iobroker/node_modules/iobroker.zigbee/main.js:463:43
at StatesController.collectOptions (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:146:23)
2022-01-03 08:29:08.979  - info: zigbee.0 (3160) DeviceConfigure successful 0x0015bc003100bab0 SMSZB-120

**Comment by asgothian** [comment]
Please open an issue for this at the zigbee-herdsman-converters project (https://github.com/Koenkk/zigbee-herdsman-converters). There seems to be an error in the converter when parsing the responses from the device.

The fix @arteck introduced ensures that the zigbee adapter does not crash due to this error, but the error itself remains.

A.
