### ISSUE TITLE
Crash during firmware update

### ISSUE THREAD

**Issue by huk13** [ioBroker/ioBroker.zigbee#1380]
When I start firmware update in the devices panel view the adapter crashes. OS is Raspberry Buster, details at end of listing.

```
2022-02-18 17:29:37.544  - info: zigbee.0 (29044) Device zigbee.0.00158d000366790e is deactivated, skipping...
2022-02-18 17:29:37.626  - info: zigbee.0 (29044) Device zigbee.0.588e81fffe2bad45 is marked unavailable, skipping...
2022-02-18 17:29:40.101  - info: zigbee.0 (29044) Failed to check if update available for '0x84fd27fffe31a812' (No image available for imageType '5634')
2022-02-18 17:29:40.320  - info: zigbee.0 (29044) Failed to check if update available for '0x0c4314fffee3cc6d' (No image available for imageType '5634')
2022-02-18 17:29:40.795  - info: zigbee.0 (29044) Failed to check if update available for '0x000d6ffffe1d3981' (No image available for imageType '10243')
2022-02-18 17:29:41.830  - info: zigbee.0 (29044) Failed to check if update available for '0x84fd27fffe2dcb8a' (No image available for imageType '5634')
2022-02-18 17:30:07.602  - info: zigbee.0 (29044) Failed to check if update available for '0x588e81fffe29b980' (Device didn't respond to OTA request)
2022-02-18 17:30:07.635  - info: zigbee.0 (29044) Failed to check if update available for '0x588e81fffe2b8efb' (Device didn't respond to OTA request)
2022-02-18 17:30:07.639  - error:  zigbee.0 (29044) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
2022-02-18 17:30:07.640  - error: zigbee.0 (29044) unhandled promise rejection: Timeout - 2737 - 1 - null - 25 - 1 after 30000ms
2022-02-18 17:30:07.641  - error: zigbee.0 (29044) Error: Timeout - 2737 - 1 - null - 25 - 1 after 30000ms
at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
at listOnTimeout (internal/timers.js:557:17)
at processTimers (internal/timers.js:500:7)
2022-02-18 17:30:07.642  - error: zigbee.0 (29044) Timeout - 2737 - 1 - null - 25 - 1 after 30000ms
2022-02-18 17:30:07.649  - info: zigbee.0 (29044) Failed to check if update available for '0xccccccfffea309d2' (Device didn't respond to OTA request)
2022-02-18 17:30:07.652  - info: zigbee.0 (29044) cleaned everything up...
2022-02-18 17:30:07.886  - info: zigbee.0 (29044) Zigbee: disabling joining new devices.
2022-02-18 17:30:08.154  - info: zigbee.0 (29044) terminating
2022-02-18 17:30:08.155  - warn: zigbee.0 (29044) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-02-18 17:30:09.045  - error:  host.raspi-3 Caught by controller[0]: This error originated either by  throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch(). The promise  rejected with the reason:
2022-02-18 17:30:09.050  - error: host.raspi-3 Caught by controller[1]: Error: Timeout - 2737 - 1 - null - 25 - 1 after 30000ms
2022-02-18 17:30:09.051  - error:  host.raspi-3 Caught by controller[1]:     at Timeout._onTimeout  (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
2022-02-18 17:30:09.051  - error: host.raspi-3 Caught by controller[1]:     at listOnTimeout (internal/timers.js:557:17)
2022-02-18 17:30:09.052  - error: host.raspi-3 Caught by controller[1]:     at processTimers (internal/timers.js:500:7)
2022-02-18 17:30:09.054  - error: host.raspi-3 instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-02-18 17:30:09.057  - info: host.raspi-3 Restart adapter system.adapter.zigbee.0 because enabled
2022-02-18 17:30:39.417  - info: host.raspi-3 instance system.adapter.zigbee.0 started with pid 18918
**2022-02-18 17:30:43.032  - info: zigbee.0 (18918) starting. Version 1.6.16 in /opt/iobroker/node_modules/iobroker.zigbee, node: v14.19.0, js-controller: 4.0.12**
**2022-02-18 17:30:43.163  - info: zigbee.0 (18918) Starting Zigbee  npm ...
2022-02-18 17:30:43.703  - info: zigbee.0 (18918) Installed Version: iobroker.zigbee@1.6.16
2022-02-18 17:30:44.105  - info:  zigbee.0 (18918) Coordinator firmware version:  {"type":"zStack3x0","meta":{"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20211217}}
2022-02-18 17:30:44.118  - info: zigbee.0 (18918) Unable to disable LED, unsupported function.
2022-02-18 17:30:44.128  - info: zigbee.0 (18918)   --> transmitPower : high
2022-02-18 17:30:44.221  - info: zigbee.0 (18918) Currently 70 devices are joined:**

```

Mod Edit - Code Tags

**Comment by asgothian** [comment]
- Can you reproduce this error consistently ?
- Is it tied to a specific device ?

A.

**Comment by huk13** [comment]
Yes I can reproduce the error consistently. It does not seem to be tied to a specific device. Errors start after different devices.

HUK

**Comment by asgothian** [comment]
can you please verify if the numbers in the error message on each crash are the same:

`Timeout - 2737 - 1 - null - 25 - 1 `

If so, can you check your shepherd.db file for a device with the NWK address 2737 ?

A.
A.

**Comment by huk13** [comment]
2737 shows up in all crashes, but other numbers occur too. These addresses belong to IKEA switches [E1743] of which I have 4. I recently re-paired them when I updated to 1.6.16 to get the battery read out.
Excerpt from shepherd.db:
{"id":42,"type":"EndDevice","ieeeAddr":"0x680ae2fffe12edb9","**nwkAddr":273**7,"manufId":4476,"manufName":"IKEA of Sweden","powerSource":"Battery","modelId":"TRADFRI on/off switch","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":2080,"inClusterList":[0,1,3,9,32,4096,64636],"outClusterList":[3,4,6,8,25,258,4096],"clusters":{"genBasic":{"attributes":{"modelId":"TRADFRI on/off switch","manufacturerName":"IKEA of Sweden","powerSource":3,"zclVersion":3,"appVersion":33,"stackVersion":98,"hwVersion":1,"dateCode":"20190723","swBuildId":"2.2.010"}},"genPollCtrl":{"attributes":{"checkinInterval":172800}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":100}}},"binds":[{"cluster":32,"type":"endpoint","deviceIeeeAddress":"0x00124b001940be8c","endpointID":1},{"cluster":6,"groupID":901,"type":"group"},{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b001940be8c","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0}],"meta":{}}},"appVersion":33,"stackVersion":98,"hwVersion":1,"dateCode":"20190723","swBuildId":"2.2.010","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-1104804361},"lastSeen":1645235524547,"defaultSendRequestWhen":"active"}
{"id":43,"type":"EndDevice","ieeeAddr":"0x588e81fffe2bad45","nwkAddr":8296,"manufId":4476,"manufName":"IKEA of Sweden","powerSource":"Battery","modelId":"TRADFRI on/off switch","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":2080,"inClusterList":[0,1,3,9,32,4096,64636],"outClusterList":[3,4,6,8,25,258,4096],"clusters":{"genPollCtrl":{"attributes":{"checkinInterval":172800}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":100}}},"binds":[{"cluster":32,"type":"endpoint","deviceIeeeAddress":"0x00124b001940be8c","endpointID":1},{"cluster":6,"groupID":901,"type":"group"},{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b001940be8c","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":33,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0}],"meta":{}}},"appVersion":33,"stackVersion":98,"hwVersion":1,"dateCode":"20190723","swBuildId":"2.2.010","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-1104804361},"lastSeen":1645204068836,"defaultSendRequestWhen":"active"}
{"id":44,"type":"EndDevice","ieeeAddr":"0xec1bbdfffe65bc5c","nwkAddr":511,"manufId":0,"manufName":"TUYATEC-p9HCE8pZ","powerSource":"Mains (single phase)","modelId":"TS0011","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":256,"inClusterList":[0,3,6],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"TS0011","manufacturerName":"TUYATEC-p9HCE8pZ","appVersion":70,"stackVersion":0}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b001940be8c","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":70,"stackVersion":0,"hwVersion":1,"dateCode":"20180608","zclVersion":2,"interviewCompleted":true,"meta":{"configured":-1482240604},"lastSeen":1645257621980,"defaultSendRequestWhen":"immediate"}

I send another crash listing where you find the additional address 8296 (also E1743):

<html><body>


2022-02-18 19:36:29.572  - info: zigbee.0 (18918) Device zigbee.0.00158d000366790e is deactivated, skipping...
2022-02-18 19:36:32.978  - info: zigbee.0 (18918) Failed to check if update available for '0x84fd27fffe2dcb8a' (No image available for imageType '5634')
2022-02-18 19:36:33.248  - info: zigbee.0 (18918) Failed to check if update available for '0x84fd27fffe31a812' (No image available for imageType '5634')
2022-02-18 19:36:33.365  - info: zigbee.0 (18918) Failed to check if update available for '0x0c4314fffee3cc6d' (No image available for imageType '5634')
2022-02-18 19:36:33.805  - info: zigbee.0 (18918) Failed to check if update available for '0x000d6ffffe1d3981' (No image available for imageType '10243')
2022-02-18 19:36:59.631  - info: zigbee.0 (18918) Failed to check if update available for '0x588e81fffe29b980' (Device didn't respond to OTA request)
2022-02-18 19:36:59.682  - error:  zigbee.0 (18918) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
2022-02-18 19:36:59.683  - error: zigbee.0 (18918) unhandled promise rejection: Timeout - 8296 - 1 - null - 25 - 1 after 30000ms
2022-02-18 19:36:59.684  - error: zigbee.0 (18918) Error: **Timeout - 8296** - 1 - null - 25 - 1 after 30000ms
at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
at listOnTimeout (internal/timers.js:557:17)
at processTimers (internal/timers.js:500:7)
2022-02-18 19:36:59.685  - error: zigbee.0 (18918) **Timeout - 8296** - 1 - null - 25 - 1 after 30000ms
2022-02-18 19:36:59.701  - info: zigbee.0 (18918) cleaned everything up...
2022-02-18 19:36:59.971  - info: zigbee.0 (18918) Zigbee: disabling joining new devices.
2022-02-18 19:36:59.993  - info: zigbee.0 (18918) Failed to check if update available for '0x588e81fffe2b8efb' (Device didn't respond to OTA request)
2022-02-18 19:36:59.994  - error:  zigbee.0 (18918) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
2022-02-18 19:36:59.995  - error: zigbee.0 (18918) unhandled promise rejection: **Timeout - 2737** - 1 - null - 25 - 1 after 30000ms
2022-02-18 19:36:59.996  - error: zigbee.0 (18918) Error: Timeout - 2737 - 1 - null - 25 - 1 after 30000ms
at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
at listOnTimeout (internal/timers.js:557:17)
at processTimers (internal/timers.js:500:7)
2022-02-18 19:36:59.997  - error: zigbee.0 (18918) **Timeout - 2737** - 1 - null - 25 - 1 after 30000ms
2022-02-18 19:37:00.000  - info: zigbee.0 (18918) Failed to check if update available for '0xccccccfffea309d2' (Device didn't respond to OTA request)
2022-02-18 19:37:00.202  - info: zigbee.0 (18918) terminating
2022-02-18 19:37:00.204  - warn: zigbee.0 (18918) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-02-18 19:37:01.074  - error:  host.raspi-3 Caught by controller[0]: This error originated either by  throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch(). The promise  rejected with the reason:
2022-02-18 19:37:01.080  - error: host.raspi-3 Caught by controller[1]: Error: **Timeout - 8296** - 1 - null - 25 - 1 after 30000ms
2022-02-18 19:37:01.080  - error:  host.raspi-3 Caught by controller[1]:     at Timeout._onTimeout  (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
2022-02-18 19:37:01.080  - error: host.raspi-3 Caught by controller[1]:     at listOnTimeout (internal/timers.js:557:17)
2022-02-18 19:37:01.081  - error: host.raspi-3 Caught by controller[1]:     at processTimers (internal/timers.js:500:7)
2022-02-18 19:37:01.081  - error:  host.raspi-3 Caught by controller[2]: This error originated either by  throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch(). The promise  rejected with the reason:
2022-02-18 19:37:01.081  - error: host.raspi-3 Caught by controller[2]: Error: Timeout - 2737 - 1 - null - 25 - 1 after 30000ms
2022-02-18 19:37:01.082  - error:  host.raspi-3 Caught by controller[2]:     at Timeout._onTimeout  (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
2022-02-18 19:37:01.082  - error: host.raspi-3 Caught by controller[2]:     at listOnTimeout (internal/timers.js:557:17)
2022-02-18 19:37:01.106  - error: host.raspi-3 Caught by controller[2]:     at processTimers (internal/timers.js:500:7)
2022-02-18 19:37:01.107  - error: host.raspi-3 instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-02-18 19:37:01.107  - info: host.raspi-3 Restart adapter system.adapter.zigbee.0 because enabled
2022-02-18 19:37:31.474  - info: host.raspi-3 instance system.adapter.zigbee.0 started with pid 26907
2022-02-18 19:37:35.153  - info: zigbee.0 (26907) starting. Version 1.6.16 in /opt/iobroker/node_modules/iobroker.zigbee, node: v14.19.0, js-controller: 4.0.12
2022-02-18 19:37:35.278  - info: zigbee.0 (26907) Starting Zigbee  npm ...


</body>
</html>

So you seem to be on the right track. Crash seems to be connected to 1.6.16 and a specific device type (IKEA E1743).

HUK

**Comment by asgothian** [comment]
Can you list the ieee of the two devices as well ?

also - if you disable these 2 devices before attempting the ota update, will the adapter still crash ?

A.

**Comment by huk13** [comment]
When I disable both of these devices the adapter does not crash. The other two devices need not to be disabled.
What is ieee? Is this the extended device information (if you hit the blue i icon)?

HUK

**Comment by huk13** [comment]
In the meantime l have re-paired 0x680ae2fffe12edb9 (was difficult to delete). The crash did not appear again. The other device keeps showing "checking" but no errors occur. So I conclude that the crash was related to the in some way not complete or successful pairing.
Thanks for the support.
HUK
