### ISSUE TITLE
NWK_TABLE_FULL

### ISSUE THREAD

**Issue by sir0drake** [ioBroker/ioBroker.zigbee#1385]
Hello,
since a couple of days, i face a slowdown in reacting of going on status of lights controlled by motion sensors.
as of now, the fully zigbee-system is not working anymore.
i see a lot of errors and warings in iobroker-logs.

<html>
<body>

zigbee.1 | 2022-02-22 19:58:55.172 | error | SREQ '--> ZDO - extRouteDisc - {"dstAddr":45248,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)')
-- | -- | -- | --
zigbee.1 | 2022-02-22 19:58:55.172 | error | Error: SREQ '--> ZDO - extRouteDisc - {"dstAddr":45248,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)') at Object.func (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:322:27) at Queue.executeNext (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
zigbee.1 | 2022-02-22 19:58:55.117 | error | unhandled promise rejection: SREQ '--> ZDO - extRouteDisc - {"dstAddr":45248,"options":0,"radius":30}' failed with status '(0xc7: NWK_TABLE_FULL)' (expected '(0x00: SUCCESS)')
zigbee.1 | 2022-02-22 19:58:55.116 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

</body>
</html>

previously i had Version 1.6.16 installed
a downgrade to 1.6.14 did not solve the problem.
went back to 1.6.16

i have installed ~40 Zigbee-devices in my network
and all of them working fine until this happen now.

here my system:
![image](https://user-images.githubusercontent.com/77205165/155202828-7490a4b6-659d-4d9a-8ea3-01af71157c57.png)
![image](https://user-images.githubusercontent.com/77205165/155206843-c5404829-d96d-4511-a909-25d1eb652de3.png)

The zigbee-coordinator is a CC2652RB by Slaesh.

Is there anything i can do ?

best regards
Drake

**Comment by sir0drake** [comment]
dear asgothian,

thanks for your quick response.

**you are right** 
zigbee.controler at channel 12
and
fritz.box 2.4GHZ at 11 makes some stress

changed fritz.box from 11 to 5 and after reboot pi it works.

Will have a look at this next days.

best regards
Drake
