### ISSUE TITLE
"Do not know how to serialize a BigInt"

### ISSUE THREAD

**Issue by Shadesh** [ioBroker/ioBroker.zigbee#1394]
Hi, with todays version from GitHub, I get this error every few (aprox 5 minutes) minutes and the adapter restarts:
```
2022-03-10 10:05:09.691 | error | instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | --
zigbee.0 | 2022-03-10 10:05:09.153 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee.0 | 2022-03-10 10:05:09.153 | info | terminating
zigbee.0 | 2022-03-10 10:05:08.711 | info | Zigbee: disabling joining new devices.
zigbee.0 | 2022-03-10 10:05:08.653 | info | cleaned everything up...
zigbee.0 | 2022-03-10 10:05:08.652 | error | Do not know how to serialize a BigInt
zigbee.0 | 2022-03-10 10:05:08.652 | error | TypeError: Do not know how to serialize a BigInt at JSON.stringify (<anonymous>) at buffer2DataObject (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/xiaomi.js:132:97) at /opt/iobroker/node_modules/zigbee-herdsman-converters/lib/xiaomi.js:282:39 at Array.forEach (<anonymous>) at Object.numericAttributes2Payload (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/xiaomi.js:140:32) at Object.convert (/opt/iobroker/node_modules/zigbee-herdsman-converters/converters/fromZigbee.js:5299:36) at /opt/iobroker/node_modules/iobroker.zigbee/main.js:463:43 at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:175:25) at processImmediate (internal/timers.js:466:21)
zigbee.0 | 2022-03-10 10:05:08.651 | error | uncaught exception: Do not know how to serialize a BigInt
```

**Comment by asgothian** [comment]
Since there is no traction on the zigbee-herdsman-converters front - would you be willing to attempt the following patch for it:

- locate the file `zigbee-herdsman-converters\lib\xiaomi.js`
- replace the line 132 (
``` 
if (meta.logger) meta.logger.debug(`${model.zigbeeModel}: Processed buffer into data ${JSON.stringify(dataObject)}`);
```
with
``` 
if (meta.logger) 
{
    let dataObject_str = undefined
    if (dataObject !== undefined) {
       meta.logger.debug(`${model.zigbeeModel}: Processed buffer into data ${JSON.stringify(dataObject, (_,v) => typeof v === 'bigint' ? v.toString() : v)}`);
    }
   else
     meta.logger.debug(`${model.zigbeeModel}: Processed buffer into data - data is undefined`);
}
```

I would try this myself but i do not have the error.

A.

**Comment by Shadesh** [comment]
Patched it, I'll let you know if it happens again.

**Comment by McGiverGim** [comment]
It seems that is working as the specification says https://tc39.es/proposal-bigint/#sec-serializejsonproperty

It seems that JSON is used among different systems so they can't add compatibility for any type of data. We must do it in our own. So applied a code similar to the one you linked.

**Comment by asgothian** [comment]
Thanks.. once i had confirmation that it works like that i would have proposed the same change.

A.
