### ISSUE TITLE
Aqara P1 Motion Sensor not identified

### ISSUE THREAD

**Issue by backlink-market** [ioBroker/ioBroker.zigbee#1402]
The new [Aqara Motion Sensor P1 (MS-S02)](https://www.aqara.com/en/product/motion-sensor-p1) is not detected correctly.

The old Aqara Motion Sensor is working fine but not the new P1 Version with the extended Batterie and Light Sensor.

I am using the latest stable Zigbee release: 1.6.16

Here are the details:
![image](https://i.imgur.com/rAXDI53.png)

![image](https://i.imgur.com/kk74qLt.png)

![image](https://i.imgur.com/3cDDMNC.png)

![image](https://i.imgur.com/lIOQ7ka.png)

**Comment by backlink-market** [comment]
Is there anything I can do to speed up the process of getting this solved?

**Comment by asgothian** [comment]
See [Here](https://github.com/ioBroker/ioBroker.zigbee/wiki/My-device-is-not-recognised).

A.

**Comment by backlink-market** [comment]
added issue on koenkk
https://github.com/Koenkk/zigbee2mqtt/issues/11990

**Comment by asgothian** [comment]
I will verify how to use that external converter tonight. I cannot do that from work.

A.

**Comment by asgothian** [comment]
This is how you use the external converter. Note: This is not really easy currently, but will be made easier.

- create a file  `/opt/iobroker/iobroker-data/zigbee_0/externalconverter.js`
- paste the content into the file.
- add the prefix `/opt/iobroker/node_modules/` to the path in each of the `require` statements.
- add the entry `/opt/iobroker/iobroker-data/zigbee_0/externalconverter.js` as external converter (see screenshot)

<img width="960" alt="Screen Shot 2022-03-31 at 19 42 32 " src="https://user-images.githubusercontent.com/45667167/161117183-ff4cac89-33d8-4de4-a5bf-af55de4a656f.png">

restart the adapter.

A.

**Comment by backlink-market** [comment]
unfortunately it throws an error:

`<html><body>


2022-03-31 20:35:50.191  - error: zigbee.1 (14080) TypeError: Cannot read property 'options' of undefined
--
at Object.addDefinition [as addDeviceDefinition] (C:\iobroker\MiCasa\node_modules\zigbee-herdsman-converters\index.js:91:23)
at Zigbee.applyExternalConverters (C:\iobroker\MiCasa\node_modules\iobroker.zigbee\main.js:236:38)
at Zigbee.onReady (C:\iobroker\MiCasa\node_modules\iobroker.zigbee\main.js:180:14)
at Zigbee.emit (events.js:400:28)
at C:\iobroker\MiCasa\node_modules\@iobroker\js-controller-adapter\build\lib\adapter\adapter.js:8226:26
2022-03-31 20:35:50.192  - error: zigbee.1 (14080) Cannot read property 'options' of undefined
2022-03-31 20:35:50.195  - info: zigbee.1 (14080) cleaned everything up...
2022-03-31 20:35:50.196  - info: zigbee.1 (14080) terminating
2022-03-31 20:35:50.198  - warn: zigbee.1 (14080) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-03-31 20:35:50.743  - error: host.server-lan(MiCasa) instance system.adapter.zigbee.1 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-03-31 20:35:50.743  - info: host.server-lan(MiCasa) Restart adapter system.adapter.zigbee.1 because enabled
2022-03-31 20:36:20.784  - info: host.server-lan(MiCasa) instance system.adapter.zigbee.1 started with pid 12676
2022-03-31 20:36:21.537  - info: host.server-lan(MiCasa) stopInstance system.adapter.zigbee.1 (force=false, process=true)
2022-03-31 20:36:21.540  - info: host.server-lan(MiCasa) stopInstance system.adapter.zigbee.1 send kill signal
2022-03-31 20:36:22.555  - info: host.server-lan(MiCasa) stopInstance system.adapter.zigbee.1 killing pid 12676
2022-03-31 20:36:22.576  - warn: host.server-lan(MiCasa) instance system.adapter.zigbee.1 terminated due to SIGTERM
2022-03-31 20:36:22.576  - info: host.server-lan(MiCasa) instance system.adapter.zigbee.1 terminated with code null ()
2022-03-31 20:36:24.596  - info: host.server-lan(MiCasa) instance system.adapter.zigbee.1 started with pid 3084
2022-03-31 20:36:26.772  - info:  zigbee.1 (3084) Plugin sentry Sentry Plugin disabled for this process  because sending of statistic data is disabled for the system
2022-03-31 20:36:26.822  - info:  zigbee.1 (3084) starting. Version 1.6.16 in  C:/iobroker/MiCasa/node_modules/iobroker.zigbee, node: v14.18.3,  js-controller: 4.0.21
2022-03-31 20:36:26.834  - info: zigbee.1 (3084) Apply converter from module: /iobroker/MiCasa/iobroker-data/zigbee_1/externalconverter.js
2022-03-31 20:36:26.839  - error:  zigbee.1 (3084) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
2022-03-31 20:36:26.839  - error: zigbee.1 (3084) unhandled promise rejection: Cannot read property 'options' of undefined
2022-03-31 20:36:26.841  - error: zigbee.1 (3084) TypeError: Cannot read property 'options' of undefined
at Object.addDefinition [as addDeviceDefinition] (C:\iobroker\MiCasa\node_modules\zigbee-herdsman-converters\index.js:91:23)
at Zigbee.applyExternalConverters (C:\iobroker\MiCasa\node_modules\iobroker.zigbee\main.js:236:38)
at Zigbee.onReady (C:\iobroker\MiCasa\node_modules\iobroker.zigbee\main.js:180:14)
at Zigbee.emit (events.js:400:28)
at C:\iobroker\MiCasa\node_modules\@iobroker\js-controller-adapter\build\lib\adapter\adapter.js:8226:26
2022-03-31 20:36:26.841  - error: zigbee.1 (3084) Cannot read property 'options' of undefined


</body>
</html>`

**Comment by asgothian** [comment]
Ah.. runs on windows.. You need to edit the path at the require statements to match the path to the zigbee-herdsman-converters project. I have no idea where this resides on windows.

A.

**Comment by asgothian** [comment]
There seems to be something in the file. I tried with my test converter and it worked flawlessly, but if i try to use the code provided the adapter crashes for me too, although the structure seems fine.

This may be something the herdsman people need to check - sorry. There is a limit on how deep i can dig into that tonight.

A.

**Comment by backlink-market** [comment]
Ah, bad. Why does the same file works on your end? Can you upload your file? Should I post my file to the koenkk issue then?

**Comment by asgothian** [comment]
Thats the thing.. it is not "the same code".. if i use the same code you use to try an external converter, it does not run. If i use one of my old test cases, it does run.

A.

**Comment by backlink-market** [comment]
When I insert the code to the xiaomi.js it throws the same Error:

Caught by controller[0]: TypeError: Cannot read property 'options' of undefined

**Comment by backlink-market** [comment]
@asgothian can you please  add support for meta.state object to ioBroker.zigbee. See #https://github.com/Koenkk/zigbee2mqtt/issues/11990#issuecomment-1091802613

Thank you very much

**Comment by asgothian** [comment]
I am afraid this will require a larger overhaul as it will affect nearly every device. An analysis of the code provided has shown:
- the device itself does not support a "detection interval". 
- the function used for the detection interval is merely a timeout which resets the "occupancy" value to false after n seconds, with 60 being the default. 
- It is completely unclear after how long a delay between the first and a following second message with occupancy = true is.
- even without the occupancy timeout this can already be utilized by triggering for "updated with true" rather than "changed". As such, this request will need to take a back seat over other changes which are in the work.


A.
