### ISSUE TITLE
Devices got lost after Unhandled promise rejection

### ISSUE THREAD

**Issue by fraggle-iw** [ioBroker/ioBroker.zigbee#1403]
Hi,

i run a Zigbee network of 74 devices using:
CC2652R
    type:zStack3x0
    version:2-1.2.7.1.
    revision:20211217
    port:/dev/ttyACM0
    channel:13
Version 1.6.14 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.22.8, js-controller: 3.3.22

Since using Version 1.6.14 i sporadically lose devices from the Database.

Inside the logs i found:
```
<html><body>
<!--StartFragment-->

2022-03-27 14:54:42.687  - error:  zigbee.0 (1520) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
--
2022-03-27 14:54:42.687  - error: zigbee.0 (1520) unhandled promise rejection: DatabaseEntry with ID '25' already exists
2022-03-27 14:54:43.076  - error: zigbee.0 (1520) Error: DatabaseEntry with ID '25' already exists
at Database.insert  (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/src/controller/database.ts:35:19)
at Device.undelete  (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/src/controller/model/device.ts:390:25)
at Controller.onDeviceJoined  (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/src/controller/controller.ts:508:20)
at ZStackAdapter.emit (events.js:314:20)
at ZStackAdapter.EventEmitter.emit (domain.js:483:12)
at ZStackAdapter.onZnpRecieved  (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:736:22)
at Znp.emit (events.js:314:20)
at Znp.EventEmitter.emit (domain.js:483:12)
at Znp.onUnpiParsed  (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:108:18)
at Parser.emit (events.js:314:20)
2022-03-27 14:54:43.077  - error: zigbee.0 (1520) DatabaseEntry with ID '25' already exists
2022-03-27 14:54:43.132  - info: zigbee.0 (1520) cleaned everything up...
2022-03-27 14:54:43.573  - info: zigbee.0 (1520) Zigbee: disabling joining new devices.
2022-03-27 14:54:43.637  - info: zigbee.0 (1520) terminating

<!--EndFragment-->
</body>
</html>
```
 After this event, the the Device ist lost. Other devices lost previously must be repaired to access them, losing all previously attached attributes like name, group membership etc.

Maybe some has a hint for me solving this issue.

Thanks a lot!

fraggle_iw
--
Mod Edit: Code tags around error message.

**Comment by fraggle-iw** [comment]
@asgothian Thank you for your quick response.

I updated from github.

In the past only Osram/Ledvance Devices got lost:
![grafik](https://user-images.githubusercontent.com/93135495/160405822-84985603-2308-440b-a882-520f6802d908.png)
![grafik](https://user-images.githubusercontent.com/93135495/160406047-db6da890-9ef6-4672-8339-5872e2f9365c.png)

The third one is a Osram Ligthify RGB Lightstipe. I cant post the exact model because it is a bit difficult to join this device.
After i managed to join it, i will post the necessary info.

Thanks fraggle-iw

**Comment by fraggle-iw** [comment]
Here ist the log with the last event an some entries bevor the error:
`<html><body>


2022-03-27 13:07:34.509  - warn: zigbee.0 (1520) Device '0x00158d0001923c99' announced itself
--
2022-03-27 13:25:43.825  - warn: zigbee.0 (1520) Device '0x00158d0001923c99' announced itself
2022-03-27 13:30:00.028  - info: javascript.0 (1407) script.js.common.HA.Fenster_Heizung_Kueche: ###Küche: Heizung ein, Temperatur: 19
2022-03-27 13:30:00.046  - info: javascript.0 (1407) script.js.common.HA.Fenster_Heizung_EZ_WZ: ###EZ:###WZ: Heizung ein, Temperatur: 21
2022-03-27 13:41:01.508  - warn: zigbee.0 (1520) DeviceAvailability:Stopping to ping 0x2c1165fffe091e37 TRADFRIbulbE27WWclear250lm after 4 ping attempts
2022-03-27 13:52:25.693  - warn: zigbee.0 (1520) DeviceAvailability:Stopping to ping 0x7cb03eaa00b127e4 Classic A60 W clear - LIGHTIFY after 4 ping attempts
2022-03-27 14:05:10.414  - info: javascript.0 (1407) script.js.Tageszeiten: neue Tagezeit: Nachmittag
2022-03-27 14:05:10.415  - info: javascript.0 (1407) script.js.Tageszeiten: nächte kommende Tagezeit: Abend
2022-03-27 14:26:51.204  - warn: zigbee.0 (1520) State value to set for "zigbee.0.842e14fffe2694a0.load_estimate" has value "-8000" less than min "0"
2022-03-27 14:44:21.133  - warn: zigbee.0 (1520) Device '0x00158d0001923c99' announced itself
2022-03-27 14:54:33.436  - warn: zigbee.0 (1520) Device '0x00158d0001923c99' announced itself
2022-03-27 14:54:41.407  - warn: zigbee.0 (1520) Device '0x7cb03eaa0a0507b9' announced itself
2022-03-27 14:54:41.413  - warn: zigbee.0 (1520) Device '0x7cb03eaa00b130fd' announced itself
2022-03-27 14:54:41.469  - warn: zigbee.0 (1520) Blocked interview for 'undefined' because the network is closed
2022-03-27 14:54:41.998  - info: javascript.0 (1407) script.js.common.LS.BWM_Carport: ###Carport:eingeschaltet, Dimmwert_low.
2022-03-27 14:54:42.216  - info: javascript.0 (1407) script.js.common.LS.BWM_Carport: ###Carport:eingeschaltet, Dimmwert_low.
2022-03-27 14:54:42.687  - error:  zigbee.0 (1520) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
2022-03-27 14:54:42.687  - error: zigbee.0 (1520) unhandled promise rejection: DatabaseEntry with ID '25' already exists
2022-03-27 14:54:43.076  - error: zigbee.0 (1520) Error: DatabaseEntry with ID '25' already exists
at Database.insert  (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/src/controller/database.ts:35:19)
at Device.undelete  (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/src/controller/model/device.ts:390:25)
at Controller.onDeviceJoined  (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/src/controller/controller.ts:508:20)
at ZStackAdapter.emit (events.js:314:20)
at ZStackAdapter.EventEmitter.emit (domain.js:483:12)
at ZStackAdapter.onZnpRecieved  (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:736:22)
at Znp.emit (events.js:314:20)
at Znp.EventEmitter.emit (domain.js:483:12)
at Znp.onUnpiParsed  (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:108:18)
at Parser.emit (events.js:314:20)
2022-03-27 14:54:43.077  - error: zigbee.0 (1520) DatabaseEntry with ID '25' already exists
2022-03-27 14:54:43.132  - info: zigbee.0 (1520) cleaned everything up...
2022-03-27 14:54:43.573  - info: zigbee.0 (1520) Zigbee: disabling joining new devices.
2022-03-27 14:54:43.637  - info: zigbee.0 (1520) terminating
2022-03-27 14:54:43.640  - warn: zigbee.0 (1520) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-03-27 14:54:48.481  - error:  host.ioBroker Caught by controller[0]: This error originated either by  throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch(). The promise  rejected with the reason:
2022-03-27 14:54:48.502  - error: host.ioBroker Caught by controller[1]: Error: DatabaseEntry with ID '25' already exists
2022-03-27 14:54:48.503  - error:  host.ioBroker Caught by controller[1]:     at Database.insert  (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/src/controller/database.ts:35:19)
2022-03-27 14:54:48.504  - error:  host.ioBroker Caught by controller[1]:     at Device.undelete  (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/src/controller/model/device.ts:390:25)
2022-03-27 14:54:48.505  - error:  host.ioBroker Caught by controller[1]:     at Controller.onDeviceJoined   (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/src/controller/controller.ts:508:20)
2022-03-27 14:54:48.505  - error: host.ioBroker Caught by controller[1]:     at ZStackAdapter.emit (events.js:314:20)
2022-03-27 14:54:48.506  - error: host.ioBroker Caught by controller[1]:     at ZStackAdapter.EventEmitter.emit (domain.js:483:12)
2022-03-27 14:54:48.506  - error:  host.ioBroker Caught by controller[1]:     at  ZStackAdapter.onZnpRecieved  (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:736:22)
2022-03-27 14:54:48.507  - error: host.ioBroker Caught by controller[1]:     at Znp.emit (events.js:314:20)
2022-03-27 14:54:48.507  - error: host.ioBroker Caught by controller[1]:     at Znp.EventEmitter.emit (domain.js:483:12)
2022-03-27 14:54:48.508  - error:  host.ioBroker Caught by controller[1]:     at Znp.onUnpiParsed  (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:108:18)
2022-03-27 14:54:48.509  - error: host.ioBroker Caught by controller[1]:     at Parser.emit (events.js:314:20)
2022-03-27 14:54:48.510  - error: host.ioBroker instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-03-27 14:54:48.511  - info: host.ioBroker Restart adapter system.adapter.zigbee.0 because enabled
2022-03-27 14:55:18.573  - info: host.ioBroker instance system.adapter.zigbee.0 started with pid 16505
2022-03-27 14:55:27.914  - info: zigbee.0 (16505) starting. Version 1.6.14 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.22.8, js-controller: 3.3.22
2022-03-27 14:55:28.150  - info: zigbee.0 (16505) Starting Zigbee  npm ...
2022-03-27 14:55:29.402  - info: zigbee.0 (16505) Installed Version: iobroker.zigbee@1.6.14
2022-03-27 14:55:29.884  - info:  zigbee.0 (16505) Coordinator firmware version:  {"type":"zStack3x0","meta":{"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20211217}}
2022-03-27 14:55:29.896  - info: zigbee.0 (16505) Unable to disable LED, unsupported function.
2022-03-27 14:55:29.918  - info: zigbee.0 (16505)   --> transmitPower : high
2022-03-27 14:55:29.938  - info: zigbee.0 (16505) Currently 74 devices are joined:
2022-03-27 14:55:30.218  - info: zigbee.0 (16505) Configuring 0x7cb03eaa00a98895 Classic B40 TW - LIGHTIFY
2022-03-27 14:55:30.226  - info: zigbee.0 (16505) 0x00158d000192ca4b (addr 54062): SPZB0001 - Eurotronic Spirit Zigbee wireless heater thermostat (EndDevice)
2022-03-27 14:55:30.263  - info: zigbee.0 (16505) 0x00158d0001923c99 (addr 41488): SPZB0001 - Eurotronic Spirit Zigbee wireless heater thermostat (EndDevice)
2022-03-27 14:55:30.267  - info: zigbee.0 (16505) 0x000d6f000f5e0c89 (addr 57962): AC01353010G - OSRAM SMART+ Motion Sensor (EndDevice)
 


</body>
</html>`

**Comment by fraggle-iw** [comment]
Here`s the data from the Device which got lost during the error described in the log from my previous post.
![grafik](https://user-images.githubusercontent.com/93135495/160440602-ef6b7b04-3f4c-4091-b394-ee4e455bf998.png)

**Comment by asgothian** [comment]
Can you verify that this message is present each time the error occurs ?

`2022-03-27 14:54:41.469 - warn: zigbee.0 (1520) Blocked interview for 'undefined' because the network is closed`

This message is an indicator that a device is trying to join the network despite the network never having been officially opened. We had to stop certain things from happening due to some Osram Devices resetting at random and then triggering a network join process without the network being opened - creating a number of odd issues in the process.

A.

**Comment by fraggle-iw** [comment]
The device which got lost, has the IEEE 8418260000ca99d2 (which is the database id 34). 
The device with the database id 25 has the IEEE 7cb03eaa00a98895 (btw. also an OSRAM device).

For futher investigation i have to wait until the next device will vanish.

Thanks a lot, fraggle-iw

**Comment by asgothian** [comment]
If you are willing to patch your adapter, you can make it easier to ensure that you identify the correct device:

- Open the file `\opt\iobroker\node_modules\iobroker.zigbee\lib\zigbeecontroller.js` with a text editor.
- Locate the line ` this.warn(`Blocked interview for '${message.ieeeAddr}' because the network is closed`);` (should be around line 585
- Modify the line to read this.warn(`Blocked interview for '${JSON.stringify(message)}' because the network is closed`);
- Save the file and restart the adapter

When the error occurs again, this line should provide you with more information to the device which causes the issue.

A.

**Comment by fraggle-iw** [comment]
OK. I patched zigbeecontroller.js waiting for the error to occur.

**Comment by fraggle-iw** [comment]
Hi,
so last night the error happened agsain:
`2022-03-30 03:00:48.484 - error: zigbee.0 (23270) Error collectOptions for 842e14fffe2694a0. Error: TypeError: Cannot read property '0' of undefined
at Object.convert (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman-converters/converters/fromZigbee.js:3400:55)
at /opt/iobroker/node_modules/iobroker.zigbee/main.js:465:43
at StatesController.collectOptions (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:179:23)
2022-03-30 03:02:02.120 - error: zigbee.0 (23270) Error collectOptions for 842e14fffe20510f. Error: TypeError: Cannot read property '2' of undefined
at Object.convert (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman-converters/converters/fromZigbee.js:3400:55)
at /opt/iobroker/node_modules/iobroker.zigbee/main.js:465:43
at StatesController.collectOptions (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:179:23)
2022-03-30 03:09:20.829 - info: javascript.0 (23243) script.js.common.LS.BWM_Carport: ###Carport:eingeschaltet, Dimmwert_low.
2022-03-30 04:00:00.033 - info: javascript.0 (23243) script.js.common.HA.Fenster_Heizung_Bad: ###Bad: Heizung ein, Temperatur: 22.5
2022-03-30 04:09:05.266 - info: javascript.0 (23243) script.js.common.LS.BWM_Carport: ###Carport:eingeschaltet, Dimmwert_low.
2022-03-30 04:21:28.774 - info: javascript.0 (23243) script.js.common.LS.BWM_Kuechenterrasse: ###Küchenterrasse: Bewegung erkannt, Dimmwert_high.
2022-03-30 04:24:28.768 - info: javascript.0 (23243) script.js.common.LS.BWM_Kuechenterrasse: ###Küchenterrasse: Bewegung beendet, Dimmwert_low.
2022-03-30 04:39:05.657 - info: javascript.0 (23243) script.js.common.LS.BWM_Carport: ###Carport:eingeschaltet, Dimmwert_low.
2022-03-30 04:51:30.624 - info: javascript.0 (23243) script.js.common.LS.BWM_Kuechenterrasse: ###Küchenterrasse: Bewegung erkannt, Dimmwert_high.
2022-03-30 04:54:30.618 - info: javascript.0 (23243) script.js.common.LS.BWM_Kuechenterrasse: ###Küchenterrasse: Bewegung beendet, Dimmwert_low.
2022-03-30 05:00:00.033 - info: javascript.0 (23243) script.js.common.HA.Fenster_Heizung_EZ_WZ: ###EZ:###WZ: Heizung ein, Temperatur: 20
2022-03-30 05:00:00.058 - info: javascript.0 (23243) script.js.common.HA.Fenster_Heizung_Kueche: ###Küche: Heizung ein, Temperatur: 17.5
2022-03-30 05:08:41.358 - info: javascript.0 (23243) script.js.Tageszeiten: neue Tagezeit: Morgendämmerung
2022-03-30 05:08:41.359 - info: javascript.0 (23243) script.js.Tageszeiten: nächte kommende Tagezeit: Sonnenaufgang
2022-03-30 05:09:06.067 - info: javascript.0 (23243) script.js.common.LS.BWM_Carport: ###Carport:eingeschaltet, Dimmwert_low.
2022-03-30 05:39:06.589 - info: javascript.0 (23243) script.js.common.LS.BWM_Carport: ###Carport:eingeschaltet, Dimmwert_low.
2022-03-30 05:52:41.357 - info: javascript.0 (23243) script.js.common.LS.SW_Bad_neu: ###Bad: nauticalDawn: ein, 75.
2022-03-30 05:52:41.359 - info: javascript.0 (23243) script.js.common.LS.SW_EZ_Schreibtisch: ###EZ_Schreibtisch: nauticalDawn: ein, 75.
2022-03-30 05:53:41.358 - info: javascript.0 (23243) script.js.common.LS.BWM_Buero: ###Buero: nauticalDawn: ein, Dimmwert_low.
2022-03-30 05:53:41.359 - info: javascript.0 (23243) script.js.common.LS.SW_Gruppe_Kueche: ###Küche: nauticalDawn: ein, 20.
2022-03-30 05:53:41.359 - info: javascript.0 (23243) script.js.common.LS.SW_Flur_oben: ###Flur_oben: nauticalDawn: ein, Dimmwert_high.
2022-03-30 05:53:41.360 - info: javascript.0 (23243) script.js.common.LS.Gruppe_Wohnzimmer: ###EZ/WZ: nauticalDawn: ein, Dimmwert_low.
2022-03-30 05:53:41.361 - info: javascript.0 (23243) script.js.common.LS.Gruppe_Sterne: ###Sterne: nauticalDawn: ein, Dimmwert_low.
2022-03-30 05:53:41.362 - info: javascript.0 (23243) script.js.common.LS.SW_Kueche_Fenster: ###Kueche: nauticalDawn: ein, Dimmwert_high.
2022-03-30 05:55:30.610 - warn: zigbee.0 (23270) unread brightness change for group members ["0xf0d1b80000147671","0x50325ffffe0d5a71","0x50325ffffe0c908b","0xb4e3f9fffed892eb","0x50325ffffe1367f4"]
2022-03-30 06:00:00.030 - info: javascript.0 (23243) script.js.common.HA.Fenster_Heizung_EZ_WZ: ###EZ:###WZ: Heizung ein, Temperatur: 21
2022-03-30 06:00:00.050 - info: javascript.0 (23243) script.js.common.HA.Fenster_Heizung_Kueche: ###Küche: Heizung ein, Temperatur: 19
2022-03-30 06:08:12.750 - warn: zigbee.0 (23270) Device '0xb4e3f9fffe14c8cf' announced itself
2022-03-30 06:09:07.580 - info: javascript.0 (23243) script.js.common.LS.BWM_Carport: ###Carport:eingeschaltet, Dimmwert_low.
2022-03-30 06:09:11.075 - warn: zigbee.0 (23270) Device '0x000d6f000f77ca3e' announced itself
2022-03-30 06:19:10.499 - info: javascript.0 (23243) script.js.common.LS.BWM_Kuechenterrasse: ###Küchenterrasse: Bewegung erkannt, Dimmwert_high.
2022-03-30 06:22:10.482 - info: javascript.0 (23243) script.js.common.LS.BWM_Kuechenterrasse: ###Küchenterrasse: Bewegung beendet, Dimmwert_low.
2022-03-30 07:08:18.371 - info: javascript.0 (23243) script.js.common.LS.BWM_Carport: ###Carport:eingeschaltet, Dimmwert_low.
2022-03-30 07:09:28.179 - info: javascript.0 (23243) script.js.Tageszeiten: neue Tagezeit: Sonnenaufgang
2022-03-30 07:09:28.180 - info: javascript.0 (23243) script.js.Tageszeiten: nächte kommende Tagezeit: Morgen
2022-03-30 07:10:28.179 - info: javascript.0 (23243) script.js.common.LS.BWM_Buero: ###Buero: sunrise+1: aus, Dimmwert_low.
2022-03-30 07:10:28.180 - info: javascript.0 (23243) script.js.common.LS.SW_Flur_oben: ###Flur_oben: sunrise: aus.
2022-03-30 07:10:28.181 - info: javascript.0 (23243) script.js.common.LS.BWM_Kuechenterrasse: ###Küchenterrasse: sunrise+1, ausgeschaltet.
2022-03-30 07:10:28.182 - info: javascript.0 (23243) script.js.common.LS.SW_Bad_neu: ###Bad: sunrise: aus, 30.
2022-03-30 07:10:28.183 - info: javascript.0 (23243) script.js.common.LS.SW_Kueche_Fenster: ###Kueche: sunrise: aus.
2022-03-30 07:10:28.184 - info: javascript.0 (23243) script.js.common.LS.SW_Gruppe_Kueche: ###Küche: sunrise: aus, 0.
2022-03-30 07:10:28.185 - info: javascript.0 (23243) script.js.common.LS.SW_EZ_Schreibtisch: ###EZ_Schreibtisch: sunrise: aus, 30.
2022-03-30 07:10:54.222 - warn: zigbee.0 (23270) Device '0xccccccfffe25a083' announced itself
2022-03-30 07:11:00.721 - warn: zigbee.0 (23270) Blocked interview for '{"status":"started","device":{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":34,"_type":"Router","_ieeeAddr":"0x8418260000ca99d2","_networkAddress":22881,"_manufacturerID":48042,"_endpoints":[{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":3,"profileID":49246,"deviceID":528,"inputClusters":[4096,0,3,4,5,6,8,768,64527],"outputClusters":[25],"deviceNetworkAddress":22881,"deviceIeeeAddress":"0x8418260000ca99d2","clusters":{},"_binds":[],"_configuredReportings":[],"meta":{},"pendingRequests":[]}],"_manufacturerName":"OSRAM","_powerSource":"Mains (single phase)","_modelID":"Flex RGBW","_applicationVersion":1,"_stackVersion":2,"_zclVersion":1,"_hardwareVersion":1,"_dateCode":"20140331CNWT****","_softwareBuildID":"V1.05.10","_interviewCompleted":false,"_interviewing":false,"_skipDefaultResponse":false,"_skipTimeResponse":false,"meta":{},"_lastSeen":1648617060719,"_defaultSendRequestWhen":"immediate","_linkquality":43,"_deleted":false}}' because the network is closed
2022-03-30 07:11:00.756 - warn: zigbee.0 (23270) Blocked interview for '{"status":"started","device":{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":25,"_type":"Unknown","_ieeeAddr":"0x7cb03eaa00b130e9","_networkAddress":1185,"_endpoints":[],"_interviewCompleted":false,"_interviewing":false,"_skipDefaultResponse":false,"_skipTimeResponse":false,"meta":{},"_lastSeen":1648617060756,"_defaultSendRequestWhen":"immediate"}}' because the network is closed
2022-03-30 07:11:00.763 - error: zigbee.0 (23270) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-03-30 07:11:00.764 - error: zigbee.0 (23270) unhandled promise rejection: DatabaseEntry with ID '25' already exists
2022-03-30 07:11:01.091 - error: zigbee.0 (23270) Error: DatabaseEntry with ID '25' already exists
at Database.insert (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/src/controller/database.ts:35:19)
at Device.undelete (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/src/controller/model/device.ts:390:25)
at Controller.onDeviceJoined (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/src/controller/controller.ts:510:20)
at ZStackAdapter.emit (events.js:314:20)
at ZStackAdapter.EventEmitter.emit (domain.js:483:12)
at ZStackAdapter.onZnpRecieved (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:736:22)
at Znp.emit (events.js:314:20)
at Znp.EventEmitter.emit (domain.js:483:12)
at Znp.onUnpiParsed (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:108:18)
at Parser.emit (events.js:314:20)
2022-03-30 07:11:01.092 - error: zigbee.0 (23270) DatabaseEntry with ID '25' already exists
2022-03-30 07:11:01.131 - info: zigbee.0 (23270) cleaned everything up...
2022-03-30 07:11:01.582 - info: zigbee.0 (23270) Zigbee: disabling joining new devices.
2022-03-30 07:11:01.638 - warn: zigbee.0 (23270) Object zigbee.0.7cb03eaa00a98895 is invalid: obj.type has to exist
2022-03-30 07:11:01.639 - warn: zigbee.0 (23270) This object will not be created in future versions. Please report this to the developer.
2022-03-30 07:11:01.640 - warn: zigbee.0 (23270) Object zigbee.0.8418260000ca99d2 is invalid: obj.type has to exist
2022-03-30 07:11:01.641 - warn: zigbee.0 (23270) This object will not be created in future versions. Please report this to the developer.
2022-03-30 07:11:01.645 - info: zigbee.0 (23270) terminating
2022-03-30 07:11:01.647 - warn: zigbee.0 (23270) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-03-30 07:11:01.879 - info: zigbee.0 (23270) Successfully interviewed '0x8418260000ca99d2', device has succesfully been paired
2022-03-30 07:11:01.880 - info: zigbee.0 (23270) Device '0x8418260000ca99d2' is supported, identified as: OSRAM Flex RGBW (4052899926110)
2022-03-30 07:11:01.885 - info: zigbee.0 (23270) Configuring 0x8418260000ca99d2 Flex RGBW
2022-03-30 07:11:02.255 - warn: zigbee.0 (23270) get state error: Connection is closed.
2022-03-30 07:11:02.259 - warn: zigbee.0 (23270) Could not perform strict object check of state zigbee.0.8418260000ca99d2.link_quality: Connection is closed.
2022-03-30 07:11:02.260 - warn: zigbee.0 (23270) get state error: Connection is closed.
2022-03-30 07:11:02.400 - error: host.ioBroker Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-03-30 07:11:02.422 - error: host.ioBroker Caught by controller[1]: Error: DatabaseEntry with ID '25' already exists
2022-03-30 07:11:02.423 - error: host.ioBroker Caught by controller[1]: at Database.insert (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/src/controller/database.ts:35:19)
2022-03-30 07:11:02.424 - error: host.ioBroker Caught by controller[1]: at Device.undelete (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/src/controller/model/device.ts:390:25)
2022-03-30 07:11:02.424 - error: host.ioBroker Caught by controller[1]: at Controller.onDeviceJoined (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/src/controller/controller.ts:510:20)
2022-03-30 07:11:02.425 - error: host.ioBroker Caught by controller[1]: at ZStackAdapter.emit (events.js:314:20)
2022-03-30 07:11:02.425 - error: host.ioBroker Caught by controller[1]: at ZStackAdapter.EventEmitter.emit (domain.js:483:12)
2022-03-30 07:11:02.426 - error: host.ioBroker Caught by controller[1]: at ZStackAdapter.onZnpRecieved (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:736:22)
2022-03-30 07:11:02.426 - error: host.ioBroker Caught by controller[1]: at Znp.emit (events.js:314:20)
2022-03-30 07:11:02.427 - error: host.ioBroker Caught by controller[1]: at Znp.EventEmitter.emit (domain.js:483:12)
2022-03-30 07:11:02.427 - error: host.ioBroker Caught by controller[1]: at Znp.onUnpiParsed (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:108:18)
2022-03-30 07:11:02.428 - error: host.ioBroker Caught by controller[1]: at Parser.emit (events.js:314:20)
2022-03-30 07:11:02.429 - error: host.ioBroker instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-03-30 07:11:02.430 - info: host.ioBroker Restart adapter system.adapter.zigbee.0 because enabled
2022-03-30 07:11:32.478 - info: host.ioBroker instance system.adapter.zigbee.0 started with pid 5413
2022-03-30 07:11:38.401 - info: zigbee.0 (5413) starting. Version 1.6.16 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.22.8, js-controller: 3.3.22
2022-03-30 07:11:38.575 - info: zigbee.0 (5413) Starting Zigbee npm ...
2022-03-30 07:11:39.691 - info: zigbee.0 (5413) Installed Version: ioBroker/ioBroker.zigbee
2022-03-30 07:11:40.071 - info: zigbee.0 (5413) Coordinator firmware version: {"type":"zStack3x0","meta":{"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20211217}}
2022-03-30 07:11:40.081 - info: zigbee.0 (5413) Unable to disable LED, unsupported function.
2022-03-30 07:11:40.099 - info: zigbee.0 (5413) --> transmitPower : high
2022-03-30 07:11:40.123 - info: zigbee.0 (5413) Currently 75 devices are joined:
2022-03-30 07:11:40.426 - info: zigbee.0 (5413) Configuring 0x8418260000ca99d2 Flex RGBW
2022-03-30 07:11:40.434 - info: zigbee.0 (5413) 0x00158d000192ca4b (addr 54062): SPZB0001 - Eurotronic Spirit Zigbee wireless heater thermostat (EndDevice)
2022-03-30 07:11:40.468 - info: zigbee.0 (5413) 0x00158d0001923c99 (addr 41488): SPZB0001 - Eurotronic Spirit Zigbee wireless heater thermostat (EndDevice)
`

This is ID25 from Shepherd.db:
`{{"id":25,"type":"Router","ieeeAddr":"0x7cb03eaa00b130e9","nwkAddr":1185,"manufId":48042,"epList":[3],"endpoints":{"3":{"profId":49246,"epId":3,"devId":256,"inClusterList":[4096,0,3,4,5,6,8,64527],"outCluste$`

**Comment by asgothian** [comment]
Unfortunately, the data for ID25 is incomplete - can you please check what kind of device this is ? It seems that 2 devices send a device joined request, but only one of the two devices (the second) causes the crash. This is the device which is already present on ID25 in your shepherd.db 
```
Blocked interview for '{"status":"started","device":{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":25,"_type":"Unknown","_ieeeAddr":"0x7cb03eaa00b130e9","_networkAddress":1185,"_endpoints":[],"_interviewCompleted":false,"_interviewing":false,"_skipDefaultResponse":false,"_skipTimeResponse":false,"meta":{},"_lastSeen":1648617060756,"_defaultSendRequestWhen":"immediate"}}' because the network is closed
```
The data from the line above (_ieeeAddr, _networkAddress) match the data from the DB entry 25.

It seems that the trigger for the crash is the fact that the device is defined as "_type":"Unknown", while the previous Blocked interview for the Eurotronic Thermostat lists the correct device info and does not cause a crash.

I would suggest as an initial test to
- identify the exact device
- perform a full reset of the device (remove the device from the network, power down the device, power up the device)

A.

**Comment by fraggle-iw** [comment]
The device with ID25 from shepherd.db no longer exists. I deleted the entry and several other orphaned lines from shephard.db.

I will further observe the network.

Thanks for your time. fraggle-iw

**Comment by fraggle-iw** [comment]
After 48 h all seems to be good.
