### ISSUE TITLE
701721 - Smart thermostat based on Danfoss Ally (014G2461), Error collectOptions for

### ISSUE THREAD

**Issue by fraggle-iw** [ioBroker/ioBroker.zigbee#1410]
Hi,

all four POPP thermostat [https://www.zigbee2mqtt.io/devices/701721.html](url) on my network produce errors like this one:
```
2022-04-06 19:17:59.199 - error: zigbee.0 (16482) Error collectOptions for 0c4314fffe45309a. Error: TypeError: Cannot read property '0' of undefined
at Object.convert (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman-converters/converters/fromZigbee.js:3407:56)
at /opt/iobroker/node_modules/iobroker.zigbee/main.js:465:43
at StatesController.collectOptions (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:179:23)
```

The errors are varying in the read property '**NUMBER**'. They occure every 10 to 15 minutes for each device.

The devices have different firmware versions.
My Setup:
zigbee Adapter 1.6.16 (non-npm: ioBroker/ioBroker.zigbee) in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.22.8, js-controller: 4.0.21

type:zStack3x0
version:2-1.2.7.1.
revision:20211217
port:/dev/ttyACM0
channel:13

Thank you for support, fraggle-iw

**Comment by asgothian** [comment]
Please provide Context for the error message by
- adding the text `e45309a` to the state zigbee.0.info.debugmessages
- posting the  10 messages from zigbee.0 before and the 10 messages from zigbee.0 following the error.

**Comment by fraggle-iw** [comment]
Here`re the first log entrys.

```
zigbee.0 | 2022-04-08 08:23:12.543 | warn | ELEVATED publishToState: value generated '153' from device 0c4314fffe45309a for 'Link quality'
-- | -- | -- | --
zigbee.0 | 2022-04-08 08:23:12.542 | warn | ELEVATED publishToState: message received '{"linkquality":153}' from device 0c4314fffe45309a type '701721'
zigbee.0 | 2022-04-08 08:19:29.883 | warn | ELEVATED  publishToState: value generated '28' from device 0c4314fffe45309a for  'Position of the valve (= demanded heat) where 0% is fully closed and  100% is fully open'
zigbee.0 | 2022-04-08 08:19:29.883 | warn | ELEVATED publishToState: message received '{"pi_heating_demand":28}' from device 0c4314fffe45309a type '701721'
zigbee.0 | 2022-04-08 08:19:29.883 | warn | ELEVATED  publishToState: value generated '11' from device 0c4314fffe45309a for  'Position of the valve (= demanded heat) where 0% is fully closed and  100% is fully open'
zigbee.0 | 2022-04-08 08:19:29.882 | warn | ELEVATED publishToState: message received '{"pi_heating_demand":11}' from device 0c4314fffe45309a type '701721'
zigbee.0 | 2022-04-08 08:19:29.874 | warn | ELEVATED publishToState: value generated '149' from device 0c4314fffe45309a for 'Link quality'
zigbee.0 | 2022-04-08 08:19:29.873 | warn | ELEVATED publishToState: message received '{"linkquality":149}' from device 0c4314fffe45309a type '701721'
zigbee.0 | 2022-04-08 08:18:10.788 | warn | ELEVATED publishToState: value generated '145' from device 0c4314fffe45309a for 'Link quality'
zigbee.0 | 2022-04-08 08:18:10.787 | warn | ELEVATED publishToState: message received '{"linkquality":145}' from device 0c4314fffe45309a type '701721'
zigbee.0 | 2022-04-08 08:14:46.732 | warn | ELEVATED publishToState: message received '{}' from device 0c4314fffe45309a type '701721'
zigbee.0 | 2022-04-08 08:14:46.731 | error | Error  collectOptions for 0c4314fffe45309a. Error: TypeError: Cannot read  property '2' of undefined     at Object.convert  (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman-converters/converters/fromZigbee.js:3400:55)     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:465:43     at StatesController.collectOptions  (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:179:23)
zigbee.0 | 2022-04-08 08:14:46.719 | warn | ELEVATED publishToState: value generated '153' from device 0c4314fffe45309a for 'Link quality'
zigbee.0 | 2022-04-08 08:14:46.719 | warn | ELEVATED publishToState: message received '{"linkquality":153}' from device 0c4314fffe45309a type '701721'
zigbee.0 | 2022-04-08 08:13:08.874 | warn | ELEVATED publishToState: value generated '149' from device 0c4314fffe45309a for 'Link quality'
zigbee.0 | 2022-04-08 08:13:08.873 | warn | ELEVATED publishToState: message received '{"linkquality":149}' from device 0c4314fffe45309a type '701721'
zigbee.0 | 2022-04-08 08:08:07.035 | warn | ELEVATED publishToState: value generated '142' from device 0c4314fffe45309a for 'Link quality'
zigbee.0 | 2022-04-08 08:08:07.034 | warn | ELEVATED publishToState: message received '{"linkquality":142}' from device 0c4314fffe45309a type '701721'
zigbee.0 | 2022-04-08 08:08:06.191 | warn | ELEVATED publishToState: value generated '95' from device 0c4314fffe45309a for 'Battery percent'
zigbee.0 | 2022-04-08 08:08:06.190 | warn | ELEVATED publishToState: message received '{"battery":95}' from device 0c4314fffe45309a type '701721'
zigbee.0 | 2022-04-08 08:08:06.184 | warn | ELEVATED publishToState: value generated '145' from device 0c4314fffe45309a for 'Link quality'
zigbee.0 | 2022-04-08 08:08:06.182 | warn | ELEVATED publishToState: message received '{"linkquality":145}' from device 0c4314fffe45309a type '701721'
zigbee.0 | 2022-04-08 07:50:15.375 | warn | State value to set for "zigbee.0.842e14fffe2694a0.load_estimate" has value "-8000" less than min "0"
zigbee.0 | 2022-04-08 07:48:52.406 | error | Error  collectOptions for 0c4314fffe48780a. Error: TypeError: Cannot read  property '2' of undefined    at Object.convert  (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman-converters/converters/fromZigbee.js:3400:55)     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:465:43    at  StatesController.collectOptions  (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:179:23)
zigbee.0 | 2022-04-08 07:14:24.648 | error | Error  collectOptions for 0c4314fffe45309a. Error: TypeError: Cannot read  property '2' of undefined    at Object.convert  (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman-converters/converters/fromZigbee.js:3400:55)     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:465:43    at  StatesController.collectOptions  (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:179:23)
```

**Comment by fraggle-iw** [comment]
Maybe this is the cause: [https://github.com/ioBroker/ioBroker.js-controller/issues/1770](url)

**Comment by asgothian** [comment]
No, this is an error in the zigbee-herdsman-converters. 

The error is that in constants.js, structures named `danfossAdaptationRunControl` and `danfossAdaptationRunStatus` are defined, but in the device and from zigbee definitions, they are referenced via `danfossAdaptionRunControl` and `danfossAdaptionRunStatus`

Fixing this requires access to the device.

A.

**Comment by fraggle-iw** [comment]
@asgothian 
Thank you for your effort.

If i can provide any data let me know.

Fraggle-iw

**Comment by asgothian** [comment]
Can you try to patch the zigbee-herdsman-converters code to test possible changes ?

A.

**Comment by fraggle-iw** [comment]
Yes.

**Comment by asgothian** [comment]
If you take a look at the linked issue at the zigbee-herdsman-converters, most relevant code locations should be listed.

initially, i would suggest to patch the "constants.js" file from `danfossAdaptationRun...` to `danfossAdaptionRun...`.

Note that you will have to modify both the definitions and the exports section.

A.

**Comment by fraggle-iw** [comment]
OK. Patched constants.js (both occurrances). Waiting for log data.

**Comment by fraggle-iw** [comment]
Mybee th DP naming should also be corrected:
![grafik](https://user-images.githubusercontent.com/93135495/162695818-2f035bcc-e9da-4595-ba1f-a5d8bc0ba578.png)

**Comment by asgothian** [comment]
> Maybe the DP naming should also be corrected:
> ![grafik](https://user-images.githubusercontent.com/93135495/162695818-2f035bcc-e9da-4595-ba1f-a5d8bc0ba578.png)

I advise against changing this, as it introduces a potentially breaking change. The mane of the DP and the internal name of the functions no not have to match.

A.

**Comment by fraggle-iw** [comment]
OK i won't thouch it. 
No collectOptions errors loged so far. (no errors at all)

**Comment by asgothian** [comment]
Can you post your changes and results at the issue i made on the zigbee-herdsman-converters ?

**Comment by fraggle-iw** [comment]
Yes.

**Comment by asgothian** [comment]
thanks for the help.
