### ISSUE TITLE
Upgrade from v1.6.18 to v1.7.0: Cannot find io-package.json

### ISSUE THREAD

**Issue by BernhardLinz** [ioBroker/ioBroker.zigbee#1457]
Log shows Upgrade and try a start, downgrade is after that not possible
Fragen auch gerne in Deutsch

```
2022-05-28 16:25:47.002  - info: host.iobroker iobroker upgrade zigbee@1.7.0
2022-05-28 16:25:48.565  - info: host.iobroker iobroker Update zigbee from @1.6.18 to @1.7.0
2022-05-28 16:25:48.614  - info: host.iobroker iobroker host.iobroker Adapter "system.adapter.zigbee.0" is stopped.
2022-05-28 16:25:48.644  - info: host.iobroker "system.adapter.zigbee.0" disabled
2022-05-28 16:25:48.645  - info: host.iobroker stopInstance system.adapter.zigbee.0 (force=false, process=true)
2022-05-28 16:25:48.648  - info: host.iobroker stopInstance system.adapter.zigbee.0 send kill signal
2022-05-28 16:25:48.648  - info: zigbee.0 (2238) Got terminate signal TERMINATE_YOURSELF
2022-05-28 16:25:48.660  - info: zigbee.0 (2238) cleaned everything up...
2022-05-28 16:25:48.759  - info: zigbee.0 (2238) Zigbee: disabling joining new devices.
2022-05-28 16:25:48.788  - info: host.iobroker iobroker host.iobroker Adapter "system.adapter.zigbee.1" is stopped.
2022-05-28 16:25:48.879  - info: zigbee.0 (2238) terminating
2022-05-28 16:25:48.881  - info: zigbee.0 (2238) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2022-05-28 16:25:48.904  - info: host.iobroker "system.adapter.zigbee.1" disabled
2022-05-28 16:25:48.905  - info: host.iobroker stopInstance system.adapter.zigbee.1 (force=false, process=true)
2022-05-28 16:25:49.229  - info: host.iobroker stopInstance system.adapter.zigbee.1 send kill signal
2022-05-28 16:25:49.037  - info: zigbee.1 (2261) Got terminate signal TERMINATE_YOURSELF
2022-05-28 16:25:49.078  - info: zigbee.1 (2261) cleaned everything up...
2022-05-28 16:25:49.235  - info: zigbee.1 (2261) Zigbee: disabling joining new devices.
2022-05-28 16:25:49.591  - info: zigbee.1 (2261) terminating
2022-05-28 16:25:49.612  - info: zigbee.1 (2261) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2022-05-28 16:25:49.652  - info: host.iobroker stopInstance system.adapter.zigbee.0 killing pid 2238
2022-05-28 16:25:49.900  - info: host.iobroker iobroker NPM version: 6.14.17Installing iobroker.zigbee@1.7.0... (System call)
2022-05-28 16:25:49.930  - info: host.iobroker instance system.adapter.zigbee.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2022-05-28 16:25:50.235  - info: host.iobroker stopInstance system.adapter.zigbee.1 killing pid 2261
2022-05-28 16:25:50.344  - info: host.iobroker instance system.adapter.zigbee.1 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2022-05-28 16:26:25.965  - info: host.iobroker iobroker + iobroker.zigbee@1.7.0added 1 package from 1 contributor, removed 1 package and updated 10 packages in 35.024s
2022-05-28 16:26:28.025  - info: host.iobroker iobroker 118 packages are looking for funding  run `npm fund` for details
2022-05-28 16:26:28.070  - error: host.iobroker iobroker Cannot find io-package.json in /opt/iobroker/node_modules/iobroker.zigbee
2022-05-28 16:26:29.110  - info: host.iobroker iobroker exit 29
2022-05-28 16:27:01.871  - info: host.iobroker "system.adapter.zigbee.0" enabled
2022-05-28 16:27:02.099  - info: host.iobroker instance system.adapter.zigbee.0 started with pid 1104611
2022-05-28 16:27:04.200  - error: host.iobroker Caught by controller[0]: /opt/iobroker/node_modules/@iobroker/js-controller-adapter/node_modules/jsonfile/index.js:56
2022-05-28 16:27:04.201  - error: host.iobroker Caught by controller[0]:       throw err
2022-05-28 16:27:04.201  - error: host.iobroker Caught by controller[0]:       ^
2022-05-28 16:27:04.201  - error: host.iobroker Caught by controller[0]: SyntaxError: /opt/iobroker/node_modules/iobroker.zigbee/io-package.json: Unexpected token o in JSON at position 10271
2022-05-28 16:27:04.202  - error: host.iobroker Caught by controller[0]:     at JSON.parse (<anonymous>)
2022-05-28 16:27:04.202  - error: host.iobroker Caught by controller[0]:     at Object.readFileSync (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/node_modules/jsonfile/index.js:52:17)
2022-05-28 16:27:04.203  - error: host.iobroker Caught by controller[0]:     at new Adapter (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:289:30)
2022-05-28 16:27:04.203  - error: host.iobroker Caught by controller[0]:     at new Zigbee (/opt/iobroker/node_modules/iobroker.zigbee/main.js:63:9)
2022-05-28 16:27:04.203  - error: host.iobroker Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/main.js:904:5)
2022-05-28 16:27:04.204  - error: host.iobroker Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
2022-05-28 16:27:04.204  - error: host.iobroker Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2022-05-28 16:27:04.204  - error: host.iobroker Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:950:32)
2022-05-28 16:27:04.204  - error: host.iobroker Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
2022-05-28 16:27:04.205  - error: host.iobroker Caught by controller[0]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
2022-05-28 16:27:04.205  - error: host.iobroker instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2022-05-28 16:27:04.206  - info: host.iobroker Restart adapter system.adapter.zigbee.0 because enabled
2022-05-28 16:27:33.895  - info: host.iobroker iobroker upgrade zigbee@1.6.18
2022-05-28 16:27:34.399  - info: host.iobroker instance system.adapter.zigbee.0 started with pid 1105188
2022-05-28 16:27:36.277  - error: host.iobroker iobroker Cannot upgrade: /opt/iobroker/node_modules/iobroker.zigbee/io-package.json: Unexpected token o in JSON at position 10271
2022-05-28 16:27:37.099  - error: host.iobroker Caught by controller[0]: /opt/iobroker/node_modules/@iobroker/js-controller-adapter/node_modules/jsonfile/index.js:56
2022-05-28 16:27:37.099  - error: host.iobroker Caught by controller[0]:       throw err
2022-05-28 16:27:37.100  - error: host.iobroker Caught by controller[0]:       ^
2022-05-28 16:27:37.100  - error: host.iobroker Caught by controller[0]: SyntaxError: /opt/iobroker/node_modules/iobroker.zigbee/io-package.json: Unexpected token o in JSON at position 10271
2022-05-28 16:27:37.100  - error: host.iobroker Caught by controller[0]:     at JSON.parse (<anonymous>)
2022-05-28 16:27:37.100  - error: host.iobroker Caught by controller[0]:     at Object.readFileSync (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/node_modules/jsonfile/index.js:52:17)
2022-05-28 16:27:37.100  - error: host.iobroker Caught by controller[0]:     at new Adapter (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:289:30)
2022-05-28 16:27:37.100  - error: host.iobroker Caught by controller[0]:     at new Zigbee (/opt/iobroker/node_modules/iobroker.zigbee/main.js:63:9)
2022-05-28 16:27:37.100  - error: host.iobroker Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/main.js:904:5)
2022-05-28 16:27:37.100  - error: host.iobroker Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
2022-05-28 16:27:37.100  - error: host.iobroker Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2022-05-28 16:27:37.101  - error: host.iobroker Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:950:32)
2022-05-28 16:27:37.101  - error: host.iobroker Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
2022-05-28 16:27:37.101  - error: host.iobroker Caught by controller[0]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
2022-05-28 16:27:37.101  - error: host.iobroker instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2022-05-28 16:27:37.101  - info: host.iobroker Restart adapter system.adapter.zigbee.0 because enabled
2022-05-28 16:27:37.315  - info: host.iobroker iobroker exit 45
```

**Comment by peer69** [comment]
Same here.

**Comment by Horgul123** [comment]
Can confirm the problem

**Comment by peer69** [comment]
Using npm to downgrade worked for me. Instance came back with former settings without any problems. 1.7 seems to be broken for now. 

> npm install iobroker.zigbee@1.6.18 --loglevel error --prefix "/opt/iobroker"

**Comment by arteck** [comment]
check 1.7.1

**Comment by Grothesk242** [comment]
1.7.1 is installing and starting.
