### ISSUE TITLE
Update to 1.7.1 with failure

### ISSUE THREAD

**Issue by kueppert** [ioBroker/ioBroker.zigbee#1458]
2022-05-28 21:02:30.655 - info: zigbee.0 (9870) starting. Version 1.7.1 in /opt/iobroker/node_modules/iobroker.zigbee, node: v14.19.1, js-controller: 4.0.23
2022-05-28 21:02:30.836 - info: zigbee.0 (9870) delete old Backup files. keep only last 10
2022-05-28 21:02:30.839 - info: zigbee.0 (9870) Starting Zigbee npm ...
2022-05-28 21:02:31.698 - info: zigbee.0 (9870) Installed Version: iobroker.zigbee@1.7.1
2022-05-28 21:02:32.124 - info: zigbee.0 (9870) Coordinator firmware version: {"type":"zStack3x0","meta":{"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20220219}}
2022-05-28 21:02:32.137 - info: zigbee.0 (9870) Unable to disable LED, unsupported function.
2022-05-28 21:02:32.167 - info: zigbee.0 (9870) --> transmitPower : normal
2022-05-28 21:02:32.187 - info: zigbee.0 (9870) Currently 45 devices are joined:
...
2022-05-28 21:02:32.494 - info: zigbee.0 (9870) Zigbee started
2022-05-28 21:02:32.714 - info: zigbee.0 (9870) debug devices set to []
2022-05-28 21:02:33.027 - error: zigbee.0 (9870) uncaught exception: error is not defined
2022-05-28 21:02:33.033 - error: zigbee.0 (9870) ReferenceError: error is not defined
at WriteStream. (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:523:46)
at WriteStream.emit (events.js:412:35)
at WriteStream.emit (domain.js:475:12)
at /opt/iobroker/node_modules/graceful-fs/graceful-fs.js:228:14
at /opt/iobroker/node_modules/graceful-fs/graceful-fs.js:258:16
at FSReqCallback.oncomplete (fs.js:179:23)
2022-05-28 21:02:33.033 - error: zigbee.0 (9870) error is not defined
2022-05-28 21:02:33.041 - error: zigbee.0 (9870) uncaught exception: error is not defined
2022-05-28 21:02:33.041 - error: zigbee.0 (9870) ReferenceError: error is not defined
at WriteStream. (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:523:46)
at WriteStream.emit (events.js:412:35)
at WriteStream.emit (domain.js:475:12)
at /opt/iobroker/node_modules/graceful-fs/graceful-fs.js:228:14
at /opt/iobroker/node_modules/graceful-fs/graceful-fs.js:258:16
at FSReqCallback.oncomplete (fs.js:179:23)
2022-05-28 21:02:33.042 - error: zigbee.0 (9870) error is not defined
2022-05-28 21:02:33.049 - info: zigbee.0 (9870) cleaned everything up...
2022-05-28 21:02:33.244 - info: zigbee.0 (9870) Zigbee: disabling joining new devices.
2022-05-28 21:02:33.317 - error: zigbee.0 (9870) uncaught exception: Cannot read property 'deleteDeviceStates' of undefined
2022-05-28 21:02:33.318 - error: zigbee.0 (9870) TypeError: Cannot read property 'deleteDeviceStates' of undefined
at /opt/iobroker/node_modules/iobroker.zigbee/lib/groups.js:329:51
at Array.forEach ()
at Immediate. (/opt/iobroker/node_modules/iobroker.zigbee/lib/groups.js:325:29)
at processImmediate (internal/timers.js:466:21)
2022-05-28 21:02:33.319 - error: zigbee.0 (9870) Cannot read property 'deleteDeviceStates' of undefined
2022-05-28 21:02:34.061 - info: zigbee.0 (9870) terminating
2022-05-28 21:02:34.068 - warn: zigbee.0 (9870) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-05-28 21:02:34.700 - error: host.ioBroker2 Caught by controller[0]: ReferenceError: error is not defined
2022-05-28 21:02:34.701 - error: host.ioBroker2 Caught by controller[0]: at WriteStream. (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:523:46)
2022-05-28 21:02:34.701 - error: host.ioBroker2 Caught by controller[0]: at WriteStream.emit (events.js:412:35)
2022-05-28 21:02:34.702 - error: host.ioBroker2 Caught by controller[0]: at WriteStream.emit (domain.js:475:12)
2022-05-28 21:02:34.702 - error: host.ioBroker2 Caught by controller[0]: at /opt/iobroker/node_modules/graceful-fs/graceful-fs.js:228:14
2022-05-28 21:02:34.702 - error: host.ioBroker2 Caught by controller[0]: at /opt/iobroker/node_modules/graceful-fs/graceful-fs.js:258:16
2022-05-28 21:02:34.702 - error: host.ioBroker2 Caught by controller[0]: at FSReqCallback.oncomplete (fs.js:179:23)
2022-05-28 21:02:34.703 - error: host.ioBroker2 Caught by controller[1]: ReferenceError: error is not defined
2022-05-28 21:02:34.703 - error: host.ioBroker2 Caught by controller[1]: at WriteStream. (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:523:46)
2022-05-28 21:02:34.703 - error: host.ioBroker2 Caught by controller[1]: at WriteStream.emit (events.js:412:35)
2022-05-28 21:02:34.703 - error: host.ioBroker2 Caught by controller[1]: at WriteStream.emit (domain.js:475:12)
2022-05-28 21:02:34.704 - error: host.ioBroker2 Caught by controller[1]: at /opt/iobroker/node_modules/graceful-fs/graceful-fs.js:228:14
2022-05-28 21:02:34.704 - error: host.ioBroker2 Caught by controller[1]: at /opt/iobroker/node_modules/graceful-fs/graceful-fs.js:258:16
2022-05-28 21:02:34.704 - error: host.ioBroker2 Caught by controller[1]: at FSReqCallback.oncomplete (fs.js:179:23)
2022-05-28 21:02:34.704 - error: host.ioBroker2 Caught by controller[2]: TypeError: Cannot read property 'deleteDeviceStates' of undefined
2022-05-28 21:02:34.705 - error: host.ioBroker2 Caught by controller[2]: at /opt/iobroker/node_modules/iobroker.zigbee/lib/groups.js:329:51
2022-05-28 21:02:34.705 - error: host.ioBroker2 Caught by controller[2]: at Array.forEach ()
2022-05-28 21:02:34.705 - error: host.ioBroker2 Caught by controller[2]: at Immediate. (/opt/iobroker/node_modules/iobroker.zigbee/lib/groups.js:325:29)
2022-05-28 21:02:34.706 - error: host.ioBroker2 Caught by controller[2]: at processImmediate (internal/timers.js:466:21)
2022-05-28 21:02:34.706 - error: host.ioBroker2 instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2022-05-28 21:03:09.053 - error: zigbee.0 (9888) adapter disabled

**Comment by arteck** [comment]
install from GIT plz

**Comment by ToTXR4Y** [comment]
With Git Version:
<html><body>


host.iobroker | 2022-05-28 22:13:17.495 | info | Restart adapter system.adapter.zigbee.0 because enabled
-- | -- | -- | --
host.iobroker | 2022-05-28 22:13:17.494 | error | instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker | 2022-05-28 22:13:17.494 | error | Caught by controller[0]:     at processTicksAndRejections (node:internal/process/task_queues:83:21)
host.iobroker | 2022-05-28 22:13:17.494 | error | Caught by controller[0]:     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
host.iobroker | 2022-05-28 22:13:17.494 | error | Caught by controller[0]:     at emitErrorNT (node:internal/streams/destroy:157:8)
host.iobroker | 2022-05-28 22:13:17.494 | error | Caught by controller[0]:     at WriteStream.emit (node:domain:475:12)
host.iobroker | 2022-05-28 22:13:17.494 | error | Caught by controller[0]:     at WriteStream.emit (node:events:539:35)
host.iobroker | 2022-05-28 22:13:17.494 | error | Caught  by controller[0]:     at WriteStream.<anonymous>  (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:523:37)
host.iobroker | 2022-05-28 22:13:17.493 | error | Caught by controller[0]: TypeError: callback is not a function
zigbee.0 | 2022-05-28 22:13:16.734 | info | Zigbee: disabling joining new devices.
zigbee.0 | 2022-05-28 22:13:16.640 | info | cleaned everything up...
zigbee.0 | 2022-05-28 22:13:16.611 | error | callback is not a function
zigbee.0 | 2022-05-28 22:13:16.611 | error | TypeError: callback is not a function     at WriteStream.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:523:37)     at WriteStream.emit (node:events:539:35)     at WriteStream.emit (node:domain:475:12)     at emitErrorNT (node:internal/streams/destroy:157:8)     at emitErrorCloseNT (node:internal/streams/destroy:122:3)     at processTicksAndRejections (node:internal/process/task_queues:83:21)
zigbee.0 | 2022-05-28 22:13:16.610 | error | uncaught exception: callback is not a function
zigbee.0 | 2022-05-28 22:13:16.308 | info | Zigbee started


</body>
</html>

**Comment by kueppert** [comment]
Updated 2 Minutes ago from Git - and it is now working for me. Thank you :)

**Comment by kueppert** [comment]
With the last version from Git from some minutes ago it is now working for me

**Comment by arteck** [comment]
fixed
