### ISSUE TITLE
Error after update to 1.7.1

### ISSUE THREAD

**Issue by quotschmacher** [ioBroker/ioBroker.zigbee#1463]
After upgrading to 1.7.1 (or higher, even yesterdays Github version) the adapter isn't starting anymore.

Here the complete log (Device configuration only for one device every time)

```
2022-05-31 09:07:40.884 - info: host.iobroker "system.adapter.zigbee.0" enabled
2022-05-31 09:07:41.026 - info: host.iobroker instance system.adapter.zigbee.0 started with pid 896
2022-05-31 09:07:43.087 - debug: zigbee.0 (896) Redis Objects: Use Redis connection: 0.0.0.0:7777
2022-05-31 09:07:43.132 - debug: zigbee.0 (896) Objects client ready ... initialize now
2022-05-31 09:07:43.133 - debug: zigbee.0 (896) Objects create System PubSub Client
2022-05-31 09:07:43.134 - debug: zigbee.0 (896) Objects create User PubSub Client
2022-05-31 09:07:43.212 - debug: zigbee.0 (896) Objects client initialize lua scripts
2022-05-31 09:07:43.217 - debug: zigbee.0 (896) Objects connected to redis: 0.0.0.0:7777
2022-05-31 09:07:43.247 - debug: zigbee.0 (896) Redis States: Use Redis connection: 0.0.0.0:7778
2022-05-31 09:07:43.264 - debug: zigbee.0 (896) States create System PubSub Client
2022-05-31 09:07:43.265 - debug: zigbee.0 (896) States create User PubSub Client
2022-05-31 09:07:43.301 - debug: zigbee.0 (896) States connected to redis: 0.0.0.0:7778
2022-05-31 09:07:43.407 - debug: zigbee.0 (896) Plugin sentry Initialize Plugin (enabled=true)
2022-05-31 09:07:43.698 - info: zigbee.0 (896) starting. Version 1.7.1 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.22.10, js-controller: 4.0.15
2022-05-31 09:07:43.733 - debug: zigbee.0 (896) Using zigbee-herdsman with settings: {"network":{"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11],"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13]},"databasePath":"/opt/iobroker/iobroker-data/zigbee_0/shepherd.db","backupPath":"/opt/iobroker/iobroker-data/zigbee_0/nvbackup.json","serialPort":{"baudRate":115200,"rtscts":false,"path":"tcp://192.168.188.73:20108","adapter":"zstack"},"adapter":{"forceStartWithInconsistentAdapterConfiguration":false}}
2022-05-31 09:07:43.771 - info: zigbee.0 (896) delete old Backup files. keep only last 10
2022-05-31 09:07:43.773 - info: zigbee.0 (896) Starting Zigbee npm ...
2022-05-31 09:07:43.774 - debug: zigbee.0 (896) Starting zigbee-herdsman...
2022-05-31 09:07:44.033 - info: zigbee.0 (896) Installed Version: iobroker.zigbee@1.7.1
2022-05-31 09:07:44.043 - debug: zigbee.0 (896) Backup /opt/iobroker/iobroker-data/zigbee_0/backup_2022_05_31-09_07_43.tar.gz success
2022-05-31 09:07:45.381 - debug: zigbee.0 (896) zigbee-herdsman started
2022-05-31 09:07:45.381 - info: zigbee.0 (896) Coordinator firmware version: {"type":"zStack3x0","meta":{"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20211219}}
2022-05-31 09:07:45.389 - debug: zigbee.0 (896) Zigbee network parameters: panID=6754 channel=11 extendedPanID=dddddddddddddddd
2022-05-31 09:07:45.390 - info: zigbee.0 (896) Unable to disable LED, unsupported function.
2022-05-31 09:07:45.401 - info: zigbee.0 (896) --> transmitPower : normal
2022-05-31 09:07:45.442 - info: zigbee.0 (896) Currently 28 devices are joined:
2022-05-31 09:07:45.442 - debug: zigbee.0 (896) DeviceAvailability:Publish available for 0xb4e3f9fffeb69891 = true
2022-05-31 09:07:45.447 - debug: zigbee.0 (896) DeviceAvailability:Publish LQ for 0xb4e3f9fffeb69891 = 10
...
2022-05-31 09:07:45.527 - debug: zigbee.0 (896) DeviceConfigure:DeviceConfigure 0x90fd9ffffed59a21 TRADFRI bulb E27 WS opal 980lm not needed
...
2022-05-31 09:07:45.535 - info: zigbee.0 (896) Configuring 0x0c4314fffe7a9913 TRADFRI on/off switch
2022-05-31 09:07:45.548 - debug: zigbee.0 (896) New device event: {"type":"device","device":{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":5,"_type":"Router","_ieeeAddr":"0x0017880109d3e7cd","_networkAddress":1376,"_manufacturerID":4107,"_endpoints":[{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":11,"profileID":260,"deviceID":266,"inputClusters":[0,3,4,5,6,8,4096,64514],"outputClusters":[25],"deviceNetworkAddress":1376,"deviceIeeeAddress":"0x0017880109d3e7cd","clusters":{"genBasic":{"attributes":{"modelId":"LOM001","manufacturerName":"Signify Netherlands B.V.","powerSource":1,"zclVersion":2,"appVersion":2,"stackVersion":1,"hwVersion":1,"dateCode":"20211119","swBuildId":"1.93.6"}},"genOnOff":{"attributes":{"onOff":0}}},"_binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b00219fc1d7","endpointID":1}],"_configuredReportings":[{"cluster":6,"attrId":0,"minRepIntval":0,"maxRepIntval":3600,"repChange":0}],"meta":{},"pendingRequests":[]},{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":242,"profileID":41440,"deviceID":97,"inputClusters":[],"outputClusters":[33],"deviceNetworkAddress":1376,"deviceIeeeAddress":"0x0017880109d3e7cd","clusters":{},"_binds":[],"_configuredReportings":[],"meta":{},"pendingRequests":[]}],"_manufacturerName":"Signify Netherlands B.V.","_powerSource":"Mains (single phase)","_modelID":"LOM001","_applicationVersion":2,"_stackVersion":1,"_zclVersion":2,"_hardwareVersion":1,"_dateCode":"20211119","_softwareBuildID":"1.93.6","_interviewCompleted":true,"_interviewing":false,"_skipDefaultResponse":false,"_skipTimeResponse":false,"meta":{"configured":1},"_lastSeen":1653980520234,"_defaultSendRequestWhen":"immediate"},"mapped":{"exposes":[{"type":"switch","features":[{"type":"binary","name":"state","property":"state","access":7,"value_on":"ON","value_off":"OFF","description":"On/off state of the switch","value_toggle":"TOGGLE"}]},{"type":"numeric","name":"linkquality","property":"linkquality","access":1,"unit":"lqi","description":"Link quality (signal strength)","value_min":0,"value_max":255}],"fromZigbee":[{"cluster":"genOnOff","type":["attributeReport","readResponse"]},{"cluster":"genBasic","type":["attributeReport","readResponse"]}],"toZigbee":[{"key":["state","on_time","off_wait_time"]},{"key":["hue_power_on_behavior"]},{"key":["hue_power_on_brightness","hue_power_on_color_temperature","hue_power_on_color"]},{"key":["scene_store"]},{"key":["scene_recall"]},{"key":["scene_add"]},{"key":["scene_remove"]},{"key":["scene_remove_all"]},{"key":["read"]},{"key":["write"]},{"key":["command"]}],"zigbeeModel":["LOM001"],"model":"929002240401","vendor":"Philips","description":"Hue smart plug - EU","ota":{},"options":[]},"name":"0x0017880109d3e7cd"}
...
2022-05-31 09:07:45.578 - info: zigbee.0 (896) 0x0c4314fffe7a9913 (addr 3640): E1743 - IKEA TRADFRI ON/OFF switch (EndDevice)
2022-05-31 09:07:45.579 - info: zigbee.0 (896) 0x00158d00042341f5 (addr 46666): Not supported (model undefined)(Unknown)
2022-05-31 09:07:45.579 - info: zigbee.0 (896) Zigbee started
2022-05-31 09:07:45.699 - debug: zigbee.0 (896) getGroups result: {"901":"Group 901"}
2022-05-31 09:07:45.714 - debug: zigbee.0 (896) DeviceAvailability:register device Ping for "0x90fd9ffffed59a21"
...
2022-05-31 09:07:45.868 - error: zigbee.0 (896) uncaught exception: error is not defined
2022-05-31 09:07:45.868 - error: zigbee.0 (896) ReferenceError: error is not defined
at WriteStream. (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:523:46)
at WriteStream.emit (events.js:326:22)
at WriteStream.EventEmitter.emit (domain.js:483:12)
at internal/fs/streams.js:361:12
at FSReqCallback.oncomplete (fs.js:156:23)
2022-05-31 09:07:45.872 - error: zigbee.0 (896) error is not defined
2022-05-31 09:07:45.887 - info: zigbee.0 (896) cleaned everything up...
2022-05-31 09:07:45.889 - debug: zigbee.0 (896) DeviceAvailability:Publish available for 0x90fd9ffffed59a21 = false
2022-05-31 09:07:45.891 - debug: zigbee.0 (896) DeviceAvailability:Publish LQ for 0x90fd9ffffed59a21 = 0
2022-05-31 09:07:45.893 - debug: zigbee.0 (896) DeviceAvailability:Publish available for 0x7cb03eaa00ad778a = false
...
2022-05-31 09:07:45.980 - info: zigbee.0 (896) Zigbee: disabling joining new devices.
2022-05-31 09:07:46.085 - error: zigbee.0 (896) uncaught exception: error is not defined
2022-05-31 09:07:46.093 - error: zigbee.0 (896) ReferenceError: error is not defined
at WriteStream. (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:523:46)
at WriteStream.emit (events.js:326:22)
at WriteStream.EventEmitter.emit (domain.js:483:12)
at errorOrDestroy (internal/streams/destroy.js:108:12)
at onwriteError (_stream_writable.js:418:5)
at onwrite (_stream_writable.js:445:5)
at doWrite (_stream_writable.js:399:11)
at writeOrBuffer (_stream_writable.js:387:5)
at WriteStream.Writable.write (_stream_writable.js:318:11)
at Request.ondata (internal/streams/legacy.js:19:31)
2022-05-31 09:07:46.095 - error: zigbee.0 (896) error is not defined
2022-05-31 09:07:46.099 - error: zigbee.0 (896) uncaught exception: Parse Error: JS Exception
2022-05-31 09:07:46.099 - error: zigbee.0 (896) Error: Parse Error: JS Exception
at TLSSocket.socketOnData (_http_client.js:474:22)
at TLSSocket.emit (events.js:314:20)
at TLSSocket.EventEmitter.emit (domain.js:483:12)
at addChunk (_stream_readable.js:297:12)
at readableAddChunk (_stream_readable.js:272:9)
at TLSSocket.Readable.push (_stream_readable.js:213:10)
at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
2022-05-31 09:07:46.099 - error: zigbee.0 (896) Exception-Code: HPE_JS_EXCEPTION: Parse Error: JS Exception
2022-05-31 09:07:46.253 - error: host.iobroker Caught by controller[0]: ReferenceError: error is not defined
2022-05-31 09:07:46.253 - error: host.iobroker Caught by controller[0]: at WriteStream. (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:523:46)
2022-05-31 09:07:46.253 - error: host.iobroker Caught by controller[0]: at WriteStream.emit (events.js:326:22)
2022-05-31 09:07:46.254 - error: host.iobroker Caught by controller[0]: at WriteStream.EventEmitter.emit (domain.js:483:12)
2022-05-31 09:07:46.254 - error: host.iobroker Caught by controller[0]: at internal/fs/streams.js:361:12
2022-05-31 09:07:46.254 - error: host.iobroker Caught by controller[0]: at FSReqCallback.oncomplete (fs.js:156:23)
2022-05-31 09:07:46.254 - error: host.iobroker Caught by controller[1]: ReferenceError: error is not defined
2022-05-31 09:07:46.254 - error: host.iobroker Caught by controller[1]: at WriteStream. (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:523:46)
2022-05-31 09:07:46.254 - error: host.iobroker Caught by controller[1]: at WriteStream.emit (events.js:326:22)
2022-05-31 09:07:46.254 - error: host.iobroker Caught by controller[1]: at WriteStream.EventEmitter.emit (domain.js:483:12)
2022-05-31 09:07:46.254 - error: host.iobroker Caught by controller[1]: at errorOrDestroy (internal/streams/destroy.js:108:12)
2022-05-31 09:07:46.254 - error: host.iobroker Caught by controller[1]: at onwriteError (_stream_writable.js:418:5)
2022-05-31 09:07:46.254 - error: host.iobroker Caught by controller[1]: at onwrite (_stream_writable.js:445:5)
2022-05-31 09:07:46.254 - error: host.iobroker Caught by controller[1]: at doWrite (_stream_writable.js:399:11)
2022-05-31 09:07:46.255 - error: host.iobroker Caught by controller[1]: at writeOrBuffer (_stream_writable.js:387:5)
2022-05-31 09:07:46.255 - error: host.iobroker Caught by controller[1]: at WriteStream.Writable.write (_stream_writable.js:318:11)
2022-05-31 09:07:46.255 - error: host.iobroker Caught by controller[1]: at Request.ondata (internal/streams/legacy.js:19:31)
2022-05-31 09:07:46.255 - error: host.iobroker Caught by controller[1]: Error: Parse Error: JS Exception
2022-05-31 09:07:46.255 - error: host.iobroker Caught by controller[1]: at TLSSocket.socketOnData (_http_client.js:474:22)
2022-05-31 09:07:46.255 - error: host.iobroker Caught by controller[1]: at TLSSocket.emit (events.js:314:20)
2022-05-31 09:07:46.255 - error: host.iobroker Caught by controller[1]: at TLSSocket.EventEmitter.emit (domain.js:483:12)
2022-05-31 09:07:46.255 - error: host.iobroker Caught by controller[1]: at addChunk (_stream_readable.js:297:12)
2022-05-31 09:07:46.255 - error: host.iobroker Caught by controller[1]: at readableAddChunk (_stream_readable.js:272:9)
2022-05-31 09:07:46.255 - error: host.iobroker Caught by controller[1]: at TLSSocket.Readable.push (_stream_readable.js:213:10)
2022-05-31 09:07:46.255 - error: host.iobroker Caught by controller[1]: at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
2022-05-31 09:07:46.256 - error: host.iobroker instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2022-05-31 09:07:46.256 - info: host.iobroker Restart adapter system.adapter.zigbee.0 because enabled
2022-05-31 09:07:51.594 - info: host.iobroker "system.adapter.zigbee.0" disabled
```

**Comment by asgothian** [comment]
Please update to the current 1.7.4 from GitHub.

**Comment by quotschmacher** [comment]
looks good. adapter is now running. but i got one warning 

```
DeviceConfigure:DeviceConfigure failed 0x0c4314fffe7a9913 TRADFRI on/off switch, attempt 1 (TypeError: Cannot read property 'split' of undefined at Object.configureRemote [as configure] (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/ikea.js:53:44) at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:145:28) at processTicksAndRejections (internal/process/task_queues.js:97:5) at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:124:17) at DeviceConfigure.onZigbeeStarted (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:60:21) at async Promise.all (index 1))
```

but i think this would be an extra issue.

thanks!
