### ISSUE TITLE
Cannot read property 'color_options' of undefined

### ISSUE THREAD

**Issue by hail0** [ioBroker/ioBroker.zigbee#1481]
Hello,

my Zigbee adapter in iobroker runs regulary in an error when using an ikea bulb. 
Error log enclosed. Does anyone have a clue, what causes the problem?

`2022-06-23` 03:10:18.962  - warn: zigbee.0 (16498) Device '0x50325ffffebc63cc' announced itself
--
2022-06-23 03:10:18.964  - warn: zigbee.0 (16498) Device '0x50325ffffec97604' announced itself
2022-06-23 03:10:18.965  - warn: zigbee.0 (16498) Device '0x50325ffffebf9152' announced itself
2022-06-23 03:10:18.978  - error:  zigbee.0 (16498) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
2022-06-23 03:10:18.978  - error: zigbee.0 (16498) unhandled promise rejection: Cannot read property 'color_options' of undefined
2022-06-23 03:10:18.980  - error: zigbee.0 (16498) TypeError: Cannot read property 'color_options' of undefined
at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/ikea.js:39:19)
at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:44:26)
at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:26:18)
at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:236:54)
at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:560:18)
2022-06-23 03:10:18.980  - error: zigbee.0 (16498) Cannot read property 'color_options' of undefined
2022-06-23 03:10:18.989  - error:  zigbee.0 (16498) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
2022-06-23 03:10:18.989  - error: zigbee.0 (16498) unhandled promise rejection: Cannot read property 'color_options' of undefined
2022-06-23 03:10:18.990  - error: zigbee.0 (16498) TypeError: Cannot read property 'color_options' of undefined
at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/ikea.js:39:19)
at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:44:26)
at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:26:18)
at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:236:54)
at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:560:18)
2022-06-23 03:10:18.990  - error: zigbee.0 (16498) Cannot read property 'color_options' of undefined
2022-06-23 03:10:18.993  - error:  zigbee.0 (16498) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
2022-06-23 03:10:18.993  - error: zigbee.0 (16498) unhandled promise rejection: Cannot read property 'color_options' of undefined
2022-06-23 03:10:18.993  - error: zigbee.0 (16498) TypeError: Cannot read property 'color_options' of undefined
at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/ikea.js:39:19)
at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:44:26)
at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:26:18)
at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:236:54)
at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:560:18)
2022-06-23 03:10:18.993  - error: zigbee.0 (16498) Cannot read property 'color_options' of undefined
2022-06-23 03:10:19.010  - info: zigbee.0 (16498) cleaned everything up...
2022-06-23 03:10:19.050  - info: zigbee.0 (16498) Zigbee: disabling joining new devices.
2022-06-23 03:10:19.511  - info: zigbee.0 (16498) terminating
2022-06-23 03:10:19.512  - warn: zigbee.0 (16498) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-06-23 03:10:20.068  - error:  host.IoBroker Caught by controller[0]: This error originated either by  throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch(). The promise  rejected with the reason:
2022-06-23 03:10:20.068  - error: host.IoBroker Caught by controller[1]: TypeError: Cannot read property 'color_options' of undefined
2022-06-23 03:10:20.068  - error:  host.IoBroker Caught by controller[1]:     at Object.bulbOnEvent [as  onEvent]  (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/ikea.js:39:19)
2022-06-23 03:10:20.068  - error:  host.IoBroker Caught by controller[1]:     at DeviceEvent.callOnEvent  (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:44:26)
2022-06-23 03:10:20.068  - error:  host.IoBroker Caught by controller[1]:     at DeviceEvent.onZigbeeEvent  (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:26:18)
2022-06-23 03:10:20.068  - error:  host.IoBroker Caught by controller[1]:     at  ZigbeeController.callExtensionMethod  (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:236:54)
2022-06-23 03:10:20.069  - error:  host.IoBroker Caught by controller[1]:     at  ZigbeeController.handleDeviceAnnounce  (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:560:18)
2022-06-23 03:10:20.069  - error:  host.IoBroker Caught by controller[2]: This error originated either by  throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch(). The promise  rejected with the reason:
2022-06-23 03:10:20.069  - error: host.IoBroker Caught by controller[3]: TypeError: Cannot read property 'color_options' of undefined
2022-06-23 03:10:20.069  - error:  host.IoBroker Caught by controller[3]:     at Object.bulbOnEvent [as  onEvent]  (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/ikea.js:39:19)
2022-06-23 03:10:20.069  - error:  host.IoBroker Caught by controller[3]:     at DeviceEvent.callOnEvent  (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:44:26)
2022-06-23 03:10:20.069  - error:  host.IoBroker Caught by controller[3]:     at DeviceEvent.onZigbeeEvent  (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:26:18)
2022-06-23 03:10:20.069  - error:  host.IoBroker Caught by controller[3]:     at  ZigbeeController.callExtensionMethod  (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:236:54)
2022-06-23 03:10:20.069  - error:  host.IoBroker Caught by controller[3]:     at  ZigbeeController.handleDeviceAnnounce  (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:560:18)
2022-06-23 03:10:20.069  - error:  host.IoBroker Caught by controller[4]: This error originated either by  throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch(). The promise  rejected with the reason:
2022-06-23 03:10:20.069  - error: host.IoBroker Caught by controller[5]: TypeError: Cannot read property 'color_options' of undefined
2022-06-23 03:10:20.069  - error:  host.IoBroker Caught by controller[5]:     at Object.bulbOnEvent [as  onEvent]  (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/ikea.js:39:19)
2022-06-23 03:10:20.070  - error:  host.IoBroker Caught by controller[5]:     at DeviceEvent.callOnEvent  (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:44:26)
2022-06-23 03:10:20.070  - error:  host.IoBroker Caught by controller[5]:     at DeviceEvent.onZigbeeEvent  (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:26:18)
2022-06-23 03:10:20.070  - error:  host.IoBroker Caught by controller[5]:     at  ZigbeeController.callExtensionMethod  (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:236:54)
2022-06-23 03:10:20.070  - error:  host.IoBroker Caught by controller[5]:     at  ZigbeeController.handleDeviceAnnounce  (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:560:18)
2022-06-23 03:10:20.070  - error: host.IoBroker instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
`

Best regards,
hail0

**Comment by Zefau** [comment]
same for me

<html><body>


zigbee.0 | 2022-06-25 22:57:22.418 | error | Cannot read properties of undefined (reading 'color_options')
-- | -- | -- | --
zigbee.0 | 2022-06-25 22:57:22.418 | error | TypeError: Cannot read properties of undefined (reading 'color_options')     at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/ikea.js:39:19)     at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:44:26)     at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:26:18)     at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:236:54)     at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:560:18)
zigbee.0 | 2022-06-25 22:57:22.417 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'color_options')
zigbee.0 | 2022-06-25 22:57:22.416 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().


</body>
</html>

**Comment by arteck** [comment]
check now

**Comment by hail0** [comment]
> check now

How can we check it?

**Comment by Zefau** [comment]
@hail0 I think he means install from Github (via https://github.com/ioBroker/ioBroker.zigbee) and check if he fixed it.

**Comment by Zefau** [comment]
Usually always enough to install over the old one

**Comment by sir0drake** [comment]
Hello,
just run also into this issue.
Same error message happen to me and in result, the adapter crashes and is been stopped by iob-Host.
i am using the 1.7.5 adapter and dont know from where to load an update.

should i do it by Adapter/Admin-Mode/Katze/Github ?
Does this overwrite the current 1.7.5 ? 

thanks for supporting me

**Comment by hail0** [comment]
> check now

@arteck : Thank you very much for fixing the problem. The error log is clean the last two days -> Problem solved.

BR hail0

**Comment by Git-Romer** [comment]
Had the same problem. Fixed the problem as well for me.
