### ISSUE TITLE
Zigbee-Adapter wird andauernd neu gestartet

### ISSUE THREAD

**Issue by nobtuk** [ioBroker/ioBroker.zigbee#1488]
Hallo,
ich habe seit den letzten Updates Probleme mit dem Zigbee-Adapter. Die Instanz wird immer wieder neu gestartet und dann irgendwann wegen der häufigen Neustarts gestoppt.
Kann das sein das sich der Adapter nicht mit dem aktuellem Admin Adapter verträgt? Älterer Zigbee 1.6.18 und Admin 5.3.8 scheint keine Probleme zu haben. Admin Adapter 5.3.8 und Zigbee 1.7.15 hat wiederumg Probleme.

**Comment by Apollon77** [comment]
mal Log Meldungen posten hilft vllt mehr zu sehen :-)

**Comment by nobtuk** [comment]
Ich hoffe das ist das was Du meinst:

2022-07-04 05:12:44.324 - warn: zigbee.0 (8495) Device '0x842e14fffe14de3e' announced itself
2022-07-04 05:12:44.443 - error: zigbee.0 (8495) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-07-04 05:12:44.445 - error: zigbee.0 (8495) unhandled promise rejection: Cannot read properties of undefined (reading 'color_options')
2022-07-04 05:12:44.488 - error: zigbee.0 (8495) TypeError: Cannot read properties of undefined (reading 'color_options')
at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/ikea.js:39:19)
at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:44:26)
at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:26:18)
at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:236:54)
at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:560:18)
2022-07-04 05:12:44.490 - error: zigbee.0 (8495) Cannot read properties of undefined (reading 'color_options')
2022-07-04 05:12:44.598 - info: zigbee.0 (8495) cleaned everything up...
2022-07-04 05:12:44.816 - info: zigbee.0 (8495) Zigbee: disabling joining new devices.
2022-07-04 05:12:45.133 - info: zigbee.0 (8495) terminating
2022-07-04 05:12:45.143 - warn: zigbee.0 (8495) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-07-04 05:12:45.831 - error: host.raspberrypi Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-07-04 05:12:45.835 - error: host.raspberrypi Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'color_options')
2022-07-04 05:12:45.836 - error: host.raspberrypi Caught by controller[1]: at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/ikea.js:39:19)
2022-07-04 05:12:45.837 - error: host.raspberrypi Caught by controller[1]: at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:44:26)
2022-07-04 05:12:45.837 - error: host.raspberrypi Caught by controller[1]: at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:26:18)
2022-07-04 05:12:45.838 - error: host.raspberrypi Caught by controller[1]: at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:236:54)
2022-07-04 05:12:45.839 - error: host.raspberrypi Caught by controller[1]: at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:560:18)
2022-07-04 05:12:45.839 - error: host.raspberrypi instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-07-04 05:12:45.840 - info: host.raspberrypi Restart adapter system.adapter.zigbee.0 because enabled
2022-07-04 05:13:16.015 - info: host.raspberrypi instance system.adapter.zigbee.0 started with pid 24202
2022-07-04 05:13:32.012 - info: zigbee.0 (24202) starting. Version 1.7.5 in /opt/iobroker/node_modules/iobroker.zigbee, node: v16.15.1, js-controller: 4.0.23
2022-07-04 05:13:32.435 - info: zigbee.0 (24202) delete old Backup files. keep only last 10
2022-07-04 05:13:32.443 - info: zigbee.0 (24202) Starting Zigbee npm ...
2022-07-04 05:13:34.610 - info: zigbee.0 (24202) Installed Version: iobroker.zigbee@1.7.5
2022-07-04 05:13:34.779 - info: zigbee.0 (24202) Coordinator firmware version: {"type":"ConBee2/RaspBee2","meta":{"transportrev":0,"product":0,"majorrel":38,"minorrel":120,"maintrel":0,"revision":"0x26780700"}}
2022-07-04 05:13:34.885 - info: zigbee.0 (24202) Unable to disable LED, unsupported function.
2022-07-04 05:13:34.959 - info: zigbee.0 (24202) --> transmitPower : normal
2022-07-04 05:13:35.596 - info: zigbee.0 (24202) Unable to set transmit power, unsupported function.
2022-07-04 05:13:35.619 - info: zigbee.0 (24202) Currently 12 devices are joined:
2022-07-04 05:13:35.866 - info: zigbee.0 (24202) 0xd0cf5efffeef21d0 (addr 54639): E1746 - IKEA TRADFRI signal repeater (Router)
2022-07-04 05:13:35.896 - info: zigbee.0 (24202) 0x00124b0022fb8fdb (addr 13079): SNZB-04 - SONOFF Contact sensor (EndDevice)
2022-07-04 05:13:35.903 - info: zigbee.0 (24202) 0x00124b00234ddb30 (addr 46999): SNZB-04 - SONOFF Contact sensor (EndDevice)
2022-07-04 05:13:35.908 - info: zigbee.0 (24202) 0x00124b0022fb86d9 (addr 25988): SNZB-04 - SONOFF Contact sensor (EndDevice)
2022-07-04 05:13:35.913 - info: zigbee.0 (24202) 0x00124b0022fd144b (addr 21040): SNZB-04 - SONOFF Contact sensor (EndDevice)
2022-07-04 05:13:35.919 - info: zigbee.0 (24202) 0x00124b0022fb8e76 (addr 14181): SNZB-04 - SONOFF Contact sensor (EndDevice)
2022-07-04 05:13:35.929 - info: zigbee.0 (24202) 0x84fd27fffec22cf6 (addr 39672): TS011F_plug_1 - TuYa Smart plug (with power monitoring) (Router)
2022-07-04 05:13:35.934 - info: zigbee.0 (24202) 0x00124b0022fb80a4 (addr 23289): SNZB-04 - SONOFF Contact sensor (EndDevice)
2022-07-04 05:13:35.942 - info: zigbee.0 (24202) 0xb4e3f9fffe19f114 (addr 38941): TS011F_plug_1 - TuYa Smart plug (with power monitoring) (Router)
2022-07-04 05:13:35.949 - info: zigbee.0 (24202) 0x00124b0022fb8207 (addr 14514): SNZB-04 - SONOFF Contact sensor (EndDevice)
2022-07-04 05:13:35.957 - info: zigbee.0 (24202) 0x804b50fffe047d6d (addr 65395): LCZ030 - TuYa Temperature & humidity & illuminance sensor with display (EndDevice)
2022-07-04 05:13:35.964 - info: zigbee.0 (24202) 0x842e14fffe14de3e (addr 45752): LED1836G9 - IKEA TRADFRI LED bulb E26/E27 806 lumen, dimmable, warm white (Router)
2022-07-04 05:13:35.967 - info: zigbee.0 (24202) Zigbee started
2022-07-04 05:14:37.430 - warn: zigbee.0 (24202) DeviceAvailability:Failed to ping 0xd0cf5efffeef21d0 TRADFRI signal repeater
2022-07-04 05:15:39.436 - warn: zigbee.0 (24202) DeviceAvailability:Failed to ping 0x842e14fffe14de3e TRADFRI bulb E27 WW 806lm
2022-07-04 05:25:47.604 - warn: zigbee.0 (24202) Device '0x842e14fffe14de3e' announced itself
2022-07-04 05:25:47.642 - error: zigbee.0 (24202) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-07-04 05:25:47.644 - error: zigbee.0 (24202) unhandled promise rejection: Cannot read properties of undefined (reading 'color_options')
2022-07-04 05:25:47.652 - error: zigbee.0 (24202) TypeError: Cannot read properties of undefined (reading 'color_options')
at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/ikea.js:39:19)
at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:44:26)
at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:26:18)
at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:236:54)
at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:560:18)
2022-07-04 05:25:47.654 - error: zigbee.0 (24202) Cannot read properties of undefined (reading 'color_options')
2022-07-04 05:25:47.704 - info: zigbee.0 (24202) cleaned everything up...
2022-07-04 05:25:47.929 - info: zigbee.0 (24202) Zigbee: disabling joining new devices.
2022-07-04 05:25:48.209 - info: zigbee.0 (24202) terminating
2022-07-04 05:25:48.215 - warn: zigbee.0 (24202) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-07-04 05:25:48.947 - error: host.raspberrypi Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-07-04 05:25:48.951 - error: host.raspberrypi Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'color_options')
2022-07-04 05:25:48.952 - error: host.raspberrypi Caught by controller[1]: at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/ikea.js:39:19)
2022-07-04 05:25:48.952 - error: host.raspberrypi Caught by controller[1]: at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:44:26)
2022-07-04 05:25:48.953 - error: host.raspberrypi Caught by controller[1]: at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:26:18)
2022-07-04 05:25:48.953 - error: host.raspberrypi Caught by controller[1]: at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:236:54)
2022-07-04 05:25:48.954 - error: host.raspberrypi Caught by controller[1]: at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:560:18)
2022-07-04 05:25:48.954 - error: host.raspberrypi instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-07-04 05:25:48.955 - info: host.raspberrypi Restart adapter system.adapter.zigbee.0 because enabled
2022-07-04 05:26:19.146 - info: host.raspberrypi instance system.adapter.zigbee.0 started with pid 24677
2022-07-04 05:26:32.434 - info: zigbee.0 (24677) starting. Version 1.7.5 in /opt/iobroker/node_modules/iobroker.zigbee, node: v16.15.1, js-controller: 4.0.23
2022-07-04 05:26:32.787 - info: zigbee.0 (24677) delete old Backup files. keep only last 10
2022-07-04 05:26:32.794 - info: zigbee.0 (24677) Starting Zigbee npm ...
2022-07-04 05:26:34.653 - info: zigbee.0 (24677) Installed Version: iobroker.zigbee@1.7.5
2022-07-04 05:26:34.766 - info: zigbee.0 (24677) Coordinator firmware version: {"type":"ConBee2/RaspBee2","meta":{"transportrev":0,"product":0,"majorrel":38,"minorrel":120,"maintrel":0,"revision":"0x26780700"}}
2022-07-04 05:26:34.810 - info: zigbee.0 (24677) Unable to disable LED, unsupported function.
2022-07-04 05:26:34.879 - info: zigbee.0 (24677) --> transmitPower : normal
2022-07-04 05:26:35.548 - info: zigbee.0 (24677) Unable to set transmit power, unsupported function.
2022-07-04 05:26:35.574 - info: zigbee.0 (24677) Currently 12 devices are joined:
2022-07-04 05:26:35.815 - info: zigbee.0 (24677) 0xd0cf5efffeef21d0 (addr 54639): E1746 - IKEA TRADFRI signal repeater (Router)
2022-07-04 05:26:35.843 - info: zigbee.0 (24677) 0x00124b0022fb8fdb (addr 13079): SNZB-04 - SONOFF Contact sensor (EndDevice)
2022-07-04 05:26:35.850 - info: zigbee.0 (24677) 0x00124b00234ddb30 (addr 46999): SNZB-04 - SONOFF Contact sensor (EndDevice)
2022-07-04 05:26:35.856 - info: zigbee.0 (24677) 0x00124b0022fb86d9 (addr 25988): SNZB-04 - SONOFF Contact sensor (EndDevice)
2022-07-04 05:26:35.861 - info: zigbee.0 (24677) 0x00124b0022fd144b (addr 21040): SNZB-04 - SONOFF Contact sensor (EndDevice)
2022-07-04 05:26:35.868 - info: zigbee.0 (24677) 0x00124b0022fb8e76 (addr 14181): SNZB-04 - SONOFF Contact sensor (EndDevice)
2022-07-04 05:26:35.878 - info: zigbee.0 (24677) 0x84fd27fffec22cf6 (addr 39672): TS011F_plug_1 - TuYa Smart plug (with power monitoring) (Router)
2022-07-04 05:26:35.884 - info: zigbee.0 (24677) 0x00124b0022fb80a4 (addr 23289): SNZB-04 - SONOFF Contact sensor (EndDevice)
2022-07-04 05:26:35.893 - info: zigbee.0 (24677) 0xb4e3f9fffe19f114 (addr 38941): TS011F_plug_1 - TuYa Smart plug (with power monitoring) (Router)
2022-07-04 05:26:35.900 - info: zigbee.0 (24677) 0x00124b0022fb8207 (addr 14514): SNZB-04 - SONOFF Contact sensor (EndDevice)
2022-07-04 05:26:35.908 - info: zigbee.0 (24677) 0x804b50fffe047d6d (addr 65395): LCZ030 - TuYa Temperature & humidity & illuminance sensor with display (EndDevice)
2022-07-04 05:26:35.915 - info: zigbee.0 (24677) 0x842e14fffe14de3e (addr 45752): LED1836G9 - IKEA TRADFRI LED bulb E26/E27 806 lumen, dimmable, warm white (Router)
2022-07-04 05:26:35.919 - info: zigbee.0 (24677) Zigbee started

**Comment by nobtuk** [comment]
Ja, ich habe eine Ikea bulb, einen Ikea Repeater und einen Schalter von Ikea. Ich habe jetzt alle Ikea entbunden und habe keine Probleme mehr. Wenn ich den Adapter über Github neu installiere, wie ich aus folgendem Link entnommen habe (https://forum.iobroker.net/topic/55346/zigbee-st%C3%BCrzt-beim-schalten-von-birnen-%C3%BCber-shalter-ab) ändert sich da aber auch noch nichts. Die dort erwähnten Änderungen scheinen doch wohl noch nicht drin zu sein.

**Comment by arteck** [comment]
ist doch schon längst behoben.. in der GIT version

**Comment by klein0r** [comment]
@arteck Auf Facebook und im Forum schlagen immer wieder Leute mit dem Fehler auf, welche dann die GitHub Version installieren. Bald ein neuer Release geplant?

**Comment by arteck** [comment]
mach ich morgen früh

**Comment by andys003** [comment]
Ich habe extra wegen Problemen mit dem Netatmo Adapter, iobroker neu auf den Pi aufgesetzt. Erster Adapter Zigbee läuft schon mal nicht, auch mit der udev/stable 247.3-7+deb11u2 Änderung auf udev/stable 247.3-7+deb11u1 selbe Ergebnis. Stunden verblödelt ohne Ergebnis. Bitte Nachricht wenn es wieder funktioniert.

**Comment by Ilovegym66** [comment]
Bitte im Forum ein Thread eröffnen, mit Details wie in der Vorlage.
Das hier ist ein Jahr alt und kann geschlossen werden.
