### ISSUE TITLE
latest dev build crashes

### ISSUE THREAD

**Issue by cimba007** [ioBroker/ioBroker.zigbee#150]
```

host.ioBroker-RasPi | 2019-01-16 21:06:07.486 | error | instance system.adapter.zigbee.0 terminated with code 0 (OK)
-- | -- | -- | --
Caught | 2019-01-16 21:06:07.486 | error | by controller[124]: 2019-01-16T20:06:07.356Z zigbee:controller info zigbee-shepherd stopped undefined
Caught | 2019-01-16 21:06:07.485 | error | by controller[124]: 2019-01-16T20:06:07.354Z zigbee-shepherd zigbee-shepherd is stopped.
Caught | 2019-01-16 21:06:07.485 | error | by controller[124]: Wed, 16 Jan 2019 20:06:07 GMT cc-znp The serialport /dev/ttyACM1 is closed.
Caught | 2019-01-16 21:06:07.484 | error | by controller[123]: Wed, 16 Jan 2019 20:06:07 GMT cc-znp:SREQ --> ZDO:mgmtPermitJoinReq, { addrmode: 15, dstaddr: 65532, duration: 0, tcsignificance: 0 }
Caught | 2019-01-16 21:06:07.484 | error | by controller[122]: 2019-01-16T20:06:07.271Z zigbee-shepherd:request REQ --> ZDO:mgmtPermitJoinReq
Caught | 2019-01-16 21:06:07.484 | error | by controller[121]: 2019-01-16T20:06:07.251Z zigbee-shepherd zigbee-shepherd is stopping.
Caught | 2019-01-16 21:06:07.483 | error | by controller[120]: at ZShepherd.emit (events.js:208:7)
Caught | 2019-01-16 21:06:07.483 | error | by controller[120]: at emitNone (events.js:106:13)
Caught | 2019-01-16 21:06:07.483 | error | by controller[120]: at ZigbeeController.handleReady (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:118:14)
Caught | 2019-01-16 21:06:07.482 | error | by controller[120]: at ZigbeeController.emit (events.js:208:7)
Caught | 2019-01-16 21:06:07.482 | error | by controller[120]: at emitNone (events.js:106:13)
Caught | 2019-01-16 21:06:07.482 | error | by controller[120]: at ZigbeeController.onReady (/opt/iobroker/node_modules/iobroker.zigbee/main.js:583:19)
Caught | 2019-01-16 21:06:07.481 | error | by controller[120]: at Array.forEach (<anonymous>)
Caught | 2019-01-16 21:06:07.481 | error | by controller[120]: at activeDevices.forEach.device (/opt/iobroker/node_modules/iobroker.zigbee/main.js:585:41)
Caught | 2019-01-16 21:06:07.481 | error | by controller[120]: at getDeviceStartupLogMessage (/opt/iobroker/node_modules/iobroker.zigbee/main.js:598:39)
Caught | 2019-01-16 21:06:07.480 | error | by controller[120]: at Object.findByZigbeeModel (/opt/iobroker/node_modules/zigbee-shepherd-converters/index.js:20:46)
Caught | 2019-01-16 21:06:07.480 | error | by controller[120]: TypeError: Cannot read property 'replace' of undefined
Caught | 2019-01-16 21:06:07.480 | error | by controller[119]: 2019-01-16T20:06:07.184Z zigbee:controller info zigbee-shepherd ready. version: 2.6.3 rev 20181024 undefined
Caught | 2019-01-16 21:06:07.479 | error | by controller[118]: 2019-01-16T20:06:07.132Z zigbee:controller info zigbee-shepherd started! undefined
Caught | 2019-01-16 21:06:07.479 | error | by controller[117]: 2019-01-16T20:06:07.130Z zigbee-shepherd zigbee-shepherd is _ready and _enabled
Caught | 2019-01-16 21:06:07.478 | error | by controller[116]: 2019-01-16T20:06:07.128Z zigbee-shepherd:init Loading devices from database done.
Caught | 2019-01-16 21:06:07.478 | error | by controller[115]: 2019-01-16T20:06:06.846Z zigbee-shepherd:msgHdlr IND <-- ZDO:mgmtPermitJoinRsp
Caught | 2019-01-16 21:06:07.478 | error | by controller[115]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:AREQ <-- ZDO:mgmtPermitJoinRsp, { srcaddr: 0, status: 0 }
Caught | 2019-01-16 21:06:07.477 | error | by controller[114]: 2019-01-16T20:06:06.844Z zigbee-shepherd:msgHdlr IND <-- ZDO:permitJoinInd
Caught | 2019-01-16 21:06:07.477 | error | by controller[113]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:AREQ <-- ZDO:permitJoinInd, { duration: 0 }
Caught | 2019-01-16 21:06:07.477 | error | by controller[112]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SRSP <-- ZDO:mgmtPermitJoinReq, { status: 0 }
Caught | 2019-01-16 21:06:07.476 | error | by controller[111]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SREQ --> ZDO:mgmtPermitJoinReq, { addrmode: 2, dstaddr: 0, duration: 0, tcsignificance: 0 }
Caught | 2019-01-16 21:06:07.476 | error | by controller[111]: 2019-01-16T20:06:06.805Z zigbee-shepherd:request REQ --> ZDO:mgmtPermitJoinReq
Caught | 2019-01-16 21:06:07.476 | error | by controller[110]: 2019-01-16T20:06:06.790Z zigbee-shepherd:msgHdlr IND <-- ZDO:activeEpRsp
Caught | 2019-01-16 21:06:07.475 | error | by controller[109]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:AREQ <-- ZDO:activeEpRsp, { srcaddr: 0, status: 0, nwkaddr: 0, activeepcount: 6, activeeplist: <Buffer 06 05 04 03 02 01> }
Caught | 2019-01-16 21:06:07.475 | error | by controller[108]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SRSP <-- ZDO:activeEpReq, { status: 0 }
Caught | 2019-01-16 21:06:07.474 | error | by controller[107]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SREQ --> ZDO:activeEpReq, { dstaddr: 0, nwkaddrofinterest: 0 }
Caught | 2019-01-16 21:06:07.474 | error | by controller[106]: 2019-01-16T20:06:06.763Z zigbee-shepherd:request REQ --> ZDO:activeEpReq
Caught | 2019-01-16 21:06:07.474 | error | by controller[105]: 2019-01-16T20:06:06.761Z zigbee-shepherd:msgHdlr IND <-- ZDO:nodeDescRsp
Caught | 2019-01-16 21:06:07.473 | error | by controller[104]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:AREQ <-- ZDO:nodeDescRsp, { srcaddr: 0, status: 0, nwkaddr: 0, logicaltype_cmplxdescavai_userdescavai: 0, apsflags_freqband: 64, maccapflags:
Caught | 2019-01-16 21:06:07.473 | error | by controller[103]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SRSP <-- ZDO:nodeDescReq, { status: 0 }
Caught | 2019-01-16 21:06:07.473 | error | by controller[102]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SREQ --> ZDO:nodeDescReq, { dstaddr: 0, nwkaddrofinterest: 0 }
Caught | 2019-01-16 21:06:07.472 | error | by controller[101]: 2019-01-16T20:06:06.718Z zigbee-shepherd:request REQ --> ZDO:nodeDescReq
Caught | 2019-01-16 21:06:07.472 | error | by controller[100]: 2019-01-16T20:06:06.714Z zigbee-shepherd:init Register delegator, epId: 6, profId: 265
Caught | 2019-01-16 21:06:07.471 | error | by controller[99]: 2019-01-16T20:06:06.702Z zigbee-shepherd:request RSP <-- AF:register, status: 0
Caught | 2019-01-16 21:06:07.471 | error | by controller[98]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SRSP <-- AF:register, { status: 0 }
Caught | 2019-01-16 21:06:07.471 | error | by controller[97]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SREQ --> AF:register, { endpoint: 6, appprofid: 265, appdeviceid: 5, appdevver: 0, latencyreq: 0, appnuminclusters: 0, appinclusterlist: [], ap
Caught | 2019-01-16 21:06:07.470 | error | by controller[96]: 2019-01-16T20:06:06.685Z zigbee-shepherd:request REQ --> AF:register
Caught | 2019-01-16 21:06:07.470 | error | by controller[95]: 2019-01-16T20:06:06.684Z zigbee-shepherd:init Register delegator, epId: 5, profId: 264
Caught | 2019-01-16 21:06:07.470 | error | by controller[94]: 2019-01-16T20:06:06.668Z zigbee-shepherd:request RSP <-- AF:register, status: 0
Caught | 2019-01-16 21:06:07.469 | error | by controller[93]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SRSP <-- AF:register, { status: 0 }
Caught | 2019-01-16 21:06:07.469 | error | by controller[92]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SREQ --> AF:register, { endpoint: 5, appprofid: 264, appdeviceid: 5, appdevver: 0, latencyreq: 0, appnuminclusters: 0, appinclusterlist: [], ap
Caught | 2019-01-16 21:06:07.469 | error | by controller[91]: 2019-01-16T20:06:06.648Z zigbee-shepherd:request REQ --> AF:register
Caught | 2019-01-16 21:06:07.468 | error | by controller[90]: 2019-01-16T20:06:06.647Z zigbee-shepherd:init Register delegator, epId: 4, profId: 263
Caught | 2019-01-16 21:06:07.468 | error | by controller[89]: 2019-01-16T20:06:06.635Z zigbee-shepherd:request RSP <-- AF:register, status: 0
Caught | 2019-01-16 21:06:07.467 | error | by controller[88]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SRSP <-- AF:register, { status: 0 }
Caught | 2019-01-16 21:06:07.467 | error | by controller[87]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SREQ --> AF:register, { endpoint: 4, appprofid: 263, appdeviceid: 5, appdevver: 0, latencyreq: 0, appnuminclusters: 0, appinclusterlist: [], ap
Caught | 2019-01-16 21:06:07.467 | error | by controller[86]: 2019-01-16T20:06:06.619Z zigbee-shepherd:request REQ --> AF:register
Caught | 2019-01-16 21:06:07.466 | error | by controller[85]: 2019-01-16T20:06:06.618Z zigbee-shepherd:init Register delegator, epId: 3, profId: 261
Caught | 2019-01-16 21:06:07.466 | error | by controller[84]: 2019-01-16T20:06:06.606Z zigbee-shepherd:request RSP <-- AF:register, status: 0
Caught | 2019-01-16 21:06:07.466 | error | by controller[83]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SRSP <-- AF:register, { status: 0 }
Caught | 2019-01-16 21:06:07.465 | error | by controller[82]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SREQ --> AF:register, { endpoint: 3, appprofid: 261, appdeviceid: 5, appdevver: 0, latencyreq: 0, appnuminclusters: 0, appinclusterlist: [], ap
Caught | 2019-01-16 21:06:07.465 | error | by controller[81]: 2019-01-16T20:06:06.590Z zigbee-shepherd:request REQ --> AF:register
Caught | 2019-01-16 21:06:07.464 | error | by controller[80]: 2019-01-16T20:06:06.589Z zigbee-shepherd:init Register delegator, epId: 2, profId: 257
Caught | 2019-01-16 21:06:07.464 | error | by controller[79]: 2019-01-16T20:06:06.576Z zigbee-shepherd:request RSP <-- AF:register, status: 0
Caught | 2019-01-16 21:06:07.464 | error | by controller[78]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SRSP <-- AF:register, { status: 0 }
Caught | 2019-01-16 21:06:07.463 | error | by controller[77]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SREQ --> AF:register, { endpoint: 2, appprofid: 257, appdeviceid: 5, appdevver: 0, latencyreq: 0, appnuminclusters: 0, appinclusterlist: [], ap
Caught | 2019-01-16 21:06:07.463 | error | by controller[76]: 2019-01-16T20:06:06.560Z zigbee-shepherd:request REQ --> AF:register
Caught | 2019-01-16 21:06:07.463 | error | by controller[75]: 2019-01-16T20:06:06.559Z zigbee-shepherd:init Register delegator, epId: 1, profId: 260
Caught | 2019-01-16 21:06:07.462 | error | by controller[74]: 2019-01-16T20:06:06.545Z zigbee-shepherd:request RSP <-- AF:register, status: 0
Caught | 2019-01-16 21:06:07.462 | error | by controller[73]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SRSP <-- AF:register, { status: 0 }
Caught | 2019-01-16 21:06:07.461 | error | by controller[72]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SREQ --> AF:register, { endpoint: 1, appprofid: 260, appdeviceid: 5, appdevver: 0, latencyreq: 0, appnuminclusters: 0, appinclusterlist: [], ap
Caught | 2019-01-16 21:06:07.461 | error | by controller[71]: 2019-01-16T20:06:06.528Z zigbee-shepherd:request REQ --> AF:register
Caught | 2019-01-16 21:06:07.461 | error | by controller[70]: 2019-01-16T20:06:06.513Z zigbee-shepherd:msgHdlr IND <-- ZDO:activeEpRsp
Caught | 2019-01-16 21:06:07.460 | error | by controller[69]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:AREQ <-- ZDO:activeEpRsp, { srcaddr: 0, status: 0, nwkaddr: 0, activeepcount: 0, activeeplist: <Buffer > }
Caught | 2019-01-16 21:06:07.460 | error | by controller[68]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SRSP <-- ZDO:activeEpReq, { status: 0 }
Caught | 2019-01-16 21:06:07.460 | error | by controller[67]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SREQ --> ZDO:activeEpReq, { dstaddr: 0, nwkaddrofinterest: 0 }
Caught | 2019-01-16 21:06:07.459 | error | by controller[66]: 2019-01-16T20:06:06.488Z zigbee-shepherd:request REQ --> ZDO:activeEpReq
Caught | 2019-01-16 21:06:07.459 | error | by controller[65]: 2019-01-16T20:06:06.482Z zigbee-shepherd:msgHdlr IND <-- ZDO:nodeDescRsp
Caught | 2019-01-16 21:06:07.458 | error | by controller[64]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:AREQ <-- ZDO:nodeDescRsp, { srcaddr: 0, status: 0, nwkaddr: 0, logicaltype_cmplxdescavai_userdescavai: 0, apsflags_freqband: 64, maccapflags: 1
Caught | 2019-01-16 21:06:07.458 | error | by controller[63]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SRSP <-- ZDO:nodeDescReq, { status: 0 }
Caught | 2019-01-16 21:06:07.458 | error | by controller[62]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SREQ --> ZDO:nodeDescReq, { dstaddr: 0, nwkaddrofinterest: 0 }
Caught | 2019-01-16 21:06:07.457 | error | by controller[61]: 2019-01-16T20:06:06.451Z zigbee-shepherd:request REQ --> ZDO:nodeDescReq
Caught | 2019-01-16 21:06:07.457 | error | by controller[60]: 2019-01-16T20:06:06.441Z zigbee-shepherd:request RSP <-- SAPI:getDeviceInfo
Caught | 2019-01-16 21:06:07.457 | error | by controller[59]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SRSP <-- SAPI:getDeviceInfo, { param: 7, value: <Buffer dd dd dd dd dd dd dd dd> }
Caught | 2019-01-16 21:06:07.456 | error | by controller[58]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SREQ --> SAPI:getDeviceInfo, { param: 7 }
Caught | 2019-01-16 21:06:07.456 | error | by controller[57]: 2019-01-16T20:06:06.427Z zigbee-shepherd:request REQ --> SAPI:getDeviceInfo
Caught | 2019-01-16 21:06:07.456 | error | by controller[56]: 2019-01-16T20:06:06.425Z zigbee-shepherd:request RSP <-- SAPI:getDeviceInfo
Caught | 2019-01-16 21:06:07.455 | error | by controller[55]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SRSP <-- SAPI:getDeviceInfo, { param: 6, value: <Buffer 62 1a 00 ff 0c 00 01 b5> }
Caught | 2019-01-16 21:06:07.455 | error | by controller[54]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SREQ --> SAPI:getDeviceInfo, { param: 6 }
Caught | 2019-01-16 21:06:07.454 | error | by controller[53]: 2019-01-16T20:06:06.410Z zigbee-shepherd:request REQ --> SAPI:getDeviceInfo
Caught | 2019-01-16 21:06:07.454 | error | by controller[52]: 2019-01-16T20:06:06.408Z zigbee-shepherd:request RSP <-- SAPI:getDeviceInfo
Caught | 2019-01-16 21:06:07.453 | error | by controller[51]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SRSP <-- SAPI:getDeviceInfo, { param: 5, value: <Buffer 0b 0f 00 ff 0c 00 01 b5> }
Caught | 2019-01-16 21:06:07.453 | error | by controller[50]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SREQ --> SAPI:getDeviceInfo, { param: 5 }
Caught | 2019-01-16 21:06:07.452 | error | by controller[49]: 2019-01-16T20:06:06.391Z zigbee-shepherd:request REQ --> SAPI:getDeviceInfo
Caught | 2019-01-16 21:06:07.452 | error | by controller[48]: 2019-01-16T20:06:06.388Z zigbee-shepherd:request RSP <-- SAPI:getDeviceInfo
Caught | 2019-01-16 21:06:07.451 | error | by controller[47]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SRSP <-- SAPI:getDeviceInfo, { param: 2, value: <Buffer 00 00 00 00 08 00 00 00> }
Caught | 2019-01-16 21:06:07.450 | error | by controller[46]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SREQ --> SAPI:getDeviceInfo, { param: 2 }
Caught | 2019-01-16 21:06:07.450 | error | by controller[45]: 2019-01-16T20:06:06.366Z zigbee-shepherd:request REQ --> SAPI:getDeviceInfo
Caught | 2019-01-16 21:06:07.449 | error | by controller[44]: 2019-01-16T20:06:06.362Z zigbee-shepherd:request RSP <-- SAPI:getDeviceInfo
Caught | 2019-01-16 21:06:07.449 | error | by controller[43]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SRSP <-- SAPI:getDeviceInfo, { param: 1, value: <Buffer 87 ab e1 18 00 4b 12 00> }
Caught | 2019-01-16 21:06:07.448 | error | by controller[42]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SREQ --> SAPI:getDeviceInfo, { param: 1 }
Caught | 2019-01-16 21:06:07.448 | error | by controller[41]: 2019-01-16T20:06:06.346Z zigbee-shepherd:request REQ --> SAPI:getDeviceInfo
Caught | 2019-01-16 21:06:07.447 | error | by controller[40]: 2019-01-16T20:06:06.343Z zigbee-shepherd:request RSP <-- SAPI:getDeviceInfo
Caught | 2019-01-16 21:06:07.441 | error | by controller[39]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SRSP <-- SAPI:getDeviceInfo, { param: 0, value: <Buffer 09 06 00 ff fe 01 45 c0> }
Caught | 2019-01-16 21:06:07.441 | error | by controller[38]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SREQ --> SAPI:getDeviceInfo, { param: 0 }
Caught | 2019-01-16 21:06:07.441 | error | by controller[37]: 2019-01-16T20:06:06.325Z zigbee-shepherd:request REQ --> SAPI:getDeviceInfo
Caught | 2019-01-16 21:06:07.440 | error | by controller[36]: 2019-01-16T20:06:06.318Z zigbee-shepherd:request RSP <-- SYS:version
Caught | 2019-01-16 21:06:07.440 | error | by controller[35]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SRSP <-- SYS:version, { transportrev: 2, product: 0, majorrel: 2, minorrel: 6, maintrel: 3, revision: 20181024 }
Caught | 2019-01-16 21:06:07.439 | error | by controller[34]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SREQ --> SYS:version, {}
Caught | 2019-01-16 21:06:07.439 | error | by controller[33]: 2019-01-16T20:06:06.297Z zigbee-shepherd:request REQ --> SYS:version
Caught | 2019-01-16 21:06:07.439 | error | by controller[32]: 2019-01-16T20:06:06.295Z zigbee-shepherd:init Now the ZNP is a coordinator.
Caught | 2019-01-16 21:06:07.438 | error | by controller[31]: 2019-01-16T20:06:06.292Z zigbee-shepherd:msgHdlr IND <-- ZDO:stateChangeInd
Caught | 2019-01-16 21:06:07.438 | error | by controller[30]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:AREQ <-- ZDO:stateChangeInd, { state: 9 }
Caught | 2019-01-16 21:06:07.438 | error | by controller[29]: Wed, 16 Jan 2019 20:06:06 GMT cc-znp:SRSP <-- ZDO:startupFromApp, { status: 0 }
Caught | 2019-01-16 21:06:07.437 | error | by controller[28]: Wed, 16 Jan 2019 20:06:05 GMT cc-znp:SREQ --> ZDO:startupFromApp, { startdelay: 100 }
Caught | 2019-01-16 21:06:07.437 | error | by controller[27]: 2019-01-16T20:06:05.621Z zigbee-shepherd:request REQ --> ZDO:startupFromApp
Caught | 2019-01-16 21:06:07.436 | error | by controller[26]: 2019-01-16T20:06:05.620Z zigbee-shepherd:init Start the ZNP as a coordinator...
Caught | 2019-01-16 21:06:07.436 | error | by controller[25]: 2019-01-16T20:06:05.617Z zigbee-shepherd:request RSP <-- SAPI:getDeviceInfo
Caught | 2019-01-16 21:06:07.435 | error | by controller[24]: Wed, 16 Jan 2019 20:06:05 GMT cc-znp:SRSP <-- SAPI:getDeviceInfo, { param: 0, value: <Buffer 00 01 00 08 00 00 10 00> }
Caught | 2019-01-16 21:06:07.434 | error | by controller[23]: Wed, 16 Jan 2019 20:06:05 GMT cc-znp:SREQ --> SAPI:getDeviceInfo, { param: 0 }
Caught | 2019-01-16 21:06:07.434 | error | by controller[22]: 2019-01-16T20:06:05.602Z zigbee-shepherd:request REQ --> SAPI:getDeviceInfo
Caught | 2019-01-16 21:06:07.433 | error | by controller[21]: 2019-01-16T20:06:05.585Z zigbee-shepherd:request RSP <-- SAPI:readConfiguration, status: 0
Caught | 2019-01-16 21:06:07.432 | error | by controller[20]: Wed, 16 Jan 2019 20:06:05 GMT cc-znp:SRSP <-- SAPI:readConfiguration, { status: 0, configid: 99, len: 1, value: <Buffer 00> }
Caught | 2019-01-16 21:06:07.432 | error | by controller[19]: Wed, 16 Jan 2019 20:06:05 GMT cc-znp:SREQ --> SAPI:readConfiguration, { configid: 99, len: 1, value: [ 0 ] }
Caught | 2019-01-16 21:06:07.432 | error | by controller[18]: 2019-01-16T20:06:05.558Z zigbee-shepherd:request REQ --> SAPI:readConfiguration
Caught | 2019-01-16 21:06:07.431 | error | by controller[17]: 2019-01-16T20:06:05.545Z zigbee-shepherd:request RSP <-- SAPI:readConfiguration, status: 0
Caught | 2019-01-16 21:06:07.430 | error | by controller[16]: Wed, 16 Jan 2019 20:06:05 GMT cc-znp:SRSP <-- SAPI:readConfiguration, { status: 0, configid: 98, len: 16, value: <Buffer 01 03 05 07 09 0b 0d 0f 00 02 04 06 08 0a 0c 0d> }
Caught | 2019-01-16 21:06:07.430 | error | by controller[15]: Wed, 16 Jan 2019 20:06:05 GMT cc-znp:SREQ --> SAPI:readConfiguration, { configid: 98, len: 16, value: [ 1, 3, 5, 7, 9, 11, 13, 15, 0, 2, 4, 6, 8, 10, 12, 13 ] }
Caught | 2019-01-16 21:06:07.429 | error | by controller[14]: 2019-01-16T20:06:05.512Z zigbee-shepherd:request REQ --> SAPI:readConfiguration
Caught | 2019-01-16 21:06:07.429 | error | by controller[13]: 2019-01-16T20:06:05.499Z zigbee-shepherd:request RSP <-- SAPI:readConfiguration, status: 0
Caught | 2019-01-16 21:06:07.428 | error | by controller[12]: Wed, 16 Jan 2019 20:06:05 GMT cc-znp:SRSP <-- SAPI:readConfiguration, { status: 0, configid: 132, len: 4, value: <Buffer 00 08 00 00> }
Caught | 2019-01-16 21:06:07.428 | error | by controller[11]: Wed, 16 Jan 2019 20:06:05 GMT cc-znp:SREQ --> SAPI:readConfiguration, { configid: 132, len: 4, value: [ 0, 8, 0, 0 ] }
Caught | 2019-01-16 21:06:07.427 | error | by controller[10]: 2019-01-16T20:06:05.484Z zigbee-shepherd:request REQ --> SAPI:readConfiguration
Caught | 2019-01-16 21:06:07.426 | error | by controller[9]: 2019-01-16T20:06:05.471Z zigbee-shepherd:request RSP <-- SAPI:readConfiguration, status: 0
Caught | 2019-01-16 21:06:07.426 | error | by controller[8]: Wed, 16 Jan 2019 20:06:05 GMT cc-znp:SRSP <-- SAPI:readConfiguration, { status: 0, configid: 131, len: 2, value: <Buffer 62 1a> }
Caught | 2019-01-16 21:06:07.425 | error | by controller[7]: Wed, 16 Jan 2019 20:06:05 GMT cc-znp:SREQ --> SAPI:readConfiguration, { configid: 131, len: 2, value: [ 98, 26 ] }
Caught | 2019-01-16 21:06:07.424 | error | by controller[6]: 2019-01-16T20:06:05.397Z zigbee-shepherd:request REQ --> SAPI:readConfiguration
Caught | 2019-01-16 21:06:07.423 | error | by controller[5]: 2019-01-16T20:06:05.379Z zigbee-shepherd:request RSP <-- SYS:osalNvRead, status: 0
Caught | 2019-01-16 21:06:07.423 | error | by controller[4]: Wed, 16 Jan 2019 20:06:05 GMT cc-znp:SRSP <-- SYS:osalNvRead, { status: 0, len: 1, value: <Buffer 55> }
Caught | 2019-01-16 21:06:07.422 | error | by controller[3]: Wed, 16 Jan 2019 20:06:05 GMT cc-znp:SREQ --> SYS:osalNvRead, { id: 3840, offset: 0, len: 1, value: [ 85 ] }
Caught | 2019-01-16 21:06:07.422 | error | by controller[2]: 2019-01-16T20:06:05.249Z zigbee-shepherd:request REQ --> SYS:osalNvRead
Caught | 2019-01-16 21:06:07.421 | error | by controller[1]: Wed, 16 Jan 2019 20:06:05 GMT cc-znp The serialport /dev/ttyACM1 is opened.
Caught | 2019-01-16 21:06:07.419 | error | by controller[0]: 2019-01-16T20:06:05.143Z zigbee-shepherd:init zigbee-shepherd booting...
zigbee.0 | 2019-01-16 21:06:07.356 | info | zigbee-shepherd stopped


```

**Comment by arteck** [comment]
its a dev branch :-)

**Comment by cimba007** [comment]
No Problem, Just Pointinger Out a Bug so it can bei fixed
