### ISSUE TITLE
Firmwarecheck (OTA) crashed, wenn IKEA Styrbar (IKEA E2001/E2002) aktiv

### ISSUE THREAD

**Issue by tugsi** [ioBroker/ioBroker.zigbee#1518]
Wenn man auf Firmware-Updates überprüft, stürzt der Zigbee-Adapter ab, wenn IKEA-Styrbar auch aktiv geschaltet ist und mit gecheckt wird.
Dabei ist es auch egal, wenn man beim OTA-Check vorher den Schalter aufgeweckt hatte.
Er sucht aber zuerst nach aktuelleren Firmwares und es scheint, erst wenn er eine Rückmeldung bekommt, ob es eine neue Version gibt oder nicht, dass er dann erst crashed.

Gerät: https://www.zigbee2mqtt.io/devices/E2001_E2002.html
Infos zum Gerät: 
stack version:103
date code:20200708
build:1.0.024

Fehlermeldung im ioBroker: 

2022-09-01 17:58:53.956 - error: zigbee.0 (10519) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-09-01 17:58:53.957 - error: zigbee.0 (10519) unhandled promise rejection: Timeout - 63764 - 1 - null - 25 - 1 after 30000ms
2022-09-01 17:58:53.959 - error: zigbee.0 (10519) Error: Timeout - 63764 - 1 - null - 25 - 1 after 30000ms
at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
at listOnTimeout (internal/timers.js:557:17)
at processTimers (internal/timers.js:500:7)
2022-09-01 17:58:53.960 - error: zigbee.0 (10519) Timeout - 63764 - 1 - null - 25 - 1 after 30000ms
2022-09-01 17:58:53.983 - info: zigbee.0 (10519) cleaned everything up...
2022-09-01 17:58:54.339 - info: zigbee.0 (10519) Zigbee: disabling joining new devices.
2022-09-01 17:58:54.368 - info: zigbee.0 (10519) Failed to check if update available for '0x14b457fffe91707c' (Device didn't respond to OTA request)
2022-09-01 17:58:54.485 - info: zigbee.0 (10519) terminating
2022-09-01 17:58:54.488 - warn: zigbee.0 (10519) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-09-01 17:58:55.701 - error: host.raspberrypi Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-09-01 17:58:55.712 - error: host.raspberrypi Caught by controller[1]: Error: Timeout - 63764 - 1 - null - 25 - 1 after 30000ms
2022-09-01 17:58:55.713 - error: host.raspberrypi Caught by controller[1]: at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
2022-09-01 17:58:55.714 - error: host.raspberrypi Caught by controller[1]: at listOnTimeout (internal/timers.js:557:17)
2022-09-01 17:58:55.715 - error: host.raspberrypi Caught by controller[1]: at processTimers (internal/timers.js:500:7)
2022-09-01 17:58:55.717 - error: host.raspberrypi instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-09-01 17:58:55.718 - info: host.raspberrypi Restart adapter system.adapter.zigbee.0 because enabled

Deaaktiviert man den Schalter, dann kann man OTA ohne Probleme benutzen.

**Comment by tugsi** [comment]
Hab noch einen aktuelleren Styrbar (mit silbernen Deckel), wenn ich den anmelde und OTA ausprobiere, funktioniert alles normal, er checked und sagt, dass es keine neue Firmware gibt (date code: 20200708
build: 1.0.024), aber der alte Styrbar hat dieselben Daten.
Also vermute ich, dass es an den Schalter selber liegt, dass der Adapter crashed.

**Comment by asgothian** [comment]
Bitte verifizieren: Ist der Styrbar der den Absturz verursacht direkt mit dem Koordinator verbunden oder geht der über einen Router ?

**Comment by arteck** [comment]
installier mal die GIT version ..immer noch ?

**Comment by tugsi** [comment]
> installier mal die GIT version ..immer noch ?

Gerade gemacht, klappt, kein Absturz mehr! 
Danke schön 👍🏻
