### ISSUE TITLE
Adapter crashes randomly

### ISSUE THREAD

**Issue by DcFamas** [ioBroker/ioBroker.zigbee#1520]
Hey there,
Node.js: v16.15.1 (16.17.0)
NPM: 8.11.0 (8.15.0)
Debian, latest version on Synology NAS
Zigbee adapter: latest version
Texas Instruments CC26X2R1 

My Zigbee adapters keeps crashing after a few days. Sometimes I haven't got any problems for a few weeks, sometimes it happens twice a week:

```
host.ioBroker 2022-09-07 15:04:09.688	info	instance system.adapter.zigbee.0 started with pid 833

host.ioBroker 2022-09-07 15:03:39.407	info	Restart adapter system.adapter.zigbee.0 because enabled

host.ioBroker 2022-09-07 15:03:39.401	error	instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

zigbee.0 2022-09-07 15:03:36.744	warn	get state error: Connection is closed.

zigbee.0 2022-09-07 15:03:36.744	warn	Could not perform strict object check of state 
zigbee.0.14b457fffe40f0da.link_quality: DB closed

zigbee.0 2022-09-07 15:03:36.743	warn	get state error: Connection is closed.

zigbee.0 2022-09-07 15:03:36.742	warn	Could not perform strict object check of state zigbee.0.14b457fffe40f0da.available: DB closed

zigbee.0 2022-09-07 15:03:36.434	info	terminating with timeout

zigbee.0 2022-09-07 15:03:35.434	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason

zigbee.0 2022-09-07 15:03:35.433	info	terminating

zigbee.0 2022-09-07 15:03:35.089	info	Zigbee: disabling joining new devices.

zigbee.0 2022-09-07 15:03:34.928	info	cleaned everything up...

zigbee.0 2022-09-07 15:03:34.911	error	Cannot read properties of undefined (reading 'color_options')

zigbee.0 2022-09-07 15:03:34.911	error	TypeError: Cannot read properties of undefined (reading 'color_options') at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/ikea.js:39:19) at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:44:26) at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:26:18) at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:236:54) at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:560:18)

zigbee.0 2022-09-07 15:03:34.910	error	unhandled promise rejection: Cannot read properties of undefined (reading 'color_options')

zigbee.0 2022-09-07 15:03:34.910	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

zigbee.0 2022-09-07 15:03:34.898	warn	Device '0x14b457fffe40f0da' announced itself
```

It all starts with an new device, which want to join. In this case the 0x14b457fffe40f0da. This device is already paired without any problems. I haven't started the joining mode, also I haven't worked on ioBroker or the zigbee adapter. It happens randomly. Sometimes in the middle of the night. It is always this "color_options" failure. In this case the light is an Ikea Float Panel 30x30.

Do you have any idea why this happens?

Thank you and best regards :)

**Comment by asgothian** [comment]
Does "latest version" refer to the current version installed from GitHub ?

A.

**Comment by DcFamas** [comment]
Hey @asgothian. No I meant the latest version which ioBroker want to install. So right now it is v1.7.5. But I have this problem since a few versions, but was to lazy to write an issue on Github. #shameonme Thank you for your fast reply! :)

**Comment by asgothian** [comment]
Please install the current GitHub version and verify if the error persists.

A.

**Comment by DcFamas** [comment]
Installed the current GitHub version. I'll get in touch, when the problem occurs again. Thank you! :)

**Comment by TeraX** [comment]
I have the same issue with different Ikea Tradfri Lamps.
Everytime I switch them on (means they get power - because it's currently not possible to connect them permanantly to a power stripe) the adapter crashs with the same error message also including the Color_code issue.

I will now also update to the lastest guthub version and give feedback what happens (because this happens many times per day till the adapter restarts to many and ioBroker stop the adapter).

**Comment by TeraX** [comment]
After updating the ZigBee Adapter with the GitHub Version 1.7.6 the issue seems resolved.
I will have a look into the log the follow hours and days and give a feedback if there is something not working again.

Issue with ZigBee v.1.7.5
`2022-09-14 07:17:53.793 - warn: zigbee.0 (9243) Device '0x000b57fffeec3596' announced itself
--
2022-09-14 07:17:53.798 - error: zigbee.0 (9243) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-09-14 07:17:53.798 - error: zigbee.0 (9243) unhandled promise rejection: Cannot read properties of undefined (reading 'color_options')
2022-09-14 07:17:53.799 - error: zigbee.0 (9243) TypeError: Cannot read properties of undefined (reading 'color_options')
at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/ikea.js:39:19)
at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:44:26)
at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:26:18)
at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:236:54)
at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:560:18)
2022-09-14 07:17:53.800 - error: zigbee.0 (9243) Cannot read properties of undefined (reading 'color_options')
2022-09-14 07:17:53.805 - info: zigbee.0 (9243) cleaned everything up...
2022-09-14 07:17:53.832 - info: zigbee.0 (9243) Zigbee: disabling joining new devices.
2022-09-14 07:17:54.306 - info: zigbee.0 (9243) terminating
2022-09-14 07:17:54.307 - warn: zigbee.0 (9243) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-09-14 07:17:54.811 - warn: zigbee.0 (9243) get state error: Connection is closed.
2022-09-14 07:17:54.865 - error: host.iobroker Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-09-14 07:17:54.866 - error: host.iobroker Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'color_options')
2022-09-14 07:17:54.866 - error: host.iobroker Caught by controller[1]: at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/ikea.js:39:19)
2022-09-14 07:17:54.866 - error: host.iobroker Caught by controller[1]: at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:44:26)
2022-09-14 07:17:54.866 - error: host.iobroker Caught by controller[1]: at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:26:18)
2022-09-14 07:17:54.866 - error: host.iobroker Caught by controller[1]: at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:236:54)
2022-09-14 07:17:54.866 - error: host.iobroker Caught by controller[1]: at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:560:18)
2022-09-14 07:17:54.866 - error: host.iobroker instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-09-14 07:17:54.866 - info: host.iobroker Restart adapter system.adapter.zigbee.0 because enabled
`

After GitHub Update 1.7.6
`
2022-09-14 08:54:00.157 - warn: zigbee.0 (9574) Device '0x842e14fffe0e91c0' announced itself
--
2022-09-14 08:54:00.159 - warn: zigbee.0 (9574) Device '0xbc33acfffebe6b2d' announced itself
`
No other issues in the log and the adapter is not stopping / restarting automatically.
