### ISSUE TITLE
Adapter is crashing permanently

### ISSUE THREAD

**Issue by WOli19** [ioBroker/ioBroker.zigbee#1564]
The Zigbee adapter ist crashing permanently because of an unhandled exception:

2022-11-07 06:27:11.585 - warn: zigbee.0 (16535) Device '0x003c84fffefacfc2' announced itself
--
2022-11-07 06:27:11.635 - error: zigbee.0 (16535) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-11-07 06:27:11.636 - error: zigbee.0 (16535) unhandled promise rejection: Cannot read properties of undefined (reading 'color_options')
2022-11-07 06:27:11.641 - error: zigbee.0 (16535) TypeError: Cannot read properties of undefined (reading 'color_options')
at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/ikea.js:39:19)
at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:44:26)
at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:26:18)
at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:236:54)
at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:560:18)
2022-11-07 06:27:11.642 - error: zigbee.0 (16535) Cannot read properties of undefined (reading 'color_options')
2022-11-07 06:27:11.673 - info: zigbee.0 (16535) cleaned everything up...
2022-11-07 06:27:11.733 - info: zigbee.0 (16535) Zigbee: disabling joining new devices.
2022-11-07 06:27:12.176 - info: zigbee.0 (16535) terminating
2022-11-07 06:27:12.177 - warn: zigbee.0 (16535) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-11-07 06:27:12.760 - error: host.raspberrypi Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-11-07 06:27:12.767 - error: host.raspberrypi Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'color_options')
2022-11-07 06:27:12.768 - error: host.raspberrypi Caught by controller[1]: at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/ikea.js:39:19)
2022-11-07 06:27:12.768 - error: host.raspberrypi Caught by controller[1]: at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:44:26)
2022-11-07 06:27:12.768 - error: host.raspberrypi Caught by controller[1]: at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:26:18)
2022-11-07 06:27:12.768 - error: host.raspberrypi Caught by controller[1]: at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:236:54)
2022-11-07 06:27:12.768 - error: host.raspberrypi Caught by controller[1]: at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:560:18)
2022-11-07 06:27:12.769 - error: host.raspberrypi instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-11-07 06:27:12.769 - info: host.raspberrypi Restart adapter system.adapter.zigbee.0 because enabled
2022-11-07 06:27:42.857 - info: host.raspberrypi instance system.adapter.zigbee.0 started with pid 39789
2022-11-07 06:27:46.464 - info: zigbee.0 (39789) starting. Version 1.7.5 in /opt/iobroker/node_modules/iobroker.zigbee, node: v18.9.1, js-controller: 4.0.23
2022-11-07 06:27:46.579 - info: zigbee.0 (39789) delete old Backup files. keep only last 10
2022-11-07 06:27:46.582 - info: zigbee.0 (39789) Starting Zigbee npm ...
2022-11-07 06:27:47.052 - info: zigbee.0 (39789) Installed Version: iobroker.zigbee@1.7.5
2022-11-07 06:27:47.463 - info: zigbee.0 (39789) Coordinator firmware version: {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}
2022-11-07 06:27:47.470 - info: zigbee.0 (39789) Unable to disable LED, unsupported function.
2022-11-07 06:27:47.487 - info: zigbee.0 (39789) --> transmitPower : normal
2022-11-07 06:27:47.497 - info: zigbee.0 (39789) Currently 10 devices are joined:
2022-11-07 06:27:47.527 - info: zigbee.0 (39789) 0x9035eafffe1ee6b4 (addr 5967): E2001/E2002 - IKEA STYRBAR remote control N2 (EndDevice)
2022-11-07 06:27:47.534 - info: zigbee.0 (39789) 0x5c0272fffebd4934 (addr 746): 57008000 - Insta Blinds actor with lift/tilt calibration & with with inputs for wall switches (Router)
2022-11-07 06:27:47.536 - info: zigbee.0 (39789) 0x5c0272fffebd4c7a (addr 6950): 57008000 - Insta Blinds actor with lift/tilt calibration & with with inputs for wall switches (Router)
2022-11-07 06:27:47.538 - info: zigbee.0 (39789) 0x5c0272fffebd4c79 (addr 29488): 57008000 - Insta Blinds actor with lift/tilt calibration & with with inputs for wall switches (Router)
2022-11-07 06:27:47.540 - info: zigbee.0 (39789) 0x5c0272fffebd4c93 (addr 53972): 57008000 - Insta Blinds actor with lift/tilt calibration & with with inputs for wall switches (Router)
2022-11-07 06:27:47.542 - info: zigbee.0 (39789) 0x540f57fffe1b6106 (addr 35137): E2001/E2002 - IKEA STYRBAR remote control N2 (EndDevice)
2022-11-07 06:27:47.544 - info: zigbee.0 (39789) 0x94deb8fffe6d6927 (addr 19555): LED2003G10 - IKEA TRADFRI LED bulb E26/27 1100/1055 lumen, dimmable, white spectrum, opal white (Router)
2022-11-07 06:27:47.546 - info: zigbee.0 (39789) 0x003c84fffe6da50b (addr 11276): LED2003G10 - IKEA TRADFRI LED bulb E26/27 1100/1055 lumen, dimmable, white spectrum, opal white (Router)
2022-11-07 06:27:47.548 - info: zigbee.0 (39789) 0x84b4dbfffe90fd3e (addr 28382): E2001/E2002 - IKEA STYRBAR remote control N2 (EndDevice)
2022-11-07 06:27:47.549 - info: zigbee.0 (39789) 0x003c84fffefacfc2 (addr 37206): LED1924G9 - IKEA TRADFRI bulb E26/E27 CWS 800/806 lumen, dimmable, color, opal white (Router)
2022-11-07 06:27:47.550 - info: zigbee.0 (39789) Zigbee started
2022-11-07 06:28:10.209 - warn: zigbee.0 (39789) DeviceAvailability:Failed to ping 0x003c84fffe6da50b TRADFRIbulbE27WSglobeopal1055lm
2022-11-07 06:43:57.803 - warn: zigbee.0 (39789) Device '0x94deb8fffe6d6927' announced itself
2022-11-07 06:43:57.808 - error: zigbee.0 (39789) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-11-07 06:43:57.809 - error: zigbee.0 (39789) unhandled promise rejection: Cannot read properties of undefined (reading 'color_options')
2022-11-07 06:43:57.811 - error: zigbee.0 (39789) TypeError: Cannot read properties of undefined (reading 'color_options')
at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/ikea.js:39:19)
at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:44:26)
at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:26:18)
at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:236:54)
at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:560:18)
2022-11-07 06:43:57.812 - error: zigbee.0 (39789) Cannot read properties of undefined (reading 'color_options')
2022-11-07 06:43:57.821 - info: zigbee.0 (39789) cleaned everything up...
2022-11-07 06:43:57.874 - info: zigbee.0 (39789) Zigbee: disabling joining new devices.
2022-11-07 06:43:58.322 - info: zigbee.0 (39789) terminating
2022-11-07 06:43:58.324 - warn: zigbee.0 (39789) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-11-07 06:43:58.834 - warn: zigbee.0 (39789) get state error: Connection is closed.
2022-11-07 06:43:58.899 - error: host.raspberrypi Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-11-07 06:43:58.900 - error: host.raspberrypi Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'color_options')
2022-11-07 06:43:58.900 - error: host.raspberrypi Caught by controller[1]: at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/ikea.js:39:19)
2022-11-07 06:43:58.900 - error: host.raspberrypi Caught by controller[1]: at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:44:26)
2022-11-07 06:43:58.901 - error: host.raspberrypi Caught by controller[1]: at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:26:18)
2022-11-07 06:43:58.901 - error: host.raspberrypi Caught by controller[1]: at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:236:54)
2022-11-07 06:43:58.901 - error: host.raspberrypi Caught by controller[1]: at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:560:18)
2022-11-07 06:43:58.901 - error: host.raspberrypi instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-11-07 06:43:58.901 - info: host.raspberrypi Restart adapter system.adapter.zigbee.0 because enabled
2022-11-07 06:44:28.962 - info: host.raspberrypi instance system.adapter.zigbee.0 started with pid 40636
2022-11-07 06:44:32.541 - info: zigbee.0 (40636) starting. Version 1.7.5 in /opt/iobroker/node_modules/iobroker.zigbee, node: v18.9.1, js-controller: 4.0.23
2022-11-07 06:44:32.662 - info: zigbee.0 (40636) delete old Backup files. keep only last 10
2022-11-07 06:44:32.665 - info: zigbee.0 (40636) Starting Zigbee npm ...
2022-11-07 06:44:33.111 - info: zigbee.0 (40636) Installed Version: iobroker.zigbee@1.7.5
2022-11-07 06:44:33.519 - info: zigbee.0 (40636) Coordinator firmware version: {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}
2022-11-07 06:44:33.526 - info: zigbee.0 (40636) Unable to disable LED, unsupported function.
2022-11-07 06:44:33.544 - info: zigbee.0 (40636) --> transmitPower : normal
2022-11-07 06:44:33.554 - info: zigbee.0 (40636) Currently 10 devices are joined:
2022-11-07 06:44:33.587 - info: zigbee.0 (40636) 0x9035eafffe1ee6b4 (addr 5967): E2001/E2002 - IKEA STYRBAR remote control N2 (EndDevice)
2022-11-07 06:44:33.593 - info: zigbee.0 (40636) 0x5c0272fffebd4934 (addr 746): 57008000 - Insta Blinds actor with lift/tilt calibration & with with inputs for wall switches (Router)
2022-11-07 06:44:33.595 - info: zigbee.0 (40636) 0x5c0272fffebd4c7a (addr 6950): 57008000 - Insta Blinds actor with lift/tilt calibration & with with inputs for wall switches (Router)
2022-11-07 06:44:33.597 - info: zigbee.0 (40636) 0x5c0272fffebd4c79 (addr 29488): 57008000 - Insta Blinds actor with lift/tilt calibration & with with inputs for wall switches (Router)
2022-11-07 06:44:33.599 - info: zigbee.0 (40636) 0x5c0272fffebd4c93 (addr 53972): 57008000 - Insta Blinds actor with lift/tilt calibration & with with inputs for wall switches (Router)
2022-11-07 06:44:33.601 - info: zigbee.0 (40636) 0x540f57fffe1b6106 (addr 35137): E2001/E2002 - IKEA STYRBAR remote control N2 (EndDevice)
2022-11-07 06:44:33.603 - info: zigbee.0 (40636) 0x94deb8fffe6d6927 (addr 19555): LED2003G10 - IKEA TRADFRI LED bulb E26/27 1100/1055 lumen, dimmable, white spectrum, opal white (Router)
2022-11-07 06:44:33.605 - info: zigbee.0 (40636) 0x003c84fffe6da50b (addr 11276): LED2003G10 - IKEA TRADFRI LED bulb E26/27 1100/1055 lumen, dimmable, white spectrum, opal white (Router)
2022-11-07 06:44:33.607 - info: zigbee.0 (40636) 0x84b4dbfffe90fd3e (addr 28382): E2001/E2002 - IKEA STYRBAR remote control N2 (EndDevice)
2022-11-07 06:44:33.609 - info: zigbee.0 (40636) 0x003c84fffefacfc2 (addr 37206): LED1924G9 - IKEA TRADFRI bulb E26/E27 CWS 800/806 lumen, dimmable, color, opal white (Router)
2022-11-07 06:44:33.610 - info: zigbee.0 (40636) Zigbee started
2022-11-07 06:44:56.322 - warn: zigbee.0 (40636) DeviceAvailability:Failed to ping 0x003c84fffe6da50b TRADFRIbulbE27WSglobeopal1055lm
2022-11-07 06:45:00.460 - warn: zigbee.0 (40636) DeviceAvailability:Failed to ping 0x94deb8fffe6d6927 TRADFRIbulbE27WSglobeopal1055lm
2022-11-07 06:47:34.002 - warn: zigbee.0 (40636) Device '0x94deb8fffe6d6927' announced itself
2022-11-07 06:47:34.030 - error: zigbee.0 (40636) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-11-07 06:47:34.031 - error: zigbee.0 (40636) unhandled promise rejection: Cannot read properties of undefined (reading 'color_options')
2022-11-07 06:47:34.035 - error: zigbee.0 (40636) TypeError: Cannot read properties of undefined (reading 'color_options')
at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/ikea.js:39:19)
at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:44:26)
at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:26:18)
at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:236:54)
at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:560:18)
2022-11-07 06:47:34.036 - error: zigbee.0 (40636) Cannot read properties of undefined (reading 'color_options')
2022-11-07 06:47:34.052 - info: zigbee.0 (40636) cleaned everything up...

**Comment by arteck** [comment]
also with GIT version ?

**Comment by WOli19** [comment]
I just use the one provided by ioBroker! I have no idea how to use a different one!

**Comment by WOli19** [comment]
Okay I found the documentation! I’ll give it a try.

**Comment by WOli19** [comment]
With the GIT version the same error occurs! How should we proceed?


2022-11-08 06:39:57.072 - info: zigbee.0 (108078) Zigbee started
--
2022-11-08 06:40:19.733 - warn: zigbee.0 (108078) DeviceAvailability:Failed to ping 0x003c84fffe6da50b TRADFRIbulbE27WSglobeopal1055lm
2022-11-08 06:40:32.427 - warn: zigbee.0 (108078) DeviceAvailability:Failed to ping 0x003c84fffefacfc2 TRADFRI bulb E27 CWS 806lm
2022-11-08 06:41:13.621 - warn: zigbee.0 (108078) Device '0x003c84fffefacfc2' announced itself
2022-11-08 06:41:13.635 - error: zigbee.0 (108078) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-11-08 06:41:13.636 - error: zigbee.0 (108078) unhandled promise rejection: Cannot read properties of undefined (reading 'color_options')
2022-11-08 06:41:13.639 - error: zigbee.0 (108078) TypeError: Cannot read properties of undefined (reading 'color_options')
at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/ikea.js:39:19)
at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:44:26)
at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:26:18)
at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:236:54)
at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:560:18)
2022-11-08 06:41:13.639 - error: zigbee.0 (108078) Cannot read properties of undefined (reading 'color_options')
2022-11-08 06:41:13.653 - info: zigbee.0 (108078) cleaned everything up...
2022-11-08 06:41:13.709 - info: zigbee.0 (108078) Zigbee: disabling joining new devices.
2022-11-08 06:41:14.154 - info: zigbee.0 (108078) terminating
2022-11-08 06:41:14.156 - warn: zigbee.0 (108078) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-11-08 06:41:14.734 - error: host.raspberrypi Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-11-08 06:41:14.735 - error: host.raspberrypi Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'color_options')
2022-11-08 06:41:14.735 - error: host.raspberrypi Caught by controller[1]: at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/ikea.js:39:19)
2022-11-08 06:41:14.735 - error: host.raspberrypi Caught by controller[1]: at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:44:26)
2022-11-08 06:41:14.735 - error: host.raspberrypi Caught by controller[1]: at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:26:18)
2022-11-08 06:41:14.735 - error: host.raspberrypi Caught by controller[1]: at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:236:54)
2022-11-08 06:41:14.735 - error: host.raspberrypi Caught by controller[1]: at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:560:18)
2022-11-08 06:41:14.735 - error: host.raspberrypi instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-11-08 06:41:14.736 - info: host.raspberrypi Restart adapter system.adapter.zigbee.0 because enabled
2022-11-08 06:41:44.848 - info: host.raspberrypi instance system.adapter.zigbee.0 started with pid 108184
2022-11-08 06:41:48.506 - info: zigbee.0 (108184) starting. Version 1.7.5 in /opt/iobroker/node_modules/iobroker.zigbee, node: v18.9.1, js-controller: 4.0.23
2022-11-08 06:41:48.615 - info: zigbee.0 (108184) delete old Backup files. keep only last 10
2022-11-08 06:41:48.617 - info: zigbee.0 (108184) Starting Zigbee npm ...
2022-11-08 06:41:49.061 - info: zigbee.0 (108184) Installed Version: iobroker.zigbee
2022-11-08 06:41:49.485 - info: zigbee.0 (108184) Coordinator firmware version: {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}
2022-11-08 06:41:49.492 - info: zigbee.0 (108184) Unable to disable LED, unsupported function.
2022-11-08 06:41:49.510 - info: zigbee.0 (108184) --> transmitPower : normal
2022-11-08 06:41:49.520 - info: zigbee.0 (108184) Currently 10 devices are joined:
2022-11-08 06:41:49.551 - info: zigbee.0 (108184) 0x9035eafffe1ee6b4 (addr 5967): E2001/E2002 - IKEA STYRBAR remote control N2 (EndDevice)
2022-11-08 06:41:49.558 - info: zigbee.0 (108184) 0x5c0272fffebd4934 (addr 746): 57008000 - Insta Blinds actor with lift/tilt calibration & with with inputs for wall switches (Router)
2022-11-08 06:41:49.560 - info: zigbee.0 (108184) 0x5c0272fffebd4c7a (addr 6950): 57008000 - Insta Blinds actor with lift/tilt calibration & with with inputs for wall switches (Router)
2022-11-08 06:41:49.562 - info: zigbee.0 (108184) 0x5c0272fffebd4c79 (addr 29488): 57008000 - Insta Blinds actor with lift/tilt calibration & with with inputs for wall switches (Router)
2022-11-08 06:41:49.564 - info: zigbee.0 (108184) 0x5c0272fffebd4c93 (addr 53972): 57008000 - Insta Blinds actor with lift/tilt calibration & with with inputs for wall switches (Router)
2022-11-08 06:41:49.565 - info: zigbee.0 (108184) 0x540f57fffe1b6106 (addr 35137): E2001/E2002 - IKEA STYRBAR remote control N2 (EndDevice)
2022-11-08 06:41:49.568 - info: zigbee.0 (108184) 0x94deb8fffe6d6927 (addr 19555): LED2003G10 - IKEA TRADFRI LED bulb E26/27 1100/1055 lumen, dimmable, white spectrum, opal white (Router)
2022-11-08 06:41:49.569 - info: zigbee.0 (108184) 0x003c84fffe6da50b (addr 11276): LED2003G10 - IKEA TRADFRI LED bulb E26/27 1100/1055 lumen, dimmable, white spectrum, opal white (Router)
2022-11-08 06:41:49.571 - info: zigbee.0 (108184) 0x84b4dbfffe90fd3e (addr 28382): E2001/E2002 - IKEA STYRBAR remote control N2 (EndDevice)
2022-11-08 06:41:49.573 - info: zigbee.0 (108184) 0x003c84fffefacfc2 (addr 37206): LED1924G9 - IKEA TRADFRI bulb E26/E27 CWS 800/806 lumen, dimmable, color, opal white (Router)
2022-11-08 06:41:49.574 - info: zigbee.0 (108184) Zigbee started

**Comment by WOli19** [comment]
The issue seems to be fixed in version 1.7.6 from GIT! Thanks a lot!
