### ISSUE TITLE
Hinzufügen in eine Gruppe oder entfernen aus einer Gruppe nicht möglich

### ISSUE THREAD

**Issue by redo82** [ioBroker/ioBroker.zigbee#1604]
Es können keine Geräte mehr in Gruppen hinzugefügt oder entfernt werden. Auch bei einer neu angelegten Gruppe geht es nicht. Adapter-Version ist 1.8.7.  Im Log sehe ich kein Fehler.

**Comment by redo82** [comment]
Zigbee-Geräte werden nicht mehr angezeigt aber reagieren noch. Netzwerkkarte ist auch leer. Es ist kein Test möglich.

**Comment by asgothian** [comment]
Etwas mehr infos brauche ich schon - bei mir geht es aktuell

**Comment by redo82** [comment]
Wenn ich beim Adapter auf der Geräteliste bin ist diese Leer. Folgende Fehlermeldung im LOG.

`2022-12-07 21:45:11.464  - [31merror[39m: zigbee.0 (15810) getDevices error: ReferenceError: splitdev is not defined
    at getZbId (/opt/iobroker/node_modules/iobroker.zigbee/lib/utils.js:99:5)
    at /opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js:269:36`

**Comment by asgothian** [comment]
das ist seltsam. Kannst du bitte mal die Zeilen 92 - 101 aus der Datei /optiobroker.node_modules/iobroker.zigbee/lib/utils.js posten ?

**Comment by asgothian** [comment]
bitte nochmal installieren - sollte jetzt weg sein.

A.

**Comment by redo82** [comment]
Klappt noch nicht. Bei den vorhandenen Geräten ist die Gruppenauswahl weg. 

![keine gruppe](https://user-images.githubusercontent.com/114657458/206302852-2dccc328-fcbd-46ce-b479-cee2124dae38.png)

Und dann sind weiter unten noch viele unbekannte Geräte. Dort ist eine Auswahl möglich.

![unbekannt](https://user-images.githubusercontent.com/114657458/206302950-0b6ad4ca-cff8-4be2-acaa-a57051642f6c.png)

**Comment by redo82** [comment]
hier noch Fehlermeldungen aus dem Log.

`2022-12-07 22:46:56.121  - [31merror[39m: zigbee.0 (19498) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-12-07 22:46:56.121  - [31merror[39m: zigbee.0 (19498) unhandled promise rejection: Cannot read properties of undefined (reading 'mapped')
2022-12-07 22:46:56.122  - [31merror[39m: zigbee.0 (19498) TypeError: Cannot read properties of undefined (reading 'mapped')
    at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:541:36)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-12-07 22:46:56.123  - [31merror[39m: zigbee.0 (19498) Cannot read properties of undefined (reading 'mapped')
2022-12-07 22:46:56.146  - [32minfo[39m: zigbee.0 (19498) cleaned everything up...
2022-12-07 22:46:56.372  - [32minfo[39m: zigbee.0 (19498) Zigbee: disabling joining new devices.
2022-12-07 22:46:56.617  - [32minfo[39m: zigbee.0 (19498) terminating
2022-12-07 22:46:56.619  - [33mwarn[39m: zigbee.0 (19498) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-12-07 22:46:57.237  - [31merror[39m: host.iobroker instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-12-07 22:46:57.237  - [32minfo[39m: host.iobroker Restart adapter system.adapter.zigbee.0 because enabled
2022-12-07 22:46:57.238  - [33mwarn[39m: host.iobroker Do not restart adapter system.adapter.zigbee.0 because restart loop detected`

**Comment by redo82** [comment]
Hi, ja es klappt jetzt mit der Version aus dem Test-Repository.  Ich habe Geräte hinzugefügt, wieder entfernt und eine neue Gruppe angelegt. Alles super.

**Comment by asgothian** [comment]
Bedingt - die Version war noch nicht so sauber wie ich sie haben will.

kannst Du bitte noch einmal neu installieren und testen. Wichtig ist das du nach dem installieren die Zigbee Seite neu aufbaust, dann sollten die Gruppenanpassungen auch direkt an der Kachel sichtbar sein. 

Wenn das passt gibt es einen PR ins offizielle Repository

**Comment by redo82** [comment]
Ist ja witzig. Das war Gefühlt schon länger so und ich habe das als normal empfunden. Ich habe die Seite immer neu Aufgebaut um die Geräte in den Gruppen zu sehen.  Aber jetzt sind so ohne Neuaufbau drin, Sprich ich nehme sie in die Gruppe auf und sehe die Geräte gleich in der Gruppe. 

So am Rande:  Wenn ich eine Gruppe neu anlege ist sie nicht gleich sichtbar. Da muss ich die Seite für neu aufbauen.

**Comment by asgothian** [comment]
fixed in 1.8.10
