### ISSUE TITLE
Unable to add devices to group

### ISSUE THREAD

**Issue by ThorstenDtk** [ioBroker/ioBroker.zigbee#1619]
I'm trying to add devices (Hue white ambiance E14) to groups by opening the lamps' properties, selecting the group and clicking on OK:
![grafik](https://user-images.githubusercontent.com/35042154/207952153-cb4cc002-0e82-4488-805e-b183843de9c5.png)
The problem is that the settings do not get saved:

![grafik](https://user-images.githubusercontent.com/35042154/207952408-4ecbe3e3-893b-4fec-adc0-898336982b4d.png)

I'm using v1.8.9 of the adapter. Am I doing someting wrong? I tried with different lights and different groups, it never works. I also enabled logging. But don't see any errors or warnings. Any ideas?

**Comment by asgothian** [comment]
The fix for this did not make it to 1.8.9, it requires the current GitHub version (1.8.10)

**Comment by ThorstenDtk** [comment]
Thank you! I searched for this problem but didn't find anything. Otherwise I wouldn't have asked. Do you have a link to the bug? I'm just curious.

**Comment by ThorstenDtk** [comment]
Unfortunately I can't do the upgrade. In the admin I activated the beta repo:
![image](https://user-images.githubusercontent.com/35042154/208078105-f6978b65-f7ad-412b-b99e-c7e28caa2575.png)
After that I tried to upgrade the adapter
![image](https://user-images.githubusercontent.com/35042154/208078556-09a1adcd-44f3-4f83-8ad5-063bfed1d3af.png)
but it failed with 
```
$ iobroker upgrade zigbee@1.8.10 --debug

Update zigbee from @1.8.9 to @1.8.10

host.raspberrypi Adapter "system.adapter.zigbee.0" is stopped.

NPM version: 9.2.0

Installing iobroker.zigbee@1.8.10... (System call)

npm ERR! code ETARGET

npm ERR! notarget No matching version found for iobroker.zigbee@1.8.10.

npm ERR! notarget In most cases you or one of your dependencies are requesting

npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:npm ERR! /home/iobroker/.npm/_logs/2022-12-16T10_28_34_789Z-debug-0.log

Update "system.adapter.zigbee.0"

upload [322] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/adapter-settings.js adapter-settings.js application/javascript

upload [300] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/Bitron_AV201021A.png img/Bitron_AV201021A.png image/png

upload [250] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/bitron_motion.png img/bitron_motion.png image/png

upload [200] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/hive.png img/hive.png image/png

upload [150] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/lh_32Zb.png img/lh_32Zb.png image/png

upload [100] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/philips_amaze.png img/philips_amaze.png image/png

upload [90] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/philips_hue_ambiance.png img/philips_hue_ambiance.png image/png

upload [80] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/philips_hue_e27_ambiance.png img/philips_hue_e27_ambiance.png image/png

upload [70] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/philips_hue_ltc021.png img/philips_hue_ltc021.png image/png

upload [60] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/plug.png img/plug.png image/png

upload [50] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/sensor_philipshue.png img/sensor_philipshue.png image/png

upload [40] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/smartthings_motion.png img/smartthings_motion.png image/png

upload [30] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/ts0203.png img/ts0203.png image/png

upload [20] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/tuya_tyzs1l.png img/tuya_tyzs1l.png image/png

upload [19] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/unavailable.png img/unavailable.png image/png

upload [18] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/unknown.png img/unknown.png image/png

upload [17] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/wemo.png img/wemo.png image/png

upload [16] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/xiaomi_plug_eu.png img/xiaomi_plug_eu.png image/png

upload [15] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/xiaomi_wireless_switch.png img/xiaomi_wireless_switch.png image/png

upload [14] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/zbt_e27.png img/zbt_e27.png image/png

upload [13] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/zbt_e27_rgbw.png img/zbt_e27_rgbw.png image/png

upload [12] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/zbt_led_panel.png img/zbt_led_panel.png image/png

upload [11] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/zbt_smart_switch.png img/zbt_smart_switch.png image/png

upload [10] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/zemismart_sw2.png img/zemismart_sw2.png image/png

upload [9] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/index.html index.html text/html

upload [8] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/index_m.html index_m.html text/html

upload [7] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/moment.min.js moment.min.js application/javascript

upload [6] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/shuffle.min.js shuffle.min.js application/javascript

upload [5] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/tab_m.html tab_m.html text/html

upload [4] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/vis-network.min.css vis-network.min.css text/css

upload [3] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/vis-network.min.js vis-network.min.js application/javascript

upload [2] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/words.js words.js application/javascript

upload [1] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/zigbee.png zigbee.png image/png

upload [0] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/zigbee.svg zigbee.svg image/svg+xml

host.raspberrypi Adapter "system.adapter.zigbee.0" is started

Process exited with code 0
```
I removed the adapter, reinstalled it and tried the upgrade again. Same result.

Then I removed it again. Installation from the shell fails too:

![image](https://user-images.githubusercontent.com/35042154/208079308-79ac3c1b-892c-4791-a8c6-7ad6892c45ff.png)

2022-12-16T10_31_32_634Z-debug-0.log:


```
0 verbose cli /usr/bin/node /usr/local/bin/npm
1 info using npm@9.2.0
2 info using node@v14.21.1
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 4ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 4ms
6 timing config:load:builtin Completed in 5ms
7 timing config:load:cli Completed in 10ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/opt/iobroker/.npmrc Completed in 0ms
10 timing config:load:project Completed in 4ms
11 timing config:load:file:/home/iobroker/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 3ms
16 timing config:load Completed in 28ms
17 timing npm:load:configload Completed in 28ms
18 timing npm:load:mkdirpcache Completed in 1ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm install iobroker.zigbee@1.8.10
21 verbose argv "install" "--save-exact" "iobroker.zigbee@1.8.10"
22 timing npm:load:setTitle Completed in 4ms
23 timing config:load:flatten Completed in 8ms
24 timing npm:load:display Completed in 12ms
25 verbose logfile logs-max:10 dir:/home/iobroker/.npm/_logs/2022-12-16T10_31_32_634Z-
26 verbose logfile /home/iobroker/.npm/_logs/2022-12-16T10_31_32_634Z-debug-0.log
27 timing npm:load:logFile Completed in 13ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 61ms
31 silly logfile start cleaning logs, removing 2 files
32 timing config:load:flatten Completed in 2ms
33 timing arborist:ctor Completed in 3ms
34 silly logfile done cleaning log files
35 timing idealTree:init Completed in 4124ms
36 timing idealTree:userRequests Completed in 36ms
37 silly idealTree buildDeps
38 silly fetch manifest iobroker.zigbee@1.8.10
39 timing arborist:ctor Completed in 0ms
40 http fetch GET 200 https://registry.npmjs.org/iobroker.zigbee 3691ms (cache hit)
41 silly placeDep ROOT iobroker.zigbee@ OK for: iobroker.inst@2.0.3 want: 1.8.10
42 timing idealTree:#root Completed in 3728ms
43 timing idealTree:node_modules/iobroker.zigbee Completed in 0ms
44 timing idealTree:buildDeps Completed in 3732ms
45 timing idealTree:fixDepFlags Completed in 84ms
46 timing idealTree Completed in 7981ms
47 timing command:install Completed in 8008ms
48 verbose type version
49 verbose stack iobroker.zigbee: No matching version found for iobroker.zigbee@1.8.10.
49 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
49 verbose stack     at RegistryFetcher.manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:117:22)
49 verbose stack     at async Arborist.[nodeFromEdge] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build>
49 verbose stack     at async Arborist.[buildDepStep] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build>
49 verbose stack     at async Arborist.buildIdealTree (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build>
49 verbose stack     at async Promise.all (index 1)
49 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:156:5)
49 verbose stack     at async Install.exec (/usr/local/lib/node_modules/npm/lib/commands/install.js:146:5)
49 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:133:5)
50 verbose cwd /opt/iobroker
51 verbose Linux 5.15.83-v7l+
52 verbose node v14.21.1
53 verbose npm  v9.2.0
54 error code ETARGET
55 error notarget No matching version found for iobroker.zigbee@1.8.10.
56 error notarget In most cases you or one of your dependencies are requesting
56 error notarget a package version that doesn't exist.
57 verbose exit 1
58 timing npm Completed in 8144ms
59 verbose unfinished npm timer reify 1671186692753
60 verbose unfinished npm timer reify:loadTrees 1671186692768
61 verbose code 1
62 error A complete log of this run can be found in:
62 error     /home/iobroker/.npm/_logs/2022-12-16T10_31_32_634Z-debug-0.log
```

**Comment by asgothian** [comment]
Upgrade to 1.8.10 requires installation from Github via the expert mode.

1.8.10 is not yet latest.

A.
