### ISSUE TITLE
UseeLink SM-0306E-2W DeviceConfigure:Failed

### ISSUE THREAD

**Issue by lindi200000** [ioBroker/ioBroker.zigbee#1642]
Hallo,
ich habe eine UseeLink SM-0306E-2W Steckdosenleiste (https://www.zigbee2mqtt.io/devices/SM-0306E-2W.html). Diese konnte ich ohne weiteres anlernen und ich kann auch die einzelnen Ports schalten. Ich werde aber vom Zigbee Adapter mit folgenden Befehl zugespamt:
`DeviceConfigure:Failed to DeviceConfigure.configure 0x70b3d52b60016803 TS011F (TypeError: Cannot read property 'debug' of undefined at Object.configureMagicPacket (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/tuya.js:1183:20) at async Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/useelink.js:36:13) at async DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13) at async DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:112:17))`

Zusätzlich kann ich nicht den Namen des Geräts ändern.
Installiert ist der Zigbee Adapter v1.8.9 

hat wer eine Lösung für das Problem?

**Comment by lindi200000** [comment]
Gerade festgestellt, das es das Ticket nochmal gibt, also closed. https://github.com/ioBroker/ioBroker.zigbee/issues/1629
