### ISSUE TITLE
Unable to integrate Sonoff SNZB-04

### ISSUE THREAD

**Issue by dmnkmnr** [ioBroker/ioBroker.zigbee#1652]
**Describe the bug**  
I am unable to integrate my Sonoff SNZB-04 Door-/Window sensors.
I tried new and used ones (see log file; one new, one was used before).
I get two error messages:
- interview failed
- device not described in statesMapping

**To Reproduce**  
1. start joining new devices
2. press the reset button on the sensor to start the interview
3. wait, get error messages

**Expected behavior**  
I want the adapter to complete the interview and to successfully connect to the sensors.

**Screenshots & Logfiles**  

```
2023-01-11 15:16:11.477 - info: zigbee.0 (125802) Zigbee: allowing new devices to join.
2023-01-11 15:17:38.380 - info: zigbee.0 (125802) Starting interview of '0x00124b0023b44262'
2023-01-11 15:17:41.030 - error: zigbee.0 (125802) Device 0x00124b0023b44262 "undefined" not described in statesMapping.
2023-01-11 15:17:44.882 - error: zigbee.0 (125802) Failed to interview '0x00124b00234e79fc', device has not successfully been paired. undefined
2023-01-11 15:17:55.849 - error: zigbee.0 (125802) Failed to interview '0x00124b0023b44262', device has not successfully been paired. undefined
2023-01-11 15:18:12.796 - info: zigbee.0 (125802) Zigbee: stop joining

```

**Versions:**  
 - Adapter version: 1.8.10
 - JS-Controller version: 4.0.24
 - Node version: 16.19.0
 - Operating system: lxc proxmox
 - Bridge: Sonoff Zigbee Gateway, ZBDongle-E (EZSP)

**Comment by asgothian** [comment]
Try to keep the device away until the interview is completed.

Else downgrade to 1.8.9 and try again - there seems to be an issue with the newer zigbee-herdsman and the EZSP support.

A.

**Comment by dmnkmnr** [comment]
> Try to keep the device away until the interview is completed.

Away from what? The ZBDongle? I tried that, same error messages display.


> Else downgrade to 1.8.9 and try again - there seems to be an issue with the newer zigbee-herdsman and the EZSP support.

I had the same issues with 1.8.9, I upgraded because I hoped that will do it. But obviously the issue is still there...

**Comment by dmnkmnr** [comment]
Edit:

a new error message came up while keeping the sensor away from the ZBDongle: Failed to DeviceConfigure.configure, than timeout.

```
2023-01-11 21:16:21.081 - info: zigbee.0 (583) Zigbee: allowing new devices to join.
--
2023-01-11 21:16:44.451 - info: zigbee.0 (583) Starting interview of '0x00124b00234e79fc'
2023-01-11 21:18:22.381 - info: zigbee.0 (583) Zigbee: stop joining
2023-01-11 21:18:47.939 - info: admin.0 (401) <== Disconnect system.user.admin from ::ffff:192.168.178.60
2023-01-11 21:18:51.904 - info: admin.0 (401) ==> Connected system.user.admin from ::ffff:192.168.178.60
2023-01-11 21:18:52.034 - info: zigbee.0 (583) List of port: [{"path":"/dev/ttyACM0"},{"path":"/dev/ttyS1"},{"path":"/dev/ttyS10"},{"path":"/dev/ttyS11"},{"path":"/dev/ttyS12"},{"path":"/dev/ttyS13"},{"path":"/dev/ttyS14"},{"path":"/dev/ttyS15"},{"path":"/dev/ttyS16"},{"path":"/dev/ttyS17"},{"path":"/dev/ttyS18"},{"path":"/dev/ttyS19"},{"path":"/dev/ttyS2"},{"path":"/dev/ttyS20"},{"path":"/dev/ttyS21"},{"path":"/dev/ttyS22"},{"path":"/dev/ttyS23"},{"path":"/dev/ttyS24"},{"path":"/dev/ttyS25"},{"path":"/dev/ttyS26"},{"path":"/dev/ttyS27"},{"path":"/dev/ttyS28"},{"path":"/dev/ttyS29"},{"path":"/dev/ttyS3"},{"path":"/dev/ttyS30"},{"path":"/dev/ttyS31"},{"path":"/dev/ttyS4"},{"path":"/dev/ttyS5"},{"path":"/dev/ttyS6"},{"path":"/dev/ttyS7"},{"path":"/dev/ttyS8"},{"path":"/dev/ttyS9"},{"path":"/dev/ttyS0"}]
2023-01-11 21:19:22.296 - info: admin.0 (401) <== Disconnect system.user.admin from ::ffff:192.168.178.60
2023-01-11 21:19:27.479 - info: admin.0 (401) ==> Connected system.user.admin from ::ffff:192.168.178.60
2023-01-11 21:19:27.617 - info: zigbee.0 (583) List of port: [{"path":"/dev/ttyACM0"},{"path":"/dev/ttyS1"},{"path":"/dev/ttyS10"},{"path":"/dev/ttyS11"},{"path":"/dev/ttyS12"},{"path":"/dev/ttyS13"},{"path":"/dev/ttyS14"},{"path":"/dev/ttyS15"},{"path":"/dev/ttyS16"},{"path":"/dev/ttyS17"},{"path":"/dev/ttyS18"},{"path":"/dev/ttyS19"},{"path":"/dev/ttyS2"},{"path":"/dev/ttyS20"},{"path":"/dev/ttyS21"},{"path":"/dev/ttyS22"},{"path":"/dev/ttyS23"},{"path":"/dev/ttyS24"},{"path":"/dev/ttyS25"},{"path":"/dev/ttyS26"},{"path":"/dev/ttyS27"},{"path":"/dev/ttyS28"},{"path":"/dev/ttyS29"},{"path":"/dev/ttyS3"},{"path":"/dev/ttyS30"},{"path":"/dev/ttyS31"},{"path":"/dev/ttyS4"},{"path":"/dev/ttyS5"},{"path":"/dev/ttyS6"},{"path":"/dev/ttyS7"},{"path":"/dev/ttyS8"},{"path":"/dev/ttyS9"},{"path":"/dev/ttyS0"}]
2023-01-11 21:19:32.872 - error: zigbee.0 (583) Failed to interview '0x00124b00234e79fc', device has not successfully been paired. undefined
2023-01-11 21:19:47.748 - info: zigbee.0 (583) Configuring 0x00124b00234e79fc DS01
2023-01-11 21:19:57.750 - error: zigbee.0 (583) DeviceConfigure:Failed to DeviceConfigure.configure 0x00124b00234e79fc DS01 (Error: Bind 0x00124b00234e79fc/1 genPowerCfg from '0xe0798dfffe718aad/1' failed ({"address":43396,"clusterId":32801,"sequence":168} after 10000ms)
at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
at listOnTimeout (node:internal/timers:559:17)
at processTimers (node:internal/timers:502:7))
```

**Comment by dmnkmnr** [comment]
Edit 2: 

a few tries later this error message came up:

```
2023-01-11 21:28:10.062 - warn: zigbee.0 (583) Object zigbee.0.0x00124b00234e79fc is invalid: obj.type has to exist
2023-01-11 21:28:10.062 - warn: zigbee.0 (583) This object will not be created in future versions. Please report this to the developer.
2023-01-11 21:28:33.230 - info: zigbee.0 (583) Configuring 0x00124b00234e79fc DS01
2023-01-11 21:28:43.232 - error: zigbee.0 (583) DeviceConfigure:Failed to DeviceConfigure.configure 0x00124b00234e79fc DS01 (Error: Bind 0x00124b00234e79fc/1 genPowerCfg from '0xe0798dfffe718aad/1' failed ({"address":43396,"clusterId":32801,"sequence":68} after 10000ms)
```

**obj.type has to exist, please report this to the developer.** This sounds like I can't do anything about it for now, right?

**Comment by achimmm** [comment]
Hi,
Having nearly the same issue with snzb-02 devices and an ikea motion sensor.
Most of the time, the interview does not work. Sometimes, the interview cannot be finished and the device is undefined.
downgrading to 1.8.9 did not help.

**Comment by nhet** [comment]
Hi guys,

same problem here.
SNZB-04 Window - Switch can not be added.

**Versions:**
* Zigbee Coordinator
** CC2531
** type:zStack12
** version:2-0.2.6.3.
** revision:20190223
** port:/dev/ttyACM0
** channel:14
* Zigbee-Adapter 1.8.10
* JS-Controller version: 4.0.24
* Node version: v16.19.1

**Debug output:**
`
zigbee.0 | 2023-04-15 23:12:37.736 | error | Failed to interview '0x00124b002a4ea564', device has not successfully been paired. undefined
-- | -- | -- | --
zigbee.0 | 2023-04-15 23:12:37.730 | debug | handleDeviceInterview. {"status":"failed","device":{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":3,"_type":"Unknown","_ieeeAddr":"0x00124b002a4ea564","_networkAddress":24701,"_endpoints":[],"_interviewCompleted":false,"_interviewing":false,"_skipDefaultResponse":false,"_skipTimeResponse":false,"meta":{},"_lastSeen":1681593019270,"_defaultSendRequestWhen":"immediate"}}
zigbee.0 | 2023-04-15 23:12:37.730 | debug | zigbee-herdsman:controller:error Interview failed for '0x00124b002a4ea564 with error 'Error: Interview failed because can not get node descriptor ('0x00124b002a4ea564')'
zigbee.0 | 2023-04-15 23:12:37.704 | debug | zigbee-herdsman:controller:device:log Interview - failed for device '0x00124b002a4ea564' with error 'Error: Interview failed because can not get node descriptor ('0x00124b002a4ea564') at Device.interviewInternal (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/device.ts:558:19) at Device.interview (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/device.ts:445:13) at Controller.onDeviceJoined (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/controller.ts:567:17)'

`

**Comment by achimmm** [comment]
To give you a hint- i solved my problems by changing the channel (in my case, i moved the wifi). After that, including worked as designed.

there are same tools which visualize the traffic on the different channels. Take a look at https://www.metageek.com/training/resources/zigbee-wifi-coexistence/
