### ISSUE TITLE
Heimann HS2SK Plug doesn't pair anymore

### ISSUE THREAD

**Issue by fu-zhou** [ioBroker/ioBroker.zigbee#1662]
The plug stopped working with Zigbee somewhen last week (didn't send any values any more) so I tried to re-pair it with the following log-entries:
`Error: DeviceConfigure:Failed to DeviceConfigure.configure 0x000d6f00161fa665 SmartPlug (TypeError: Cannot read properties of undefined (reading 'defaultSendRequestWhen')
    at Endpoint.getOptionsWithDefaults (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:852:39)
    at Endpoint.configureReporting (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:650:24)
    at Object.currentSummDelivered (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/reporting.js:127:24)
    at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/heiman.js:53:29)
    at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13)
    at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:112:17)). undefined
Pairing time left: 43
Interview successful: {"friendly_name":"0x000d6f00161fa665","model":"HS2SK","vendor":"HEIMAN","description":"Smart metering plug","supported":true}
Pairing time left: 44
New device joined '0x000d6f00161fa665' model HS2SK
Device '0x000d6f00161fa665' announced itself
Interview started: 0x000d6f00161fa665`

Zigbee Adapter Version: 1.8.10
Zigbee Stick: Sonoff CC2652P with Firmware CC1352P2_CC2652P_launchpad_coordinator_20220219.zip

Any hints? Shall I also report the issue with koenkk?

**Comment by fu-zhou** [comment]
After the Adapter restarted several times it works now
