### ISSUE TITLE
Time on HEIMAN HS3AQ Smart air quality monitor

### ISSUE THREAD

**Issue by jcberens** [ioBroker/ioBroker.zigbee#1682]
Hello,

I own a Heiman HS3AQ smart air quality monitor. The internal clock of the device is very imprecise (several minutes in less than a week). So I have to readjust the time manually in order to have the display turn off correctly over night.
There is no state under the options to adjust the time, but I can adjust it successfully over the developers tab in the Zigbee instance:

![image](https://user-images.githubusercontent.com/118105945/218312607-957ea474-29a1-4ed5-b6a4-292f2e2c8b22.png)

I tried to create a script to update the time every day at midnight, but I don't succeed to send this as a payload. Here is what I have tried:

![image](https://user-images.githubusercontent.com/118105945/218312727-db5981a2-cc24-442c-9da6-e9895d889488.png)

But I receive the following error message in the logs:

_No converter available for '' with key 'genTime'_

Any help would be greatly appreciated. May be an update including a state for the time value in seconds would be nice too.

Regards,

Jean-Claude

**Comment by jcberens** [comment]
Hello,
Thanks for your answer. I have just tried to send the JSON via blockly, but this didn't work. Here is the JSON that should set time to 00:00

{
    "devId": "zigbee.0.84fd27fffe08105f",
    "ep": "",
    "cid": "genTime",
    "cmd": "write",
    "cmdType": "foundation",
    "zclData": {
        "time": 0
    },
    "cfg": null
}

This works fine when executed under the developer tab.
But I think, for me, it would be the easiest way to set the time, by scheduling a blockly script every day on 00:00 that resets the time.

Here is a screenshot with the info tab showing the cluster genTime twice under input and output:

![image](https://user-images.githubusercontent.com/118105945/218515531-f470e81c-7495-4418-b5dc-9e04ada7fb5c.png)

JC

**Comment by asgothian** [comment]
What result do you get ?

If I see it correctly, you misspelled the command: sendToZigbee, not SendToZigbee.


A.

**Comment by jcberens** [comment]
I didn't have any results in the logs when I misspelled the command, but when I changed it to sendToZigbee, the whole Zigbee Instance seemed to have crashed. It has restarted. Here are the logs:



2023-02-13 18:55:18.898 - info: admin.0 (13153) ==> Connected system.user.admin from ::ffff:192.168.0.42
--
2023-02-13 18:55:22.041 - info: javascript.0 (2277) Start javascript script.js.common.Script_1
2023-02-13 18:55:22.049 - info: javascript.0 (2277) script.js.common.Script_1: registered 0 subscriptions, 0 schedules, 0 messages, 0 logs and 0 file subscriptions
2023-02-13 18:55:22.054 - error: zigbee.0 (20742) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-02-13 18:55:22.055 - error: zigbee.0 (20742) unhandled promise rejection: Cannot read properties of undefined (reading 'replace')
2023-02-13 18:55:22.201 - error: zigbee.0 (20742) TypeError: Cannot read properties of undefined (reading 'replace')
at Developer.sendToZigbee (/opt/iobroker/node_modules/iobroker.zigbee/lib/developer.js:86:45)
at Developer.onMessage (/opt/iobroker/node_modules/iobroker.zigbee/lib/developer.js:45:26)
at Zigbee.emit (node:events:525:35)
at Zigbee.emit (node:domain:489:12)
at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:5824:34)
at Immediate. (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:322:37)
at processImmediate (node:internal/timers:466:21)
2023-02-13 18:55:22.201 - error: zigbee.0 (20742) Cannot read properties of undefined (reading 'replace')
2023-02-13 18:55:22.209 - info: zigbee.0 (20742) cleaned everything up...
2023-02-13 18:55:22.385 - info: zigbee.0 (20742) Zigbee: disabling joining new devices.
2023-02-13 18:55:22.710 - info: zigbee.0 (20742) terminating
2023-02-13 18:55:22.711 - warn: zigbee.0 (20742) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-02-13 18:55:23.280 - error: host.iobroker Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-02-13 18:55:23.280 - error: host.iobroker Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'replace')
2023-02-13 18:55:23.280 - error: host.iobroker Caught by controller[1]: at Developer.sendToZigbee (/opt/iobroker/node_modules/iobroker.zigbee/lib/developer.js:86:45)
2023-02-13 18:55:23.280 - error: host.iobroker Caught by controller[1]: at Developer.onMessage (/opt/iobroker/node_modules/iobroker.zigbee/lib/developer.js:45:26)
2023-02-13 18:55:23.281 - error: host.iobroker Caught by controller[1]: at Zigbee.emit (node:events:525:35)
2023-02-13 18:55:23.281 - error: host.iobroker Caught by controller[1]: at Zigbee.emit (node:domain:489:12)
2023-02-13 18:55:23.281 - error: host.iobroker Caught by controller[1]: at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:5824:34)
2023-02-13 18:55:23.281 - error: host.iobroker Caught by controller[1]: at Immediate. (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:322:37)
2023-02-13 18:55:23.281 - error: host.iobroker Caught by controller[1]: at processImmediate (node:internal/timers:466:21)
2023-02-13 18:55:23.281 - error: host.iobroker instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-02-13 18:55:23.281 - info: host.iobroker Restart adapter system.adapter.zigbee.0 because enabled

**Comment by asgothian** [comment]
No results are what is expected if you set the logging to "none".
The crash shows that it does indeed call the function, but some of the data is incorrect. The risk of using internal functions via script. I can check how it should look, but that will take a bit

**Comment by asgothian** [comment]
Please try to replace the "data" variable name with "message" and see if it then runs without crashing. Please also set the log level to debug.

**Comment by jcberens** [comment]
Another crash:



2023-02-13 19:16:44.925 - info: admin.0 (13153) ==> Connected system.user.admin from ::ffff:192.168.0.42
--
2023-02-13 19:16:50.785 - info: javascript.0 (2277) Start javascript script.js.common.Script_1
2023-02-13 19:16:50.817 - info: javascript.0 (2277) script.js.common.Script_1: registered 0 subscriptions, 0 schedules, 0 messages, 0 logs and 0 file subscriptions
2023-02-13 19:16:50.824 - error: zigbee.0 (20816) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-02-13 19:16:50.826 - error: zigbee.0 (20816) unhandled promise rejection: Cannot read properties of undefined (reading 'replace')
2023-02-13 19:16:51.016 - error: zigbee.0 (20816) TypeError: Cannot read properties of undefined (reading 'replace')
at Developer.sendToZigbee (/opt/iobroker/node_modules/iobroker.zigbee/lib/developer.js:86:45)
at Developer.onMessage (/opt/iobroker/node_modules/iobroker.zigbee/lib/developer.js:45:26)
at Zigbee.emit (node:events:525:35)
at Zigbee.emit (node:domain:489:12)
at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:5824:34)
at Immediate. (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:322:37)
at processImmediate (node:internal/timers:466:21)
2023-02-13 19:16:51.017 - error: zigbee.0 (20816) Cannot read properties of undefined (reading 'replace')
2023-02-13 19:16:51.027 - info: zigbee.0 (20816) cleaned everything up...
2023-02-13 19:16:51.231 - info: zigbee.0 (20816) Zigbee: disabling joining new devices.
2023-02-13 19:16:51.530 - info: zigbee.0 (20816) terminating
2023-02-13 19:16:51.532 - warn: zigbee.0 (20816) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-02-13 19:16:52.108 - error: host.iobroker Caught by controller[1]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-02-13 19:16:52.109 - error: host.iobroker Caught by controller[2]: TypeError: Cannot read properties of undefined (reading 'replace')
2023-02-13 19:16:52.109 - error: host.iobroker Caught by controller[2]: at Developer.sendToZigbee (/opt/iobroker/node_modules/iobroker.zigbee/lib/developer.js:86:45)
2023-02-13 19:16:52.109 - error: host.iobroker Caught by controller[2]: at Developer.onMessage (/opt/iobroker/node_modules/iobroker.zigbee/lib/developer.js:45:26)
2023-02-13 19:16:52.109 - error: host.iobroker Caught by controller[2]: at Zigbee.emit (node:events:525:35)
2023-02-13 19:16:52.109 - error: host.iobroker Caught by controller[2]: at Zigbee.emit (node:domain:489:12)
2023-02-13 19:16:52.110 - error: host.iobroker Caught by controller[2]: at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:5824:34)
2023-02-13 19:16:52.110 - error: host.iobroker Caught by controller[2]: at Immediate. (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:322:37)
2023-02-13 19:16:52.110 - error: host.iobroker Caught by controller[2]: at processImmediate (node:internal/timers:466:21)
2023-02-13 19:16:52.110 - error: host.iobroker instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-02-13 19:16:52.110 - info: host.iobroker Restart adapter system.adapter.zigbee.0 because enabled
2023-02-13 19:16:54.340 - info: javascript.0 (2277) Stop script script.js.common.Script_1
2023-02-13 19:16:55.911 - info: admin.0 (13153) <== Disconnect system.user.admin from ::ffff:192.168.0.42 javascript

**Comment by jcberens** [comment]
sendTo("zigbee.0", "sendToZigbee", {
   "message": {     "devId": "zigbee.0.84fd27fffe08105f",     "ep": "",     "cid": "genTime",     "cmd": "write",     "cmdType": "foundation",     "zclData": {         "time": 0     },     "cfg": null }
});
console.debug("zigbee.0: " + "");

**Comment by asgothian** [comment]
Ok.. seems  the standard blocks can't do it. Please generate a 'JS function' node with this content:
<img width="378" alt="Screenshot 2023-02-13 at 20 37 20" src="https://user-images.githubusercontent.com/45667167/218557092-a847055b-a6e5-409d-aecd-7948d2675719.png">

```
sendTo("zigbee.0", 
       {"command:"sendToZigbee", "message": { "devId": "zigbee.0.84fd27fffe08105f", "ep": "", "cid": "genTime", "cmd": "write", "cmdType": "foundation", "zclData": { "time": 0 }, "cfg": null }}
);
```

and see what happens

**Comment by jcberens** [comment]
I got a syntax error, so I added quotes behind command. But nothing happens I combined it with a button to execute it like so:

![image](https://user-images.githubusercontent.com/118105945/218565287-ddd07e60-516c-4a1b-ae5f-defce737fb09.png)

The whole script looks like this in Javascript now:

// Describe this function...
async function resettime() {
    sendTo("zigbee.0",
           {"command":"sendToZigbee", "message": { "devId": "zigbee.0.84fd27fffe08105f", "ep": "", "cid": "genTime", "cmd": "write", "cmdType": "foundation", "zclData": { "time": 0 }, "cfg": null }}
    );
}


on({id: [].concat(['zigbee.0.00158d0007e94f8a.click']), val: true}, async function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
  await resettime();
});

But unfortunately this doesn't change anything to the time on the device. There are no error messages in the logs.

**Comment by asgothian** [comment]
2 final attempts: change the `devId` entry to either `0x84fd27fffe08105f` or `84fd27fffe08105f`

Either of the 2 should work.

A.

**Comment by jcberens** [comment]
I tried both, but unfortunately this didn't work. At least it didn't crash the Zigbee adapter. I guess I'll have to continue to use the developers tab in the Zigbee instance to set the time.

JC

**Comment by asgothian** [comment]
for the time being - yes. I will see if there is a way to add the functionality to the device properly

**Comment by jcberens** [comment]
That'll be great as the time certainly doesn't use a quartz clock. I have to readjust it once a week. And thanks a lot for your help and your efforts.

**Comment by jcberens** [comment]
No, problem, that's fine for me.
