### ISSUE TITLE
Zigbee adapter crashes on uncaught exception in ioBroker

### ISSUE THREAD

**Issue by bruno4712** [ioBroker/ioBroker.zigbee#1704]
system configuration:
Zigbee adapter v1.8.10
ioBroker Node.js: v16.19.1 NPM: 8.19.3
Zigbee Coordinator type:zStack12 version:2-0.2.6.3. revision:20211115

github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_Home_1.2/bin/default/CC2531_DEFAULT_20211115.zip
CC2531 ZigBee USB Stick https://www.ebay.de/itm/125501356220

reboot loop caused after throwing uncaught exception than ioBroker stops the adapter.

ioBroker protocol (with Zigbee debug mode) see attachment:
[20230313 Zigbee reboot issue.pdf](https://github.com/ioBroker/ioBroker.zigbee/files/10970596/20230313.Zigbee.reboot.issue.pdf)

**Comment by asgothian** [comment]
Lesen bildet. Der Adapter stürzt nicht ab, statt dessen hast du deine Konfiguration geändert.

Was geändert wurde steht im Log.
Was zu tun ist steht im Log.

Mehr können wir nicht tun. Lösen musst du es selber.

**Comment by bruno4712** [comment]
Danke für deine Antwort. Am Zigbee Coordinator habe ich nichts geändert. Der Adapter stürzt auch so immer noch regelmäßig ab.  Nun zum Log:

2023-03-13 00:00:40.103 - error: zigbee.0 (119923) uncaught exception: Value '2' is not allowed, expected one of [object Object],[object Object],[object Object]
2023-03-13 00:00:40.105 - error: zigbee.0 (119923) Error: Value '2' is not allowed, expected one of [object Object],[object Object],[object Object]

Wie kann ich den hier erkennen, welcher DP mit einem ungültigen Wert gefüllt wurde?

2023-03-13 00:00:41.214 - error: host.iobrokertc Caught by controller[0]: Error: Value '2' is not allowed, expected one of [object Object],[object Object],[object Object]
2023-03-13 00:00:41.215 - error: host.iobrokertc Caught by controller[0]: at Object.from (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/tuya.js:1232:35)
2023-03-13 00:00:41.215 - error: host.iobrokertc Caught by controller[0]: at Object.convert (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/tuya.js:1734:57)
2023-03-13 00:00:41.215 - error: host.iobrokertc Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.zigbee/main.js:534:43
2023-03-13 00:00:41.216 - error: host.iobrokertc Caught by controller[0]: at Immediate. (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:183:25)
2023-03-13 00:00:41.216 - error: host.iobrokertc Caught by controller[0]: at processImmediate (node:internal/timers:468:21)
2023-03-13 00:00:41.216 - error: host.iobrokertc Caught by controller[1]: SentryError: HTTP Error (429)
2023-03-13 00:00:41.216 - error: host.iobrokertc Caught by controller[1]: at new SentryError (/opt/iobroker/node_modules/@sentry/src/error.ts:9:5)
2023-03-13 00:00:41.217 - error: host.iobrokertc Caught by controller[1]: at ClientRequest. (/opt/iobroker/node_modules/@sentry/src/transports/base/index.ts:254:22)
2023-03-13 00:00:41.217 - error: host.iobrokertc Caught by controller[1]: at Object.onceWrapper (node:events:628:26)
2023-03-13 00:00:41.217 - error: host.iobrokertc Caught by controller[1]: at ClientRequest.emit (node:events:513:28)
2023-03-13 00:00:41.217 - error: host.iobrokertc Caught by controller[1]: at ClientRequest.emit (node:domain:489:12)
2023-03-13 00:00:41.217 - error: host.iobrokertc Caught by controller[1]: at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
2023-03-13 00:00:41.218 - error: host.iobrokertc Caught by controller[1]: at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
2023-03-13 00:00:41.218 - error: host.iobrokertc Caught by controller[1]: at TLSSocket.socketOnData (node:_http_client:534:22)
2023-03-13 00:00:41.218 - error: host.iobrokertc Caught by controller[1]: at TLSSocket.emit (node:events:513:28)
2023-03-13 00:00:41.218 - error: host.iobrokertc Caught by controller[1]: at TLSSocket.emit (node:domain:489:12)
2023-03-13 00:00:41.219 - error: host.iobrokertc instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

Was ist hier ein SentryError: HTTP Error (429) und warum gibt es dann eine Exception? Was ist hier passiert und was kann man dagegen tun?
