### ISSUE TITLE
Zigbee adapter crashes on uncaught exception in ioBroker

### ISSUE THREAD

**Issue by bruno4712** [ioBroker/ioBroker.zigbee#1735]
Ich habe nochmal die weiteren Fehler aufgeführt. Die habe ich ins Issue #1704 geschrieben. Ich kriege nun den Adapter nicht mehr zum Laufen. Uncaugt Exeption ist meiner Meinung nach ein Code Fehler, oder?

Am Zigbee Coordinator habe ich nichts geändert. Der Adapter stürzt auch so immer noch regelmäßig ab. Nun zum Log:

2023-03-13 00:00:40.103 - error: zigbee.0 (119923) uncaught exception: Value '2' is not allowed, expected one of [object Object],[object Object],[object Object]
2023-03-13 00:00:40.105 - error: zigbee.0 (119923) Error: Value '2' is not allowed, expected one of [object Object],[object Object],[object Object]

Wie kann ich den hier erkennen, welcher DP mit einem ungültigen Wert gefüllt wurde?

2023-03-13 00:00:41.214 - error: host.iobrokertc Caught by controller[0]: Error: Value '2' is not allowed, expected one of [object Object],[object Object],[object Object]
2023-03-13 00:00:41.215 - error: host.iobrokertc Caught by controller[0]: at Object.from (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/tuya.js:1232:35)
2023-03-13 00:00:41.215 - error: host.iobrokertc Caught by controller[0]: at Object.convert (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/tuya.js:1734:57)
2023-03-13 00:00:41.215 - error: host.iobrokertc Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.zigbee/main.js:534:43
2023-03-13 00:00:41.216 - error: host.iobrokertc Caught by controller[0]: at Immediate. (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:183:25)
2023-03-13 00:00:41.216 - error: host.iobrokertc Caught by controller[0]: at processImmediate (node:internal/timers:468:21)
2023-03-13 00:00:41.216 - error: host.iobrokertc Caught by controller[1]: SentryError: HTTP Error (429)
2023-03-13 00:00:41.216 - error: host.iobrokertc Caught by controller[1]: at new SentryError (/opt/iobroker/node_modules/@sentry/src/error.ts:9:5)
2023-03-13 00:00:41.217 - error: host.iobrokertc Caught by controller[1]: at ClientRequest. (/opt/iobroker/node_modules/@sentry/src/transports/base/index.ts:254:22)
2023-03-13 00:00:41.217 - error: host.iobrokertc Caught by controller[1]: at Object.onceWrapper (node:events:628:26)
2023-03-13 00:00:41.217 - error: host.iobrokertc Caught by controller[1]: at ClientRequest.emit (node:events:513:28)
2023-03-13 00:00:41.217 - error: host.iobrokertc Caught by controller[1]: at ClientRequest.emit (node:domain:489:12)
2023-03-13 00:00:41.217 - error: host.iobrokertc Caught by controller[1]: at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
2023-03-13 00:00:41.218 - error: host.iobrokertc Caught by controller[1]: at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
2023-03-13 00:00:41.218 - error: host.iobrokertc Caught by controller[1]: at TLSSocket.socketOnData (node:_http_client:534:22)
2023-03-13 00:00:41.218 - error: host.iobrokertc Caught by controller[1]: at TLSSocket.emit (node:events:513:28)
2023-03-13 00:00:41.218 - error: host.iobrokertc Caught by controller[1]: at TLSSocket.emit (node:domain:489:12)
2023-03-13 00:00:41.219 - error: host.iobrokertc instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

Was ist hier ein SentryError: HTTP Error (429) und warum gibt es dann eine Exception? Was ist hier passiert und was kann man dagegen tun?

**Comment by bruno4712** [comment]
nach Neukonfiguration kommt es nun zu einem Loop.
[Document2.pdf](https://github.com/ioBroker/ioBroker.zigbee/files/11412847/Document2.pdf)

**Comment by arteck** [comment]
installer mal den Adapter von GIT und schau nochmal.. da scheint was mit der Tuya datei nicht zu stimmen..

**Comment by bruno4712** [comment]
Ich glaube, die meisten Probleme kann man schon beheben, indem man zigbee-herdsman und zigbee-herdsman-converters am saubersten mit npm im Terminal aktualisiert! Das wird ja nicht automatisch über den Zigbee Adapter aktualisiert. Das sollte mal im iobroker gelöst werden, das man da immer konsistente Versionen hat. Dazu folgende kurze Anleitung:

* Zigbee Adapter im ioBroker anhalten
* Update im Terminal
cd /opt/iobroker/node_modules/iobroker.zigbee/
npm install zigbee-herdsman
npm install zigbee-herdsman-converters

* quick hack im zigbee Adapter für die Analyse müssen dann 'Prüfungen' in der main.js gemacht werden, um das betroffene Zigbee Gerät zu finden

nano main.js

* die Ergebnisse in den ioBroker Protokollen prüfen und den Vorgang ggf. wiederholen (npm muss hier nicht mehr ausgeführt werden)

* Zigbee Adapter im ioBroker starten

Hier werde ich noch nach den 'fehlerhaften' Zigbee Gerät suchen und entsprechende Incidents bei zigbee-herdsman aufmachen. Wenn es keine Dumps (siehe im Protokoll) mehr gibt, kann man sich natürlich die Bearbeitung des main.js ersparen.

Quelle: https://forum.iobroker.net/topic/41046/gel%C3%B6st-zigbee-herdsmann-converters-wie-manuell-updaten/5

**Comment by bruno4712** [comment]
This error occurs again: "Cannot read properties of undefined (reading 'mapped')"

2023-06-21 16:07:29.050 - error: zigbee.0 (15132) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
--
2023-06-21 16:07:29.052 - error: zigbee.0 (15132) unhandled promise rejection: Cannot read properties of undefined (reading 'mapped')
2023-06-21 16:07:29.055 - error: zigbee.0 (15132) TypeError: Cannot read properties of undefined (reading 'mapped')
at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:571:36)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-06-21 16:07:29.056 - error: zigbee.0 (15132) Cannot read properties of undefined (reading 'mapped')
2023-06-21 16:07:29.070 - info: zigbee.0 (15132) cleaned everything up...
2023-06-21 16:07:29.160 - info: zigbee.0 (15132) Zigbee: disabling joining new devices.
2023-06-21 16:07:29.572 - info: zigbee.0 (15132) terminating
2023-06-21 16:07:29.574 - warn: zigbee.0 (15132) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-06-21 16:07:30.176 - error: host.iobrokertc Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-06-21 16:07:30.177 - error: host.iobrokertc Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'mapped')
2023-06-21 16:07:30.177 - error: host.iobrokertc Caught by controller[1]: at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:571:36)
2023-06-21 16:07:30.178 - error: host.iobrokertc Caught by controller[1]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-06-21 16:07:30.178 - error: host.iobrokertc instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

**Comment by ninja-warrior** [comment]
I get the same kind of error with newest version of zigbee adapter when setting the level of tuya TS130F blind actuators. 

I recognized a weird behaviour of the blind actuators months ago and also reported an [issue](https://github.com/ioBroker/ioBroker.zigbee/issues/1610).

**Comment by bruno4712** [comment]
how will the properties declared? Are the some missing for different devices? I am not so fit to read the JS code. I think they must be declared in herdsman adapter ...

**Comment by arteck** [comment]
check new GIT version

**Comment by bruno4712** [comment]
Upgrade to Zigbee v1.8.16 will help to fix this now. I hope so. No dumps occur now.
