### ISSUE TITLE
Fehlermeldungen bei SM-0306E-2W schaltbaren Steckdosen

### ISSUE THREAD

**Issue by Pla5ma** [ioBroker/ioBroker.zigbee#1757]
Die schaltbaren Steckdosen SM-0306E-2W werfen kontinuierlich Fehler im Log:

_DeviceConfigure:Failed to DeviceConfigure.configure 0xXXX TS011F (TypeError: Cannot read properties of undefined (reading 'debug') at Object.configureMagicPacket (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/tuya.js:1188:20) at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/useelink.js:36:13) at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13) at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:112:17))_

<img width="230" alt="image" src="https://github.com/ioBroker/ioBroker.zigbee/assets/57805183/9b3f1c90-2a87-46e5-84ce-5a46b3e3217e">

**Comment by arteck** [comment]
mit der neuen Version von GIT auch ?

**Comment by Pla5ma** [comment]
Warum wurde das Issue geschlossen? Es tritt auch mit der neuen Version auf.

**Comment by arteck** [comment]
weil es nicht adapter problem ist sonders des zigbee-herdsman-converters

**Comment by Pla5ma** [comment]
Das Gerät wurde nochmal angelernt, gleicher Fehler. Und das Log ist nicht nur ein Schnipsel, sondern die gesamte Fehlermeldung.

**Comment by arteck** [comment]
wieder nur so ein schnippsel... poste doch bitte ordentliches LOG
bevor der aussteigt.. da sind noch paar Meldungen mehr... und in code Tag und nicht als Screenshot bitte
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/6681528/dd38f3ba-94e2-4aa8-8fe9-811c07567446)

**Comment by Pla5ma** [comment]
Du erkennst schon, dass es immer die selbe Fehlermeldung ist??? Aber bitte:

`<html>
<body>


zigbee.0 | 2023-08-02 11:42:16.303 | error | DeviceConfigure:Failed to DeviceConfigure.configure 0x70b3d52b600145fc TS011F (TypeError: Cannot read properties of undefined (reading 'debug') at Object.configureMagicPacket (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/tuya.js:1188:20) at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/useelink.js:36:13) at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13) at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:112:17))
-- | -- | -- | --
zigbee.0 | 2023-08-02 11:37:04.753 | error | DeviceConfigure:Failed to DeviceConfigure.configure 0x70b3d52b600145fc TS011F (TypeError: Cannot read properties of undefined (reading 'debug') at Object.configureMagicPacket (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/tuya.js:1188:20) at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/useelink.js:36:13) at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13) at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:112:17))
zigbee.0 | 2023-08-02 11:31:08.822 | error | DeviceConfigure:Failed to DeviceConfigure.configure 0x70b3d52b600145fc TS011F (TypeError: Cannot read properties of undefined (reading 'debug') at Object.configureMagicPacket (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/tuya.js:1188:20) at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/useelink.js:36:13) at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13) at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:112:17))


</body>
</html>`

Bevor du wieder nachfragen musst: Wieviele von den immer gleichen Fehlermeldungen hättest du gerne als Codeschnipsel? Reicht die Anzahl oder willst du mehr?

**Comment by arteck** [comment]
ok ich gib auf.. wenn du meinst das es alles ist.. was im LOG steht dann ist das so....
ich hab noch so eine Dose hier.. ich schaue es mir an wenn ich Zeit habe..

**Comment by Pla5ma** [comment]
Das hat nichts mit _ich gebe es auf zu tun_ oder _das ich meine, dass es alles ist_, es ist alles.

Ich habe gefiltert auf Zigbee Adapter, Errorlevel ist auf Info, somit ist alles vom Zigbee Adapter im Log sichtbar und diese Fehlermeldung ist alles was es gibt.

Du brauchst nicht zu tun, als ob ich keine Ahnung habe, ich bin vom Fach und weiß was ich sage.

**Comment by arteck** [comment]
> Du brauchst nicht zu tun, als ob ich keine Ahnung habe, ich bin vom Fach und weiß was ich sage.

wenn du vom Fach bist dann freue ich mich auf ein PR für das Problem

**Comment by Pla5ma** [comment]
So hier ein Auszug mit mehreren dieser Fehler direkt aus meiner Log Datei, ungefiltert, Zigbee Instanz steht auf alles loggen:

```
2023-08-02 21:15:46.744 - info: mqtt.0 (470) Client [Zisterne1] connection closed: closed
2023-08-02 21:16:08.568 - info: mqtt.0 (470) Client [Zisterne1] connected with secret xxx
2023-08-02 21:16:08.568 - info: mqtt.0 (470) Client [Zisterne1] connection closed: closed
2023-08-02 21:17:03.395 - info: mqtt.0 (470) Client [Zisterne1] connected with secret xxx
2023-08-02 21:17:03.397 - info: mqtt.0 (470) Client [Zisterne1] connection closed: closed
2023-08-02 21:18:28.446 - error: zigbee.0 (485) DeviceConfigure:Failed to DeviceConfigure.configure 0x70b3d52b600145fc TS011F (TypeError: Cannot read properties of undefined (reading 'debug')
at Object.configureMagicPacket (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/tuya.js:1188:20)
at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/useelink.js:36:13)
at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13)
at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:112:17))
2023-08-02 21:19:08.167 - info: mqtt.0 (470) Client [Zisterne1] connected with secret xxx
2023-08-02 21:19:08.168 - info: mqtt.0 (470) Client [Zisterne1] connection closed: closed
2023-08-02 21:20:00.036 - info: host.SRV-IOBROKER instance system.adapter.netatmo-crawler.0 started with pid 9251
2023-08-02 21:20:00.552 - info: netatmo-crawler.0 (9251) starting. Version 0.8.1 in /opt/iobroker/node_modules/iobroker.netatmo-crawler, node: v16.19.0, js-controller: 4.0.23
2023-08-02 21:20:00.564 - info: netatmo-crawler.0 (9251) Getting data for stationid:xxx
2023-08-02 21:20:01.152 - info: netatmo-crawler.0 (9251) Terminated (ADAPTER_REQUESTED_TERMINATION): Everything done. Going to terminate till next schedule
2023-08-02 21:20:01.661 - info: host.SRV-IOBROKER instance system.adapter.netatmo-crawler.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2023-08-02 21:20:49.141 - info: mqtt.0 (470) Client [Wetterstation1] connected with secret xxx
2023-08-02 21:20:49.170 - info: mqtt.0 (470) Client [Wetterstation1] subscribes on "Garage/Wetterstation1/Device/#" with regex /^Garage\.Wetterstation1\.Device\..*/
2023-08-02 21:20:49.170 - info: mqtt.0 (470) Client [Wetterstation1] subscribes on "Garage/Wetterstation1/Device/#" with regex /^mqtt\.0\.Garage\.Wetterstation1\.Device\..*/
2023-08-02 21:20:49.370 - info: mqtt.0 (470) Client [Wetterstation1] publishOnSubscribe send all known states
2023-08-02 21:20:54.132 - info: mqtt.0 (470) Client [Wetterstation1] connection closed: disconnected
2023-08-02 21:24:13.581 - error: zigbee.0 (485) DeviceConfigure:Failed to DeviceConfigure.configure 0x70b3d52b600145fc TS011F (TypeError: Cannot read properties of undefined (reading 'debug')
at Object.configureMagicPacket (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/tuya.js:1188:20)
at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/useelink.js:36:13)
at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13)
at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:112:17))
2023-08-02 21:25:00.043 - info: host.SRV-IOBROKER instance system.adapter.netatmo-crawler.0 started with pid 9268
2023-08-02 21:25:00.514 - info: netatmo-crawler.0 (9268) starting. Version 0.8.1 in /opt/iobroker/node_modules/iobroker.netatmo-crawler, node: v16.19.0, js-controller: 4.0.23
2023-08-02 21:25:00.527 - info: netatmo-crawler.0 (9268) Getting data for stationid:xxx
2023-08-02 21:25:01.121 - info: netatmo-crawler.0 (9268) Terminated (ADAPTER_REQUESTED_TERMINATION): Everything done. Going to terminate till next schedule
2023-08-02 21:25:01.629 - info: host.SRV-IOBROKER instance system.adapter.netatmo-crawler.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2023-08-02 21:28:24.394 - info: mqtt.0 (470) Client [Zisterne1] connected with secret xxx
2023-08-02 21:28:24.404 - info: mqtt.0 (470) Client [Zisterne1] subscribes on "Zisterne/Zisterne1/Out/#" with regex /^Zisterne\.Zisterne1\.Out\..*/
2023-08-02 21:28:24.404 - info: mqtt.0 (470) Client [Zisterne1] subscribes on "Zisterne/Zisterne1/Out/#" with regex /^mqtt\.0\.Zisterne\.Zisterne1\.Out\..*/
2023-08-02 21:28:24.604 - info: mqtt.0 (470) Client [Zisterne1] publishOnSubscribe send all known states
2023-08-02 21:28:26.709 - info: mqtt.0 (470) Client [Pool2] connection closed: timeout
2023-08-02 21:28:26.975 - info: mqtt.0 (470) Client [Pool2] connected with secret xxx
2023-08-02 21:28:27.025 - info: mqtt.0 (470) Client [Pool2] subscribes on "Pool/Pool2/Out/#" with regex /^Pool\.Pool2\.Out\..*/
2023-08-02 21:28:27.025 - info: mqtt.0 (470) Client [Pool2] subscribes on "Pool/Pool2/Out/#" with regex /^mqtt\.0\.Pool\.Pool2\.Out\..*/
2023-08-02 21:28:27.226 - info: mqtt.0 (470) Client [Pool2] publishOnSubscribe send all known states
2023-08-02 21:29:54.904 - error: zigbee.0 (485) DeviceConfigure:Failed to DeviceConfigure.configure 0x70b3d52b600145fc TS011F (TypeError: Cannot read properties of undefined (reading 'debug')
at Object.configureMagicPacket (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/tuya.js:1188:20)
at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/useelink.js:36:13)
at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13)
at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:112:17))
2023-08-02 21:30:00.029 - info: host.SRV-IOBROKER instance system.adapter.netatmo-crawler.0 started with pid 9286
```

Ich habe nur die Station ID für Netamo, damit nicht jeder meine Lokation kennt, und meine MQTT Secrets gelöscht. Jetzt verrate mir doch einmal, als jemand vom Fach, wo da noch mehr Infos zum Abbruch stehen?

**Comment by arteck** [comment]
und wieder so ein LOG schnippsel

wo sind die infos vom Adapter Start ?? wo sind die infos zur hardware.. 

es sind essenzielle klamotten die ich WISSEN MUSS.. sonst lass ich den scheiss sein.. und gut ist
also..

Adapter Stop
adapter start dann posten.. wann kommt die Meldung ?? machst du was (reconfigure in der Kachel drücken) oder kommt der Abbruch so.. imlaufen Betrieb..
