### ISSUE TITLE
TuYa motion detector is detected incorrectly 

### ISSUE THREAD

**Issue by leovandavart** [ioBroker/ioBroker.zigbee#1765]
my TuYa 809WZT is recognized as TS0202 and does not work correctly.

this is supposed to be it https://www.zigbee2mqtt.io/devices/809WZT.html
 but it is recognized https://www.zigbee2mqtt.io/devices/TS0202.html 

`
Geräteinformation

    modelZigbee:TS0202
    type:EndDevice
    nwk:60757
    manuf id:4417
    manufacturer:_TZ3040_bb6xaihh
    power:Battery
    app version:72
    hard version:1
    zcl version:3
    stack version:0
    date code:
    interviewed:true
    configured:false

    endpoint:1
    profile:260
    input clusters:genPowerCfg (1)
    genIdentify (3)
    genGroups (4)
    ssIasZone (1280)
    genBasic (0)
    output clusters:genGroups (4)
    genOnOff (6)
    touchlink (4096)
    genOta (25)
    genTime (10)

`

what can I do so that it is properly detected

**Comment by arteck** [comment]
also with GIT version ?

**Comment by leovandavart** [comment]
I don't know what you mean

**Comment by leovandavart** [comment]
```
zigbee.0
	2023-07-04 20:47:36.525	error	Device 0xa4c13824c7cc7493 "ZTH02" not described in statesMapping.
zigbee.0
	2023-07-04 20:47:36.512	error	Device 0xa4c138f09c0716a3 "809WZT" not described in statesMapping.
zigbee.0
	2023-07-04 20:46:19.527	error	DeviceConfigure:Failed to DeviceConfigure.configure 0xa4c138f09c0716a3 TS0202 (Error: Bind 0xa4c138f09c0716a3/1 genPowerCfg from '0x00124b002a2ec568/1' failed (AREQ - ZDO - bindRsp after 10000ms) at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (node:internal/timers:569:17) at processTimers (node:internal/timers:512:7))
zigbee.0
	2023-07-04 20:46:03.820	error	DeviceConfigure:Failed to DeviceConfigure.configure 0xa4c13824c7cc7493 TS0601 (Error: Read 0xa4c13824c7cc7493/1 genBasic(["manufacturerName","zclVersion","appVersion","modelId","powerSource",65534], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 36646 - 1 - 115 - 0 - 1 after 10000ms) at Timeout._onTimeout (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (node:internal/timers:569:17) at processTimers (node:internal/timers:512:7))
```

**Comment by arteck** [comment]
> I don't know what you mean

install the GIT verion... and check again
