### ISSUE TITLE
Zigbee startet immer neu (auch nach neuinstalliertem adapter oder iobroker)

### ISSUE THREAD

**Issue by bjoernszw** [ioBroker/ioBroker.zigbee#1767]
Hallo,

ich bin von iobroker windows auf debian auf proxmox umgeschwenkt und hab mein iobroker aus dem backup adapter wiederhergestellt. soweit so gut. den Zigbee Coordinator nutzte ich via IP (CC2652P2-TCP). Funktionierte unter Windows auch ohne Probleme. Nun unter Debian, hab ich das Problem, dass der Adapter imemr wieder nuestartet nach dem er die Konfig geladen hat. Am CC2652P2-TCP sehe ich kurz eine Verbindung und im Zigbee Adapter unter Iobroker sehe ich kurz die Geräte, dann startet der Adapter wieder neu.

Im Log steht folgendes:
```
zigbee.0	2401	2023-07-01 11:48:56.933	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee.0	2401	2023-07-01 11:48:56.933	debug	Plugin sentry destroyed
zigbee.0	2401	2023-07-01 11:48:56.932	info	terminating
zigbee.0	2401	2023-07-01 11:48:56.432	info	Zigbee: disabling joining new devices.
zigbee.0	2401	2023-07-01 11:48:56.431	info	cleaned everything up...
zigbee.0	2401	2023-07-01 11:48:56.422	error	Cannot read properties of undefined (reading 'mapped')
zigbee.0	2401	2023-07-01 11:48:56.422	error	TypeError: Cannot read properties of undefined (reading 'mapped') at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:571:36)
zigbee.0	2401	2023-07-01 11:48:56.421	error	unhandled promise rejection: Cannot read properties of undefined (reading 'mapped')
zigbee.0	2401	2023-07-01 11:48:56.421	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0	2401	2023-07-01 11:48:56.421	debug	entity: undefined
zigbee.0	2401	2023-07-01 11:48:56.419	debug	Change state 'state' at device 0xcc86ecfffe89dfde type 'E1603/E1702/E1708'
zigbee.0	2401	2023-07-01 11:48:56.416	debug	User stateChange zigbee.0.cc86ecfffe89dfde.state {"val":true,"ack":false,"ts":1688204936415,"q":0,"from":"system.adapter.zigbee.0","user":"system.user.admin","lc":1688204936415}
zigbee.0	2401	2023-07-01 11:48:56.413	debug	SetState_typed called without type
zigbee.0	2401	2023-07-01 11:48:29.433	debug	getBinding result: []
zigbee.0	2401	2023-07-01 11:48:29.433	debug	getExclude result: []
``` 

Nun dachte ich, es liegt an der neuinstallation mit rückspielung des Backups. Also installierte ich mir eine neue VM mit debian und einem firschen iobroker. Danach nur den zigbee adapter drauf und versucht das gerät anzubinden. leider startet der Adapter sofort wieder neu?!.

Folgende Software Versionen hab ich im Einsatz:
type:zStack3x0
version:2-1.2.7.1.
revision:20220219
CC2652P2-TCP

Node.js version
18.16.1
NPM version
9.5.1
js-controller
4.0.24

Vielleicht hat einer eine Lösung.

Danke!

**Comment by daniel-lo** [comment]
Habe genau das Gleiche. Danchte ein Downgrad auf den stable js-controller hilft .. aber auch nicht .. nun sind wir zwei die ratlos sind.

Node.js: v16.19.1
NPM: 8.19.3(9.5.1)
js-controller: 4.0.24

**Comment by Ilovegym66** [comment]
Im Log steht: sentry destroyed... 
Schalte mal Sentry fuer den Zigbee Adapter ab ( bei Instanzen im Expertenmodus das gruene Symbol ganz rechts aus schalten)
und starte den Adapter nochmals.. vielleicht hilfts ja.

**Comment by bjoernszw** [comment]
Hallo,
danke für dein Vorschlag.
Hab ich gemacht, leider hat das nichts gebracht.

heir der Auszug aus dem Log:

```
zigbee.0	3977	2023-07-01 12:53:05.530	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee.0	3977	2023-07-01 12:53:05.530	info	terminating
zigbee.0	3977	2023-07-01 12:53:05.058	error	Cannot read properties of undefined (reading 'mapped')
zigbee.0	3977	2023-07-01 12:53:05.058	error	TypeError: Cannot read properties of undefined (reading 'mapped') at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:571:36)
zigbee.0	3977	2023-07-01 12:53:05.058	error	unhandled promise rejection: Cannot read properties of undefined (reading 'mapped')
zigbee.0	3977	2023-07-01 12:53:05.058	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0	3977	2023-07-01 12:53:05.058	debug	entity: undefined
zigbee.0	3977	2023-07-01 12:53:05.057	debug	Change state 'state' at device 0xcc86ecfffe8dbd7e type 'E1603/E1702/E1708'
zigbee.0	3977	2023-07-01 12:53:05.030	info	Zigbee: disabling joining new devices.
zigbee.0	3977	2023-07-01 12:53:05.029	info	cleaned everything up...
zigbee.0	3977	2023-07-01 12:53:05.029	error	Cannot read properties of undefined (reading 'mapped')
zigbee.0	3977	2023-07-01 12:53:05.028	error	TypeError: Cannot read properties of undefined (reading 'mapped') at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:571:36)
zigbee.0	3977	2023-07-01 12:53:05.028	error	unhandled promise rejection: Cannot read properties of undefined (reading 'mapped')
zigbee.0	3977	2023-07-01 12:53:05.028	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0	3977	2023-07-01 12:53:05.028	debug	entity: undefined
zigbee.0	3977	2023-07-01 12:53:05.027	debug	Change state 'state' at device 0xcc86ecfffe89dfde type 'E1603/E1702/E1708'
zigbee.0	3977	2023-07-01 12:53:05.025	error	Cannot read properties of undefined (reading 'mapped')
zigbee.0	3977	2023-07-01 12:53:05.025	error	TypeError: Cannot read properties of undefined (reading 'mapped') at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:571:36) at runNextTicks (node:internal/process/task_queues:60:5) at process.processImmediate (node:internal/timers:447:9)
zigbee.0	3977	2023-07-01 12:53:05.025	error	unhandled promise rejection: Cannot read properties of undefined (reading 'mapped')
zigbee.0	3977	2023-07-01 12:53:05.024	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0	3977	2023-07-01 12:53:05.024	debug	entity: undefined
zigbee.0	3977	2023-07-01 12:53:05.023	debug	Change state 'state' at device 0xcc86ecfffe875089 type 'E1603/E1702/E1708'
zigbee.0	3977	2023-07-01 12:53:05.020	error	Cannot read properties of undefined (reading 'mapped')
zigbee.0	3977	2023-07-01 12:53:05.019	error	TypeError: Cannot read properties of undefined (reading 'mapped') at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:571:36)
zigbee.0	3977	2023-07-01 12:53:05.019	error	unhandled promise rejection: Cannot read properties of undefined (reading 'mapped')
zigbee.0	3977	2023-07-01 12:53:05.018	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0	3977	2023-07-01 12:53:05.018	debug	entity: undefined
zigbee.0	3977	2023-07-01 12:53:05.015	debug	Change state 'state' at device 0xcc86ecfffe8db9e1 type 'E1603/E1702/E1708'
zigbee.0	3977	2023-07-01 12:53:05.011	debug	User stateChange zigbee.0.cc86ecfffe8dbd7e.state {"val":false,"ack":false,"ts":1688208785003,"q":0,"c":"script.js.Zentralsteuerung.Steckdosen_Terrasse","from":"system.adapter.javascript.0","user":"system.user.admin","lc":1687710148589}
zigbee.0	3977	2023-07-01 12:53:05.011	silly	States user redis pmessage zigbee.0.*/zigbee.0.cc86ecfffe8dbd7e.state:{"val":false,"ack":false,"ts":1688208785003,"q":0,"c":"script.js.Zentralsteuerung.Steckdosen_Terrasse","from":"system.adapter.javascript.0","user":"system.user.admin","lc":1687710148589}
zigbee.0	3977	2023-07-01 12:53:05.010	debug	User stateChange zigbee.0.cc86ecfffe89dfde.state {"val":false,"ack":false,"ts":1688208785003,"q":0,"c":"script.js.Zentralsteuerung.Steckdosen_Terrasse","from":"system.adapter.javascript.0","user":"system.user.admin","lc":1688204945004}
zigbee.0	3977	2023-07-01 12:53:05.009	silly	States user redis pmessage zigbee.0.*/zigbee.0.cc86ecfffe89dfde.state:{"val":false,"ack":false,"ts":1688208785003,"q":0,"c":"script.js.Zentralsteuerung.Steckdosen_Terrasse","from":"system.adapter.javascript.0","user":"system.user.admin","lc":1688204945004}
zigbee.0	3977	2023-07-01 12:53:05.009	debug	User stateChange zigbee.0.cc86ecfffe875089.state {"val":false,"ack":false,"ts":1688208785003,"q":0,"c":"script.js.Zentralsteuerung.Steckdosen_Terrasse","from":"system.adapter.javascript.0","user":"system.user.admin","lc":1688208725003}
zigbee.0	3977	2023-07-01 12:53:05.008	silly	States user redis pmessage zi
```

**Comment by Ilovegym66** [comment]
Stop mal das Script, das will ein device schalten, das wohl nicht richtig eingebunden ist...

**Comment by bjoernszw** [comment]
bringt nix, hab ich auch schon. hab ja letztendlich wie oben geschrieben eine komplett neue vm mit iobroker installiert und einem leeren iobroker und einem leeren zigbee. das macht die gleichen probleme. ich würde tippen es liegt an irgendeiner version vom js oder ähnliches... @daniel-lo hat ja gleiches problem.

gruß

**Comment by arteck** [comment]
lösche das Gerät 0xcc86ecfffe8dbd7e mal.. gehts dann

**Comment by daniel-lo** [comment]
Das bei benannte Gerät hab ich rausgelöscht und es scheint das Problem zu beheben. Neu Koppeln hat nicht geholfen - das Gerät macht auch dann noch Probleme. Sollte ich lieber davon ausgehen, dass das Gerät kaputt ist?

**Comment by bjoernszw** [comment]
wenn ich alles lösche und auch ne neue instanz komplett leer anlege bleibt das problem bestehen.

**Comment by arteck** [comment]
> Es wäre ein Osram Plug

die machen ehh nur Probleme.. schmeiss das Ding
