### ISSUE TITLE
DeviceConfigure:Failed (Please Help)

### ISSUE THREAD

**Issue by OnkelJo8576** [ioBroker/ioBroker.zigbee#1773]
Device:

model:[WP33-EU/WP34-EU](https://www.zigbee2mqtt.io/devices/WP33-EU_WP34-EU.html)
description:Multiprise with 4 AC outlets and 2 USB super charging ports (16A)
modelZigbee:JZ-ZB-005
type:Router
nwk:64248
manuf id:4107
manufacturer:LELLKI
power:Mains (single phase)
app version:4
hard version:0
zcl version:3
stack version:2
date code:20211213
build:2.0.1
interviewed:false
configured:false

Log:

| error | DeviceConfigure:Failed to DeviceConfigure.configure 0xa4c1384aaafbce0b JZ-ZB-005 (TypeError: Cannot read properties of undefined (reading 'debug') at Object.configureMagicPacket (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/tuya.js:1188:20) at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/lellki.js:26:13) at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13) at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:112:17))
-- | -- | --

| info | Configuring 0xa4c1384aaafbce0b JZ-ZB-005

**Comment by OnkelJo8576** [comment]
Hi, is not fixed...

error | DeviceConfigure:Failed to DeviceConfigure.configure 0xa4c1384aaafbce0b JZ-ZB-005 (TypeError: Cannot read properties of undefined (reading 'debug') at Object.configureMagicPacket (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/tuya.js:1188:20) at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/lellki.js:26:13) at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:134:13) at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:112:17))
-- | -- | -- | --
zigbee.0 | 2023-07-13 15:20:58.848 | info | Configuring 0xa4c1384aaafbce0b JZ-ZB-005
zigbee.0 | 2023-07-13 15:20:58.846 | info | Device '0xa4c1384aaafbce0b' is supported, identified as: LELLKI Multiprise with 4 AC outlets and 2 USB super charging ports (16A) (WP33-EU/WP34-EU)
zigbee.0 | 2023-07-13 15:20:58.845 | info | Successfully interviewed '0xa4c1384aaafbce0b', device has successfully been paired
zigbee.0 | 2023-07-13 15:20:57.810 | warn | Device '0xa4c1384aaafbce0b' announced itself
zigbee.0 | 2023-07-13 15:20:57.770 | info | Starting interview of '0xa4c1384aaafbce0b'
zigbee.0 | 2023-07-13 15:20:56.708 | info | Zigbee: allowing new devices to join.

**Comment by OnkelJo8576** [comment]
Perfect. Big Thanks!
