### ISSUE TITLE
unhandled promise rejection: Cannot read properties of undefined (reading 'Error')

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.zigbee#1795]
```
2023-07-12 15:47:41.539 - error: zigbee.0 (182832) Send command to 0x2c1165fffe8a596d failed with no error code (SRSP - AF - dataRequest after 6000ms)
2023-07-12 15:47:41.553 - error: zigbee.0 (182832) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-07-12 15:47:41.553 - error: zigbee.0 (182832) unhandled promise rejection: Cannot read properties of undefined (reading 'Error')
2023-07-12 15:47:41.637 - error: zigbee.0 (182832) TypeError: Cannot read properties of undefined (reading 'Error')
    at /opt/iobroker/node_modules/iobroker.zigbee/main.js:122:56
    at Hub.configureScope (/opt/iobroker/node_modules/@sentry/src/hub.ts:340:1)
    at Object.configureScope (/opt/iobroker/node_modules/@sentry/src/exports.ts:76:1)
    at Zigbee.sendError (/opt/iobroker/node_modules/iobroker.zigbee/main.js:118:32)
    at Zigbee.filterError (/opt/iobroker/node_modules/iobroker.zigbee/main.js:142:18)
    at /opt/iobroker/node_modules/iobroker.zigbee/main.js:703:26
2023-07-12 15:47:41.638 - error: zigbee.0 (182832) Cannot read properties of undefined (reading 'Error')
2023-07-12 15:47:41.866 - info: zigbee.0 (182832) cleaned everything up...
2023-07-12 15:47:41.922 - info: zigbee.0 (182832) Zigbee: disabling joining new devices.
2023-07-12 15:47:42.367 - info: zigbee.0 (182832) terminating
2023-07-12 15:47:42.368 - warn: zigbee.0 (182832) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-07-12 15:47:43.109 - error: host.iobroker Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-07-12 15:47:43.114 - error: host.iobroker Caught by controller[0]: TypeError: Cannot read properties of undefined (reading 'Error')
2023-07-12 15:47:43.114 - error: host.iobroker Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:122:56
2023-07-12 15:47:43.114 - error: host.iobroker Caught by controller[0]:     at Hub.configureScope (/opt/iobroker/node_modules/@sentry/src/hub.ts:340:1)
2023-07-12 15:47:43.114 - error: host.iobroker Caught by controller[0]:     at Object.configureScope (/opt/iobroker/node_modules/@sentry/src/exports.ts:76:1)
2023-07-12 15:47:43.114 - error: host.iobroker Caught by controller[0]:     at Zigbee.sendError (/opt/iobroker/node_modules/iobroker.zigbee/main.js:118:32)
2023-07-12 15:47:43.114 - error: host.iobroker Caught by controller[0]:     at Zigbee.filterError (/opt/iobroker/node_modules/iobroker.zigbee/main.js:142:18)
2023-07-12 15:47:43.114 - error: host.iobroker Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:703:26
2023-07-12 15:47:43.115 - error: host.iobroker instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-07-12 15:48:16.303 - info: zigbee.0 (231004) starting. Version 1.8.16 in /opt/iobroker/node_modules/iobroker.zigbee, node: v16.20.1, js-controller: 5.0.7
2023-07-12 15:48:16.399 - info: zigbee.0 (231004) delete old Backup files. keep only last 10
```

maybe similar to already closed issue #1778

adapter: 1.8.16
nodejs: 16.20.1
js-controller: 5.0.7

**Comment by arteck** [comment]
switch off the Sentry in adapter

**Comment by arteck** [comment]
check plz new GIT version..

**Comment by echoDaveD** [comment]
> switch off the Sentry in adapter
wie kann man das machen?
Habe den gleichen Fehler und die aktuelle 18.17 Version wirft Fehler deshalb würde ich wieder downgraden und dieses sentry aktivieren..

**Comment by arteck** [comment]
warte auf neue version
