### ISSUE TITLE
Adapter startet nicht

### ISSUE THREAD

**Issue by Christoph1978** [ioBroker/ioBroker.zigbee#1820]
Hallo zusammen,

ich bin gerade dabei, mein System zu erweitern. Hier die neue Konfiguration: IOBroker als LXC-Container als Master und einen Raspberry 3 mit IOBroker als Slave. Den Master gab es bereits, diesen habe ich auf Multihost erweitert. Auf dem Slave möchte ich nun eine Instanz des ZigBee-Adapters mit dem Sonoff USB 3.0 Zigbee-Stick laufen lassen. Den Stick habe ich mit der neusten Firmware geflasht und er wird auch vom Pi erkannt:
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/45732493/c2cb74b8-87c8-41ab-a0a7-759db94fc4c7)

und ist auch im Adapter eingetragen:
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/45732493/a0595e9c-df91-4577-be3f-c808fae97703)

Der Adapter bricht dann mit 

2023-08-02 13:24:30.604 - warn: host.iob2 Do not restart adapter system.adapter.zigbee.0 because restart loop detected

ab.

Hier ein Auszug aus dem Log:
<html>
<body>

2023-08-02 13:23:04.583 - info: zigbee.0 (2297) starting. Version 1.8.16 in /opt/iobroker/node_modules/iobroker.zigbee, node: v18.17.0, js-controller: 4.0.24
2023-08-02 13:23:04.681 - debug: zigbee.0 (2297) Using zigbee-herdsman with settings: {"network":{"panID":6754,"channelList":[11],"networkKey":[1,3,5,7,9,10,13,15,0,2,4,6,8,10,12,13],"extenedPanID":[221,221,221,221,219,221,221,221]},"databasePath":"/opt/iobroker/iobroker-data/zigbee_0/shepherd.db","backupPath":"/opt/iobroker/iobroker-data/zigbee_0/nvbackup.json","serialPort":{"baudRate":115200,"rtscts":false,"path":"/dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0","adapter":"zstack"},"adapter":{"forceStartWithInconsistentAdapterConfiguration":false}}
2023-08-02 13:23:04.815 - info: zigbee.0 (2297) delete old Backup files. keep only last 10
2023-08-02 13:23:04.819 - info: zigbee.0 (2297) Starting Zigbee npm ...
2023-08-02 13:23:04.822 - debug: zigbee.0 (2297) Starting zigbee-herdsman...
2023-08-02 13:23:06.177 - info: zigbee.0 (2297) Installed Version: iobroker.zigbee@1.8.16
2023-08-02 13:23:06.199 - debug: zigbee.0 (2297) Backup /opt/iobroker/iobroker-data/zigbee_0/backup_2023_08_02-13_23_04.tar.gz success
2023-08-02 13:23:06.540 - debug: zigbee.0 (2297) zigbee-herdsman started
2023-08-02 13:23:06.542 - info: zigbee.0 (2297) Coordinator firmware version: {"type":"zStack3x0","meta":{"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20230507}}
2023-08-02 13:23:06.551 - debug: zigbee.0 (2297) Zigbee network parameters: panID=6754 channel=11 extendedPanID=63b1e829004b1200
2023-08-02 13:23:06.553 - info: zigbee.0 (2297) Unable to disable LED, unsupported function.
2023-08-02 13:23:06.586 - info: zigbee.0 (2297) --> transmitPower : normal
2023-08-02 13:23:06.595 - info: zigbee.0 (2297) Currently no devices.
2023-08-02 13:23:06.598 - info: zigbee.0 (2297) Zigbee started
2023-08-02 13:23:06.599 - debug: zigbee.0 (2297) Config value 0xdddddddbdddddddd : Network value 0x00124b0029e8b163
2023-08-02 13:23:06.604 - error: zigbee.0 (2297) Unable to apply ExtPanID changes: Error: SRSP - SYS - osalNvRead after 0,2ms
2023-08-02 13:23:06.606 - error: zigbee.0 (2297) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-08-02 13:23:06.607 - error: zigbee.0 (2297) unhandled promise rejection: Cannot read properties of undefined (reading 'Error')
2023-08-02 13:23:06.705 - error: zigbee.0 (2297) TypeError: Cannot read properties of undefined (reading 'Error')
at /opt/iobroker/node_modules/iobroker.zigbee/main.js:122:56
at Hub.configureScope (/opt/iobroker/node_modules/@sentry/src/hub.ts:340:1)
at Object.configureScope (/opt/iobroker/node_modules/@sentry/src/exports.ts:76:1)
at Zigbee.sendError (/opt/iobroker/node_modules/iobroker.zigbee/main.js:118:32)
at Zigbee.onZigbeeAdapterReady (/opt/iobroker/node_modules/iobroker.zigbee/main.js:415:30)
2023-08-02 13:23:06.706 - error: zigbee.0 (2297) Cannot read properties of undefined (reading 'Error')
2023-08-02 13:23:06.726 - info: zigbee.0 (2297) cleaned everything up...
2023-08-02 13:23:06.731 - info: zigbee.0 (2297) Zigbee: disabling joining new devices.
2023-08-02 13:23:07.305 - info: zigbee.0 (2297) terminating
2023-08-02 13:23:07.307 - debug: zigbee.0 (2297) Plugin sentry destroyed
2023-08-02 13:23:07.309 - warn: zigbee.0 (2297) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-08-02 13:23:07.894 - error: host.iob2 Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-08-02 13:23:07.895 - error: host.iob2 Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'Error')
2023-08-02 13:23:07.896 - error: host.iob2 Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.zigbee/main.js:122:56
2023-08-02 13:23:07.896 - error: host.iob2 Caught by controller[1]: at Hub.configureScope (/opt/iobroker/node_modules/@sentry/src/hub.ts:340:1)
2023-08-02 13:23:07.896 - error: host.iob2 Caught by controller[1]: at Object.configureScope (/opt/iobroker/node_modules/@sentry/src/exports.ts:76:1)
2023-08-02 13:23:07.896 - error: host.iob2 Caught by controller[1]: at Zigbee.sendError (/opt/iobroker/node_modules/iobroker.zigbee/main.js:118:32)
2023-08-02 13:23:07.897 - error: host.iob2 Caught by controller[1]: at Zigbee.onZigbeeAdapterReady (/opt/iobroker/node_modules/iobroker.zigbee/main.js:415:30)
2023-08-02 13:23:07.897 - error: host.iob2 instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-08-02 13:23:07.898 - info: host.iob2 Restart adapter system.adapter.zigbee.0 because enabled

</body>
</html>

Ich hoffe, ihr könnt mir hierzu einen Tipp geben.

Vielen Dank schon mal im Voraus!

Gruß
Christoph

**Comment by arteck** [comment]
schau bitte im Forum nach.. das Thema wird oft behandelt
