### ISSUE TITLE
Regelmäßiger Absturz Version 1.8.21

### ISSUE THREAD

**Issue by Bulls91** [ioBroker/ioBroker.zigbee#1825]
Hallo zusammen,

mein Adapter stürzt immer wieder ab und ich erhalte folgende Meldungen im ioBroker:

2023-08-03 16:01:46.314 - error: zigbee.1 (22668) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
--
2023-08-03 16:01:46.315 - error: zigbee.1 (22668) unhandled promise rejection: Cannot read properties of null (reading 'meta')
2023-08-03 16:01:46.316 - error: zigbee.1 (22668) TypeError: Cannot read properties of null (reading 'meta')
at Zigbee.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/main.js:480:25)
2023-08-03 16:01:46.316 - error: zigbee.1 (22668) Cannot read properties of null (reading 'meta')
2023-08-03 16:01:46.344 - info: zigbee.1 (22668) cleaned everything up...
2023-08-03 16:01:46.366 - info: zigbee.1 (22668) Zigbee: disabling joining new devices.
2023-08-03 16:01:46.845 - info: zigbee.1 (22668) terminating
2023-08-03 16:01:46.847 - warn: zigbee.1 (22668) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-08-03 16:01:47.547 - error: host.raspberrypi Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-08-03 16:01:47.548 - error: host.raspberrypi Caught by controller[0]: TypeError: Cannot read properties of null (reading 'meta')
2023-08-03 16:01:47.548 - error: host.raspberrypi Caught by controller[0]: at Zigbee.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/main.js:480:25)
2023-08-03 16:01:47.548 - error: host.raspberrypi instance system.adapter.zigbee.1 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-08-03 16:01:47.548 - info: host.raspberrypi Restart adapter system.adapter.zigbee.1 because enabled

Sobald der Adapter wieder läuft dauert es keine Stunde bis dieser Ausfall wieder auftritt. Angeschlossen habe ich an dem Adapter den CC2652P2 TCP Ethernet Coordinator und es sind ein Aqara Temperatursensor und zwei Aqara Taster verbunden.

Hat jemand eine Idee was ich machen kann, um den Adapter wieder in einen stabilen Zustand zu bekommen?

Installiert ist die Version 1.8.21 des Adapters.

**Comment by StefanTR96** [comment]
Same Problem here!

**Comment by arteck** [comment]
installiermal die GIT version.. gehts damit ??

**Comment by Bulls91** [comment]
Habe aus dem gut installiert und leider besteht der Fehler immer noch und es kommt zum Absturz:



2023-08-03 19:01:31.891 - error: zigbee.1 (4141) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
--
2023-08-03 19:01:31.892 - error: zigbee.1 (4141) unhandled promise rejection: Cannot read properties of null (reading 'meta')
2023-08-03 19:01:31.893 - error: zigbee.1 (4141) TypeError: Cannot read properties of null (reading 'meta')
at Zigbee.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/main.js:473:25)
2023-08-03 19:01:31.893 - error: zigbee.1 (4141) Cannot read properties of null (reading 'meta')
2023-08-03 19:01:31.933 - info: zigbee.1 (4141) cleaned everything up...
2023-08-03 19:01:31.963 - info: zigbee.1 (4141) Zigbee: disabling joining new devices.
2023-08-03 19:01:32.435 - info: zigbee.1 (4141) terminating
2023-08-03 19:01:32.437 - warn: zigbee.1 (4141) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-08-03 19:01:33.115 - error: host.raspberrypi Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-08-03 19:01:33.116 - error: host.raspberrypi Caught by controller[0]: TypeError: Cannot read properties of null (reading 'meta')
2023-08-03 19:01:33.116 - error: host.raspberrypi Caught by controller[0]: at Zigbee.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/main.js:473:25)
2023-08-03 19:01:33.116 - error: host.raspberrypi instance system.adapter.zigbee.1 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-08-03 19:01:33.116 - info: host.raspberrypi Restart adapter system.adapter.zigbee.1 because enabled
2023-08-03 19:02:03.280 - info: host.raspberrypi instance system.adapter.zigbee.1 started with pid 8106

**Comment by arteck** [comment]
noch ne runde.. nochmal von GIT installieren

**Comment by Bulls91** [comment]
problem bleibt leider bestehen

**Comment by arteck** [comment]
ok installier mal
`
https://github.com/ioBroker/ioBroker.zigbee/tarball/bug1
`

es kommt jetzt ein error vor dem abbruch..die meldung brauch ich

**Comment by Bulls91** [comment]
@arteck  es kommt jetzt dieser Error. Meinst Du das?

2023-08-04 11:01:27.035 - error: zigbee.1 (27481) Type attributeReport device {"type":"device","device":{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":3,"_type":"EndDevice","_ieeeAddr":"0x00158d0008cffd5d","_networkAddress":10118,"_manufacturerID":4151,"_endpoints":[{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":1,"profileID":260,"deviceID":259,"inputClusters":[0,18,3],"outputClusters":[0],"deviceNetworkAddress":10118,"deviceIeeeAddress":"0x00158d0008cffd5d","clusters":{"genBasic":{"attributes":{"65281":{"1":3005,"3":23,"4":17320,"5":24,"6":[0,1],"10":0},"modelId":"lumi.remote.b1acn01","appVersion":2,"manufacturerName":"LUMI","powerSource":3,"zclVersion":1,"stackVersion":2,"hwVersion":2,"dateCode":"20180525","swBuildId":"3000-0001"}},"genMultistateInput":{"attributes":{"presentValue":1}}},"_binds":[],"_configuredReportings":[],"meta":{},"pendingRequests":{},"sendInProgress":false}],"_manufacturerName":"LUMI","_powerSource":"Battery","_modelID":"lumi.remote.b1acn01","_applicationVersion":2,"_stackVersion":2,"_zclVersion":1,"_hardwareVersion":2,"_dateCode":"20180525","_softwareBuildID":"3000-0001","_interviewCompleted":true,"_interviewing":false,"_skipDefaultResponse":false,"_skipTimeResponse":false,"meta":{},"_lastSeen":1691139687009,"_defaultSendRequestWhen":"immediate","_pendingRequestTimeout":0,"_linkquality":149},"mapped":{"zigbeeModel":["lumi.sensor_switch.aq2","lumi.remote.b1acn01"],"model":"WXKG11LM","vendor":"Xiaomi","description":"Aqara wireless switch","meta":{"battery":{"voltageToPercentage":"3V_2850_3000"}},"exposes":[{"type":"numeric","name":"battery","property":"battery","access":1,"unit":"%","description":"Remaining battery in %, can take up to 24 hours before reported.","value_min":0,"value_max":100},{"type":"numeric","name":"voltage","property":"voltage","access":1,"unit":"mV","description":"Voltage of the battery in millivolts"},{"type":"enum","name":"action","property":"action","access":1,"values":["single","double","triple","quadruple","hold","release"],"description":"Triggered action (e.g. a button click)"},{"type":"numeric","name":"device_temperature","property":"device_temperature","access":1,"unit":"°C","description":"Temperature of the device"},{"type":"numeric","name":"power_outage_count","property":"power_outage_count","access":1,"description":"Number of power outages (since last pairing)"},{"type":"numeric","name":"linkquality","property":"linkquality","access":1,"unit":"lqi","description":"Link quality (signal strength)","value_min":0,"value_max":255}],"fromZigbee":[{"cluster":"genMultistateInput","type":["attributeReport"]},{"cluster":"genOnOff","type":["attributeReport","readResponse"]},{"cluster":"genBasic","type":["attributeReport","readResponse"]},{"cluster":"genOnOff","type":["attributeReport","readResponse"],"options":[{"type":"binary","name":"legacy","property":"legacy","access":2,"value_on":true,"value_off":false,"description":"Set to false to disable the legacy integration (highly recommended), will change structure of the published payload (default true)."}]},{"cluster":"genMultistateInput","type":["attributeReport","readResponse"],"options":[{"type":"binary","name":"legacy","property":"legacy","access":2,"value_on":true,"value_off":false,"description":"Set to false to disable the legacy integration (highly recommended), will change structure of the published payload (default true)."}]}],"toZigbee":[{"key":["scene_store"]},{"key":["scene_recall"]},{"key":["scene_add"]},{"key":["scene_remove"]},{"key":["scene_remove_all"]},{"key":["read"]},{"key":["write"]},{"key":["command"]},{"key":["reset"]}],"options":[{"type":"numeric","name":"device_temperature_calibration","property":"device_temperature_calibration","access":2,"description":"Calibrates the device_temperature value (absolute offset), takes into effect on next report of device."},"[Circular]"]},"name":"0x00158d0008cffd5d"}
--

**Comment by arteck** [comment]
ja

**Comment by Bulls91** [comment]
habe hier auch nochmal einen zusammenhängenden errorlog, was nun beim letzten Absturz in den Meldungen gekommen ist:


2023-08-04 11:17:14.740 - error: zigbee.1 (27481) Type attributeReport device {"type":"device","device":{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":6,"_type":"Unknown","_ieeeAddr":"0x00158d000894d6a8","_networkAddress":55790,"_endpoints":[{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":1,"inputClusters":[],"outputClusters":[],"deviceNetworkAddress":55790,"deviceIeeeAddress":"0x00158d000894d6a8","clusters":{"genBasic":{"attributes":{"65281":{"1":3015,"3":28,"4":17320,"5":13,"6":[0,1],"10":0,"11":115,"100":0}}},"msIlluminanceMeasurement":{"attributes":{"measuredValue":50}},"msOccupancySensing":{"attributes":{"occupancy":1}}},"_binds":[],"_configuredReportings":[],"meta":{},"pendingRequests":{},"sendInProgress":false}],"_interviewCompleted":false,"_interviewing":false,"_skipDefaultResponse":false,"_skipTimeResponse":false,"meta":{},"_lastSeen":1691140634725,"_defaultSendRequestWhen":"immediate","_pendingRequestTimeout":0,"_linkquality":0},"mapped":null,"name":"0x00158d000894d6a8"}
--
2023-08-04 11:17:14.743 - error: zigbee.1 (27481) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-08-04 11:17:14.744 - error: zigbee.1 (27481) unhandled promise rejection: Cannot read properties of null (reading 'meta')
2023-08-04 11:17:14.745 - error: zigbee.1 (27481) TypeError: Cannot read properties of null (reading 'meta')
at Zigbee.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/main.js:475:25)
2023-08-04 11:17:14.745 - error: zigbee.1 (27481) Cannot read properties of null (reading 'meta')
2023-08-04 11:17:14.779 - info: zigbee.1 (27481) cleaned everything up...
2023-08-04 11:17:14.810 - info: zigbee.1 (27481) Zigbee: disabling joining new devices.
2023-08-04 11:17:15.281 - info: zigbee.1 (27481) terminating
2023-08-04 11:17:15.282 - warn: zigbee.1 (27481) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-08-04 11:17:15.990 - error: host.raspberrypi Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-08-04 11:17:15.991 - error: host.raspberrypi Caught by controller[0]: TypeError: Cannot read properties of null (reading 'meta')
2023-08-04 11:17:15.992 - error: host.raspberrypi Caught by controller[0]: at Zigbee.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/main.js:475:25)
2023-08-04 11:17:15.992 - error: host.raspberrypi instance system.adapter.zigbee.1 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-08-04 11:17:15.992 - info: host.raspberrypi Restart adapter system.adapter.zigbee.1 because enabled

**Comment by arteck** [comment]
was its das für ein DEvice 0x00158d000894d6a8

**Comment by Fichte79** [comment]
Hab das selbe mit dem Device 0x84fd27fffebb78fe und das ist ein model: HG06335/HG07310

<html>
<body>


zigbee.0 | 2023-08-04 11:37:20.656 | error | Device 0x84fd27fffebb78fe "undefined" not described in statesMapping.
-- | -- | -- | --
host.ioBroker | 2023-08-04 11:36:46.964 | error | instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.ioBroker | 2023-08-04 11:36:46.964 | error | Caught by controller[0]: at Zigbee.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/main.js:480:25)
host.ioBroker | 2023-08-04 11:36:46.964 | error | Caught by controller[0]: TypeError: Cannot read properties of null (reading 'meta')
host.ioBroker | 2023-08-04 11:36:46.964 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
zigbee.0 | 2023-08-04 11:36:45.895 | error | Cannot read properties of null (reading 'meta')
zigbee.0 | 2023-08-04 11:36:45.895 | error | TypeError: Cannot read properties of null (reading 'meta') at Zigbee.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/main.js:480:25)
zigbee.0 | 2023-08-04 11:36:45.895 | error | unhandled promise rejection: Cannot read properties of null (reading 'meta')
zigbee.0 | 2023-08-04 11:36:45.895 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().


</body>
</html>

**Comment by arteck** [comment]
jetzt mal GIT installieren..

**Comment by Fichte79** [comment]
Das ist das Gerät hab 2 Stück am laufen und diese macht Stress

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/107550931/d5dedbb8-7e87-4b92-b80c-fed12a9550c2)

**Comment by Bulls91** [comment]
ich habe seit neusten zwei undefined-geräte bei mir. Diese kann ich leider auch unter die unteren buttons nicht löschen:

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/92435210/3d5de9df-172f-4944-80b0-e9fbd4a03822)

**Comment by Fichte79** [comment]
Hab Zwei solche dinger sehen so aus

Der der Funktioniert 
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/107550931/bd17ce57-f1f2-483d-8870-7452553c88e7)
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/107550931/74fb1c35-4a2c-46ae-819d-df2aaff9924a)


Und der der nicht Funktioniert

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/107550931/927c37d7-5477-48c8-bbc4-a044db8e070e)
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/107550931/a279c898-2d17-4349-95e0-b59adad72dbb)

**Comment by arteck** [comment]
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/6681528/351386c8-e740-492b-9d23-8adea666819f)
war mir klar... der muss sich melden.. also so langen probieren bis da was steht

**Comment by arteck** [comment]
> ich habe seit neusten zwei undefined-geräte bei mir. Diese kann ich leider auch unter die unteren buttons nicht löschen:
> 

doch kannst du 

![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/6681528/6c40feed-364f-4ac1-a043-ff6d9f08248f)


da drauf und dann kommt ein Dialog..

**Comment by Bulls91** [comment]
ok Kommando zurück. habe es rausgefunden. Mit safari geht das löschen bzw. das selektieren der Buttons in der Reihe nicht. Mit Chrome klappt es!!

**Comment by Fichte79** [comment]
> @Fichte79
> 
> ![grafik](https://user-images.githubusercontent.com/6681528/258386642-351386c8-e740-492b-9d23-8adea666819f.png) war mir klar... der muss sich melden.. also so langen probieren bis da was steht

Ich hab ihn mir jetzt geholt und einfach neu gepairt, nun scheint er wieder da zu sein

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/107550931/a06cabc0-daf6-4984-adb4-c59ecc769486)

**Comment by arteck** [comment]
> ok Kommando zurück. habe es rausgefunden. Mit safari geht das löschen bzw. das selektieren der Buttons in der Reihe nicht. Mit Chrome klappt es!!

ja Fehler ist bekannt.. mir dem Safari

was ist mit dem abbruch?

**Comment by Bulls91** [comment]
bis jetzt läuft es alles ohne Probleme. Aus dem Bauch raus würde ich sagen der Fehler ist behoben! Vielen vielen Dank dafür :)

**Comment by Fichte79** [comment]
> bis jetzt läuft es alles ohne Probleme. Aus dem Bauch raus würde ich sagen der Fehler ist behoben! Vielen vielen Dank dafür :)

Kann @Bulls91 nur zustimmen. 👍
