### ISSUE TITLE
Falsche Erkennung von BHT-002, folgende Fehler/Warnungen und seit 1.8.21 Absturz nach pairing

### ISSUE THREAD

**Issue by Sebliner** [ioBroker/ioBroker.zigbee#1827]
Hallo miteinander,

Danke für die tolle Arbeit mit diesem Adapter!!
Ich habe erst seit rund 2 Wochen einen zigbee Adapter (Sonoff E - EFR32) und unter 1.8.18 erfolgreich meine Thermostate von Moes (BHT-002) verbunden. 
Die Geräte wurden allerdings fälschlicherweise als BHT-006 erkannt, Bedienung funktioniert aber.
Eventuell daraus folgend gibt es schon immer ganz regelmäßig solche Warnungen im log:

_warn: zigbee.0 (1170) State value to set for "zigbee.0.a4c138546f8b460b.current_heating_setpoint" has value "135266816" greater than max "35"
warn: zigbee.0 (928947) State value to set for "zigbee.0.a4c1381824420c43.current_heating_setpoint" has value "-1442686021" less than min "5"_

und

_warn: zigbee.0 (928947) convert problem with 'BHT-006GBZB' 'a4c13815bc2d0bf0'_

Ich dachte nach dem Versionsupdate verbinde ich einen Thermostat neu und schaue ob er nun richtig erkannt wird und das Problem gelöst ist. Also das Gerät zunächst gelöscht. Beim anschließenden neuen pairing wird allerdings keine Verbindung mehr vom Adapter erkannt und entsprechend ist auch kein Pairing möglich. Außerdem stürzt der Adapter nach dem Pairing zuverlässig ab.

_2023-08-04 23:56:37.517 - info: zigbee.0 (1554) Zigbee: stop joining
2023-08-04 23:56:37.542 - error: zigbee.0 (1554) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-08-04 23:56:37.542 - error: zigbee.0 (1554) unhandled promise rejection: Cannot read properties of null (reading 'meta')
2023-08-04 23:56:37.543 - error: zigbee.0 (1554) TypeError: Cannot read properties of null (reading 'meta')
at Zigbee.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/main.js:480:25)
2023-08-04 23:56:37.543 - error: zigbee.0 (1554) Cannot read properties of null (reading 'meta')
2023-08-04 23:56:37.547 - info: zigbee.0 (1554) cleaned everything up...
2023-08-04 23:56:37.616 - info: zigbee.0 (1554) Zigbee: disabling joining new devices.
2023-08-04 23:56:37.912 - info: zigbee.0 (1554) terminating
2023-08-04 23:56:37.913 - warn: zigbee.0 (1554) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-08-04 23:56:38.474 - error: host.iobroker instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-08-04 23:56:38.475 - info: host.iobroker Restart adapter system.adapter.zigbee.0 because enabled_

Ich bin nicht sicher ob es am Dongle liegt oder am Adapter. Neustart natürlich erledigt, Dongle auch länger abgezogen.
Über jede Hilfestellung bin ich sehr dankbar!

Grüße

**Comment by arteck** [comment]
installier mal von GIT...

**Comment by Sebliner** [comment]
Habe ich soeben gemacht und beim paring mit dem Gerät wird dann im log folgendes angezeigt:

_2023-08-05 13:18:12.071 - info: zigbee.0 (14908) Zigbee: allowing new devices to join.
2023-08-05 13:18:54.815 - info: zigbee.0 (14908) Starting interview of '0xa4c138ef10afc0ec'
2023-08-05 13:18:55.286 - error: zigbee.0 (14908) Device 0xa4c138ef10afc0ec "TS0601" not described in statesMapping.
2023-08-05 13:18:55.836 - info: zigbee.0 (14908) Successfully interviewed '0xa4c138ef10afc0ec', device has successfully been paired
2023-08-05 13:18:55.836 - info: zigbee.0 (14908) Device '0xa4c138ef10afc0ec' is supported, identified as: Moes Smart heating thermostat (BHT-006GBZB)
2023-08-05 13:18:55.855 - warn: zigbee.0 (14908) download icon from https://www.zigbee2mqtt.io/images/devices/BHT-006GBZB.jpg saved into /opt/iobroker/node_modules/iobroker.zigbee/admin/img/BHT-006GBZB.png
2023-08-05 13:18:56.034 - warn: zigbee.0 (14908) Object a4c138ef10afc0ec.mode is invalid: obj.common.states has an invalid type! Expected "object", received "string"
2023-08-05 13:18:56.034 - warn: zigbee.0 (14908) This object will not be created in future versions. Please report this to the developer.
2023-08-05 13:18:56.058 - warn: zigbee.0 (14908) Object zigbee.0.a4c138ef10afc0ec.mode is invalid: obj.common.states has an invalid type! Expected "object", received "string"
2023-08-05 13:18:56.059 - warn: zigbee.0 (14908) This object will not be created in future versions. Please report this to the developer.
2023-08-05 13:19:13.337 - info: zigbee.0 (14908) Zigbee: stop joining
2023-08-05 13:19:13.365 - error: zigbee.0 (14908) Device 0xe0798dfffecd31ae "undefined" not described in statesMapping._

Auf jeden Fall kann das Gerät wieder gepaired werden und der Adapter stürzt nicht mehr ab - super! Das Gerät wird allerdings weiterhin als das falsche erkannt.

Diese Warnung mit dem absurden current heat value ohne Eingabe/Änderung von mir ist gerade ebenfalls wieder aufgetreten:

_2023-08-05 13:52:36.129 - warn: zigbee.0 (14908) State value to set for "zigbee.0.a4c1381824420c43.current_heating_setpoint" has value "6150" greater than max "35"_

Kann ich noch etwas versuchen?

**Comment by arteck** [comment]
zeigmal die Info kachel

**Comment by Sebliner** [comment]
Das wäre die Kachel von einem meiner Thermostate
![kachel](https://github.com/ioBroker/ioBroker.zigbee/assets/141459376/d1b9c5d2-e7ec-4342-860a-1f347675ddb9)

Tatsächlich installiert ist wie gesagt ein BHT-002, dieses hier:
[https://www.aliexpress.com/item/4001326539649.html?spm=a2g0o.order_list.order_list_main.28.21ef18023v9etw](url)

**Comment by bufl282** [comment]
Fehler kann ich bei mir bestätigen. Habe ebenfalls Sonoff Dongle E. Beim Pairing (bei mir Fenstersensor) erhalte ich einen Fehler und Adapter wird neu gestartet:


```
host.raspberrypi
2023-08-07 12:27:01.833	error	instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.raspberrypi
2023-08-07 12:27:01.833	error	Caught by controller[1]: at Zigbee.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/main.js:480:25)
host.raspberrypi
2023-08-07 12:27:01.833	error	Caught by controller[1]: TypeError: Cannot read properties of null (reading 'meta')
host.raspberrypi
2023-08-07 12:27:01.832	error	Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:

zigbee.0
2023-08-07 12:27:00.685	error	Cannot read properties of null (reading 'meta')

zigbee.0
2023-08-07 12:27:00.684	error	TypeError: Cannot read properties of null (reading 'meta') at Zigbee.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/main.js:480:25)

zigbee.0
2023-08-07 12:27:00.684	error	unhandled promise rejection: Cannot read properties of null (reading 'meta')

zigbee.0
2023-08-07 12:27:00.684	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

zigbee.0
2023-08-07 12:26:33.113	error	Failed to interview '0xec1bbdfffe8d3dae', device has not successfully been paired. undefined
```

**Comment by arteck** [comment]
das da will ich sehen
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/6681528/d5d748b0-c1fc-4a20-80da-1e4cca689661)

**Comment by Sebliner** [comment]
🤦
Hier dann hoffentlich korrekt:
![Info](https://github.com/ioBroker/ioBroker.zigbee/assets/141459376/6835d26a-e728-4875-8b71-27dc997ecf10)

**Comment by arteck** [comment]
check 1.10.0

**Comment by Sebliner** [comment]
Danke für das update, ich kam nun endlich dazu mir alles in Ruhe anzuschauen.

Der Fehler mit den falschen Werten bei current heat setpoint tritt weiterhin auf:
_2024-01-24 12:14:59.711 - warn: zigbee.0 (740) State value to set for "zigbee.0.a4c138b3cbd9ce71.current_heating_setpoint" has value "398377" greater than max "35"_


Gleichzeitig habe ich festgestellt dass meine CPU-Last mit aktiviertem Adapter deutlich ansteigt (so 30% meines Intel N3450 quad), außerdem wird der komplette iobroker träger und bei der entsprechenden Zigbee-Instanz zeigt mir iobroker teils 4 stellige Eingabe- und Ausgabeereignisse an. Daraufhin logging auf debug geändert und festgestellt, dass die Thermostate unfassbar viele (unnötige) Nachrichten senden welche alle verarbeitet werden - teils alle 50 ms, manchmal auch etwas Pause dazwischen. Entsprechend häufig werden auch Datenpunkte mit den immer gleichen Werten beschrieben. Dass ich 12 von den Dingern habe macht die Flutung noch stärker.

Daraufhin hier die Beschreibung des flooding bugs gefunden: https://www.zigbee2mqtt.io/devices/BHT-002-GCLZB.html
Dort soll der bug durch die Ergänzung von debounce in der configuration.yaml umgangen werden. 
Meine Thermostate werden aber nicht als diese erkannt, sondern als BHT-002/BHT-006 was zu diesem link führt: https://www.zigbee2mqtt.io/devices/BHT-002_BHT-006.html
Dort ist nichts vom flooding zu lesen, entsprechend wird der Adapter so beschäftigt.

Leider habe ich überhaupt keine Ahnung von Programmierung, deswegen weiß ich nicht mal wo ich den Fehler melden sollte - sollten meine Thermostate als die BHT-002 erkannt werden? Muss im Adapter etwas geändert werden? Muss der herdsman geändert werden? Vermutlich würde sich am Fehler mit den falschen Werten beim current heating setpoint damit auch nichts ändern, aber zumindest die CPU Last runtergehen?


Für Hilfestellung bin ich sehr dankbar - wenn ich noch etwas testen/untersuchen kann gerne Bescheid geben!

Grüße und danke!

**Comment by kugelkopf123** [comment]
Habe das gleiche Problem. 
`State value to set for "zigbee.0.a4c138fd676181b0.current_heating_setpoint" has value "9196970" greater than max "35"`

Gibt es inzw. eine Lösung?

**Comment by arteck** [comment]
wenn immer noch mach bitte neuen issue auf
