### ISSUE TITLE
Crash when activating scene

### ISSUE THREAD

**Issue by gaudes** [ioBroker/ioBroker.zigbee#1832]
Hi,

the adapter in current version 1.8.21 is often crashing.

The current version is always crashing when activating a scene which sets some lights.

Please see the attached log file.

Any ideas ?

Kind regards,
Ralf
[Zigbee_crash.txt](https://github.com/ioBroker/ioBroker.zigbee/files/12284785/Zigbee_crash.txt)

**Comment by gaudes** [comment]
Got some additional information. I have a group of two light bulbs:

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/34286177/193d9532-e804-4e29-83a2-9145fba6baf8)

When doing changes (on/off) on the group the adapter is crashing with these log:

```
<html>
<body>
<!--StartFragment-->

zigbee.0 | 2023-08-07 22:15:39.327 | error | getGroupMembersFromController: error is {} "Error: \n at Groups.getGroupMembersFromController (/opt/iobroker/node_modules/iobroker.zigbee/lib/groups.js:88:119)\n at Groups.queryGroupMemberState (/opt/iobroker/node_modules/iobroker.zigbee/lib/groups.js:170:36)\n at Zigbee.callPluginMethod (/opt/iobroker/node_modules/iobroker.zigbee/main.js:863:45)\n at /opt/iobroker/node_modules/iobroker.zigbee/main.js:729:40"
-- | -- | -- | --
zigbee.0 | 2023-08-07 22:15:39.270 | info | Zigbee: disabling joining new devices.
zigbee.0 | 2023-08-07 22:15:39.110 | info | cleaned everything up...
zigbee.0 | 2023-08-07 22:15:39.084 | error | Cannot read properties of null (reading 'meta')
zigbee.0 | 2023-08-07 22:15:39.084 | error | TypeError: Cannot read properties of null (reading 'meta') at Zigbee.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/main.js:480:25)
zigbee.0 | 2023-08-07 22:15:39.083 | error | unhandled promise rejection: Cannot read properties of null (reading 'meta')
zigbee.0 | 2023-08-07 22:15:39.083 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

<!--EndFragment-->
</body>
</html>
``` 

I'm using a Conbee II

Thanks.

**Comment by arteck** [comment]
install 1.8.22
