### ISSUE TITLE
Adapter stürzt ständig ab

### ISSUE THREAD

**Issue by 20silencer04** [ioBroker/ioBroker.zigbee#1835]
Hallo ich verwende einen Conbee Stick 2 mit der Version 1.8.21 und habe seit geraumer Zeit das Problem das der Adapter ständig abstürzt. Ich habe auch den ioBroker komplett neu installiert und vorherige Version der Zigbee Adapters versucht. Leider komme ich immer zu dem selben Ergebnis. Das ganze System lief Monate ohne ein einziges Problem. Hat jemand einen Tipp für mich. 

Vielen Dank
Log...
`zigbee.0
2023-08-08 21:55:00.277	error	getGroupMembersFromController: error is {} "Error: \n at Groups.getGroupMembersFromController (/opt/iobroker/node_modules/iobroker.zigbee/lib/groups.js:88:119)\n at Groups.queryGroupMemberState (/opt/iobroker/node_modules/iobroker.zigbee/lib/groups.js:170:36)\n at Zigbee.callPluginMethod (/opt/iobroker/node_modules/iobroker.zigbee/main.js:863:45)\n at /opt/iobroker/node_modules/iobroker.zigbee/main.js:729:40"

zigbee.0
2023-08-08 21:55:00.044	error	Cannot read properties of null (reading 'meta')

zigbee.0
2023-08-08 21:55:00.044	error	TypeError: Cannot read properties of null (reading 'meta') at Zigbee.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/main.js:480:25)

zigbee.0
2023-08-08 21:55:00.043	error	unhandled promise rejection: Cannot read properties of null (reading 'meta')

zigbee.0
2023-08-08 21:55:00.042	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

zigbee.0
2023-08-08 21:54:10.749	error	Send command to 0xcccc030201034a87 failed with no error code (no response received (65)

zigbee.0
2023-08-08 21:54:08.769	error	Send command to 0xccccccfffedbe06d failed with no error code (no response received (58)

zigbee.0
2023-08-08 21:54:08.763	error	Send command to 0xcccc030201034a87 failed with no error code (no response received (59)

zigbee.0
2023-08-08 21:54:08.752	error	Send command to 0x7cb03eaa00aca3e1 failed with no error code (no response received (63)

zigbee.0
2023-08-08 21:50:00.409	error	getGroupMembersFromController: error is {} "Error: \n at Groups.getGroupMembersFromController (/opt/iobroker/node_modules/iobroker.zigbee/lib/groups.js:88:119)\n at Groups.queryGroupMemberState (/opt/iobroker/node_modules/iobroker.zigbee/lib/groups.js:170:36)\n at Zigbee.callPluginMethod (/opt/iobroker/node_modules/iobroker.zigbee/main.js:863:45)\n at /opt/iobroker/node_modules/iobroker.zigbee/main.js:729:40"

zigbee.0
2023-08-08 21:50:00.103	error	Cannot read properties of null (reading 'meta')

zigbee.0
2023-08-08 21:50:00.103	error	TypeError: Cannot read properties of null (reading 'meta') at Zigbee.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/main.js:480:25)

zigbee.0
2023-08-08 21:50:00.102	error	unhandled promise rejection: Cannot read properties of null (reading 'meta')

zigbee.0
2023-08-08 21:50:00.100	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().`

**Comment by arteck** [comment]
1.8.22 ist draussen
