### ISSUE TITLE
Nach Update auf 1.8.23 startete der Adapter nicht mehr!

### ISSUE THREAD

**Issue by UweLoyal** [ioBroker/ioBroker.zigbee#1846]
Nach Update auf 1.8.23 startete der Adapter nicht mehr!
Rollback auf 1.8.19 und Umstellung COM port name von
/dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rr_stick_-_slaesh_s_iot_xxxxxx
auf
/dev/ttyUSB0 [Silicon Labs]
brachte den Adapter wieder zum Laufen.

Gruß
Uwe Loyal

**Comment by pankewen** [comment]
Had the same issue here. Thanks for the hint of the rollback version. 1.8.22 also did not work, I jumped back to 1.8.19 and the adapter was running again.

**Comment by Apollon77** [comment]
Cool ... SOrry huys but what about some logs? Else you will never get ny solution and are stick on that version.

**Comment by UweLoyal** [comment]
Logs?
After activating them nothing came.
Really nothing!
After rollbach the upper Info came.

Sorry!

Rgds
Uwe

**Comment by kloppy1984** [comment]
i had the same Problem.

Logs:



host.raspberrypi | 2023-08-19 19:29:29.342 | warn | adapter "zigbee" seems to be installed for a different version of Node.js. Trying to rebuild it... 3 attempt
-- | -- | -- | --
host.raspberrypi | 2023-08-19 19:29:29.341 | info | system.adapter.zigbee.0 will be rebuilt
host.raspberrypi | 2023-08-19 19:29:29.341 | info | Adapter system.adapter.zigbee.0 needs rebuild and will be restarted afterwards.
host.raspberrypi | 2023-08-19 19:29:29.341 | error | instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.raspberrypi | 2023-08-19 19:29:29.340 | error | Caught by controller[0]: }
host.raspberrypi | 2023-08-19 19:29:29.340 | error | Caught by controller[0]: ]
host.raspberrypi | 2023-08-19 19:29:29.340 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.zigbee/main.js'
host.raspberrypi | 2023-08-19 19:29:29.340 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.zigbee/node_modules/@iobroker/adapter-core/build/index.js',
host.raspberrypi | 2023-08-19 19:29:29.340 | error | Caught by controller[0]: requireStack: [
host.raspberrypi | 2023-08-19 19:29:29.339 | error | Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.raspberrypi | 2023-08-19 19:29:29.339 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:1003:19) {
host.raspberrypi | 2023-08-19 19:29:29.339 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:819:12)
host.raspberrypi | 2023-08-19 19:29:29.339 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:979:32)
host.raspberrypi | 2023-08-19 19:29:29.339 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
host.raspberrypi | 2023-08-19 19:29:29.339 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1114:14)
host.raspberrypi | 2023-08-19 19:29:29.338 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/@iobroker/adapter-core/build/index.js:21:1)
host.raspberrypi | 2023-08-19 19:29:29.338 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:107:18)
host.raspberrypi | 2023-08-19 19:29:29.338 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:1003:19)
host.raspberrypi | 2023-08-19 19:29:29.338 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:774:27)
host.raspberrypi | 2023-08-19 19:29:29.338 | error | Caught by controller[0]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
host.raspberrypi | 2023-08-19 19:29:29.338 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.zigbee/main.js
host.raspberrypi | 2023-08-19 19:29:29.337 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.zigbee/node_modules/@iobroker/adapter-core/build/index.js
host.raspberrypi | 2023-08-19 19:29:29.337 | error | Caught by controller[0]: Require stack:
host.raspberrypi | 2023-08-19 19:29:29.337 | error | Caught by controller[0]: Error: Cannot find module '@iobroker/types'
host.raspberrypi | 2023-08-19 19:29:29.337 | error | Caught by controller[0]: ^
host.raspberrypi | 2023-08-19 19:29:29.336 | error | Caught by controller[0]: throw err;
host.raspberrypi | 2023-08-19 19:29:29.336 | error | Caught by controller[0]: internal/modules/cjs/loader.js:934
host.raspberrypi | 2023-08-19 19:29:27.364 | info | instance system.adapter.zigbee.0 started with pid 22995
host.raspberrypi | 2023-08-19 19:29:26.824 | error | Cannot set object: null
host.raspberrypi | 2023-08-19 19:29:26.813 | info | "system.adapter.zigbee.0" enabled

**Comment by pankewen** [comment]
Here the log from my update try:




2023-08-18 17:15:01.721  - info: host.iobroker instance system.adapter.zigbee.1 started with pid 1168719
--
2023-08-18 17:15:02.399  - error: host.iobroker Caught by controller[0]: internal/modules/cjs/loader.js:905
2023-08-18 17:15:02.400  - error: host.iobroker Caught by controller[0]:   throw err;
2023-08-18 17:15:02.400  - error: host.iobroker Caught by controller[0]:   ^
2023-08-18 17:15:02.400  - error: host.iobroker Caught by controller[0]: Error: Cannot find module '@iobroker/types'
2023-08-18 17:15:02.400  - error: host.iobroker Caught by controller[0]: Require stack:
2023-08-18 17:15:02.400  - error:  host.iobroker Caught by controller[0]: -  /opt/iobroker/node_modules/iobroker.zigbee/node_modules/@iobroker/adapter-core/build/index.js
2023-08-18 17:15:02.401  - error: host.iobroker Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.zigbee/main.js
2023-08-18 17:15:02.401  - error: host.iobroker Caught by controller[0]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
2023-08-18 17:15:02.401  - error: host.iobroker Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
2023-08-18 17:15:02.401  - error: host.iobroker Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:974:19)
2023-08-18 17:15:02.401  - error: host.iobroker Caught by controller[0]:     at require (internal/modules/cjs/helpers.js:101:18)
2023-08-18 17:15:02.401  - error: host.iobroker Caught by controller[0]:     at Object. (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/@iobroker/adapter-core/build/index.js:21:1)
2023-08-18 17:15:02.401  - error: host.iobroker Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
2023-08-18 17:15:02.402  - error: host.iobroker Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2023-08-18 17:15:02.402  - error: host.iobroker Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:950:32)
2023-08-18 17:15:02.402  - error: host.iobroker Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
2023-08-18 17:15:02.402  - error: host.iobroker Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:974:19) {
2023-08-18 17:15:02.402  - error: host.iobroker Caught by controller[0]:   code: 'MODULE_NOT_FOUND',
2023-08-18 17:15:02.402  - error: host.iobroker Caught by controller[0]:   requireStack: [
2023-08-18 17:15:02.403  - error:  host.iobroker Caught by controller[0]:      '/opt/iobroker/node_modules/iobroker.zigbee/node_modules/@iobroker/adapter-core/build/index.js',
2023-08-18 17:15:02.403  - error: host.iobroker Caught by controller[0]:     '/opt/iobroker/node_modules/iobroker.zigbee/main.js'
2023-08-18 17:15:02.403  - error: host.iobroker Caught by controller[0]:   ]
2023-08-18 17:15:02.403  - error: host.iobroker Caught by controller[0]: }
2023-08-18 17:15:02.403  - error: host.iobroker instance system.adapter.zigbee.1 terminated with code 1 (JS_CONTROLLER_STOPPED)

**Comment by kloppy1984** [comment]
Ah, i have the  node.js 14!

I will be Update it the next days.

Please make a Info in the changelog, that this is necessary.

**Comment by UweLoyal** [comment]
> which node.js version is used? Minimum Node.js 16 might be required

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/5464553/aff44edd-ce74-44f4-ab40-8acb433ee000)

That is the actual Version in ioBroker, no available newer Version for installation shown!
Is the left Version or the right Version in Screenshot that one you require?

Rgds
Uwe

**Comment by pankewen** [comment]
Ok, i was curious: after having updated to Node 18.17.1 the Zigbee adapter could be installed in my iobroker instance.

**Comment by UweLoyal** [comment]
Sorry, aber mein Problem ist nicht gelöst!

Siehe auch hier:
2. Wer sollte updaten?

Aktuell empfehlen wir, bei ioBroker-Neuinstallationen mindestens Node.js 10, besser noch 12.x. zu verwenden. Es sind wenige Adapter bekannt, die nicht mit Node 10/12 funktionieren: Details dazu in https://forum.iobroker.net/topic/30561/status-iobroker-und-node-js-12-x
