### ISSUE TITLE
adapter crashes when trying to remove binding

### ISSUE THREAD

**Issue by FernetMenta** [ioBroker/ioBroker.zigbee#1873]
I just got a new Tint panel "Aris" which seem to have an updated remote:

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/576009/ca8e7d60-b6b6-498b-9027-57276240eee6)

I am able to pair this remote but binding doesn't work. I created 4 consective groups as describer here: https://www.zigbee2mqtt.io/devices/MLI-404011_MLI-404049.html
The binding is created but it doesn't work. Lights added to the groups do not react on commands. When I try to delete the binding, the adapter crashes.

```
2023-09-19 07:52:00.962  - [33mwarn[39m: zigbee.0 (31794) getBindEp called with illegal ep: undefined
2023-09-19 07:52:01.755  - [32minfo[39m: zigbee.0 (31794) Successfully unbound cluster 'genScenes' from '0x540f57fffefdc325' to 'Group 6'
2023-09-19 07:52:01.897  - [32minfo[39m: zigbee.0 (31794) Successfully unbound cluster 'genOnOff' from '0x540f57fffefdc325' to 'Group 6'
2023-09-19 07:52:02.337  - [32minfo[39m: zigbee.0 (31794) Successfully unbound cluster 'genLevelCtrl' from '0x540f57fffefdc325' to 'Group 6'
2023-09-19 07:52:02.348  - [31merror[39m: zigbee.0 (31794) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-09-19 07:52:02.350  - [31merror[39m: zigbee.0 (31794) unhandled promise rejection: Parameter "parentDevice" needs to be of type "string" but type "object" has been passed
2023-09-19 07:52:03.259  - [31merror[39m: zigbee.0 (31794) Error: Parameter "parentDevice" needs to be of type "string" but type "object" has been passed
    at Function.assertString (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:241:19)
    at Zigbee.deleteState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:5882:19)
    at /opt/iobroker/node_modules/iobroker.zigbee/lib/binding.js:263:42
    at Binding.doBindUnbind (/opt/iobroker/node_modules/iobroker.zigbee/lib/binding.js:175:35)
    at /opt/iobroker/node_modules/iobroker.zigbee/lib/binding.js:259:21
2023-09-19 07:52:03.260  - [31merror[39m: zigbee.0 (31794) Parameter "parentDevice" needs to be of type "string" but type "object" has been passed
2023-09-19 07:52:03.300  - [32minfo[39m: zigbee.0 (31794) cleaned everything up...
2023-09-19 07:52:03.459  - [32minfo[39m: zigbee.0 (31794) Zigbee: disabling joining new devices.
2023-09-19 07:52:03.805  - [32minfo[39m: zigbee.0 (31794) terminating
2023-09-19 07:52:03.808  - [33mwarn[39m: zigbee.0 (31794) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-09-19 07:52:04.005  - [32minfo[39m: zigbee.0 (31794) terminating
2023-09-19 07:52:04.584  - [31merror[39m: host.iobroker Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-09-19 07:52:04.587  - [31merror[39m: host.iobroker Caught by controller[1]: Error: Parameter "parentDevice" needs to be of type "string" but type "object" has been passed
2023-09-19 07:52:04.587  - [31merror[39m: host.iobroker Caught by controller[1]:     at Function.assertString (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:241:19)
2023-09-19 07:52:04.588  - [31merror[39m: host.iobroker Caught by controller[1]:     at Zigbee.deleteState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:5882:19)
2023-09-19 07:52:04.588  - [31merror[39m: host.iobroker Caught by controller[1]:     at /opt/iobroker/node_modules/iobroker.zigbee/lib/binding.js:263:42
2023-09-19 07:52:04.588  - [31merror[39m: host.iobroker Caught by controller[1]:     at Binding.doBindUnbind (/opt/iobroker/node_modules/iobroker.zigbee/lib/binding.js:175:35)
2023-09-19 07:52:04.589  - [31merror[39m: host.iobroker Caught by controller[1]:     at /opt/iobroker/node_modules/iobroker.zigbee/lib/binding.js:259:21
2023-09-19 07:52:04.589  - [31merror[39m: host.iobroker instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
```

**Comment by FernetMenta** [comment]
I tested with an older mode of this remote: 
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/576009/a47834a0-082e-4426-9623-22717719bbe1)

Unbinding crashes the zigbee adapter too, but binding to groups do work with this one.

**Comment by arteck** [comment]
also in 1.9.1 ?

**Comment by FernetMenta** [comment]
Sorry for late reply, I was on vacation. 
I don't know. Currently I am trying the zigbee2mqtt adapter with zigbee2mqtt.
