### ISSUE TITLE
Absturz der Instanz beim Löschen eines "ausgeschlossenem" Geräten

### ISSUE THREAD

**Issue by RedGreenChilli** [ioBroker/ioBroker.zigbee#1904]
Hallo zusammen, vielleicht kann mir ja jemand bei meinem Problem helfen:

Adapter Version v1.8.23

Sobald ich eine Exclusion eines Geräts entfernen möchte, stürzt der Adapter ab. Gelöscht wird die Exclusion dabei leider auch nicht.
Hier das zugehörige Logging:
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/38230794/f291c350-9b34-46f8-9adc-46649720b9b3)

> 2023-10-27 12:25:52.899 - error: zigbee.0 (13153) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-10-27 12:25:52.899 - error: zigbee.0 (13153) unhandled promise rejection: Parameter "parentDevice" needs to be of type "string" but type "object" has been passed
2023-10-27 12:25:53.005 - error: zigbee.0 (13153) Error: Parameter "parentDevice" needs to be of type "string" but type "object" has been passed
at Function.assertString (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:241:19)
at Zigbee.deleteState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:5882:19)
at /opt/iobroker/node_modules/iobroker.zigbee/lib/exclude.js:111:34
2023-10-27 12:25:53.006 - error: zigbee.0 (13153) Parameter "parentDevice" needs to be of type "string" but type "object" has been passed
2023-10-27 12:25:53.012 - info: zigbee.0 (13153) cleaned everything up...
2023-10-27 12:25:53.131 - info: zigbee.0 (13153) Zigbee: disabling joining new devices.
2023-10-27 12:25:53.513 - info: zigbee.0 (13153) terminating
2023-10-27 12:25:53.513 - warn: zigbee.0 (13153) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-10-27 12:25:54.059 - error: host.ioBroker Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-10-27 12:25:54.059 - error: host.ioBroker Caught by controller[1]: Error: Parameter "parentDevice" needs to be of type "string" but type "object" has been passed
2023-10-27 12:25:54.059 - error: host.ioBroker Caught by controller[1]: at Function.assertString (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:241:19)
2023-10-27 12:25:54.059 - error: host.ioBroker Caught by controller[1]: at Zigbee.deleteState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:5882:19)
2023-10-27 12:25:54.059 - error: host.ioBroker Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.zigbee/lib/exclude.js:111:34
2023-10-27 12:25:54.060 - error: host.ioBroker instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-10-27 12:25:54.060 - info: host.ioBroker Restart adapter system.adapter.zigbee.0 because enabled

**Comment by funky4t** [comment]
Häng mich hier mal rein, bei mir ist es ein LUX Sensor, aber das gleiche Verhalten wie oben, ebenfalls auf V1.8.23:

Hier mein Log...


```
2023-11-05 00:18:00.396	info	<== Disconnect system.user.admin from ::ffff:192.168.2.146

admin.0
2023-11-05 00:18:00.396	info	<== Disconnect system.user.admin from ::ffff:192.168.2.146

admin.0
2023-11-05 00:18:00.396	info	<== Disconnect system.user.admin from ::ffff:192.168.2.146

admin.0
2023-11-05 00:18:00.396	info	<== Disconnect system.user.admin from ::ffff:192.168.2.146

admin.0
2023-11-05 00:18:00.396	info	<== Disconnect system.user.admin from ::ffff:192.168.2.146
host.brokernew
2023-11-05 00:17:53.000	error	instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.brokernew
2023-11-05 00:17:53.000	error	Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.zigbee/lib/exclude.js:111:34
host.brokernew
2023-11-05 00:17:53.000	error	Caught by controller[0]: at Zigbee.deleteState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:5882:19)
host.brokernew
2023-11-05 00:17:53.000	error	Caught by controller[0]: at Function.assertString (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:241:19)
host.brokernew
2023-11-05 00:17:53.000	error	Caught by controller[0]: Error: Parameter "parentDevice" needs to be of type "string" but type "object" has been passed
host.brokernew
2023-11-05 00:17:52.999	error	Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
host.brokernew
2023-11-05 00:16:11.383	error	instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.brokernew
2023-11-05 00:16:11.383	error	Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.zigbee/lib/exclude.js:111:34
host.brokernew
2023-11-05 00:16:11.383	error	Caught by controller[1]: at Zigbee.deleteState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:5882:19)
host.brokernew
2023-11-05 00:16:11.383	error	Caught by controller[1]: at Function.assertString (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:241:19)
host.brokernew
2023-11-05 00:16:11.383	error	Caught by controller[1]: Error: Parameter "parentDevice" needs to be of type "string" but type "object" has been passed
host.brokernew
2023-11-05 00:16:11.383	error	Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:

```

**Comment by arteck** [comment]
check GIT Version

**Comment by baetzst** [comment]
Ich häng mich hier mal mit dran. V1.8.24
Ausgeschlossene Geräte lassen sich nicht löschen.
 >2023-11-10 11:43:21.247 - error: zigbee.0 (29020) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-11-10 11:43:21.247 - error: zigbee.0 (29020) unhandled promise rejection: Parameter "parentDevice" needs to be of type "string" but type "object" has been passed
2023-11-10 11:43:21.519 - error: zigbee.0 (29020) Error: Parameter "parentDevice" needs to be of type "string" but type "object" has been passed
at Function.assertString (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:241:19)
at Zigbee.deleteState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:5882:19)
at /opt/iobroker/node_modules/iobroker.zigbee/lib/exclude.js:111:34
2023-11-10 11:43:21.519 - error: zigbee.0 (29020) Parameter "parentDevice" needs to be of type "string" but type "object" has been passed
2023-11-10 11:43:21.525 - info: zigbee.0 (29020) cleaned everything up...
2023-11-10 11:43:21.630 - info: zigbee.0 (29020) Zigbee: disabling joining new devices.
2023-11-10 11:43:22.025 - info: zigbee.0 (29020) terminating
2023-11-10 11:43:22.026 - warn: zigbee.0 (29020) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-11-10 11:43:22.637 - error: host.ioBroker Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-11-10 11:43:22.637 - error: host.ioBroker Caught by controller[1]: Error: Parameter "parentDevice" needs to be of type "string" but type "object" has been passed
2023-11-10 11:43:22.637 - error: host.ioBroker Caught by controller[1]: at Function.assertString (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/validator.ts:241:19)
2023-11-10 11:43:22.637 - error: host.ioBroker Caught by controller[1]: at Zigbee.deleteState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:5882:19)
2023-11-10 11:43:22.637 - error: host.ioBroker Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.zigbee/lib/exclude.js:111:34
2023-11-10 11:43:22.638 - error: host.ioBroker instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-11-10 11:43:22.638 - info: host.ioBroker Restart adapter system.adapter.zigbee.0 because enabled

**Comment by RedGreenChilli** [comment]
Still same problem in V1.8.24

**Comment by arteck** [comment]
das ist ein js-controller problem..
