### ISSUE TITLE
Hue white and color ambiance - brightness and colortemp - Send command failed - Cannot read properties of null

### ISSUE THREAD

**Issue by nicoh88** [ioBroker/ioBroker.zigbee#1923]
```
iobroker version zigbee: 1.8.23
iobroker version: 5.0.12
cat /etc/debian_version: 12.1
```

Hue white ambiance E14 & Hue white and color ambiance E26/E27/E14.

```
2023-11-03 10:37:36.310 - debug: zigbee.0 (1388189) SetState_typed called without type
--
2023-11-03 10:37:36.312 - debug: zigbee.0 (1388189) SetState_typed : converting "73" for zigbee.0.00178801039f2fba.brightness from string to number
2023-11-03 10:37:36.319 - debug: zigbee.0 (1388189) User stateChange zigbee.0.00178801039f2fba.brightness {"val":73,"ack":false,"ts":1699004256316,"q":0,"from":"system.adapter.zigbee.0","user":"system.user.admin","lc":1699004256316}
2023-11-03 10:37:36.370 - debug: zigbee.0 (1388189) Change state 'brightness' at device 0x00178801039f2fba type '8718696695203'
2023-11-03 10:37:36.372 - debug: zigbee.0 (1388189) publishFromState : 0x00178801039f2fba 8718696695203
2023-11-03 10:37:36.373 - debug: zigbee.0 (1388189) entity: 0x00178801039f2fba 8718696695203 {"type":"device","device":{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":2,"_type":"Router","_ieeeAddr":"0x00178801039f2fba","_networkAddress":47184,"_manufacturerID":4107,"_endpoints":[{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":11,"profileID":49246,"deviceID":544,"inputClusters":[0,3,4,5,6,8,4096,768],"outputClusters":[25],"deviceNetworkAddress":47184,"deviceIeeeAddress":"0x00178801039f2fba","clusters":{"genBasic":{"attributes":{"modelId":"LTW012","manufacturerName":"Philips","powerSource":1,"zclVersion":1,"appVersion":2,"stackVersion":1,"hwVersion":1,"dateCode":"20230606","swBuildId":"1.108.5"}},"genOnOff":{"attributes":{"onOff":1,"startUpOnOff":0}},"lightingColorCtrl":{"attributes":{"colorTemperature":366,"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":454,"colorMode":2,"startUpColorTemperature":366}},"genLevelCtrl":{"attributes":{"currentLevel":254,"startUpCurrentLevel":254}}},"_binds":[],"_configuredReportings":[],"meta":{},"pendingRequests":{},"sendInProgress":false},{"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":242,"profileID":41440,"deviceID":97,"inputClusters":[33],"outputClusters":[33],"deviceNetworkAddress":47184,"deviceIeeeAddress":"0x00178801039f2fba","clusters":{},"_binds":[],"_configuredReportings":[],"meta":{},"pendingRequests":{},"sendInProgress":false}],"_manufacturerName":"Philips","_powerSource":"Mains (single phase)","_modelID":"LTW012","_applicationVersion":2,"_stackVersion":1,"_zclVersion":1,"_hardwareVersion":1,"_dateCode":"20230606","_softwareBuildID":"1.108.5","_interviewCompleted":true,"_interviewing":false,"_skipDefaultResponse":false,"_skipTimeResponse":false,"meta":{"configured":2},"_lastSeen":1699004195508,"_defaultSendRequestWhen":"immediate","_pendingRequestTimeout":0,"_linkquality":78},"mapped":{"exposes":[{"type":"light","features":[{"type":"binary","name":"state","property":"state","access":7,"value_on":"ON","value_off":"OFF","value_toggle":"TOGGLE","description":"On/off state of this light"},{"type":"numeric","name":"brightness","property":"brightness","access":7,"value_min":0,"value_max":254,"description":"Brightness of this light"},{"type":"numeric","name":"color_temp","property":"color_temp","access":7,"unit":"mired","value_min":153,"value_max":454,"description":"Color temperature of this light","presets":[{"name":"coolest","value":153,"description":"Coolest temperature supported"},{"name":"cool","value":250,"description":"Cool temperature (250 mireds / 4000 Kelvin)"},{"name":"neutral","value":370,"description":"Neutral temperature (370 mireds / 2700 Kelvin)"},{"name":"warm","value":454,"description":"Warm temperature (454 mireds / 2200 Kelvin)"},{"name":"warmest","value":454,"description":"Warmest temperature supported"}]},{"type":"numeric","name":"color_temp_startup","property":"color_temp_startup","access":7,"unit":"mired","value_min":153,"value_max":454,"description":"Color temperature after cold power on of this light","presets":[{"name":"coolest","value":153,"description":"Coolest temperature supported"},{"name":"cool","value":250,"description":"Cool temperature (250 mireds / 4000 Kelvin)"},{"name":"neutral","value":370,"description":"Neutral temperature (370 mireds / 2700 Kelvin)"},{"name":"warm","value":454,"description":"Warm temperature (454 mireds / 2200 Kelvin)"},{"name":"warmest","value":454,"description":"Warmest temperature supported"},{"name":"previous","value":65535,"description":"Restore previous color_temp on cold power on"}]}]},{"type":"enum","name":"power_on_behavior","property":"power_on_behavior","access":7,"values":["off","on","toggle","previous"],"description":"Controls the behavior when the device is powered on after power loss"},{"type":"enum","name":"effect","property":"effect","access":2,"values":["blink","breathe","okay","channel_change","candle","finish_effect","stop_effect","stop_hue_effect"]},{"type":"numeric","name":"linkquality","property":"linkquality","access":1,"unit":"lqi","description":"Link quality (signal strength)","value_min":0,"value_max":255}],"fromZigbee":[{"cluster":"lightingColorCtrl","type":["attributeReport","readResponse"],"options":[{"type":"binary","name":"color_sync","property":"color_sync","access":2,"value_on":true,"value_off":false,"description":"When enabled colors will be synced, e.g. if the light supports both color x/y and color temperature a conversion from color x/y to color temperature will be done when setting the x/y color (default true)."}]},{"cluster":"genOnOff","type":["attributeReport","readResponse"],"options":[{"type":"binary","name":"state_action","property":"state_action","access":2,"value_on":true,"value_off":false,"description":"State actions will also be published as 'action' when true (default false)."}]},{"cluster":"genLevelCtrl","type":["attributeReport","readResponse"]},{"cluster":"genLevelCtrl","type":["attributeReport","readResponse"]},{"cluster":"genBasic","type":["attributeReport","readResponse"]},{"cluster":"genOnOff","type":["attributeReport","readResponse"]}],"toZigbee":[{"key":["state","brightness","brightness_percent","on_time"],"options":[{"type":"numeric","name":"transition","property":"transition","access":2,"value_min":0,"description":"Controls the transition time (in seconds) of on/off, brightness, color temperature (if applicable) and color (if applicable) changes. Defaults to `0` (no transition)."}]},{"key":["color_temp","color_temp_percent"],"options":[{"type":"binary","name":"color_sync","property":"color_sync","access":2,"value_on":true,"value_off":false,"description":"When enabled colors will be synced, e.g. if the light supports both color x/y and color temperature a conversion from color x/y to color temperature will be done when setting the x/y color (default true)."},{"type":"numeric","name":"transition","property":"transition","access":2,"value_min":0,"description":"Controls the transition time (in seconds) of on/off, brightness, color temperature (if applicable) and color (if applicable) changes. Defaults to `0` (no transition)."}]},{"key":["transition"],"attr":[]},{"key":["rate"],"attr":[]},{"key":["brightness_move","brightness_move_onoff"]},{"key":["colortemp_move","color_temp_move"]},{"key":["brightness_step","brightness_step_onoff"],"options":[{"type":"numeric","name":"transition","property":"transition","access":2,"value_min":0,"description":"Controls the transition time (in seconds) of on/off, brightness, color temperature (if applicable) and color (if applicable) changes. Defaults to `0` (no transition)."}]},{"key":["color_temp_step"],"options":[{"type":"numeric","name":"transition","property":"transition","access":2,"value_min":0,"description":"Controls the transition time (in seconds) of on/off, brightness, color temperature (if applicable) and color (if applicable) changes. Defaults to `0` (no transition)."}]},{"key":["color_temp_startup"]},{"key":["level_config"]},{"key":["color_options"]},{"key":["color_mode"]},{"key":["power_on_behavior"]},{"key":["hue_power_on_behavior"]},{"key":["hue_power_on_brightness","hue_power_on_color_temperature","hue_power_on_color"]},{"key":["effect"]},{"key":["scene_store"]},{"key":["scene_recall"]},{"key":["scene_add"]},{"key":["scene_remove"]},{"key":["scene_remove_all"]},{"key":["read"]},{"key":["write"]},{"key":["command"]},{"key":["reset"]}],"ota":{},"meta":{"turnsOffAtBrightness1":true},"zigbeeModel":["LTW012"],"model":"8718696695203","vendor":"Philips","description":"Hue white ambiance E14","options":["[Circular]","[Circular]","[Circular]"]},"endpoint":"[Circular]","endpoints":"[Circular]","name":"0x00178801039f2fba"}
2023-11-03 10:37:36.374 - debug: zigbee.0 (1388189) convert brightness, 185, {"state":true,"transition_time":null,"transition":null,"brightness":185}
2023-11-03 10:37:36.375 - debug: zigbee.0 (1388189) target: {"_events":{},"_eventsCount":0,"_maxListeners":100,"ID":11,"profileID":49246,"deviceID":544,"inputClusters":[0,3,4,5,6,8,4096,768],"outputClusters":[25],"deviceNetworkAddress":47184,"deviceIeeeAddress":"0x00178801039f2fba","clusters":{"genBasic":{"attributes":{"modelId":"LTW012","manufacturerName":"Philips","powerSource":1,"zclVersion":1,"appVersion":2,"stackVersion":1,"hwVersion":1,"dateCode":"20230606","swBuildId":"1.108.5"}},"genOnOff":{"attributes":{"onOff":1,"startUpOnOff":0}},"lightingColorCtrl":{"attributes":{"colorTemperature":366,"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":454,"colorMode":2,"startUpColorTemperature":366}},"genLevelCtrl":{"attributes":{"currentLevel":254,"startUpCurrentLevel":254}}},"_binds":[],"_configuredReportings":[],"meta":{},"pendingRequests":{},"sendInProgress":false}
2023-11-03 10:37:36.377 - error: zigbee.0 (1388189) Send command to 0x00178801039f2fba failed with no error code (undefined)
2023-11-03 10:37:36.378 - debug: zigbee.0 (1388189) Stack trace for null: TypeError: Cannot read properties of null (reading 'toString')
at toNumber (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/utils.ts:509:84)
at Object.getTransition (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/utils.ts:391:28)
at Object.convertSet (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.js:870:38)
at /opt/iobroker/node_modules/iobroker.zigbee/main.js:735:52
at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Same error for `colortemp`. 
`Brightness` and `colortemp` can not be change.

**Comment by nicoh88** [comment]
> also with GIT Version ?

Yes, also with the newest GIT Version.

`iobroker url ioBroker/ioBroker.zigbee --host frida --debug`

```
2023-11-10 15:27:45.313 - error: zigbee.0 (3014184) Send command to 0x00178801039f2fba failed with no error code (undefined)
2023-11-10 15:27:54.302 - error: zigbee.0 (3014184) Send command to 0x00178801039f2fba failed with no error code (undefined)

```

**Comment by MaJaWe1975** [comment]
gibt es hier eine Lösung?

**Comment by arteck** [comment]
installier bitte die 1.8.25 und poste nochmal die Meldung.. ich brauch den Error.. aus dem jetzigen Source

**Comment by MaJaWe1975** [comment]
![zigbee](https://github.com/ioBroker/ioBroker.zigbee/assets/64575410/8d75d28d-bbc3-4a1a-bfd9-5da33a5d7e20)

error: failed with no error code (undefined)

**Comment by arteck** [comment]
zumindest knallt der jetzt nicht mehr...
zeigmal die Info Kachel...

**Comment by MaJaWe1975** [comment]
wo knallt was? 

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/64575410/4a30124a-82bb-44dc-902c-0419f862eac7)

**Comment by MaJaWe1975** [comment]
Vielleicht hilft dir das, bei der 1.18.10 funktionierte noch alles…….?

**Comment by arteck** [comment]
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/6681528/656463eb-ed9d-46ff-87ae-09607489a7da)
das hier brauch ich

**Comment by MaJaWe1975** [comment]
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/64575410/612ca387-f213-4d65-bd6d-0f8eda7581b3)

**Comment by arteck** [comment]
kannst du mal schauen mit der jetzigen GIT version

**Comment by MaJaWe1975** [comment]
bin unsicher ob ich es richtig installiert habe, es ist aber immer noch die version 25.....?

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/64575410/1e75bdb6-2fc5-43e1-b9cc-324c1b3120bb)

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/64575410/6ea5182f-2ab8-4a42-be9c-4efb4530f0ce)

**Comment by MaJaWe1975** [comment]
gleiche Problem

![image](https://github.com/ioBroker/ioBroker.zigbee/assets/64575410/59cab6a3-da57-4b95-82c7-138a7dc24c1c)

**Comment by MaJaWe1975** [comment]
gleiche Proplem bei 1.9.0

**Comment by arteck** [comment]
works with 1.9.1

**Comment by nicoh88** [comment]
> Hue white ambiance E14 & Hue white and color ambiance E26/E27/E14.

Doesn't work for Hue white ambiance E14 & Hue white and color ambiance E26/E27/E14.

<img width="364" alt="Bildschirmfoto 2023-12-25 um 07 40 47" src="https://github.com/ioBroker/ioBroker.zigbee/assets/264264/2c60e1f8-ecbf-4565-b8b7-8d31bdc8a16e">
<img width="947" alt="Bildschirmfoto 2023-12-25 um 07 40 58" src="https://github.com/ioBroker/ioBroker.zigbee/assets/264264/6917d678-f13f-42d4-8df9-956dc374c5ac">
<img width="858" alt="Bildschirmfoto 2023-12-25 um 07 41 18" src="https://github.com/ioBroker/ioBroker.zigbee/assets/264264/3533c728-b5a1-4e45-8dc3-6fbf60643d91">
