### ISSUE TITLE
TS011F_plug_1 log reports errors, always in config mode

### ISSUE THREAD

**Issue by Kami0612** [ioBroker/ioBroker.zigbee#1946]
**The plug works fine, but reports in the log every two minutes errors and is always in configuration mode.**

2023-11-19 14:31:46.048 - info: zigbee.0 (1909954) Configuring 0xa4c13848cd315038 TS011F

2023-11-19 14:31:46.400 - error: zigbee.0 (1909954) DeviceConfigure:Failed to DeviceConfigure.configure 0xa4c13848cd315038 TS011F (Error: ConfigureReporting 0xa4c13848cd315038/1 haElectricalMeasurement([{"attribute":"activePower","minimumReportInterval":5,"maximumReportInterval":3600,"reportableChange":10}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'INVALID_DATA_TYPE')
at Endpoint.checkStatus (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:421:28)
at Endpoint.configureReporting (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:762:22)
at runMicrotasks ()
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at Object.activePower (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:204:5)
at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/devices/tuya.ts:2917:13)
at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:136:13)
at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:113:21))

2023-11-19 14:33:21.191 - info: zigbee.0 (1909954) Configuring 0xa4c13848cd315038 TS011F

2023-11-19 14:33:21.624 - error: zigbee.0 (1909954) DeviceConfigure:Failed to DeviceConfigure.configure 0xa4c13848cd315038 TS011F (Error: ConfigureReporting 0xa4c13848cd315038/1 haElectricalMeasurement([{"attribute":"activePower","minimumReportInterval":5,"maximumReportInterval":3600,"reportableChange":10}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'INVALID_DATA_TYPE')
at Endpoint.checkStatus (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:421:28)
at Endpoint.configureReporting (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:762:22)
at runMicrotasks ()
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at Object.activePower (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:204:5)
at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/devices/tuya.ts:2917:13)
at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:136:13)
at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:113:21))

2023-11-19 14:35:55.766 - info: zigbee.0 (1909954) Configuring 0xa4c13848cd315038 TS011F

**Comment by arteck** [comment]
works in 1.9.1
