### ISSUE TITLE
Adapter crashes when ikea bulb is started (after hard power off)

### ISSUE THREAD

**Issue by ChrisSmartHome** [ioBroker/ioBroker.zigbee#1958]
When ever the ikea LED2005R5 are started from power off, the following error is thrown and the adapter crashes.

host.raspberrypi | 2023-11-27 12:34:20.364 | error | instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.raspberrypi | 2023-11-27 12:34:20.364 | error | Caught by controller[2]: at processImmediate (node:internal/timers:478:21)
host.raspberrypi | 2023-11-27 12:34:20.364 | error | Caught by controller[2]: at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/lib/groups.js:329:29)
host.raspberrypi | 2023-11-27 12:34:20.364 | error | Caught by controller[2]: at Array.forEach (<anonymous>)
host.raspberrypi | 2023-11-27 12:34:20.364 | error | Caught by controller[2]: at /opt/iobroker/node_modules/iobroker.zigbee/lib/groups.js:333:51
host.raspberrypi | 2023-11-27 12:34:20.363 | error | Caught by controller[2]: TypeError: Cannot read properties of undefined (reading 'deleteDeviceStates')
host.raspberrypi | 2023-11-27 12:34:20.363 | error | Caught by controller[1]: at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:591:22)
host.raspberrypi | 2023-11-27 12:34:20.363 | error | Caught by controller[1]: at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:244:54)
host.raspberrypi | 2023-11-27 12:34:20.363 | error | Caught by controller[1]: at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:25:18)
host.raspberrypi | 2023-11-27 12:34:20.363 | error | Caught by controller[1]: at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:43:26)
host.raspberrypi | 2023-11-27 12:34:20.363 | error | Caught by controller[1]: at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/devices/ikea.ts:41:36)
host.raspberrypi | 2023-11-27 12:34:20.363 | error | Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'color_options')
host.raspberrypi | 2023-11-27 12:34:20.362 | error | Caught by controller[1]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
host.raspberrypi | 2023-11-27 12:34:20.362 | error | Caught by controller[0]: at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:591:22)
host.raspberrypi | 2023-11-27 12:34:20.362 | error | Caught by controller[0]: at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:244:54)
host.raspberrypi | 2023-11-27 12:34:20.362 | error | Caught by controller[0]: at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:25:18)
host.raspberrypi | 2023-11-27 12:34:20.362 | error | Caught by controller[0]: at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:43:26)
host.raspberrypi | 2023-11-27 12:34:20.362 | error | Caught by controller[0]: at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/devices/ikea.ts:41:36)
host.raspberrypi | 2023-11-27 12:34:20.361 | error | Caught by controller[0]: TypeError: Cannot read properties of undefined (reading 'color_options')
host.raspberrypi | 2023-11-27 12:34:20.360 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
zigbee.0 | 2023-11-27 12:34:20.096 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee.0 | 2023-11-27 12:34:20.094 | info | terminating
zigbee.0 | 2023-11-27 12:34:19.665 | error | Cannot read properties of undefined (reading 'deleteDeviceStates')
zigbee.0 | 2023-11-27 12:34:19.665 | error | TypeError: Cannot read properties of undefined (reading 'deleteDeviceStates') at /opt/iobroker/node_modules/iobroker.zigbee/lib/groups.js:333:51 at Array.forEach (<anonymous>) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/lib/groups.js:329:29) at processImmediate (node:internal/timers:478:21)
zigbee.0 | 2023-11-27 12:34:19.664 | error | uncaught exception: Cannot read properties of undefined (reading 'deleteDeviceStates')
zigbee.0 | 2023-11-27 12:34:19.646 | info | Zigbee: disabling joining new devices.
zigbee.0 | 2023-11-27 12:34:19.499 | info | cleaned everything up...
zigbee.0 | 2023-11-27 12:34:19.483 | error | Cannot read properties of undefined (reading 'color_options')
zigbee.0 | 2023-11-27 12:34:19.483 | error | TypeError: Cannot read properties of undefined (reading 'color_options') at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/devices/ikea.ts:41:36) at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:43:26) at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:25:18) at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:244:54) at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:591:22)
zigbee.0 | 2023-11-27 12:34:19.479 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'color_options')
zigbee.0 | 2023-11-27 12:34:19.478 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2023-11-27 12:34:19.464 | info | Device '0x90395efffe163ccc' announced itself
zigbee.0 | 2023-11-27 12:34:19.416 | error | Cannot read properties of undefined (reading 'color_options')
zigbee.0 | 2023-11-27 12:34:19.415 | error | TypeError: Cannot read properties of undefined (reading 'color_options') at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/devices/ikea.ts:41:36) at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:43:26) at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:25:18) at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:244:54) at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:591:22)
zigbee.0 | 2023-11-27 12:34:19.350 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'color_options')
zigbee.0 | 2023-11-27 12:34:19.349 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
 

<br class="Apple-interchange-newline">

**Comment by arteck** [comment]
also with the GIT version ?

**Comment by ChrisSmartHome** [comment]
yes, just switched to the git version again and the adapter still crashes and throws the same errors

**Comment by Diginix** [comment]
Same here this night with v1.9.0. Until 1.8.25 it never happened.
Device 0x4c5bb3fffe20a5aa is an IKEA LED2104R3 GU10 Spot

```
2023-12-23 02:49:16.254 - info: zigbee.0 (1132661) Device '0x4c5bb3fffe20a5aa' announced itself
2023-12-23 02:49:16.257 - error: zigbee.0 (1132661) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-12-23 02:49:16.257 - error: zigbee.0 (1132661) unhandled promise rejection: Cannot read properties of undefined (reading 'color_options')
2023-12-23 02:49:16.305 - error: zigbee.0 (1132661) TypeError: Cannot read properties of undefined (reading 'color_options')
at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/devices/ikea.ts:41:36)
at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:43:26)
at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:25:18)
at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:263:54)
at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:610:22)
2023-12-23 02:49:16.306 - error: zigbee.0 (1132661) Cannot read properties of undefined (reading 'color_options')
2023-12-23 02:49:16.319 - info: zigbee.0 (1132661) cleaned everything up...
2023-12-23 02:49:16.413 - info: zigbee.0 (1132661) Zigbee: disabling joining new devices.
2023-12-23 02:49:16.820 - info: zigbee.0 (1132661) terminating
2023-12-23 02:49:16.821 - warn: zigbee.0 (1132661) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-12-23 02:49:17.451 - error: host.iobroker Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-12-23 02:49:17.458 - error: host.iobroker Caught by controller[0]: TypeError: Cannot read properties of undefined (reading 'color_options')
2023-12-23 02:49:17.459 - error: host.iobroker Caught by controller[0]: at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/devices/ikea.ts:41:36)
2023-12-23 02:49:17.459 - error: host.iobroker Caught by controller[0]: at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:43:26)
2023-12-23 02:49:17.459 - error: host.iobroker Caught by controller[0]: at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:25:18)
2023-12-23 02:49:17.459 - error: host.iobroker Caught by controller[0]: at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:263:54)
2023-12-23 02:49:17.460 - error: host.iobroker Caught by controller[0]: at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:610:22)
2023-12-23 02:49:17.460 - error: host.iobroker instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-12-23 02:49:50.271 - info: zigbee.0 (1159588) starting. Version 1.9.0 in /opt/iobroker/node_modules/iobroker.zigbee, node: v18.17.1, js-controller: 5.0.17
2023-12-23 02:49:50.348 - info: zigbee.0 (1159588) delete old Backup files. keep only last 10
2023-12-23 02:49:50.350 - info: zigbee.0 (1159588) Starting Zigbee npm ...
2023-12-23 02:49:50.536 - info: zigbee.0 (1159588) Installed Version: iobroker.zigbee@1.9.0
```

**Comment by arteck** [comment]
check 1.9.1 plz

**Comment by dimaiv7** [comment]
Immer noch da.

`<html><body>

2023-12-26 14:46:12.586  - info: zigbee.0 (1836) Device '0x90fd9ffffe049ad1' announced itself
--
2023-12-26 14:46:12.590  - error:  zigbee.0 (1836) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
2023-12-26 14:46:12.590  - error: zigbee.0 (1836) unhandled promise rejection: Cannot read properties of undefined (reading 'color_options')
2023-12-26 14:46:12.623  - error: zigbee.0 (1836) TypeError: Cannot read properties of undefined (reading 'color_options')
at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/devices/ikea.ts:41:36)
at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:43:26)
at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:25:18)
at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:263:54)
at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:610:22)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-12-26 14:46:12.623  - error: zigbee.0 (1836) Cannot read properties of undefined (reading 'color_options')
2023-12-26 14:46:12.633  - info: zigbee.0 (1836) cleaned everything up...
2023-12-26 14:46:12.722  - info: zigbee.0 (1836) Zigbee: disabling joining new devices.
2023-12-26 14:46:13.133  - info: zigbee.0 (1836) terminating
2023-12-26 14:46:13.134  - warn: zigbee.0 (1836) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-12-26 14:46:13.687  - error:  host.IoBroker Caught by controller[1]: This error originated either by  throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch(). The promise  rejected with the reason:
2023-12-26 14:46:13.687  - error: host.IoBroker Caught by controller[2]: TypeError: Cannot read properties of undefined (reading 'color_options')
2023-12-26 14:46:13.687  - error:  host.IoBroker Caught by controller[2]:     at Object.bulbOnEvent [as  onEvent]  (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/devices/ikea.ts:41:36)
2023-12-26 14:46:13.687  - error:  host.IoBroker Caught by controller[2]:     at DeviceEvent.callOnEvent  (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:43:26)
2023-12-26 14:46:13.687  - error:  host.IoBroker Caught by controller[2]:     at DeviceEvent.onZigbeeEvent  (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:25:18)
2023-12-26 14:46:13.687  - error:  host.IoBroker Caught by controller[2]:     at  ZigbeeController.callExtensionMethod  (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:263:54)
2023-12-26 14:46:13.687  - error:  host.IoBroker Caught by controller[2]:     at  ZigbeeController.handleDeviceAnnounce  (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:610:22)
2023-12-26 14:46:13.687  - error: host.IoBroker Caught by controller[2]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-12-26 14:46:13.687  - error: host.IoBroker instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-12-26 14:46:13.687  - info: host.IoBroker Restart adapter system.adapter.zigbee.0 because enabled
2023-12-26 14:46:43.718  - info: host.IoBroker instance system.adapter.zigbee.0 started with pid 2011
2023-12-26 14:46:44.409  - info: host.IoBroker "system.adapter.zigbee.0" disabled


</body>
</html>`

**Comment by ChrisSmartHome** [comment]
same here, error is still occurring

**Comment by earl80** [comment]
And here

**Comment by oOmaXYmOo** [comment]
Hello, the error still exists.

Version: 1.9.5

Leuchtmittel: 
![image](https://github.com/ioBroker/ioBroker.zigbee/assets/155292591/0d6876b2-95a7-4aca-9e53-cfcbf4c69a06)


LOG:
```
2023-12-31 09:20:08.727 - info: zigbee.0 (2262403) Device '0xb4e3f9fffe5d9221' announced itself
--
2023-12-31 09:20:08.731 - error: zigbee.0 (2262403) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-12-31 09:20:08.731 - error: zigbee.0 (2262403) unhandled promise rejection: Cannot read properties of undefined (reading 'color_options')
2023-12-31 09:20:08.731 - error: zigbee.0 (2262403) TypeError: Cannot read properties of undefined (reading 'color_options')
at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices/ikea.js:67:36)
at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:43:26)
at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:25:18)
at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:263:54)
at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:610:22)
2023-12-31 09:20:08.732 - error: zigbee.0 (2262403) Cannot read properties of undefined (reading 'color_options')
2023-12-31 09:20:08.734 - info: zigbee.0 (2262403) cleaned everything up...
2023-12-31 09:20:08.761 - info: zigbee.0 (2262403) Zigbee: disabling joining new devices.
2023-12-31 09:20:09.234 - info: zigbee.0 (2262403) terminating
2023-12-31 09:20:09.235 - warn: zigbee.0 (2262403) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-12-31 09:20:09.738 - warn: zigbee.0 (2262403) get state error: Connection is closed.
2023-12-31 09:20:09.799 - error: host.ioBroker instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
```

**Comment by arteck** [comment]
check GIT version

**Comment by ChrisSmartHome** [comment]
updated and it works for me!
Thank you a lot and have a great New Year!

**Comment by oOmaXYmOo** [comment]
Just updated and it works for me too!
Thank you for the change today and have a great new year!
