### ISSUE TITLE
SONOFF snzb-02d pairing failed

### ISSUE THREAD

**Issue by Hobbyflyer** [ioBroker/ioBroker.zigbee#1977]
iobroker / cc26x2R1
Node.js: v18.17.1
NPM: 9.6.7
Datenträgergröße: 7.8 GB
Freier Festplattenspeicher: 3.4 GB
Aktive Instanzen: 28

iobroker & adapter up2date

zigbee adapter Version  .24

device sonoff snzb-02d
Reproduce: Added several zigbee devices. 
Already 3 x sonoff snzb-2d connected, adding 4. creates error. Adding other device work

Error in Log :
ziggbee.0 | 2023-12-07 17:56:07.163 | error | DatabaseEntry with ID '3' already exists
zigbee.0 | 2023-12-07 17:56:07.163 | error | Error: DatabaseEntry with ID '3' already exists at Database.insert (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/database.ts:40:19) at Device.undelete (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/device.ts:438:25) at Controller.onDeviceJoined (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/controller.ts:555:20) at ZStackAdapter.emit (node:events:514:28) at ZStackAdapter.emit (node:domain:489:12) at ZStackAdapter.onZnpRecieved (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:762:22) at Znp.emit (node:events:514:28) at Znp.emit (node:domain:489:12) at Znp.onUnpiParsed (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:108:18) at Parser.emit (node:events:514:28)
zigbee.0 | 2023-12-07 17:56:07.125 | error | unhandled promise rejection: DatabaseEntry with ID '3' already exists
zigbee.0 | 2023-12-07 17:56:07.125 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

**Comment by Hobbyflyer** [comment]
maybe like this https://github.com/Koenkk/zigbee2mqtt/issues/15859

**Comment by Hobbyflyer** [comment]
After 20 attemps....it works...
