### ISSUE TITLE
"TRADFRI bulb GU10 WS 345lm" not described in statesMapping

### ISSUE THREAD

**Issue by Pittini** [ioBroker/ioBroker.zigbee#1990]
Hi,
I'm not sure if its an error or an missing definition, but if I try to pair the "TRADFRI bulb GU10 WS 345lm", it pairs, but has no functionality. Log says:

```
zigbee.0
2023-12-16 16:17:21.795	info	Successfully interviewed '0x287681fffe817f2d', device has successfully been paired

zigbee.0
2023-12-16 16:17:20.838	error	Device 0x287681fffe817f2d "TRADFRI bulb GU10 WS 345lm" not described in statesMapping.

zigbee.0
2023-12-16 16:17:20.063	info	Device '0x287681fffe817f2d' announced itself

zigbee.0
2023-12-16 16:17:20.033	info	Starting interview of '0x287681fffe817f2d'

zigbee.0
2023-12-16 16:16:36.454	info	Zigbee: allowing new devices to join.
```

**Comment by Pittini** [comment]
After some trys, the bulb was recognized correctly and works as it should, but after powerloss and repowering the bulb announcement kills the zigbee instance. Trying to pair another one, leads again to an paired, but unrecognized device like described in my first post.

```
host.iobroker | 2023-12-23 16:35:40.214 | warn | Do not restart adapter system.adapter.zigbee.0 because restart loop detected
-- | -- | -- | --
host.iobroker | 2023-12-23 16:35:40.214 | info | Restart adapter system.adapter.zigbee.0 because enabled
host.iobroker | 2023-12-23 16:35:40.214 | error | instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.iobroker | 2023-12-23 16:35:40.214 | error | Caught by controller[0]: at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:610:22)
host.iobroker | 2023-12-23 16:35:40.214 | error | Caught by controller[0]: at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:263:54)
host.iobroker | 2023-12-23 16:35:40.214 | error | Caught by controller[0]: at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:25:18)
host.iobroker | 2023-12-23 16:35:40.214 | error | Caught by controller[0]: at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:43:26)
host.iobroker | 2023-12-23 16:35:40.214 | error | Caught by controller[0]: at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/devices/ikea.ts:41:36)
host.iobroker | 2023-12-23 16:35:40.214 | error | Caught by controller[0]: TypeError: Cannot read properties of undefined (reading 'color_options')
host.iobroker | 2023-12-23 16:35:40.213 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
zigbee.0 | 2023-12-23 16:35:39.536 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee.0 | 2023-12-23 16:35:39.535 | info | terminating
zigbee.0 | 2023-12-23 16:35:39.181 | info | Zigbee: disabling joining new devices.
zigbee.0 | 2023-12-23 16:35:39.035 | info | cleaned everything up...
zigbee.0 | 2023-12-23 16:35:39.030 | error | Cannot read properties of undefined (reading 'color_options')
zigbee.0 | 2023-12-23 16:35:39.030 | error | TypeError: Cannot read properties of undefined (reading 'color_options') at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/devices/ikea.ts:41:36) at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:43:26) at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:25:18) at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:263:54) at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:610:22)
zigbee.0 | 2023-12-23 16:35:39.000 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'color_options')
zigbee.0 | 2023-12-23 16:35:39.000 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2023-12-23 16:35:38.998 | info | Device '0x287681fffe817f2d' announced itself

```

**Comment by arteck** [comment]
check 1.9.1..when not i nedd the log

**Comment by Pittini** [comment]
> check 1.9.1..when not i nedd the log

I have tryed to pair them and got again an zigbee instance kill. After instance restart , see log2


```
host.iobroker | 2023-12-24 16:35:05.064 | info | instance system.adapter.zigbee.0 started with pid 324252
-- | -- | -- | --
host.iobroker | 2023-12-24 16:34:34.984 | info | Restart adapter system.adapter.zigbee.0 because enabled
host.iobroker | 2023-12-24 16:34:34.984 | error | instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.iobroker | 2023-12-24 16:34:34.984 | error | Caught by controller[0]: at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:610:22)
host.iobroker | 2023-12-24 16:34:34.984 | error | Caught by controller[0]: at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:263:54)
host.iobroker | 2023-12-24 16:34:34.984 | error | Caught by controller[0]: at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:25:18)
host.iobroker | 2023-12-24 16:34:34.984 | error | Caught by controller[0]: at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:43:26)
host.iobroker | 2023-12-24 16:34:34.984 | error | Caught by controller[0]: at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/devices/ikea.ts:41:36)
host.iobroker | 2023-12-24 16:34:34.984 | error | Caught by controller[0]: TypeError: Cannot read properties of undefined (reading 'color_options')
host.iobroker | 2023-12-24 16:34:34.984 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
zigbee.0 | 2023-12-24 16:34:34.311 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee.0 | 2023-12-24 16:34:34.310 | info | terminating
zigbee.0 | 2023-12-24 16:34:33.982 | warn | download icon from https://www.zigbee2mqtt.io/images/devices/LED2005R5.jpg saved into /opt/iobroker/node_modules/iobroker.zigbee/admin/img/LED2005R5.png
zigbee.0 | 2023-12-24 16:34:33.961 | info | Zigbee: disabling joining new devices.
zigbee.0 | 2023-12-24 16:34:33.809 | info | cleaned everything up...
zigbee.0 | 2023-12-24 16:34:33.803 | error | Cannot read properties of undefined (reading 'color_options')
zigbee.0 | 2023-12-24 16:34:33.801 | error | TypeError: Cannot read properties of undefined (reading 'color_options') at Object.bulbOnEvent [as onEvent] (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/devices/ikea.ts:41:36) at DeviceEvent.callOnEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:43:26) at DeviceEvent.onZigbeeEvent (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceEvent.js:25:18) at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:263:54) at ZigbeeController.handleDeviceAnnounce (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:610:22)
zigbee.0 | 2023-12-24 16:34:33.752 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'color_options')
zigbee.0 | 2023-12-24 16:34:33.752 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2023-12-24 16:34:33.750 | info | Device '0x287681fffe8257db' announced itself
zigbee.0 | 2023-12-24 16:34:32.677 | info | Device '0x287681fffe817f2d' announced itself
zigbee.0 | 2023-12-24 16:34:32.504 | info | Starting interview of '0x287681fffe8257db'
zigbee.0 | 2023-12-24 16:34:32.483 | info | Starting interview of '0x287681fffe817f2d'
zigbee.0 | 2023-12-24 16:34:07.852 | info | Zigbee: allowing new devices to join.

```

Log2


```
zigbee.0 | 2023-12-24 16:37:44.376 | warn | download icon TRADFRI bulb GU10 WS 345lm for undefined Device not available. Check your devices.
-- | -- | -- | --
zigbee.0 | 2023-12-24 16:35:10.003 | error | Device 0x287681fffe817f2d "undefined" not described in statesMapping.
zigbee.0 | 2023-12-24 16:35:09.140 | error | Device 0x287681fffe8257db "undefined" not described in statesMapping.
zigbee.0 | 2023-12-24 16:35:08.651 | info | debug devices set to []
zigbee.0 | 2023-12-24 16:35:08.547 | warn | download icon TRADFRI bulb GU10 WS 345lm for undefined Device not available. Check your devices.
zigbee.0 | 2023-12-24 16:35:08.511 | warn | download icon Decke Kueche 1 for undefined Device not available. Check your devices.
zigbee.0 | 2023-12-24 16:35:08.464 | info | Zigbee started
zigbee.0 | 2023-12-24 16:35:08.463 | info | 0x287681fffe8257db (addr 21448): Not supported (model undefined)(Unknown)
```

Objectlist looks like this:
![Screenshot 2023-12-24 165222](https://github.com/ioBroker/ioBroker.zigbee/assets/51408942/f06eabc9-7d8f-48b5-9692-f8aa9583b3ca)

Zigbee view is strange, one has controls, the other one not:

![Screenshot 2023-12-24 165423](https://github.com/ioBroker/ioBroker.zigbee/assets/51408942/c5087b6c-8537-4af9-b6ed-34c655c381e7)
![Screenshot 2023-12-24 165441](https://github.com/ioBroker/ioBroker.zigbee/assets/51408942/dd1163ca-f113-48f8-8ff9-06fee8603365)

Different from the old (1.8.5) behaviour is, the zigbee instance isnt killed after power off/on.

**Comment by Pittini** [comment]
Works fine with 1.9.6, thank you
