### ISSUE TITLE
Geträt Silvercrest 3 gang switch, with 4 USB geht mit version 1.8.25 nicht mehr

### ISSUE THREAD

**Issue by blade1979** [ioBroker/ioBroker.zigbee#1994]
Nach Update auf  1.8.25 lässt sich Geträt Silvercrest 3 gang switch, with 4 USB (EU, FR, CZ, BS) ([HG06338) nicht mehr benutzen.

**Comment by Sundancer78** [comment]
das muss ich leider bestätigen, zurück auf 1.8.24 funktionieren diese wieder

**Comment by mh-hdl** [comment]
kann ich ebenfalls bestätigen...bin ggw. wieder bei 1.8.23. Damit geht's (auch)!

**Comment by Fortune95** [comment]
Kann ich auch bestätigen, bin wieder auf 1.8.24.

**Comment by Moko0815** [comment]
Gleiches hier. Danke für den Tip mit Version1.8.24.

**Comment by Fortune95** [comment]
<html><body>

2023-12-21 04:54:24.616  - error: zigbee.1 (84381) Send command to 0xbc33acfffe32ff7b failed with no error code (undefined)
--
2023-12-21 04:54:24.617  - debug: zigbee.1 (84381) Stack trace for null: Error: 'null' not allowed, choose between: toggle,off,on
at Object.validateValue (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/utils.ts:444:15)
at Object.convertSet (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:30:19)
at /opt/iobroker/node_modules/iobroker.zigbee/main.js:735:52


</body>
</html>

**Comment by arteck** [comment]
die info kachel brauche ich

**Comment by blade1979** [comment]
![Screenshot 2023-12-22 102813](https://github.com/ioBroker/ioBroker.zigbee/assets/15235628/2a8932e4-af33-4b7f-bd97-1b4b05fa00fc)

**Comment by arteck** [comment]
installier mal die GIT version

**Comment by Fortune95** [comment]
Damit funktioniert es! Vielen Dank!!! :-)

**Comment by blade1979** [comment]
mit 1.9 gehts, Danke
