### ISSUE TITLE
iobroker.zigbee does not completely exit when shut down

### ISSUE THREAD

**Issue by asgothian** [ioBroker/ioBroker.zigbee#200]
As of today (at least), i have an issue shutting down the adapter. This happens with the current version (commit from today), but also with the previous version (commit from FEB16.) I am not experienced enough to download older versions to see which change causes this.

The effect:
Starting the first instance seems to work fine :

`root@ioTinker:~# ps -ax | grep -e zigbee`
`11916 ?        Sl     0:05 io.zigbee.0`
`11977 pts/0    S+     0:00 grep -e zigbee`

If i try to shut down this instance (through admin) The adapter in the admin interface will be grayed out, but it does not seem to terminate:
`
`root@ioTinker:~# ps -ax | grep -e zigbee`
`11916 ?        Sl     0:06 io.zigbee.0`
`11979 pts/0    S+     0:00 grep -e zigbee`
`
An attempt to start a second instance seems to work fine, but zigbee attempting to change a data object in ioBroker causes the adapter to crash. From here on, it is impossible to get the system working using the admin interface. The io.zigbee.0 processes just keep piling up

`root@ioTinker:~# ps -ax | grep -e zigbee`
`11916 ?        Sl     0:06 io.zigbee.0`
`11980 ?        Sl     0:04 io.zigbee.0`
`11996 ?        Sl     0:01 /usr/bin/node /opt/iobroker/node_modules/iobroker.zigbee/main.js 0 info`
`12013 ?        Sl     0:04 io.zigbee.0`
`12037 pts/0    S+     0:00 grep -e zigbee
`

After terminating all processes, the adapter can be restarted and seems to operate normally.

**Comment by asgothian** [comment]
Follow-Up: with 2 copies running, control of zigbee objects seems possible, but each event may cause a crash from the underlying system:


`zigbee.0	2019-02-17 17:33:53.236	warn	Reconnection to DB.`
`zigbee.0	2019-02-17 17:33:53.234	warn	Reconnection to DB.`
`zigbee.0	2019-02-17 17:33:22.867	error	exception by stop: callback is not defined`
`zigbee.0	2019-02-17 17:33:22.867	error	at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)`
`zigbee.0	2019-02-17 17:33:22.867	error	at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:345:8)`
`zigbee.0	2019-02-17 17:33:22.867	error	at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
`zigbee.0	2019-02-17 17:33:22.867	error	at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)`
`zigbee.0	2019-02-17 17:33:22.867	error	at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:244:12)`
`zigbee.0	2019-02-17 17:33:22.867	error	at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:319:9)`
`zigbee.0	2019-02-17 17:33:22.867	error	at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/main.js:108:17)`
`zigbee.0	2019-02-17 17:33:22.867	error	at collectOptions (/opt/iobroker/node_modules/iobroker.zigbee/main.js:1162:15)`
`zigbee.0	2019-02-17 17:33:22.867	error	at options (/opt/iobroker/node_modules/iobroker.zigbee/main.js:109:21)`
`zigbee.0	2019-02-17 17:33:22.867	error	at publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:865:28)`
`zigbee.0	2019-02-17 17:33:22.867	error	TypeError: Cannot read property 'getDevice' of undefined`
`zigbee.0	2019-02-17 17:33:22.866	error	uncaught exception: Cannot read property 'getDevice' of undefined`
