### ISSUE TITLE
Adapter Zigbee startet unerwartet neu

### ISSUE THREAD

**Issue by LastPerfectTobi** [ioBroker/ioBroker.zigbee#2008]
Die Version Zigbee 1.9.1 bringt sporadisch folgende Errors. 

```
2023-12-25 11:35:58.539 - error: zigbee.0 (5003) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-12-25 11:35:58.556 - error: zigbee.0 (5003) unhandled promise rejection: Cannot read properties of null (reading 'hasOwnProperty')
2023-12-25 11:35:58.563 - error: zigbee.0 (5003) TypeError: Cannot read properties of null (reading 'hasOwnProperty')
at /opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:613:62
at Array.filter ()
at StatesController.publishToState (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:613:34)
2023-12-25 11:35:58.563 - error: zigbee.0 (5003) Cannot read properties of null (reading 'hasOwnProperty')
2023-12-25 11:35:59.087 - warn: zigbee.0 (5003) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-12-25 11:35:59.859 - error: host.raspberrypi Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-12-25 11:35:59.860 - error: host.raspberrypi Caught by controller[1]: TypeError: Cannot read properties of null (reading 'hasOwnProperty')
2023-12-25 11:35:59.860 - error: host.raspberrypi Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:613:62
2023-12-25 11:35:59.861 - error: host.raspberrypi Caught by controller[1]: at Array.filter ()
2023-12-25 11:35:59.861 - error: host.raspberrypi Caught by controller[1]: at StatesController.publishToState (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:613:34)
2023-12-25 11:35:59.861 - error: host.raspberrypi instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-12-25 11:35:59.861 - info: host.raspberrypi Restart adapter system.adapter.zigbee.0 because enabled
2023-12-25 11:36:30.187 - info: host.raspberrypi instance system.adapter.zigbee.0 started with pid 23034

```

Startet aber danach neu und alles funktioniert auch ohne Probleme.

**Comment by arteck** [comment]
nimm die 1.9.3 von GIT

**Comment by LastPerfectTobi** [comment]
1.9.3 hab ich gerade installiert, 
aber das Problem ist weiterhin da. 
Mir ist aufgefallen, wenn ich einen Aqara Switch Button drücke, dann kommt dieser Fehler. 


```

2023-12-26 10:47:55.021 - error: zigbee.0 (7158) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-12-26 10:47:55.022 - error: zigbee.0 (7158) unhandled promise rejection: Cannot read properties of null (reading 'hasOwnProperty')
2023-12-26 10:47:55.024 - error: zigbee.0 (7158) TypeError: Cannot read properties of null (reading 'hasOwnProperty')
at /opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:628:62
at Array.filter ()
at StatesController.publishToState (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:628:34)
2023-12-26 10:47:55.025 - error: zigbee.0 (7158) Cannot read properties of null (reading 'hasOwnProperty')
2023-12-26 10:47:55.538 - warn: zigbee.0 (7158) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-12-26 10:47:56.247 - error: host.raspberrypi Caught by controller[1]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-12-26 10:47:56.249 - error: host.raspberrypi Caught by controller[2]: TypeError: Cannot read properties of null (reading 'hasOwnProperty')
2023-12-26 10:47:56.249 - error: host.raspberrypi Caught by controller[2]: at /opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:628:62
2023-12-26 10:47:56.249 - error: host.raspberrypi Caught by controller[2]: at Array.filter ()
2023-12-26 10:47:56.249 - error: host.raspberrypi Caught by controller[2]: at StatesController.publishToState (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:628:34)
2023-12-26 10:47:56.249 - error: host.raspberrypi instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-12-26 10:47:56.250 - info: host.raspberrypi Restart adapter system.adapter.zigbee.0 because enabled
2023-12-26 10:48:26.430 - info: host.raspberrypi instance system.adapter.zigbee.0 started with pid 10130

```

**Comment by CimCup** [comment]
Ich hatte das gleiche Problem mit dem ZigBee-Adapter 1.9.2 . 
Ob es damit zusammenhängt, weiß ich nicht, aber ich hatte die Node.js v20.10.0 installiert.
Ein downgrade auf Node.js v18.19.0 + dowgrade auf ZigBee-Adapter 1.8.24 . 
Nach 'restart' und anschließendem Update auf Github-ZigBee-Adapter 1.9.3 'restart' läuft es seit einigen Stunden wieder stabil.

ConBee 2
Node.js: v18.19.0 (von v20.10.0)
NPM: 10.2.3

**Comment by LastPerfectTobi** [comment]
Hab auch gerade noch einen iobroker fix durchlaufen lassen. Aber hilft alles nicht. 

Bewegungsmelder sind kein Problem, lediglich die Taster lassen den Adapter abstürzen. 

NPM 10.2.3
Node.JS 18.19.0
Admin 6.13.11
Sonoff Zigbee CC2652P + CP2102N USB Stick

**Comment by CimCup** [comment]
Ich muss meinen Kommentar auch wieder stark einschränken. Nach einigen Stunden ist der Fehler leider wieder aufgetreten. Ich konnte noch nicht ermitteln, was diesen Fehler auslöst.
Ein downgrade auf den ZigBee-Adapter 1.8.24 hilft, ab 1.8.25 tritt der Fehler auf...

**Comment by LastPerfectTobi** [comment]
@arteck die Version 1.9.5 hat immernoch das gleiche Problem. 

Brauchst du weitere Logfiles?

**Comment by CimCup** [comment]
siehe auch unter [#2017 ](https://github.com/ioBroker/ioBroker.zigbee/issues/2017)

**Comment by arteck** [comment]
Nimm die GIT Version

**Comment by LastPerfectTobi** [comment]
Die Version 1.9.5 aus GIT funktioniert. 
Die 1.9.5 die im ioBroker als verfügbar angezeigt wird tut nicht.

**Comment by CimCup** [comment]
@LastPerfectTobi  Ich bin verwirrt. Ich hatte die 1.9.5 über die Katze, also über installiert und dennoch fehler provozieren können. 
Hab ich etwas falsch verstanden?

**Comment by LastPerfectTobi** [comment]
Geht mir auch so :)
Hätte erwartet dass über die Katze eine höhere Version installiert wird. Kam aber auch die 1.9.5.
Wieso auch immer, bei mir kommt **mein** Fehler (Absturz beim Drücken eines Aqara-Buttons) bis jetzt zumindest nicht mehr.
Und auch sonst keine Probleme oder Errors ersichtlich.

**Comment by CimCup** [comment]
Ich habe es nochmal versucht, Update per Git-URL auf v1.9.5. 
Danach eine Runde durch die Wohnung (versch. IKEA-Lampen per Hue Bewegungsmelder, IKEA-E1743 Schalter, Alexa-IoT-Steuerung etc.) und schon habe ich wieder den Fehler...

**Comment by LastPerfectTobi** [comment]
Kann wahrscheinlich nur der Experte hier beantworten. 
Hab mit der 1.9.5 aus GIT nochmal alles ausgiebig getestet und hat alles funktioniert, hab allerdings nicht versucht auf die regulär verfügbare 1.9.5 zu switchen um das da nochmal zu testen.
