### ISSUE TITLE
SNZP-06P Error

### ISSUE THREAD

**Issue by Eelisglitchy** [ioBroker/ioBroker.zigbee#2018]
Hi, hab heute den SNZP-06P Präsenzsensor bekommen und gepaired.
Er funktioniert zwar bringt aber ständig den Fehler.
Was kann ich da tun?

`
zigbee.0
2023-12-28 19:53:21.970	error	Error while processing converters DEVICE_ID: '3410f4fffee2594b'

zigbee.0
2023-12-28 19:53:21.959	error	DeviceConfigure:Failed to DeviceConfigure.configure 0x3410f4fffee2594b SNZB-06P (Error: Read 0x3410f4fffee2594b/1 64529([8193], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') at Endpoint.checkStatus (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:321:28) at Endpoint.read (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:463:22) at setupAttributes (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:62:9) at configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:72:9) at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/index.ts:139:25) at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:136:17) at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:114:21))`

**Comment by tobrog** [comment]
Ich habe den gleichen Fehler mit dem SNZB-06P Präsenzsensor und der zigbee Adapter Version 1.9.5.


zigbee.0 | 2023-12-30 21:29:48.545 | error | Error while processing converters DEVICE_ID: '3410f4fffee99489'

zigbee.0 | 2023-12-30 21:29:48.282 | error | DeviceConfigure:Failed to DeviceConfigure.configure 0x3410f4fffee99489 SNZB-06P (Error: Read 0x3410f4fffee99489/1 64529([8193], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') at Endpoint.checkStatus (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:321:28) at Endpoint.read (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:463:22) at setupAttributes (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:62:9) at configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:72:9) at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/index.ts:139:25) at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:136:17) at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:114:21))

**Comment by FredF63** [comment]
Gleiches Problem bei mir, mit Version 1.8.25 gab es diese Fehlermeldung nicht.

2023-12-31 10:18:54.310 - error: zigbee.0 (27707) Error while processing converters DEVICE_ID: '3410f4fffee39865'
2023-12-31 10:18:55.677 - info: zigbee.0 (27707) Configuring 0x3410f4fffee39865 SNZB-06P
2023-12-31 10:18:55.901 - error: zigbee.0 (27707) DeviceConfigure:Failed to DeviceConfigure.configure 0x3410f4fffee39865 SNZB-06P (Error: Read 0x3410f4fffee39865/1 64529([8193], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')

**Comment by arteck** [comment]
1.9.5 ist draussen

**Comment by FredF63** [comment]
> 1.9.6 ist draussen

Immer noch die gleiche Fehlermeldung:

2024-01-01 12:15:08.017 - error: zigbee.0 (12750) Error while processing converters DEVICE_ID: '3410f4fffee39865'
2024-01-01 12:15:09.481 - info: zigbee.0 (12750) Configuring 0x3410f4fffee39865 SNZB-06P
2024-01-01 12:15:13.745 - error: zigbee.0 (12750) DeviceConfigure:Failed to DeviceConfigure.configure 0x3410f4fffee39865 SNZB-06P (Error: Read 0x3410f4fffee39865/1 64529([8193], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')

**Comment by tobrog** [comment]
Bei mir auch die gleiche Fehlermeldung mit 1.9.6:

zigbee.0 | 2024-01-01 12:58:00.143 | error | Error while processing converters DEVICE_ID: '3410f4fffee99489'
zigbee.0 | 2024-01-01 12:58:00.119 | error | DeviceConfigure:Failed to DeviceConfigure.configure 0x3410f4fffee99489 SNZB-06P (Error: Read 0x3410f4fffee99489/1 64529([8193], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') at Endpoint.checkStatus (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:321:28) at Endpoint.read (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:463:22) at setupAttributes (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:62:9) at configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:72:9) at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/index.ts:139:25) at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:136:17) at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:114:21))
zigbee.0 | 2024-01-01 12:57:59.947 | info | Configuring 0x3410f4fffee99489 SNZB-06P

**Comment by arteck** [comment]
git mir einer das komplette log

**Comment by tobrog** [comment]
Hier das log vom start der instanz. 
Der 2. Präsenzsensor (0x048727fffeb18c96) ist momentan nicht angeschlossen.

2024-01-02 11:18:19.673  - info: zigbee.0 (3845) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2024-01-02 11:18:20.299  - info: host.iobroker stopInstance system.adapter.zigbee.0 killing pid 3845
2024-01-02 11:18:21.879  - info: host.iobroker instance system.adapter.zigbee.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2024-01-02 11:18:35.092  - info: host.iobroker "system.adapter.zigbee.0" enabled
2024-01-02 11:18:36.969  - info: host.iobroker instance system.adapter.zigbee.0 started with pid 35664
2024-01-02 11:18:43.793  - info: zigbee.0 (35664) starting. Version 1.9.6 in /opt/iobroker/node_modules/iobroker.zigbee, node: v18.19.0, js-controller: 5.0.17
2024-01-02 11:18:43.948  - info: zigbee.0 (35664) delete old Backup files. keep only last 10
2024-01-02 11:18:43.950  - info: zigbee.0 (35664) Starting Zigbee  npm ...
2024-01-02 11:18:45.447  - info: zigbee.0 (35664) Installed Version: iobroker.zigbee@latest
2024-01-02 11:18:46.695  - info: zigbee.0 (35664) Coordinator firmware version: {"type":"ConBee2/RaspBee2","meta":{"transportrev":0,"product":0,"majorrel":38,"minorrel":120,"maintrel":0,"revision":"0x26780700"}}
2024-01-02 11:18:46.734  - info: zigbee.0 (35664) Unable to disable LED, unsupported function.
2024-01-02 11:18:46.756  - info: zigbee.0 (35664)   --> transmitPower : high+
2024-01-02 11:18:46.890  - info: zigbee.0 (35664) Unable to set transmit power, unsupported function.
2024-01-02 11:18:46.893  - info: zigbee.0 (35664) Currently 18 devices are joined:
2024-01-02 11:18:46.974  - info: zigbee.0 (35664) 0x00158d0007e4c53c (addr 11255): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
2024-01-02 11:18:46.976  - info: zigbee.0 (35664) Configuring 0x3410f4fffee99489 SNZB-06P
2024-01-02 11:18:46.996  - info: zigbee.0 (35664) 0x00158d0007e5fe63 (addr 17147): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
2024-01-02 11:18:46.997  - info: zigbee.0 (35664) 0x00158d000805a976 (addr 58423): DJT11LM - Xiaomi Aqara vibration sensor (EndDevice)
2024-01-02 11:18:46.998  - info: zigbee.0 (35664) 0x00158d000700186c (addr 4751): MCCGQ11LM - Xiaomi Aqara door & window contact sensor (EndDevice)
2024-01-02 11:18:46.998  - info: zigbee.0 (35664) 0x00158d0006c521ec (addr 23215): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
2024-01-02 11:18:46.999  - info: zigbee.0 (35664) 0x00158d0006c57f78 (addr 21990): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
2024-01-02 11:18:46.999  - info: zigbee.0 (35664) 0x7cb03eaa0a0bf6b6 (addr 13030): AB3257001NJ - OSRAM Smart+ plug (Router)
2024-01-02 11:18:47.000  - info: zigbee.0 (35664) 0x7cb03eaa0a0bfb47 (addr 16039): AB3257001NJ - OSRAM Smart+ plug (Router)
2024-01-02 11:18:47.001  - info: zigbee.0 (35664) 0x7cb03eaa0a0bfbdf (addr 25609): AB3257001NJ - OSRAM Smart+ plug (Router)
2024-01-02 11:18:47.001  - info: zigbee.0 (35664) 0x7cb03eaa0a0beebe (addr 24279): AB3257001NJ - OSRAM Smart+ plug (Router)
2024-01-02 11:18:47.002  - info: zigbee.0 (35664) 0x5c0272fffef5d514 (addr 50002): LED1837R5 - IKEA TRADFRI LED bulb GU10 400 lumen, dimmable (Router)
2024-01-02 11:18:47.003  - info: zigbee.0 (35664) 0x5c0272fffed12f83 (addr 13606): LED1837R5 - IKEA TRADFRI LED bulb GU10 400 lumen, dimmable (Router)
2024-01-02 11:18:47.003  - info: zigbee.0 (35664) 0x847127fffec731ec (addr 9835): E1525/E1745 - IKEA TRADFRI motion sensor (EndDevice)
2024-01-02 11:18:47.013  - info: zigbee.0 (35664) 0x00158d0006b245e7 (addr 29823): WSDCGQ11LM - Xiaomi Aqara temperature, humidity and pressure sensor (EndDevice)
2024-01-02 11:18:47.014  - info: zigbee.0 (35664) 0x847127fffe4270a6 (addr 1307): LED1537R6/LED1739R5 - IKEA TRADFRI LED bulb GU10 400 lumen, dimmable, white spectrum (Router)
2024-01-02 11:18:47.015  - info: zigbee.0 (35664) 0x847127fffe33d461 (addr 63785): LED1537R6/LED1739R5 - IKEA TRADFRI LED bulb GU10 400 lumen, dimmable, white spectrum (Router)
2024-01-02 11:18:47.016  - info: zigbee.0 (35664) 0x3410f4fffee99489 (addr 54779): SNZB-06P - SONOFF Zigbee occupancy sensor (Router)
2024-01-02 11:18:47.016  - info: zigbee.0 (35664) 0x048727fffeb18c96 (addr 42562): SNZB-06P - SONOFF Zigbee occupancy sensor (Router)
2024-01-02 11:18:47.017  - info: zigbee.0 (35664) Zigbee started
2024-01-02 11:18:47.600  - info: zigbee.0 (35664) debug devices set to []
2024-01-02 11:18:48.393  - error: zigbee.0 (35664) DeviceConfigure:Failed to DeviceConfigure.configure 0x3410f4fffee99489 SNZB-06P (Error: Read 0x3410f4fffee99489/1 64529([8193], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.checkStatus (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:321:28)
    at Endpoint.read (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:463:22)
    at setupAttributes (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:62:9)
    at configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:72:9)
    at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/index.ts:139:25)
    at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:136:17)
    at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:114:21)
    at DeviceConfigure.onZigbeeStarted (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:54:21)
    at async Promise.all (index 1))
2024-01-02 11:18:48.394  - info: zigbee.0 (35664) Configuring 0x048727fffeb18c96 SNZB-06P
2024-01-02 11:18:48.852  - error: zigbee.0 (35664) Error while processing converters DEVICE_ID: '3410f4fffee99489' 
2024-01-02 11:18:49.736  - info: zigbee.0 (35664) Configuring 0x3410f4fffee99489 SNZB-06P
2024-01-02 11:18:49.895  - error: zigbee.0 (35664) DeviceConfigure:Failed to DeviceConfigure.configure 0x3410f4fffee99489 SNZB-06P (Error: Read 0x3410f4fffee99489/1 64529([8193], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.checkStatus (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:321:28)
    at Endpoint.read (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:463:22)
    at setupAttributes (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:62:9)
    at configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:72:9)
    at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/index.ts:139:25)
    at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:136:17)
    at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:114:21))
2024-01-02 11:18:57.097  - error: zigbee.0 (35664) Error while processing converters DEVICE_ID: '3410f4fffee99489' 
2024-01-02 11:18:58.609  - error: zigbee.0 (35664) DeviceConfigure:Failed to DeviceConfigure.configure 0x048727fffeb18c96 SNZB-06P (Error: Read 0x048727fffeb18c96/1 msOccupancySensing([32], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (no response received (8))
    at DeconzAdapter.sendZclFrameToEndpoint (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:666:23)
    at Request.send (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:81:20)
    at Endpoint.read (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:460:28)
    at setupAttributes (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:62:9)
    at configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:72:9)
    at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/index.ts:139:25)
    at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:136:17)
    at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:114:21)
    at DeviceConfigure.onZigbeeStarted (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:54:21)
    at async Promise.all (index 1))
2024-01-02 11:19:00.603  - warn: zigbee.0 (35664) DeviceAvailability:Failed to ping 0x048727fffeb18c96 SNZB-06P

**Comment by Eelisglitchy** [comment]
Hier auch nochmal meine, als Querverweis.

`2024-01-02 12:21:32.774 - info: host.eelisglitchy-server "system.adapter.zigbee.0" enabled
2024-01-02 12:21:32.925 - info: host.eelisglitchy-server instance system.adapter.zigbee.0 started with pid 2372406
2024-01-02 12:21:34.169 - info: zigbee.0 (2372406) starting. Version 1.9.6 in /opt/iobroker/node_modules/iobroker.zigbee, node: v18.19.0, js-controller: 5.0.17
2024-01-02 12:21:34.201 - info: zigbee.0 (2372406) delete old Backup files. keep only last 10
2024-01-02 12:21:34.202 - info: zigbee.0 (2372406) Starting Zigbee npm ...
2024-01-02 12:21:34.289 - info: zigbee.0 (2372406) Installed Version: iobroker.zigbee@1.9.6
2024-01-02 12:21:34.841 - info: zigbee.0 (2372406) Coordinator firmware version: {"type":"zStack3x0","meta":{"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20230507}}
2024-01-02 12:21:34.858 - info: zigbee.0 (2372406) Unable to disable LED, unsupported function.
2024-01-02 12:21:34.870 - info: zigbee.0 (2372406) --> transmitPower : high
2024-01-02 12:21:34.892 - info: zigbee.0 (2372406) Currently 24 devices are joined:
2024-01-02 12:21:34.923 - info: zigbee.0 (2372406) 0x04cf8cdf3c7b4286 (addr 33755): GZCGQ01LM - Xiaomi MiJia light intensity sensor (EndDevice)
2024-01-02 12:21:34.924 - info: zigbee.0 (2372406) Configuring 0x3410f4fffee2594b SNZB-06P
2024-01-02 12:21:34.930 - info: zigbee.0 (2372406) 0x7cb03eaa00a8b3b0 (addr 8650): AC03645 - OSRAM LIGHTIFY LED CLA60 E27 RGBW (Router)
2024-01-02 12:21:34.930 - info: zigbee.0 (2372406) 0x7cb03eaa00ac9d26 (addr 18246): AC03645 - OSRAM LIGHTIFY LED CLA60 E27 RGBW (Router)
2024-01-02 12:21:34.931 - info: zigbee.0 (2372406) 0x7cb03eaa00ada024 (addr 10924): AC03645 - OSRAM LIGHTIFY LED CLA60 E27 RGBW (Router)
2024-01-02 12:21:34.931 - info: zigbee.0 (2372406) 0x7cb03eaa00ac1d9a (addr 13381): AC03641 - OSRAM LIGHTIFY LED Classic A60 clear (Router)
2024-01-02 12:21:34.932 - info: zigbee.0 (2372406) 0xf0d1b8000015f89f (addr 39695): 4058075208414 - LEDVANCE SMART+ candle E14 tunable white (Router)
2024-01-02 12:21:34.932 - info: zigbee.0 (2372406) 0x7cb03eaa00af3c54 (addr 62444): AC03642 - OSRAM SMART+ CLASSIC A 60 TW (Router)
2024-01-02 12:21:34.933 - info: zigbee.0 (2372406) 0x7cb03eaa00af68ab (addr 39434): AC03642 - OSRAM SMART+ CLASSIC A 60 TW (Router)
2024-01-02 12:21:34.933 - info: zigbee.0 (2372406) 0x7cb03eaa00a86ea1 (addr 23544): AC03642 - OSRAM SMART+ CLASSIC A 60 TW (Router)
2024-01-02 12:21:34.934 - info: zigbee.0 (2372406) 0x84182600000f3cd2 (addr 48516): AC03642 - OSRAM SMART+ CLASSIC A 60 TW (Router)
2024-01-02 12:21:34.934 - info: zigbee.0 (2372406) 0x9035eafffe095375 (addr 1547): SNZB-02D - SONOFF Temperature and humidity sensor with screen (EndDevice)
2024-01-02 12:21:34.934 - info: zigbee.0 (2372406) 0xdc8e95fffe09093f (addr 21495): ZBMINI - SONOFF Zigbee two way smart switch (Router)
2024-01-02 12:21:34.935 - info: zigbee.0 (2372406) 0x00124b002919b59a (addr 37682): SNZB-01 - SONOFF Wireless button (EndDevice)
2024-01-02 12:21:34.935 - info: zigbee.0 (2372406) 0x3c2ef5fffebd246c (addr 6916): SNZB-02D - SONOFF Temperature and humidity sensor with screen (EndDevice)
2024-01-02 12:21:34.936 - info: zigbee.0 (2372406) 0x00124b00292c14f2 (addr 7055): SNZB-01 - SONOFF Wireless button (EndDevice)
2024-01-02 12:21:34.936 - info: zigbee.0 (2372406) 0x54ef441000781206 (addr 28156): ZNJLBL01LM - Xiaomi Aqara roller shade companion E1 (EndDevice)
2024-01-02 12:21:34.936 - info: zigbee.0 (2372406) 0x00124b002934e347 (addr 2038): SNZB-02 - SONOFF Temperature and humidity sensor (EndDevice)
2024-01-02 12:21:34.937 - info: zigbee.0 (2372406) 0x84ba20fffedeeaab (addr 60914): SNZB-02D - SONOFF Temperature and humidity sensor with screen (EndDevice)
2024-01-02 12:21:34.937 - info: zigbee.0 (2372406) 0x54ef441000841345 (addr 42735): ZNJLBL01LM - Xiaomi Aqara roller shade companion E1 (EndDevice)
2024-01-02 12:21:34.940 - info: zigbee.0 (2372406) 0x00124b00292b8383 (addr 48339): SNZB-01 - SONOFF Wireless button (EndDevice)
2024-01-02 12:21:34.940 - info: zigbee.0 (2372406) 0xec1bbdfffe78337c (addr 48656): RH3040 - TuYa PIR sensor (EndDevice)
2024-01-02 12:21:34.941 - info: zigbee.0 (2372406) 0x54ef4410009234fe (addr 59877): LGYCDD01LM - Xiaomi Aqara Zigbee 3.0 LED strip T1 (Router)
2024-01-02 12:21:34.941 - info: zigbee.0 (2372406) 0x3410f4fffee2594b (addr 22628): SNZB-06P - SONOFF Zigbee occupancy sensor (Router)
2024-01-02 12:21:34.942 - info: zigbee.0 (2372406) 0x00158d0002b7f035 (addr 20422): RTCGQ11LM - Xiaomi Aqara human body movement and illuminance sensor (EndDevice)
2024-01-02 12:21:34.942 - info: zigbee.0 (2372406) Zigbee started
2024-01-02 12:21:35.056 - info: zigbee.0 (2372406) debug devices set to []
2024-01-02 12:21:35.208 - error: zigbee.0 (2372406) DeviceConfigure:Failed to DeviceConfigure.configure 0x3410f4fffee2594b SNZB-06P (Error: Read 0x3410f4fffee2594b/1 64529([8193], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
at Endpoint.checkStatus (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:321:28)
at Endpoint.read (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:463:22)
at setupAttributes (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:62:9)
at configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:72:9)
at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/index.ts:139:25)
at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:136:17)
at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:114:21)
at DeviceConfigure.onZigbeeStarted (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:54:21)
at async Promise.all (index 1))
2024-01-02 12:21:35.224 - error: zigbee.0 (2372406) Error while processing converters DEVICE_ID: '3410f4fffee2594b'
2024-01-02 12:21:37.505 - info: zigbee.0 (2372406) Configuring 0x3410f4fffee2594b SNZB-06P
2024-01-02 12:21:37.663 - error: zigbee.0 (2372406) DeviceConfigure:Failed to DeviceConfigure.configure 0x3410f4fffee2594b SNZB-06P (Error: Read 0x3410f4fffee2594b/1 64529([8193], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
at Endpoint.checkStatus (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:321:28)
at Endpoint.read (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:463:22)
at setupAttributes (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:62:9)
at configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:72:9)
at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/index.ts:139:25)
at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:136:17)
at DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:114:21))
2024-01-02 12:21:37.669 - error: zigbee.0 (2372406) Error while processing converters DEVICE_ID: '3410f4fffee2594b'
2024-01-02 12:21:39.579 - warn: zigbee.0 (2372406) DeviceAvailability:Failed to ping 0x7cb03eaa00a86ea1 CLA60 TW OSRAM
2024-01-02 12:21:39.740 - warn: zigbee.0 (2372406) DeviceAvailability:Failed to ping 0x84182600000f3cd2 CLA60 TW OSRAM
2024-01-02 12:21:54.080 - warn: zigbee.0 (2372406) DeviceAvailability:Failed to ping 0x7cb03eaa00ada024 CLA60 RGBW OSRAM
2024-01-02 12:21:54.458 - warn: zigbee.0 (2372406) DeviceAvailability:Failed to ping 0x7cb03eaa00ac1d9a Classic A60 W clear - LIGHTIFY
2024-01-02 12:21:54.840 - warn: zigbee.0 (2372406) DeviceAvailability:Failed to ping 0x7cb03eaa00af3c54 CLA60 TW OSRAM
2024-01-02 12:21:55.044 - warn: zigbee.0 (2372406) DeviceAvailability:Failed to ping 0x7cb03eaa00af68ab CLA60 TW OSRAM
2024-01-02 12:22:02.011 - warn: zigbee.0 (2372406) DeviceAvailability:Failed to ping 0x7cb03eaa00ac9d26 CLA60 RGBW OSRAM
2024-01-02 12:22:02.382 - warn: zigbee.0 (2372406) DeviceAvailability:Failed to ping 0x7cb03eaa00a8b3b0 CLA60 RGBW OSRAM
2024-01-02 12:22:09.153 - warn: zigbee.0 (2372406) DeviceAvailability:Failed to ping 0xf0d1b8000015f89f B40 TW Z3
2024-01-02 12:22:14.628 - info: connector-local-control.0 (5428) receive server message from 192.168.20.62: 32100: {"msgType":"Heartbeat","mac":"8caab5ca9f50","deviceType":"02000001","msgID":"20240102122204344","token":"967DC7CD55376DA9","data":{"currentState":1,"numberOfDevices":1,"RSSI":-45}}
2024-01-02 12:22:14.629 - info: connector-local-control.0 (5428) Heartbeat`

**Comment by Eelisglitchy** [comment]
Problem gelöst, kann geschlossen werden.
