### ISSUE TITLE
Error mit Absturz des Adapters V1.9.5

### ISSUE THREAD

**Issue by skroob** [ioBroker/ioBroker.zigbee#2033]
Hallo Arteck

Mit der Version 1.9.5 habe ich in den letzten Tage etliche Abstürze gehabt. Heute konnte ich endlich den Verursacher finden. Es ist der LongPress vom Aquara Taster. Er führt den Befehl zwar noch aus aber im Anschluss stirbt der Adapter und startet neu.

![2024-01-02_095738](https://github.com/ioBroker/ioBroker.zigbee/assets/17686871/95a81511-2143-4e73-baa7-b06863633f1f)
<HR>
Log-Meldung:

2024-01-02 09:51:42.073  - info: zigbee.1 (1645) Zigbee started
--
2024-01-02 09:51:42.105  - info: zigbee.1 (1645) debug devices set to []
2024-01-02 09:52:00.300  - error:  zigbee.1 (1645) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
2024-01-02 09:52:00.300  - error: zigbee.1 (1645) unhandled promise rejection: Cannot read properties of null (reading 'hasOwnProperty')
2024-01-02 09:52:00.300  - error: zigbee.1 (1645) TypeError: Cannot read properties of null (reading 'hasOwnProperty')
at /opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:628:62
at Array.filter ()
at StatesController.publishToState (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:628:34)
2024-01-02 09:52:00.300  - error: zigbee.1 (1645) Cannot read properties of null (reading 'hasOwnProperty')
2024-01-02 09:52:00.302  - info: zigbee.1 (1645) cleaned everything up...
2024-01-02 09:52:00.332  - info: zigbee.1 (1645) Zigbee: disabling joining new devices.
2024-01-02 09:52:00.802  - info: zigbee.1 (1645) terminating
2024-01-02 09:52:00.803  - warn: zigbee.1 (1645) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-01-02 09:52:01.320  - error: host.ioBroker-MA Caught by controller[0]: Was not able to detect the Linky linky_mode. Default to historique
2024-01-02 09:52:01.320  - error: host.ioBroker-MA Caught by controller[1]: Was not able to detect the Linky energy_phase. Default to single_phase
2024-01-02 09:52:01.320  - error: host.ioBroker-MA Caught by controller[1]: Not able to detect the current tarif. Not filtering any expose...
2024-01-02 09:52:01.320  - error:  host.ioBroker-MA Caught by controller[2]: This error originated either  by throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch(). The promise  rejected with the reason:
2024-01-02 09:52:01.320  - error: host.ioBroker-MA Caught by controller[2]: TypeError: Cannot read properties of null (reading 'hasOwnProperty')
2024-01-02 09:52:01.320  - error: host.ioBroker-MA Caught by controller[2]:     at /opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:628:62
2024-01-02 09:52:01.320  - error: host.ioBroker-MA Caught by controller[2]:     at Array.filter ()
2024-01-02 09:52:01.320  - error:  host.ioBroker-MA Caught by controller[2]:     at  StatesController.publishToState  (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:628:34)
2024-01-02 09:52:01.320  - error: host.ioBroker-MA instance system.adapter.zigbee.1 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-01-02 09:52:01.320  - info: host.ioBroker-MA Restart adapter system.adapter.zigbee.1 because enabled
2024-01-02 09:52:01.320  - warn: host.ioBroker-MA Do not restart adapter system.adapter.zigbee.1 because restart loop detected

<HR>

System:
![2024-01-02_095908](https://github.com/ioBroker/ioBroker.zigbee/assets/17686871/1e506a3d-d5d2-4c15-8330-67369874e943)

Falls Du noch mehr Infos brauchst, kommst einfach auf mich zu. 

Vielen Dank für Deine Arbeit und ich wünsche Dir nur das Beste für das neue Jahr!

**Comment by arteck** [comment]
1.9.6 ist draussen..

**Comment by skroob** [comment]
Versuch mit 1.9.6 gemacht. Error Meldungen sind nun weg aber die Hold-Funktion geht nicht richtig. Er erkennt ein Hold und setzt den Datenpunkt auf true aber nicht mehr zurück auf false. Zusätzlich löst er ca. 3 Sekunden versetzt noche ein Singel-Klick aus. Getestet hab ich mit ausschliessen und ohne. Gleiches Fehlerbild wie mir scheint.

![2024-01-02_174133](https://github.com/ioBroker/ioBroker.zigbee/assets/17686871/85c09cd0-360b-4e0e-8a59-e9f94b7518eb)

Einfach mekern wenn ich was machen / testen soll.

Dankeschön!

**Comment by arteck** [comment]
der wird nur getriggert.. da geht nix auf false...

**Comment by skroob** [comment]
Hallo Arteck

 

Irgendwie verstehe ich das gerade nicht mehr. Wenn ich doch den Button gedrückt halte löst der Adapter

den Hold aus. Dieser setzt den Datenpunkt (Hold) kurz auf true und anschliessend gleich wieder auf false. 

So war es zumindest bis zu dieser Version und mit den anderen Zigbee Geräten. Seit 1.9.6 wechselt der

Datenpunkt, nachdem ersten Auslösen nicht mehr zurück auf false, somit sind Abfragen nicht mehr mögliche

weil der Datenpunkt (Hold) ab dann dauerhaft auf true stehen bleibt. Egal ob ich den Knopf erneut drücke.

 

Auch wird der versetzte Single-Klick (beim lange drücken des Buttons) tatsächlich ausgelöst. Ich habe auf

dem single eine andere Funktion drauf und die wird durch den auch ausgelöst. Der kommt sogar dann noch

wenn der Datenpunkt Hold bereits dauerhaft true anzeigt. So ca. 3 Sekunden nachdem gehaltenen Button.

 

Zum Test habe ich nun einen ganz neuen Aqara Button angelernt und der hat auch das selbe Problem. Gehe

ich aber zurück mit der Adapterversion auf die 1.8.24 passt alles wieder.

 

Kann es sein, dass ich irgendwo was übersehe oder nicht ganz verstehe?

 

 

Von: arteck ***@***.***> 
Gesendet: Donnerstag, 4. Januar 2024 08:51
An: ioBroker/ioBroker.zigbee ***@***.***>
Cc: skroob ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.zigbee] Error mit Absturz des Adapters V1.9.5 (Issue #2033)

 

der wird nur getriggert.. da geht nix auf false...

**Comment by skroob** [comment]
Hi arteck, 

Nur kurz zu Deiner Info. Mit der Version 1.9.7 funktionieren meine Geräte wieder wie vorgesehen.

Ein grosses Dankeschön von mir!
