### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by manuxi** [ioBroker/ioBroker.zigbee#2101]
Since several days I'm facing a non-responsive Zigbee-Instance from time to time. After a restart, everything runs as usual again. This happens every 1-2 days. I'm using v1.10.1.
I stumbled across several log entries that all had something to do with the Tuya device 0xa4c1387267ac600e, but couldn't really see the reason so far - there were just too many Zigbee log messages. 

Just now, however, I found an unhandled exception that apparently causes my Zigbee adapter to stop. Could this be the reason of the problems I'm facing?

```
zigbee.0
2024-03-07 00:10:17.069	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason

zigbee.0
2024-03-07 00:10:17.067	info	terminating

zigbee.0
2024-03-07 00:10:16.569	info	Zigbee: disabling joining new devices.

zigbee.0
2024-03-07 00:10:16.566	info	cleaned everything up...

zigbee.0
2024-03-07 00:10:16.551	error	Command 0xa4c1387267ac600e/1 manuSpecificTuya.dataQuery({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 61457 - 1 - 18 - 61184 - 11 after 10000ms)

zigbee.0
2024-03-07 00:10:16.551	error	Error: Command 0xa4c1387267ac600e/1 manuSpecificTuya.dataQuery({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 61457 - 1 - 18 - 61184 - 11 after 10000ms) at Object.start (/opt/iobroker/node_modules/zigbee-herdsman/dist/utils/waitress.js:40:23) at ZStackAdapter.sendZclFrameToEndpointInternal (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:423:47) at async Queue.execute (/opt/iobroker/node_modules/zigbee-herdsman/dist/utils/queue.js:29:20) at async Request.send (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/helpers/request.js:69:20) at async Endpoint.command (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:572:28) at async Object.onEvent (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/tuya.js:101:13)

zigbee.0
2024-03-07 00:10:16.550	error	unhandled promise rejection: Command 0xa4c1387267ac600e/1 manuSpecificTuya.dataQuery({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 61457 - 1 - 18 - 61184 - 11 after 10000ms)

zigbee.0
2024-03-07 00:10:16.550	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
```

**Comment by arteck** [comment]
check new GIT version

**Comment by manuxi** [comment]
Thank you! I'll try and let you know.

**Comment by manuxi** [comment]
Was already on 1.10.2

**Comment by arteck** [comment]
nice but install NOW the GIT version..and check again

**Comment by manuxi** [comment]
> nice but install NOW the GIT version..and check again

1.10.4 right?

**Comment by arteck** [comment]
1.10.3

**Comment by manuxi** [comment]
I'd installed the proposed 1.10.3, but Zigbee kept crashing. Therefore I switched to 1.10.4 (last week). Still issues, Zigbee crashes daily...
`<html>
<body>

zigbee.0 | 2024-05-28 01:20:18.580 | error | ZCL command 0xa4c1387267ac600e/1 manuSpecificTuya.dataQuery({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 61457 - 1 - 15 - 61184 - 11 after 10000ms)
-- | -- | -- | --
zigbee.0 | 2024-05-28 01:20:18.580 | error | Error: ZCL command 0xa4c1387267ac600e/1 manuSpecificTuya.dataQuery({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 61457 - 1 - 15 - 61184 - 11 after 10000ms) at Object.start (/opt/iobroker/node_modules/zigbee-herdsman/dist/utils/waitress.js:40:23) at ZStackAdapter.sendZclFrameToEndpointInternal (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:424:47) at async Queue.execute (/opt/iobroker/node_modules/zigbee-herdsman/dist/utils/queue.js:29:20) at async Request.send (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/helpers/request.js:69:20) at async Endpoint.zclCommand (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:585:28) at async Endpoint.command (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:447:23) at async Object.onEvent (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/tuya.js:102:13)
zigbee.0 | 2024-05-28 01:20:18.579 | error | unhandled promise rejection: ZCL command 0xa4c1387267ac600e/1 manuSpecificTuya.dataQuery({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 61457 - 1 - 15 - 61184 - 11 after 10000ms)
zigbee.0 | 2024-05-28 01:20:18.579 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().


</body>
</html>`
