### ISSUE TITLE
adapter crash after reconnect window contact

### ISSUE THREAD

**Issue by softwarecrash** [ioBroker/ioBroker.zigbee#2112]
Hallo,
ich hoffe deutsch ist okay.

mein zigbee netzwerk macht schon immer etwas probleme, geräte plötzlich offline oder einfach weg, oder sind disconnected, nach einem neuen pairing sind sie die dann ganz weg. auch ein neuaufsetzen des ganzen hat keine besserung gebracht.

aber nun stürzt der ganze adapter ab wenn ich zb in einem fensterkontakt die batterien wechsel.

```
host.iobroker | 2024-04-04 19:52:10.018 | info | instance system.adapter.zigbee.0 started with pid 2167
-- | -- | -- | --
host.iobroker | 2024-04-04 19:51:39.983 | info | Restart adapter system.adapter.zigbee.0 because enabled
host.iobroker | 2024-04-04 19:51:39.983 | error | instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.iobroker | 2024-04-04 19:51:39.983 | error | Caught  by controller[2]:     at Device.onZclData  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/device.ts:229:13)
host.iobroker | 2024-04-04 19:51:39.983 | error | Caught  by controller[2]:     at Endpoint.command  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:758:28)
host.iobroker | 2024-04-04 19:51:39.983 | error | Caught  by controller[2]:     at Request.send  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)
host.iobroker | 2024-04-04 19:51:39.983 | error | Caught by controller[2]:     at Queue.execute (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)
host.iobroker | 2024-04-04 19:51:39.983 | error | Caught by controller[2]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
host.iobroker | 2024-04-04 19:51:39.983 | error | Caught  by controller[2]:     at ZStackAdapter.sendZclFrameToEndpointInternal  (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:415:23)
host.iobroker | 2024-04-04 19:51:39.983 | error | Caught  by controller[2]: Error: Command 0x00124b0023ab33d0/1  ssIasZone.enrollRsp({"enrollrspcode":0,"zoneid":23},  {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})  failed (Data request failed with error: 'No network route' (205))
host.iobroker | 2024-04-04 19:51:39.983 | error | Caught  by controller[1]: This error originated either by throwing inside of an  async function without a catch block, or by rejecting a promise which  was not handled with .catch(). The promise rejected with the reason:
zigbee.0 | 2024-04-04 19:51:39.441 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee.0 | 2024-04-04 19:51:39.440 | info | terminating
zigbee.0 | 2024-04-04 19:51:38.941 | info | Zigbee: disabling joining new devices.
zigbee.0 | 2024-04-04 19:51:38.940 | info | cleaned everything up...
zigbee.0 | 2024-04-04 19:51:38.933 | error | Exception-Code:  205: Command 0x00124b0023ab33d0/1  ssIasZone.enrollRsp({"enrollrspcode":0,"zoneid":23},  {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})  failed (Data request failed with error: 'No network route' (205))
zigbee.0 | 2024-04-04 19:51:38.933 | error | Error:  Command 0x00124b0023ab33d0/1  ssIasZone.enrollRsp({"enrollrspcode":0,"zoneid":23},  {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})  failed (Data request failed with error: 'No network route' (205))    at  ZStackAdapter.sendZclFrameToEndpointInternal  (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:415:23)     at processTicksAndRejections  (node:internal/process/task_queues:95:5)    at Queue.execute  (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)     at Request.send  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)     at Endpoint.command  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:758:28)     at Device.onZclData  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/device.ts:229:13)
zigbee.0 | 2024-04-04 19:51:38.923 | error | unhandled  promise rejection: Command 0x00124b0023ab33d0/1  ssIasZone.enrollRsp({"enrollrspcode":0,"zoneid":23},  {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})  failed (Data request failed with error: 'No network route' (205))
zigbee.0 | 2024-04-04 19:51:38.922 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
zigbee.0 | 2024-04-04 19:51:17.315 | info | Device '0x00124b0023ab33d0' announced itself
```
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/44615614/f893b9e5-d364-48f9-b4e0-c1d34502d48d)
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/44615614/e226027c-4ed4-4c08-b3b2-7d0cfeee38f2)
der koordinator ist über ein LAn modul verbunden, die verbindung ist stabil.

ich bin grad etwas ratlos wo man noch ansetzen könnte damit das ganze stabil läuft oder wenigstens nicht abschmiert

**Comment by arteck** [comment]
nimm die GIT version
