### ISSUE TITLE
Failed  to check if update available (ZigBee Adapter 1.10.3)

### ISSUE THREAD

**Issue by gc-cacher** [ioBroker/ioBroker.zigbee#2115]
After updating the ZigBee Adapter to version 1.10.3 I always get the following error if I checks for firmware updates: 

Failed  to check if update available for '0xa4c138e71aa99d58' Converting  circular structure to JSON
    --> starting at object with constructor  'DerivedLogger'
    |     property '_readableState' -> object with  constructor 'ReadableState'
    |     property 'pipes' -> object with  constructor 'Array'
    |     index 0 -> object with constructor  'DailyRotateFile'
    --- property 'parent' closes the circle

Restarting the ioBroker didn't help. 

Regards
gc-cacher

**Comment by dimaiv7** [comment]
Ich kann es auch bestätigen.
Die Meldung kommt für alle Geräte die OTA können.

**Comment by cataclisma** [comment]
Bei mir auch. Wollte ein Issue erstellen und schliesse mich diesem hier an.

**Comment by MarkoP2507** [comment]
Habe das gleiche Problem auch mit version 1.10.4.

IKEA TRADFRI shortcut button 
Modell E1812

**Comment by guitardoc** [comment]
Selbes Problem mit Nous A1Z Zwischensteckern.

**Comment by winni-priel** [comment]
Hier auch mit allen Geräten 1.10.3 und 1.10.4 z.B.
Failed to check if update available for '0xa4c138d25f92e991' Converting circular structure to JSON --> starting at object with constructor 'DerivedLogger' | property '_readableState' -> object with constructor 'ReadableState' | property 'pipes' -> object with constructor 'Array' | index 0 -> object with constructor 'DailyRotateFile' --- property 'parent' closes the circle

**Comment by CPU-6502** [comment]
Gleiches Problem hier bei mir auch ...

**Comment by Alligator666** [comment]
Gleiches Problem hier bei mir auch ...

**Comment by PeterSmarthome** [comment]
Bei mir ebenfalls (1.10.3)
`Failed to check if update available for '0xb43522fffecfc4db' Converting circular structure to JSON --> starting at object with constructor 'DerivedLogger' | property '_readableState' -> object with constructor 'ReadableState' | property 'pipes' -> object with constructor 'Array' | index 0 -> object with constructor 'DailyRotateFile' --- property 'parent' closes the circle`

**Comment by arteck** [comment]
check GIT version

**Comment by JF62** [comment]
The verification works with this version

**Comment by dimaiv7** [comment]
> check GIT version

Die Überprüfung läuft jetzt gut durch.
Aber, sobald man ein Update vom Gerät startet, stürzt der Zigbee Adapter ab.

`<html><body>

2024-05-19 13:33:22.331  - info: zigbee.0 (8568) Start firmware update for 0x385cfbfffe6c6c30
--
2024-05-19 13:33:26.330  - error:  zigbee.0 (8568) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
2024-05-19 13:33:26.330  - error: zigbee.0 (8568) unhandled promise rejection: onProgress is not a function
2024-05-19 13:33:26.337  - error: zigbee.0 (8568) TypeError: onProgress is not a function
at callOnProgress (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:374:9)
at sendImageBlockResponse (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:508:38)
at /opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:525:25
at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-05-19 13:33:26.338  - error: zigbee.0 (8568) onProgress is not a function
2024-05-19 13:33:26.351  - info: zigbee.0 (8568) cleaned everything up...
2024-05-19 13:33:26.352  - info: zigbee.0 (8568) Zigbee: disabling joining new devices.
2024-05-19 13:33:26.851  - info: zigbee.0 (8568) terminating
2024-05-19 13:33:26.852  - warn: zigbee.0 (8568) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-05-19 13:33:27.415  - error:  host.IoBroker Caught by controller[1]: This error originated either by  throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch(). The promise  rejected with the reason:
2024-05-19 13:33:27.415  - error: host.IoBroker Caught by controller[2]: TypeError: onProgress is not a function
2024-05-19 13:33:27.415  - error:  host.IoBroker Caught by controller[2]:     at callOnProgress  (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:374:9)
2024-05-19 13:33:27.415  - error:  host.IoBroker Caught by controller[2]:     at sendImageBlockResponse  (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:508:38)
2024-05-19 13:33:27.416  - error:  host.IoBroker Caught by controller[2]:     at  /opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:525:25
2024-05-19 13:33:27.416  - error: host.IoBroker Caught by controller[2]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-05-19 13:33:27.416  - error: host.IoBroker instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-05-19 13:33:27.416  - info: host.IoBroker Restart adapter system.adapter.zigbee.0 because enabled


</body>
</html>`

**Comment by fzoellne** [comment]
> > check GIT version
> 
> Die Überprüfung läuft jetzt gut durch. Aber, sobald man ein Update vom Gerät startet, stürzt der Zigbee Adapter ab.
> 
> `2024-05-19 13:33:22.331 - info: zigbee.0 (8568) Start firmware update for 0x385cfbfffe6c6c30
> 
> 2024-05-19 13:33:26.330 - error: zigbee.0 (8568) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
> 
> 2024-05-19 13:33:26.330 - error: zigbee.0 (8568) unhandled promise rejection: onProgress is not a function
> 
> 2024-05-19 13:33:26.337 - error: zigbee.0 (8568) TypeError: onProgress is not a function at callOnProgress (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:374:9) at sendImageBlockResponse (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:508:38) at /opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:525:25 at processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
> 2024-05-19 13:33:26.338 - error: zigbee.0 (8568) onProgress is not a function
> 
> 2024-05-19 13:33:26.351 - info: zigbee.0 (8568) cleaned everything up...
> 
> 2024-05-19 13:33:26.352 - info: zigbee.0 (8568) Zigbee: disabling joining new devices.
> 
> 2024-05-19 13:33:26.851 - info: zigbee.0 (8568) terminating
> 
> 2024-05-19 13:33:26.852 - warn: zigbee.0 (8568) Terminated (UNCAUGHT_EXCEPTION): Without reason
> 
> 2024-05-19 13:33:27.415 - error: host.IoBroker Caught by controller[1]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
> 
> 2024-05-19 13:33:27.415 - error: host.IoBroker Caught by controller[2]: TypeError: onProgress is not a function
> 
> 2024-05-19 13:33:27.415 - error: host.IoBroker Caught by controller[2]: at callOnProgress (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:374:9)
> 
> 2024-05-19 13:33:27.415 - error: host.IoBroker Caught by controller[2]: at sendImageBlockResponse (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:508:38)
> 
> 2024-05-19 13:33:27.416 - error: host.IoBroker Caught by controller[2]: at /opt/iobroker/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:525:25
> 
> 2024-05-19 13:33:27.416 - error: host.IoBroker Caught by controller[2]: at processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
> 2024-05-19 13:33:27.416 - error: host.IoBroker instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
> 
> 2024-05-19 13:33:27.416 - info: host.IoBroker Restart adapter system.adapter.zigbee.0 because enabled `

can confirm this.

**Comment by goldoliver** [comment]
Also for me, updates are not working :-(
(newest github version) 

`<html><body>

zigbee.0 | 2024-05-24 17:34:56.008 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
zigbee.0 | 2024-05-24 17:34:56.004 | info | terminating
zigbee.0 | 2024-05-24 17:34:55.510 | info | Zigbee: disabling joining new devices.
zigbee.0 | 2024-05-24 17:34:55.502 | info | cleaned everything up...
zigbee.0 | 2024-05-24 17:34:55.491 | error | onProgress is not a function
zigbee.0 | 2024-05-24 17:34:55.490 | error | TypeError:  onProgress is not a function    at callOnProgress  (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/ota/common.js:342:9)     at sendImageBlockResponse  (/opt/iobroker/node_modules/zigbee-herdsman-converters/lib/ota/common.js:452:34)     at  /opt/iobroker/node_modules/zigbee-herdsman-converters/lib/ota/common.js:469:21     at process.processTicksAndRejections  (node:internal/process/task_queues:95:5)
zigbee.0 | 2024-05-24 17:34:55.489 | error | unhandled promise rejection: onProgress is not a function
zigbee.0 | 2024-05-24 17:34:55.488 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
zigbee.0 | 2024-05-24 17:34:54.569 | info | Start firmware update for 0x7cb03exxxxxxxx


</body>
</html>`

**Comment by arteck** [comment]
check again with new converter

**Comment by dimaiv7** [comment]
Nein, funktioniert immer noch nicht. Stürzt ab mit gleichem Fehler.

**Comment by goldoliver** [comment]
same here..

latest version installed before I tried..

**Comment by arteck** [comment]
bei mir gehts mit der GIT version
![grafik](https://github.com/ioBroker/ioBroker.zigbee/assets/6681528/aa575653-27ec-486a-9fc2-3b95f5065bfb)

für eine HUE Lampe

**Comment by Madaraxa** [comment]
Hab gerade die github Version installiert (1.10.4 wird jetzt angezeigt). Leider bei mir auch noch sehr viele Fehler wie weiter oben genannt. Log zeigt 99+ error an nach ein paar Sekunden und zigbee Adapter wird gestoppt

**Comment by arteck** [comment]
dann hastdu nicht die GIT version

**Comment by Madaraxa** [comment]
Hmm. Ok. Ich hab im iobroker den Expertenmodus aktiviert und bin dann bei Adapter - zigbee auf die katze oben gegangen Und hab bei github nach zigbee gesucht. War das falsch?

**Comment by fraggle-iw** [comment]
Had the same issue. Updated js-controller to 5.0.19. Now works as supposed.

**Comment by goldoliver** [comment]
I just tried again, zigbee and js up to date.
Seems like some devices do the update and some lead to a crash of the instance like described in my last message :(

**Comment by Madaraxa** [comment]
> dann hast du nicht die GIT version

Du hattest damit zwar nicht recht, aber es war ein anderer Fehler. Mit der Github Version 1.10.4 läuft es ohne Fehler (JS-Controller 6.0.4). Sorry... ich hatte den Zigbee Stick zu nah am "Host", da ich ihn zum putzen bewegt habe und nicht dran gedacht hatte ihn wieder weiter weg zu legen... Das Kabel hat gerade mal 1m Länge, aber die ist entscheidend 

English:
With the Github Version 1.10.4 everything works fine here
`<html><body>

zigbee.0 | 2024-06-17 12:04:19.168 | info | Failed to check if update available for '0x2c1165fffe8a05ce' Device didn't respond to OTA request
-- | -- | -- | --
zigbee.0 | 2024-06-17 12:04:19.165 | info | Failed to check if update available for '0x680ae2fffef98676' Device didn't respond to OTA request
zigbee.0 | 2024-06-17 12:03:19.521 | info | current Firmware for 0x04cf8cdf3c7e2910 is 24 new is 22
zigbee.0 | 2024-06-17 12:03:19.493 | info | current Firmware for 0x04cf8cdf3c7b00ca is 24 new is 22
zigbee.0 | 2024-06-17 12:03:19.473 | info | current Firmware for 0x04cf8cdf3c7b18f1 is 24 new is 22
zigbee.0 | 2024-06-17 12:03:19.422 | info | Failed to check if update available for '0x2c1165fffe7d68a2' Device didn't respond to OTA request
zigbee.0 | 2024-06-17 12:03:12.990 | info | List  of port: [{"path":"/dev/ttyACM0","manufacturer":"Texas  Instruments","pnpId":"usb-Texas_Instruments_CC2538_USB_CDC-if00","vendorId":"0451","productId":"16c8"},{"path":"/dev/ttyS0"},{"path":"/dev/ttyS1"},{"path":"/dev/ttyS2"},{"path":"/dev/ttyS3"}]


</body>
</html>`

**Comment by arteck** [comment]
@goldoliver 
> some lead to a crash of the instance like described in my last message :(

which devices ?? i've testet it with a hue bulb..

**Comment by goldoliver** [comment]
It was a normal IKEA bulb.. but it's very weird.. after some successfull updates of other devices, also these which led to crash before were updateable. Now it seems to work in most cases. Some of the battery powered devices like IKEA buttons are not working well, but at least they try to get updated without crashing the instance  ;-)

**Comment by PaulEins** [comment]
Ich habe gerade ein neues Synology NAS mit meuem Docker aufgesetzt und ioBroker darauf.
ioBroker-Zigbee-ZHA Adapter hat Version: v1.10.3
Es verwendet die Antenne SLZB-06 auf aktueller Version.
ioBroker ist alles aktuell. (gerade frisch Clean install)

`
Failed to check if update available for '0x8c6fb9fffe642632' Converting circular structure to JSON --> starting at object with constructor 'DerivedLogger' \| property '_readableState' -> object with constructor 'ReadableState' \| property 'pipes' -> object with constructor 'Array' \| index 0 -> object with constructor 'DailyRotateFile' --- property 'parent' closes the circle
--
 

<br class="Apple-interchange-newline">`

**Comment by make0815** [comment]
Hallo, weis jemand, mit welcher vorherigen Version das OTA Update noch funktioniert hat?
Und könnte diese Version über die 1.10.3 drüberinstalliert werden?

**Comment by fraggle-iw** [comment]
> Hallo, weis jemand, mit welcher vorherigen Version das OTA Update noch funktioniert hat? Und könnte diese Version über die 1.10.3 drüberinstalliert werden?

Hallo,
mit der 1.10.13 habe ich gestern noch IKEA Deices aktualisiert.

Grüße, fraggle_iw

**Comment by make0815** [comment]
> Hallo, mit der 1.10.13 habe ich gestern noch IKEA Devices aktualisiert.
> 
> Grüße, fraggle_iw

Hallo, 
diese Version ist noch nicht offiziell freigegeben. Daher möchte ich sie nicht insatllieren.
Ich weis aber, dass es mit einer Vorgängerversion noch funktioniert hat. Aber mit welcher weis ich nicht mehr.
Könnte das die 1.9.7 oder die 1.10.0 gewesen sein?

**Comment by Flothoger** [comment]
Version 1.10.0 is working fine with OTA Updates

**Comment by make0815** [comment]
> Version 1.10.0 is working fine with OTA Updates

@Flothoger, thanks for the reply. Can I install V1.10.0 over the the V1.10.3 without any problems?

**Comment by Flothoger** [comment]
> > Version 1.10.0 is working fine with OTA Updates
> 
> @Flothoger, thanks for the reply. Can I install V1.10.0 over the the V1.10.3 without any problems?

I can’t speak for your setup but downgrading from 1.10.3 worked for me. I downgraded since I also had issues with the OTA.

**Comment by make0815** [comment]
Thank you!

**Comment by make0815** [comment]
I have downgraded to V1.10.0 without any problems. OTA works now again.
