### ISSUE TITLE
New devices cant be paired (old devices wont repair)

### ISSUE THREAD

**Issue by Madaraxa** [ioBroker/ioBroker.zigbee#2149]
Im on Js-Controller 6.0.4 and zigbee adapter 1.10.3 (1.10.4 has same issues).
I noticed, that my 3 tradfri repeater are shown offline and 2 of my 7 GU10 RGB Tradfri bulbs as well.
When i try to reconnect the GU10 again (putting them in pairing mode first) i get the following log:

`<html><body>

zigbee.0 | 2024-06-17 11:29:40.560 | warn | DeviceAvailability:Stopping to ping 0x680ae2fffef98ec7 TRADFRI Signal Repeater after 4 ping attempts
-- | -- | -- | --
zigbee.0 | 2024-06-17 11:21:52.794 | error | Failed to interview '0x2c1165fffe7d55cd', device has not successfully been paired. Try again !!!!!!!!!!
zigbee.0 | 2024-06-17 11:21:47.630 | error | Failed to interview '0x2c1165fffe2cd033', device has not successfully been paired. Try again !!!!!!!!!!
zigbee.0 | 2024-06-17 11:19:14.135 | error | Error  225 on send command to 0x2c1165fffe7d68a2. Error: Error: ZCL command  0x2c1165fffe7d68a2/1  genLevelCtrl.moveToLevelWithOnOff({"level":203,"transtime":0},  {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})  failed (Data request failed with error: 'MAC channel access failure'  (225))    at ZStackAdapter.sendZclFrameToEndpointInternal  (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:411:23)     at Queue.execute  (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)     at Request.send  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)     at Endpoint.zclCommand  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:756:28)     at Endpoint.command  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:587:24)     at Object.convertSet  (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:1152:13)     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:754:36
zigbee.0 | 2024-06-17 11:19:07.055 | error | Error  225 on send command to 0x2c1165fffe9542d9. Error: Error: ZCL command  0x2c1165fffe9542d9/1  genLevelCtrl.moveToLevelWithOnOff({"level":203,"transtime":0},  {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})  failed (Data request failed with error: 'MAC channel access failure'  (225))    at ZStackAdapter.sendZclFrameToEndpointInternal  (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:411:23)     at Queue.execute  (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)     at Request.send  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)     at Endpoint.zclCommand  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:756:28)     at Endpoint.command  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:587:24)     at Object.convertSet  (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:1152:13)     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:754:36
zigbee.0 | 2024-06-17 11:19:05.856 | error | Error  225 on send command to 0x2c1165fffe85b3f6. Error: Error: ZCL command  0x2c1165fffe85b3f6/1  genLevelCtrl.moveToLevelWithOnOff({"level":203,"transtime":0},  {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})  failed (Data request failed with error: 'MAC channel access failure'  (225))    at ZStackAdapter.sendZclFrameToEndpointInternal  (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:411:23)     at Queue.execute  (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)     at Request.send  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)     at Endpoint.zclCommand  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:756:28)     at Endpoint.command  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:587:24)     at Object.convertSet  (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:1152:13)     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:754:36
zigbee.0 | 2024-06-17 11:18:58.527 | error | Error  225 on send command to 0x2c1165fffe8a05ce. Error: Error: ZCL command  0x2c1165fffe8a05ce/1  genLevelCtrl.moveToLevelWithOnOff({"level":203,"transtime":0},  {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})  failed (Data request failed with error: 'MAC channel access failure'  (225))    at ZStackAdapter.sendZclFrameToEndpointInternal  (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:411:23)     at Queue.execute  (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)     at Request.send  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)     at Endpoint.zclCommand  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:756:28)     at Endpoint.command  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:587:24)     at Object.convertSet  (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:1152:13)     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:754:36
zigbee.0 | 2024-06-17 11:18:57.624 | error | Error  225 on send command to 0x2c1165fffe94ad5d. Error: Error: ZCL command  0x2c1165fffe94ad5d/1  genLevelCtrl.moveToLevelWithOnOff({"level":203,"transtime":0},  {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})  failed (Data request failed with error: 'MAC channel access failure'  (225))    at ZStackAdapter.sendZclFrameToEndpointInternal  (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:411:23)     at Queue.execute  (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)     at Request.send  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)     at Endpoint.zclCommand  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:756:28)     at Endpoint.command  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:587:24)     at Object.convertSet  (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:1152:13)     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:754:36
zigbee.0 | 2024-06-17 11:18:50.219 | error | Error  225 on send command to 0x2c1165fffe7d68a2. Error: Error: ZCL command  0x2c1165fffe7d68a2/1  lightingColorCtrl.moveToColor({"transtime":0,"colorx":30137,"colory":26909},   {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})  failed (Data request failed with error: 'MAC channel access failure'  (225))    at ZStackAdapter.sendZclFrameToEndpointInternal  (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:411:23)     at Queue.execute  (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)     at Request.send  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)     at Endpoint.zclCommand  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:756:28)     at Endpoint.command  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:587:24)     at Object.convertSet  (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:969:17)     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:754:36
zigbee.0 | 2024-06-17 11:18:49.347 | error | Error  225 on send command to 0x2c1165fffe9542d9. Error: Error: ZCL command  0x2c1165fffe9542d9/1  lightingColorCtrl.moveToColor({"transtime":0,"colorx":30137,"colory":26909},   {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})  failed (Data request failed with error: 'MAC channel access failure'  (225))    at ZStackAdapter.sendZclFrameToEndpointInternal  (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:411:23)     at Queue.execute  (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)     at Request.send  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)     at Endpoint.zclCommand  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:756:28)     at Endpoint.command  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:587:24)     at Object.convertSet  (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:969:17)     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:754:36
zigbee.0 | 2024-06-17 11:18:41.944 | error | Error  225 on send command to 0x2c1165fffe85b3f6. Error: Error: ZCL command  0x2c1165fffe85b3f6/1  lightingColorCtrl.moveToColor({"transtime":0,"colorx":30137,"colory":26909},   {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})  failed (Data request failed with error: 'MAC channel access failure'  (225))    at ZStackAdapter.sendZclFrameToEndpointInternal  (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:411:23)     at Queue.execute  (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)     at Request.send  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)     at Endpoint.zclCommand  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:756:28)     at Endpoint.command  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:587:24)     at Object.convertSet  (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:969:17)     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:754:36
zigbee.0 | 2024-06-17 11:18:41.096 | error | Error  225 on send command to 0x2c1165fffe8a05ce. Error: Error: ZCL command  0x2c1165fffe8a05ce/1  lightingColorCtrl.moveToColor({"transtime":0,"colorx":30137,"colory":26909},   {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})  failed (Data request failed with error: 'MAC channel access failure'  (225))    at ZStackAdapter.sendZclFrameToEndpointInternal  (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:411:23)     at Queue.execute  (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)     at Request.send  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)     at Endpoint.zclCommand  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:756:28)     at Endpoint.command  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:587:24)     at Object.convertSet  (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:969:17)     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:754:36
zigbee.0 | 2024-06-17 11:18:33.648 | error | Error  225 on send command to 0x2c1165fffe94ad5d. Error: Error: ZCL command  0x2c1165fffe94ad5d/1  lightingColorCtrl.moveToColor({"transtime":0,"colorx":30137,"colory":26909},   {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})  failed (Data request failed with error: 'MAC channel access failure'  (225))    at ZStackAdapter.sendZclFrameToEndpointInternal  (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:411:23)     at Queue.execute  (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)     at Request.send  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)     at Endpoint.zclCommand  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:756:28)     at Endpoint.command  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:587:24)     at Object.convertSet  (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:969:17)     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:754:36
zigbee.0 | 2024-06-17 11:18:32.841 | error | Error  225 on send command to 0x2c1165fffe7d68a2. Error: Error: ZCL command  0x2c1165fffe7d68a2/1  genLevelCtrl.moveToLevelWithOnOff({"level":203,"transtime":0},  {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})  failed (Data request failed with error: 'MAC channel access failure'  (225))    at ZStackAdapter.sendZclFrameToEndpointInternal  (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:411:23)     at Queue.execute  (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)     at Request.send  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)     at Endpoint.zclCommand  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:756:28)     at Endpoint.command  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:587:24)     at Object.convertSet  (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:1152:13)     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:754:36
zigbee.0 | 2024-06-17 11:18:25.448 | error | Error  225 on send command to 0x2c1165fffe9542d9. Error: Error: ZCL command  0x2c1165fffe9542d9/1  genLevelCtrl.moveToLevelWithOnOff({"level":203,"transtime":0},  {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})  failed (Data request failed with error: 'MAC channel access failure'  (225))    at ZStackAdapter.sendZclFrameToEndpointInternal  (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:411:23)     at Queue.execute  (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)     at Request.send  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)     at Endpoint.zclCommand  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:756:28)     at Endpoint.command  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:587:24)     at Object.convertSet  (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:1152:13)     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:754:36
zigbee.0 | 2024-06-17 11:18:24.594 | error | Error  225 on send command to 0x2c1165fffe85b3f6. Error: Error: ZCL command  0x2c1165fffe85b3f6/1  genLevelCtrl.moveToLevelWithOnOff({"level":203,"transtime":0},  {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})  failed (Data request failed with error: 'MAC channel access failure'  (225))    at ZStackAdapter.sendZclFrameToEndpointInternal  (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:411:23)     at Queue.execute  (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)     at Request.send  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)     at Endpoint.zclCommand  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:756:28)     at Endpoint.command  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:587:24)     at Object.convertSet  (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:1152:13)     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:754:36
zigbee.0 | 2024-06-17 11:18:17.225 | error | Error  225 on send command to 0x2c1165fffe8a05ce. Error: Error: ZCL command  0x2c1165fffe8a05ce/1  genLevelCtrl.moveToLevelWithOnOff({"level":203,"transtime":0},  {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})  failed (Data request failed with error: 'MAC channel access failure'  (225))    at ZStackAdapter.sendZclFrameToEndpointInternal  (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:411:23)     at Queue.execute  (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)     at Request.send  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)     at Endpoint.zclCommand  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:756:28)     at Endpoint.command  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:587:24)     at Object.convertSet  (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:1152:13)     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:754:36
zigbee.0 | 2024-06-17 11:18:16.330 | error | Error  225 on send command to 0x2c1165fffe94ad5d. Error: Error: ZCL command  0x2c1165fffe94ad5d/1  genLevelCtrl.moveToLevelWithOnOff({"level":203,"transtime":0},  {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})  failed (Data request failed with error: 'MAC channel access failure'  (225))    at ZStackAdapter.sendZclFrameToEndpointInternal  (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:411:23)     at Queue.execute  (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)     at Request.send  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)     at Endpoint.zclCommand  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:756:28)     at Endpoint.command  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:587:24)     at Object.convertSet  (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:1152:13)     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:754:36
zigbee.0 | 2024-06-17 11:18:09.010 | error | Error  225 on send command to 0x2c1165fffe7d68a2. Error: Error: ZCL command  0x2c1165fffe7d68a2/1  lightingColorCtrl.moveToColor({"transtime":0,"colorx":30137,"colory":26909},   {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})  failed (Data request failed with error: 'MAC channel access failure'  (225))    at ZStackAdapter.sendZclFrameToEndpointInternal  (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:411:23)     at Queue.execute  (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)     at Request.send  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)     at Endpoint.zclCommand  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:756:28)     at Endpoint.command  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:587:24)     at Object.convertSet  (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:969:17)     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:754:36
zigbee.0 | 2024-06-17 11:18:07.047 | error | Error  225 on send command to 0x2c1165fffe9542d9. Error: Error: ZCL command  0x2c1165fffe9542d9/1  lightingColorCtrl.moveToColor({"transtime":0,"colorx":30137,"colory":26909},   {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})  failed (Data request failed with error: 'MAC channel access failure'  (225))    at ZStackAdapter.sendZclFrameToEndpointInternal  (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:411:23)     at Queue.execute  (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)     at Request.send  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)     at Endpoint.zclCommand  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:756:28)     at Endpoint.command  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:587:24)     at Object.convertSet  (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:969:17)     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:754:36
zigbee.0 | 2024-06-17 11:17:59.711 | error | Error  225 on send command to 0x2c1165fffe85b3f6. Error: Error: ZCL command  0x2c1165fffe85b3f6/1  lightingColorCtrl.moveToColor({"transtime":0,"colorx":30137,"colory":26909},   {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})  failed (Data request failed with error: 'MAC channel access failure'  (225))    at ZStackAdapter.sendZclFrameToEndpointInternal  (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:411:23)     at Queue.execute  (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)     at Request.send  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)     at Endpoint.zclCommand  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:756:28)     at Endpoint.command  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:587:24)     at Object.convertSet  (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:969:17)     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:754:36
zigbee.0 | 2024-06-17 11:17:58.501 | error | Error  225 on send command to 0x2c1165fffe8a05ce. Error: Error: ZCL command  0x2c1165fffe8a05ce/1  lightingColorCtrl.moveToColor({"transtime":0,"colorx":30137,"colory":26909},   {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})  failed (Data request failed with error: 'MAC channel access failure'  (225))    at ZStackAdapter.sendZclFrameToEndpointInternal  (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:411:23)     at Queue.execute  (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)     at Request.send  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)     at Endpoint.zclCommand  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:756:28)     at Endpoint.command  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:587:24)     at Object.convertSet  (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:969:17)     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:754:36
zigbee.0 | 2024-06-17 11:17:51.465 | error | Error  225 on send command to 0x2c1165fffe94ad5d. Error: Error: ZCL command  0x2c1165fffe94ad5d/1  lightingColorCtrl.moveToColor({"transtime":0,"colorx":30137,"colory":26909},   {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})  failed (Data request failed with error: 'MAC channel access failure'  (225))    at ZStackAdapter.sendZclFrameToEndpointInternal  (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:411:23)     at Queue.execute  (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)     at Request.send  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)     at Endpoint.zclCommand  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:756:28)     at Endpoint.command  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:587:24)     at Object.convertSet  (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:969:17)     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:754:36
zigbee.0 | 2024-06-17 11:17:50.218 | error | Error  225 on send command to 0x2c1165fffe7d68a2. Error: Error: ZCL command  0x2c1165fffe7d68a2/1  genLevelCtrl.moveToLevelWithOnOff({"level":203,"transtime":0},  {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})  failed (Data request failed with error: 'MAC channel access failure'  (225))    at ZStackAdapter.sendZclFrameToEndpointInternal  (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:411:23)     at Queue.execute  (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)     at Request.send  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)     at Endpoint.zclCommand  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:756:28)     at Endpoint.command  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:587:24)     at Object.convertSet  (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:1152:13)     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:754:36
zigbee.0 | 2024-06-17 11:17:43.229 | error | Error  225 on send command to 0x2c1165fffe9542d9. Error: Error: ZCL command  0x2c1165fffe9542d9/1  genLevelCtrl.moveToLevelWithOnOff({"level":203,"transtime":0},  {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})  failed (Data request failed with error: 'MAC channel access failure'  (225))    at ZStackAdapter.sendZclFrameToEndpointInternal  (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:411:23)     at Queue.execute  (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)     at Request.send  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20)     at Endpoint.zclCommand  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:756:28)     at Endpoint.command  (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:587:24)     at Object.convertSet  (/opt/iobroker/node_modules/zigbee-herdsman-converters/src/converters/toZigbee.ts:1152:13)     at /opt/iobroker/node_modules/iobroker.zigbee/main.js:754:36

</body>
</html>`

I also have an unpaired aqara door sensor. When trying to pair it it just wont show up in the log. I already have 5 door sensor of aqara here, 3 aqara switches, 2 aqara repeater (wall plugs) and an aqara vibration sensor.. all are paired and work fine.
I tried to re-pair one tradfri repeater resulting in the repeater to be deleted in the zigbee adapter. So i didnt try the other two yet.

**Comment by Madaraxa** [comment]
nevermind.. i just moved the zigbee stick 1 meter and everything seems to work again... I remembered just after opening the issue, that i had to move it to clean and forgot to move it back...
