### ISSUE TITLE
Adapter startet nach Ausfall des Koordinators nicht neu

### ISSUE THREAD

**Issue by Standarduser** [ioBroker/ioBroker.zigbee#2160]
Ich nutze den cod.m Zigbee Coordinator per Netzwerk, was im Grunde sehr gut funktioniert.

Wenn jedoch die Verbindung zum Coordinator ausfällt (zum Beispiel durch Trennen der Netzwerkverbindung) und anschließend wiederhergestellt wird, bleibt der Adapter im Status "Nicht verbunden mit Gerät oder Dienst" hängen. Es hilft lediglich ein manueller Neustart des Adapters. Außerdem wird das Logfile massiv vollgeschrieben (85 Meldungen pro Sekunde).

Ich fände es großartig, wenn der Adapter sich selbst wieder fangen könnte, da das doch eine sehr große Einschränkung in der Verfügbarkeit und Zuverlässigkeit darstellt.

```
2024-07-05 15:07:04.353 - error: zigbee.0 (597047) Adapter disconnected, stopping
2024-07-05 15:07:32.778 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:07:32.779 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:07:32.779 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:07:45.859 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:07:45.860 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:07:45.860 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:07:58.946 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:07:58.947 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:07:58.948 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:08:12.033 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:08:12.034 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:08:12.034 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:08:25.121 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:08:25.122 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:08:25.122 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:08:38.181 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:08:38.181 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:08:38.182 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:09:45.120 - error: zigbee.0 (597047) Adapter disconnected, stopping
2024-07-05 15:09:45.121 - error: zigbee.0 (597047) Adapter disconnected, stopping
2024-07-05 15:09:45.123 - error: zigbee.0 (597047) Adapter disconnected, stopping
2024-07-05 15:09:45.124 - error: zigbee.0 (597047) Adapter disconnected, stopping
2024-07-05 15:09:45.125 - error: zigbee.0 (597047) Adapter disconnected, stopping
2024-07-05 15:09:45.127 - error: zigbee.0 (597047) Adapter disconnected, stopping
2024-07-05 15:09:45.129 - error: zigbee.0 (597047) Adapter disconnected, stopping
2024-07-05 15:09:45.130 - error: zigbee.0 (597047) Adapter disconnected, stopping
2024-07-05 15:09:58.210 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:09:58.210 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:09:58.211 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:09:58.217 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:09:58.218 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:09:58.218 - error: zigbee.0 (597047) Error herdsman start

...

2024-07-05 15:13:27.618 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:13:27.618 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:13:27.618 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:13:27.623 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:13:27.623 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:13:27.623 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:13:27.630 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:13:27.630 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:13:27.631 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:13:40.678 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Cannot read properties of undefined (reading 'execute')"
2024-07-05 15:13:40.678 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:13:40.678 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:13:40.688 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Cannot read properties of undefined (reading 'execute')"
2024-07-05 15:13:40.688 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:13:40.688 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:13:40.695 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Cannot read properties of undefined (reading 'execute')"
2024-07-05 15:13:40.695 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:13:40.695 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:13:40.712 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:13:40.713 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:13:40.713 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:13:40.718 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:13:40.718 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:13:40.718 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:13:40.724 - error: zigbee.0 (597047) Adapter disconnected, stopping
2024-07-05 15:13:40.725 - error: zigbee.0 (597047) Adapter disconnected, stopping
2024-07-05 15:13:40.726 - error: zigbee.0 (597047) Adapter disconnected, stopping
2024-07-05 15:13:40.727 - error: zigbee.0 (597047) Adapter disconnected, stopping
2024-07-05 15:13:40.728 - error: zigbee.0 (597047) Adapter disconnected, stopping

...

2024-07-05 15:13:41.338 - error: zigbee.0 (597047) Adapter disconnected, stopping
2024-07-05 15:13:41.339 - error: zigbee.0 (597047) Adapter disconnected, stopping
2024-07-05 15:13:41.339 - error: zigbee.0 (597047) Adapter disconnected, stopping
2024-07-05 15:13:41.342 - error: zigbee.0 (597047) Adapter disconnected, stopping
2024-07-05 15:13:41.343 - error: zigbee.0 (597047) Adapter disconnected, stopping
2024-07-05 15:13:41.344 - error: zigbee.0 (597047) Adapter disconnected, stopping
2024-07-05 15:13:41.973 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Cannot read properties of undefined (reading 'execute')"
2024-07-05 15:13:41.973 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:13:41.973 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:13:41.980 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Cannot read properties of undefined (reading 'execute')"
2024-07-05 15:13:41.980 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:13:41.981 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:13:50.708 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:13:50.709 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:13:50.709 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:13:50.714 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:13:50.714 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:13:50.714 - error: zigbee.0 (597047) Error herdsman start

...

2024-07-05 15:15:03.013 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:03.013 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:03.013 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:03.027 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)"
2024-07-05 15:15:03.027 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:03.027 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:03.081 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:03.081 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:03.081 - error: zigbee.0 (597047) Error herdsman start

...

2024-07-05 15:15:09.250 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:09.252 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:09.253 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:09.265 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:09.265 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:09.265 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:09.375 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)"
2024-07-05 15:15:09.376 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:09.376 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:09.390 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:09.390 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:09.390 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:09.733 - warn: zigbee.0 (597047) Failed to stop zigbee during startup
2024-07-05 15:15:09.769 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)"
2024-07-05 15:15:09.769 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:09.769 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:09.901 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:09.901 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:09.901 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:10.606 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:10.606 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:10.607 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:10.617 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:10.617 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:10.617 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:10.621 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:10.621 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:10.621 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:10.653 - warn: zigbee.0 (597047) get state error: DB closed
2024-07-05 15:15:10.653 - warn: zigbee.0 (597047) get state error: DB closed
2024-07-05 15:15:10.665 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:10.665 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:10.665 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:10.676 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:10.676 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:10.676 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:10.680 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:10.680 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:10.680 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:10.684 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:10.684 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:10.684 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:10.744 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:10.744 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:10.745 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:10.768 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:10.768 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:10.768 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:10.769 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:10.769 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:10.769 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:10.769 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:10.769 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:10.769 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:10.771 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:10.771 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:10.771 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:10.774 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:10.774 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:10.774 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:10.929 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:10.929 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:10.930 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:10.931 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:10.931 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:10.932 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:10.932 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:10.932 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:10.932 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:10.945 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:10.945 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:10.945 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:10.949 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:10.949 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:10.949 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:10.953 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:10.953 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:10.953 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:10.957 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:10.957 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:10.957 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:10.960 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:10.961 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:10.961 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:10.972 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:10.973 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:10.973 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:10.973 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:10.973 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:10.973 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:10.973 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:10.973 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:10.992 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:10.993 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:10.993 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:10.993 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:10.993 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:10.993 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:10.993 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:10.993 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:10.993 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:10.993 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:10.993 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:10.993 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:11.000 - warn: zigbee.0 (597047) Could not perform strict object check of state zigbee.0.info.pairingMessage: DB closed
2024-07-05 15:15:11.000 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:11.000 - warn: zigbee.0 (597047) Could not perform strict object check of state zigbee.0.info.connection: DB closed
2024-07-05 15:15:11.001 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:11.001 - warn: zigbee.0 (597047) Could not perform strict object check of state zigbee.0.info.pairingMessage: DB closed
2024-07-05 15:15:11.001 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:11.001 - warn: zigbee.0 (597047) Could not perform strict object check of state zigbee.0.info.connection: DB closed
2024-07-05 15:15:11.001 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:11.001 - warn: zigbee.0 (597047) Could not perform strict object check of state zigbee.0.info.pairingMessage: DB closed
2024-07-05 15:15:11.001 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:11.001 - warn: zigbee.0 (597047) Could not perform strict object check of state zigbee.0.info.connection: DB closed
2024-07-05 15:15:11.001 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:11.001 - warn: zigbee.0 (597047) Could not perform strict object check of state zigbee.0.info.pairingMessage: DB closed
2024-07-05 15:15:11.001 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:11.001 - warn: zigbee.0 (597047) Could not perform strict object check of state zigbee.0.info.connection: DB closed
2024-07-05 15:15:11.003 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:11.003 - warn: zigbee.0 (597047) Could not perform strict object check of state zigbee.0.info.pairingMessage: DB closed
2024-07-05 15:15:11.004 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:11.004 - warn: zigbee.0 (597047) Could not perform strict object check of state zigbee.0.info.connection: DB closed
2024-07-05 15:15:11.004 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:11.004 - warn: zigbee.0 (597047) Could not perform strict object check of state zigbee.0.info.pairingMessage: DB closed
2024-07-05 15:15:11.004 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:11.004 - warn: zigbee.0 (597047) Could not perform strict object check of state zigbee.0.info.connection: DB closed
2024-07-05 15:15:11.004 - warn: zigbee.0 (597047) get state error: Connection is closed.
2024-07-05 15:15:11.006 - error: zigbee.0 (597047) uncaught exception: Cannot read properties of undefined (reading 'common')
2024-07-05 15:15:11.006 - error: zigbee.0 (597047) TypeError: Cannot read properties of undefined (reading 'common')
at Immediate. (/opt/iobroker/node_modules/iobroker.zigbee/main.js:311:35)
at processImmediate (node:internal/timers:478:21)
2024-07-05 15:15:11.006 - error: zigbee.0 (597047) Cannot read properties of undefined (reading 'common')
2024-07-05 15:15:11.010 - error: zigbee.0 (597047) uncaught exception: Cannot read properties of undefined (reading 'common')
2024-07-05 15:15:11.010 - error: zigbee.0 (597047) TypeError: Cannot read properties of undefined (reading 'common')
at Immediate. (/opt/iobroker/node_modules/iobroker.zigbee/main.js:311:35)
at processImmediate (node:internal/timers:478:21)
2024-07-05 15:15:11.010 - error: zigbee.0 (597047) Cannot read properties of undefined (reading 'common')
2024-07-05 15:15:11.017 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:11.017 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:11.017 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:11.019 - error: zigbee.0 (597047) uncaught exception: Cannot read properties of undefined (reading 'common')
2024-07-05 15:15:11.019 - error: zigbee.0 (597047) TypeError: Cannot read properties of undefined (reading 'common')
at Immediate. (/opt/iobroker/node_modules/iobroker.zigbee/main.js:311:35)
at processImmediate (node:internal/timers:478:21)
2024-07-05 15:15:11.019 - error: zigbee.0 (597047) Cannot read properties of undefined (reading 'common')
2024-07-05 15:15:11.024 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:11.024 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:11.024 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:11.032 - error: zigbee.0 (597047) uncaught exception: Cannot read properties of undefined (reading 'common')
2024-07-05 15:15:11.032 - error: zigbee.0 (597047) TypeError: Cannot read properties of undefined (reading 'common')
at Immediate. (/opt/iobroker/node_modules/iobroker.zigbee/main.js:311:35)
at processImmediate (node:internal/timers:478:21)
2024-07-05 15:15:11.032 - error: zigbee.0 (597047) Cannot read properties of undefined (reading 'common')
2024-07-05 15:15:11.036 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:11.036 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:11.036 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:11.049 - error: zigbee.0 (597047) uncaught exception: Cannot read properties of undefined (reading 'common')
2024-07-05 15:15:11.049 - error: zigbee.0 (597047) TypeError: Cannot read properties of undefined (reading 'common')
at Immediate. (/opt/iobroker/node_modules/iobroker.zigbee/main.js:311:35)
at processImmediate (node:internal/timers:478:21)
2024-07-05 15:15:11.049 - error: zigbee.0 (597047) Cannot read properties of undefined (reading 'common')
2024-07-05 15:15:11.054 - error: zigbee.0 (597047) Starting zigbee-herdsman problem : "Error while opening socket"
2024-07-05 15:15:11.054 - error: zigbee.0 (597047) Failed to start Zigbee
2024-07-05 15:15:11.054 - error: zigbee.0 (597047) Error herdsman start
2024-07-05 15:15:11.677 - error: host.srv-iobroker1 Caught by controller[1]: zh:controller: Failed to disable join on stop: TypeError: Cannot read properties of undefined (reading 'execute')
2024-07-05 15:15:11.678 - error: host.srv-iobroker1 Caught by controller[2]: TypeError: Cannot read properties of undefined (reading 'common')
2024-07-05 15:15:11.679 - error: host.srv-iobroker1 Caught by controller[2]: at Immediate. (/opt/iobroker/node_modules/iobroker.zigbee/main.js:311:35)
2024-07-05 15:15:11.679 - error: host.srv-iobroker1 Caught by controller[2]: at processImmediate (node:internal/timers:478:21)
2024-07-05 15:15:11.679 - error: host.srv-iobroker1 Caught by controller[2]: TypeError: Cannot read properties of undefined (reading 'common')
2024-07-05 15:15:11.679 - error: host.srv-iobroker1 Caught by controller[2]: at Immediate. (/opt/iobroker/node_modules/iobroker.zigbee/main.js:311:35)
2024-07-05 15:15:11.679 - error: host.srv-iobroker1 Caught by controller[2]: at processImmediate (node:internal/timers:478:21)
2024-07-05 15:15:11.679 - error: host.srv-iobroker1 Caught by controller[2]: TypeError: Cannot read properties of undefined (reading 'common')
2024-07-05 15:15:11.679 - error: host.srv-iobroker1 Caught by controller[2]: at Immediate. (/opt/iobroker/node_modules/iobroker.zigbee/main.js:311:35)
2024-07-05 15:15:11.679 - error: host.srv-iobroker1 Caught by controller[2]: at processImmediate (node:internal/timers:478:21)
2024-07-05 15:15:11.679 - error: host.srv-iobroker1 Caught by controller[2]: TypeError: Cannot read properties of undefined (reading 'common')
2024-07-05 15:15:11.679 - error: host.srv-iobroker1 Caught by controller[2]: at Immediate. (/opt/iobroker/node_modules/iobroker.zigbee/main.js:311:35)
2024-07-05 15:15:11.679 - error: host.srv-iobroker1 Caught by controller[2]: at processImmediate (node:internal/timers:478:21)
2024-07-05 15:15:11.679 - error: host.srv-iobroker1 Caught by controller[2]: TypeError: Cannot read properties of undefined (reading 'common')
2024-07-05 15:15:11.679 - error: host.srv-iobroker1 Caught by controller[2]: at Immediate. (/opt/iobroker/node_modules/iobroker.zigbee/main.js:311:35)
2024-07-05 15:15:11.679 - error: host.srv-iobroker1 Caught by controller[2]: at processImmediate (node:internal/timers:478:21)
```

**Comment by asgothian** [comment]
This is not easily done, as it requires the adapter to 
- identify that a connection is made via tcp/ip
- check if this connection is possible
- then restart with the current configuration.

As we do it currently, the pass the configuration for the device on to the zigbee-herdsman and rely on its response for further action. There is no internal check for connectivity

A.
