### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.zigbee#2192]
https://github.com/ioBroker/ioBroker.zigbee/blob/b9b1c4a2c76f96d9c2a9783e71155357855be51a/main.js#L694

```
2024-08-30 11:12:51.346 - error: zigbee.3 (3428664) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
--
2024-08-30 11:12:51.346 - error: zigbee.3 (3428664) unhandled promise rejection: Cannot read properties of undefined (reading 'includes')
2024-08-30 11:12:51.346 - error: zigbee.3 (3428664) TypeError: Cannot read properties of undefined (reading 'includes')
at /opt/iobroker/node_modules/iobroker.zigbee/main.js:694:78
at Array.find ()
at /opt/iobroker/node_modules/iobroker.zigbee/main.js:694:56
at Array.forEach ()
at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:634:23)
2024-08-30 11:12:51.347 - error: zigbee.3 (3428664) Cannot read properties of undefined (reading 'includes')
2024-08-30 11:12:51.352 - info: zigbee.3 (3428664) cleaned everything up...
2024-08-30 11:12:51.353 - info: zigbee.3 (3428664) Zigbee: disabling joining new devices.
2024-08-30 11:12:51.854 - info: zigbee.3 (3428664) terminating
2024-08-30 11:12:51.855 - warn: zigbee.3 (3428664) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-08-30 11:12:52.018 - info: zigbee.3 (3428664) terminating
2024-08-30 11:12:52.499 - error: host.ioBroker Caught by controller[1]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2024-08-30 11:12:52.499 - error: host.ioBroker Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'includes')
2024-08-30 11:12:52.499 - error: host.ioBroker Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.zigbee/main.js:694:78
2024-08-30 11:12:52.499 - error: host.ioBroker Caught by controller[1]: at Array.find ()
2024-08-30 11:12:52.499 - error: host.ioBroker Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.zigbee/main.js:694:56
2024-08-30 11:12:52.499 - error: host.ioBroker Caught by controller[1]: at Array.forEach ()
2024-08-30 11:12:52.499 - error: host.ioBroker Caught by controller[1]: at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:634:23)
2024-08-30 11:12:52.499 - error: host.ioBroker instance system.adapter.zigbee.3 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-08-30 11:12:52.499 - info: host.ioBroker Restart adapter system.adapter.zigbee.3 because enabled
2024-08-30 11:13:22.806 - info: host.ioBroker instance system.adapter.zigbee.3 in version "1.10.5" (non-npm: ioBroker/ioBroker.zigbee) started with pid 3428974
2024-08-30 11:13:23.860 - info: zigbee.3 (3428974) starting. Version 1.10.5 (non-npm: ioBroker/ioBroker.zigbee) in /opt/iobroker/node_modules/iobroker.zigbee, node: v20.15.0, js-controller: 6.0.11
2024-08-30 11:13:23.880 - info: zigbee.3 (3428974) delete old Backup files. keep only last 10
2024-08-30 11:13:23.880 - info: zigbee.3 (3428974) Starting Zigbee npm ...
2024-08-30 11:13:23.995 - info: zigbee.3 (3428974) Installed Version: ioBroker/ioBroker.zigbee
2024-08-30 11:13:39.621 - error: zigbee.3 (3428974) Starting zigbee-herdsman problem : "ASH_ERROR_TIMEOUTS"
2024-08-30 11:13:39.621 - error: zigbee.3 (3428974) Failed to start Zigbee
2024-08-30 11:13:39.621 - error: zigbee.3 (3428974) Error herdsman start
2024-08-30 11:13:39.905 - info: admin.0 (3427259) ==> Connected system.user.admin from ::ffff:192.168.0.23
2024-08-30 11:13:40.016 - error: zigbee.3 (3428974) getGroups: caught error: TypeError: Cannot read properties of undefined (reading 'getGroups')
2024-08-30 11:13:40.068 - info: zigbee.3 (3428974) List of port: [{"path":"/dev/ttyUSB0","manufacturer":"SMLIGHT","serialNumber":"f832a235b373ed1182ee66eefdf7b791","pnpId":"usb-SMLIGHT_SMLIGHT_SLZB-07_f832a235b373ed1182ee66eefdf7b791-if00-port0","vendorId":"10c4","productId":"ea60"},{"path":"/dev/ttyS0"},{"path":"/dev/ttyS1"},{"path":"/dev/ttyS2"},{"path":"/dev/ttyS3"}]
2024-08-30 11:13:43.207 - info: admin.0 (3427259) <== Disconnect system.user.admin from ::ffff:192.168.0.23
2024-08-30 11:13:49.622 - info: zigbee.3 (3428974) Try to reconnect. 1 attempts left
2024-08-30 11:13:49.623 - info: zigbee.3 (3428974) Starting Zigbee npm ...
2024-08-30 11:13:49.633 - info: zigbee.3 (3428974) Installed Version: ioBroker/ioBroker.zigbee
2024-08-30 11:13:49.697 - error: zigbee.3 (3428974) Starting zigbee-herdsman problem : "Failed to start EZSP layer with status=HOST_FATAL_ERROR."
2024-08-30 11:13:49.697 - error: zigbee.3 (3428974) Failed to start Zigbee
2024-08-30 11:13:49.697 - error: zigbee.3 (3428974) Error herdsman start
```

Ich habe die aktuelle Version vom Github installiert. Es stürzt einfach so ab.

Mod-Edit: corrected code tags

**Comment by asgothian** [comment]
Please put Logs into Code tags. That wall of log is next to unreadable.

**Comment by asgothian** [comment]
Bitte lass den Zigbee-Adapter seine States aufräumen (siehe Screenshot), Ich gehe davon aus das Du einen veralteten Eintrag in der Objekt-DB hast und es deswegen Probleme gibt.
<img width="374" alt="Screenshot 2024-08-30 at 16 06 02" src="https://github.com/user-attachments/assets/03f218c9-4e88-4600-9459-cd49636b539c">
Es sollte ein Log-Eintrag entstehen, der auflistet welche states gelöscht wurden, und welche nicht gelöscht wurden weil sie Konfigurationseinträge bei einem anderen Adapter (history, sql, upnp) haben. Diese bitte hier posten.

A.

**Comment by ldittmar81** [comment]
```
2024-08-31 10:42:11.730 - info: zigbee.3 (3429064) State cleanup with {"force":false}
2024-08-31 10:42:17.379 - info: zigbee.3 (3429064) deleting disconnected state "power_on_behavior" of 00158d0002a6f2c0
2024-08-31 10:42:17.379 - info: zigbee.3 (3429064) Method "deleteState" is deprecated and will be removed in js-controller 7, use "delObject" instead
```

Habs eben gemacht und das kam.

**Comment by asgothian** [comment]
Stürzt der Adapter weiterhin zufällig ab ?

**Comment by ldittmar81** [comment]
Bis jetzt noch nicht. Sollte man da aber nicht grundsätzlich prüfen ob c.key existiert, bevor man damit arbeitet?

**Comment by asgothian** [comment]
Das Problem ist nicht c.key. Auch macht die Meldung selber für mich wenig Sinn, da der Code-Block durchaus in ein try/catch eingebaut ist - sprich die Promise rejection kommt von tiefer aus der Bibliothek. Eine Verbindung zu dem nicht existenten State könnte darauf hin deuten das da etwas im argen liegt.

A.

**Comment by ldittmar81** [comment]
Hmm... ok... bis jetzt ist nichts mehr passiert. Scheint alles ganz normal wieder zu laufen. Wir könnten das Ticket schließen. Sollte wieder was sein oder sollte ich eine Eingebung haben, dann melde ich mich wieder.
