### ISSUE TITLE
Adapter chrash after assign Human Presence Sensor TUYA ZG-205Z

### ISSUE THREAD

**Issue by MiWoBln** [ioBroker/ioBroker.zigbee#2223]
Hi
i try to include an human presence sensor into my zigbee network. The pairing works without any issue and the device is correctly recognized.  After pairing the adapter chrashed with the error message below.

Admin: 7.1.5
JS-Controller 6.0.11
Zigbee: 1.10.9 (the device is not recognized in earlier versions)

Best Mirko

```
zigbee.0 | 2024-10-01 15:54:59.102 | info | Starting Zigbee npm ...
zigbee.0 | 2024-10-01 15:54:58.960 | info | starting. Version 1.10.9 (non-npm: ioBroker/ioBroker.zigbee) in /opt/iobroker/node_modules/iobroker.zigbee, node: v20.17.0, js-controller: 6.0.11
host.raspberrypi2 | 2024-10-01 15:54:53.785 | info | instance system.adapter.zigbee.0 in version "1.10.9" (non-npm: ioBroker/ioBroker.zigbee) started with pid 521121
host.raspberrypi2 | 2024-10-01 15:54:23.213 | info | Restart adapter system.adapter.zigbee.0 because enabled
host.raspberrypi2 | 2024-10-01 15:54:23.209 | error | instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.raspberrypi2 | 2024-10-01 15:54:23.209 | error | Caught by controller[1]: at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:634:23)
host.raspberrypi2 | 2024-10-01 15:54:23.209 | error | Caught by controller[1]: at Array.forEach (<anonymous>)
host.raspberrypi2 | 2024-10-01 15:54:23.209 | error | Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.zigbee/main.js:694:56
host.raspberrypi2 | 2024-10-01 15:54:23.209 | error | Caught by controller[1]: at Array.find (<anonymous>)
host.raspberrypi2 | 2024-10-01 15:54:23.209 | error | Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.zigbee/main.js:694:78
host.raspberrypi2 | 2024-10-01 15:54:23.208 | error | Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'includes')
host.raspberrypi2 | 2024-10-01 15:54:23.207 | error | Caught by controller[1]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
zigbee.0 | 2024-10-01 15:54:22.616 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee.0 | 2024-10-01 15:54:22.614 | info | terminating
zigbee.0 | 2024-10-01 15:54:22.115 | info | Zigbee: disabling joining new devices.
zigbee.0 | 2024-10-01 15:54:22.113 | info | cleaned everything up...
```

**Comment by asgothian** [comment]
please see issue #2211 for a possible solution
Note: There have been reports that a rollback to an earlier version will not work. In order to ensure that you do not fall into this problem, make a **manual** backup of the zigbee adapters datafiles (in \opt\iobroker\iobroker-data\zigbee_0) before installing the patched version from said issue. If the version does not work, you may have to restore said files after a downgrade to the current GitHub version.

Additional communication should be done in the linked issue
