### ISSUE TITLE
Zigbee Adapter chrash randomly

### ISSUE THREAD

**Issue by MiWoBln** [ioBroker/ioBroker.zigbee#2254]
From time to time (once or twice a day), the zigbee Adapter chrashes with the followig stacktrace:
```
host.raspberrypi2 | 2024-10-25 17:26:48.979 | error | instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.raspberrypi2 | 2024-10-25 17:26:48.979 | error | Caught by controller[2]: at Controller.onZclPayload (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/controller.ts:844:26)
host.raspberrypi2 | 2024-10-25 17:26:48.979 | error | Caught by controller[2]: at Controller.identifyUnknownDevice (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/controller.ts:543:26)
host.raspberrypi2 | 2024-10-25 17:26:48.979 | error | Caught by controller[2]: at ZStackAdapter.sendZdo (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:311:16)
host.raspberrypi2 | 2024-10-25 17:26:48.979 | error | Caught by controller[2]: at Queue.execute (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:36:20)
host.raspberrypi2 | 2024-10-25 17:26:48.979 | error | Caught by controller[2]: at /opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:403:47
host.raspberrypi2 | 2024-10-25 17:26:48.979 | error | Caught by controller[2]: at Object.start (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:59:23)
host.raspberrypi2 | 2024-10-25 17:26:48.978 | error | Caught by controller[2]: Error: AREQ - ZDO - ieeeAddrRsp after 10000ms
host.raspberrypi2 | 2024-10-25 17:26:48.978 | error | Caught by controller[1]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
zigbee.0 | 2024-10-25 17:26:47.855 | error | AREQ - ZDO - ieeeAddrRsp after 10000ms
zigbee.0 | 2024-10-25 17:26:47.855 | error | Error: AREQ - ZDO - ieeeAddrRsp after 10000ms at Object.start (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:59:23) at /opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:403:47 at Queue.execute (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:36:20) at ZStackAdapter.sendZdo (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:311:16) at Controller.identifyUnknownDevice (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/controller.ts:543:26) at Controller.onZclPayload (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/controller.ts:844:26)
zigbee.0 | 2024-10-25 17:26:47.840 | error | unhandled promise rejection: AREQ - ZDO - ieeeAddrRsp after 10000ms
zigbee.0 | 2024-10-25 17:26:47.839 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
``` 

Adapter-Version: 1.10.10 - Branch from #2211 
JS-controller: 7.0.1

zStack 3x0, Version: 2-1.2.7.1 (Rev: 20240710)

SideNote:
It is not possible to delete groups. (They will be deleted, but get restored after the adapter chrashes and restarts). Creating new groups is possible and they survive a restart

Best Mirko

**Comment by asgothian** [comment]
can you trigger the crash or provide any form of context for it ? As it is, the log entry gives not enough information to track the error down

The issue with the groups is known (see the thread on the iobroker forum) and a fix is being worked on.

**Comment by asgothian** [comment]
Also - please install the 1.10.10 from the official GitHub repo. There have been a number of fixes introduced.

A.

**Comment by asgothian** [comment]
No response for 4 weeks, closing this.
