### ISSUE TITLE
v1.10.12 fail to start with error: "unhandled promise rejection: Request failed with status code 404"

### ISSUE THREAD

**Issue by Osrx** [ioBroker/ioBroker.zigbee#2280]
I've just updated to v1.10.12 and one of instance fail to start.

Debug log also uploaded.
Help me please!

[iobroker.2024-11-06.log](https://github.com/user-attachments/files/17646558/iobroker.2024-11-06.log)

```zigbee.0
2024-11-06 14:03:34.121	error	Exception-Code: ERR_BAD_REQUEST: Request failed with status code 404

zigbee.0
2024-11-06 14:03:34.120	error	AxiosError: Request failed with status code 404 at settle (/opt/iobroker/node_modules/axios/dist/node/axios.cjs:2019:12) at RedirectableRequest.handleResponse (/opt/iobroker/node_modules/axios/dist/node/axios.cjs:3083:9) at RedirectableRequest.emit (node:events:519:28) at RedirectableRequest._processResponse (/opt/iobroker/node_modules/follow-redirects/index.js:398:10) at RedirectableRequest._onNativeResponse (/opt/iobroker/node_modules/follow-redirects/index.js:91:12) at Object.onceWrapper (node:events:634:26) at ClientRequest.emit (node:events:519:28) at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:702:27) at HTTPParser.parserOnHeadersComplete (node:_http_common:118:17) at TLSSocket.socketOnData (node:_http_client:544:22) at Axios.request (/opt/iobroker/node_modules/axios/dist/node/axios.cjs:4287:41) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

zigbee.0
2024-11-06 14:03:34.120	error	unhandled promise rejection: Request failed with status code 404

zigbee.0
2024-11-06 14:03:34.119	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().```

**Comment by RichieXX** [comment]
Same error. Also updatet from 1.10.12

**Comment by Haui74** [comment]
Me too
![Unbenannt](https://github.com/user-attachments/assets/408b104e-ac8f-436f-a5a8-2cad68e70d24)

**Comment by Osrx** [comment]
v1.10.13 fixed this issue!
Thanks a lot!
