### ISSUE TITLE
Zigbee crash

### ISSUE THREAD

**Issue by Haui74** [ioBroker/ioBroker.zigbee#2286]
![Unbenannt](https://github.com/user-attachments/assets/6eaafff3-5143-428a-a562-ea781c6c5948)

Version: 1.10.13
Js-Controller: 7.0.2
Admin: 7.2.6
Problem exist since update from 1.10.10

**Comment by asgothian** [comment]
- please post logs as text in code tags (<.>),  not as screenshot
- Please post a complete log of the issue - the main messages are missing at the top of the screenshot.
- please post ‘context’ for the crash. (Randomly, at start, etc.)

A.

**Comment by Haui74** [comment]
`<html>
<body>

2024-11-17 06:45:20.783 - error: zigbee.0 (84464) TypeError: Cannot read properties of undefined (reading 'includes')
--
at /opt/iobroker/node_modules/iobroker.zigbee/main.js:726:31
at Array.forEach ()
at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:652:23)
2024-11-17 06:45:20.783 - error: zigbee.0 (84464) Cannot read properties of undefined (reading 'includes')
2024-11-17 06:45:20.794 - info: zigbee.0 (84464) cleaned everything up...
2024-11-17 06:45:20.795 - info: zigbee.0 (84464) Zigbee: disabling joining new devices.
2024-11-17 06:45:20.950 - error: zigbee.0 (84464) uncaught exception: EBADF: bad file descriptor, write
2024-11-17 06:45:21.012 - error: host.Smarthome Caught by controller[1]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2024-11-17 06:45:21.013 - error: host.Smarthome Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'includes')
2024-11-17 06:45:21.013 - error: host.Smarthome Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.zigbee/main.js:726:31
2024-11-17 06:45:21.013 - error: host.Smarthome Caught by controller[1]: at Array.forEach ()
2024-11-17 06:45:21.013 - error: host.Smarthome Caught by controller[1]: at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:652:23)
2024-11-17 06:45:21.013 - error: host.Smarthome Caught by controller[2]: [Error: EBADF: bad file descriptor, write] {
2024-11-17 06:45:21.013 - error: host.Smarthome Caught by controller[2]: errno: -9,
2024-11-17 06:45:21.013 - error: host.Smarthome Caught by controller[2]: code: 'EBADF',
2024-11-17 06:45:21.013 - error: host.Smarthome Caught by controller[2]: syscall: 'write',
2024-11-17 06:45:21.013 - error: host.Smarthome Caught by controller[2]: disconnect: true
2024-11-17 06:45:21.013 - error: host.Smarthome Caught by controller[2]: }
2024-11-17 06:45:21.013 - error: host.Smarthome instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2024-11-17 06:45:53.676 - info: zigbee.0 (84572) starting. Version 1.10.13 in /opt/iobroker/node_modules/iobroker.zigbee, node: v20.5.1, js-controller: 7.0.3
2024-11-17 06:45:53.722 - info: zigbee.0 (84572) delete old Backup files. keep only last 10
2024-11-17 06:45:53.723 - info: zigbee.0 (84572) Starting Zigbee npm ...
2024-11-17 06:45:53.893 - info: zigbee.0 (84572) Installed Version: iobroker.zigbee@1.10.13
2024-11-17 06:45:54.183 - info: zigbee.0 (84572) Coordinator firmware version: {"type":"ConBee2/RaspBee2","meta":{"transportrev":0,"product":0,"majorrel":38,"minorrel":120,"maintrel":0,"revision":"0x26780700"}}
2024-11-17 06:45:54.184 - info: zigbee.0 (84572) Unable to disable LED, unsupported function.
2024-11-17 06:45:54.195 - info: zigbee.0 (84572) --> transmitPower : high+
2024-11-17 06:45:54.239 - info: zigbee.0 (84572) Unable to set transmit power, unsupported function.
2024-11-17 06:45:54.242 - info: zigbee.0 (84572) Currently 16 devices are joined:
2024-11-17 06:45:54.278 - info: zigbee.0 (84572) 0x00158d00042409f6 (addr 52658): MCCGQ11LM - Aqara Door and window sensor (EndDevice)
2024-11-17 06:45:54.280 - info: zigbee.0 (84572) 0x00158d00044ab29c (addr 63486): MCCGQ11LM - Aqara Door and window sensor (EndDevice)
2024-11-17 06:45:54.281 - info: zigbee.0 (84572) 0xa4c138da44f87556 (addr 60327): TS0001_fingerbot - Tuya Zigbee fingerbot plus (EndDevice)
2024-11-17 06:45:54.282 - info: zigbee.0 (84572) 0x00158d000423c689 (addr 1616): MCCGQ11LM - Aqara Door and window sensor (EndDevice)
2024-11-17 06:45:54.283 - info: zigbee.0 (84572) 0x842e14fffef8d21e (addr 56673): HG06337 - Lidl Silvercrest smart plug (EU, CH, FR, BS, DK) (Router)
2024-11-17 06:45:54.284 - info: zigbee.0 (84572) 0x842e14fffe61ca77 (addr 20680): HG06337 - Lidl Silvercrest smart plug (EU, CH, FR, BS, DK) (Router)
2024-11-17 06:45:54.284 - info: zigbee.0 (84572) 0xa4c1387921c85daf (addr 21072): TS0001_fingerbot - Tuya Zigbee fingerbot plus (EndDevice)
2024-11-17 06:45:54.285 - info: zigbee.0 (84572) 0xa4c138c8c5f0c0a8 (addr 60551): TS0203 - Tuya Door sensor (EndDevice)
2024-11-17 06:45:54.286 - info: zigbee.0 (84572) 0xa4c13891fc1f849a (addr 5079): TS0001_fingerbot - Tuya Zigbee fingerbot plus (EndDevice)
2024-11-17 06:45:54.286 - info: zigbee.0 (84572) 0xa4c1380c3e60ad66 (addr 22991): TS0203 - Tuya Door sensor (EndDevice)
2024-11-17 06:45:54.287 - info: zigbee.0 (84572) 0x842e14fffef5a390 (addr 37250): HG06337 - Lidl Silvercrest smart plug (EU, CH, FR, BS, DK) (Router)
2024-11-17 06:45:54.288 - info: zigbee.0 (84572) 0x28dba7fffe6096f7 (addr 40711): TS0207_repeater - Tuya Repeater (Router)
2024-11-17 06:45:54.289 - info: zigbee.0 (84572) 0xa4c13879a405014f (addr 57339): TS0203 - Tuya Door sensor (EndDevice)
2024-11-17 06:45:54.289 - info: zigbee.0 (84572) 0xa4c13869b566857f (addr 29419): TS0203 - Tuya Door sensor (EndDevice)
2024-11-17 06:45:54.290 - info: zigbee.0 (84572) 0xec1bbdfffeaec1dc (addr 26603): HG06335/HG07310 - Lidl Silvercrest smart motion sensor (EndDevice)
2024-11-17 06:45:54.293 - info: zigbee.0 (84572) 0xa4c138115ccec886 (addr 3143): TS0601_soil - Tuya Soil sensor (EndDevice)
2024-11-17 06:45:54.294 - info: zigbee.0 (84572) Zigbee started
2024-11-17 06:45:54.339 - info: zigbee.0 (84572) debug devices set to []


</body>
</html>
`

Das passiert, wenn ich meine Fingerbots trigger, egal ob manuell oder per Alexa. Habe di eBots ach schon mal entfernt und wieder gekoppelt, aber das Ergebniss ist das gleiche.
