### ISSUE TITLE
Can't set any state, join or delete devices, receiving states works

### ISSUE THREAD

**Issue by BenjaminHae** [ioBroker/ioBroker.zigbee#2306]
### describe the problem in Detail. What do you expect to happen ? What does happen ?

I've recently upgraded to 1.10.13, after a restart of my host, suddenly the following symptoms started:
- I still receive data from sensors (temperature sensors, buttons, ...)
- Changing the state of a device has no effect the state is changed in the object list, but changing the state of a light bulb for example does not turn it on
- Deleting Devices is not possible
- Pairing devices is not possible (it just shows `Pairing started` but no countdown, no new devices appear)
- Executing "Hard reset" does not do anything, the adapter restarts, but all devices are still present.

I've tried:
- reinstalling iobroker with a backup
- changing the zigbee stick
- hard reset, soft reset, rejoining devices

### Adapter version

1.10.13

### Coordinator firmware version

20190608

### Coordinator

zStack12

### Setup

on Raspberry pi, in docker container

### Protocol of the error (as text, encapsulated in multiline code tags <>). Separate different occurrances into clearly split log sections

Error (I guess from hard reset):
``` 
Error: AREQ - SYS - resetInd after 30000ms at Object.start (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:59:23) at /opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:303:37 at Queue.execute (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/queue.ts:36:26) at Znp.request (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:278:27) at ZStackAdapter.reset (/opt/iobroker/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:215:28) at Controller.reset (/opt/iobroker/node_modules/zigbee-herdsman/src/controller/controller.ts:414:28) at ZigbeeController.reset (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:990:27) at Developer.onMessage (/opt/iobroker/node_modules/iobroker.zigbee/lib/developer.js:45:39) at Zigbee.emit (node:events:529:35) at Zigbee.emit (node:domain:489:12)
```

**Comment by asgothian** [comment]
Please pick 2 devices which you should be able to control from ioBroker, and follow [this document](https://github.com/ioBroker/ioBroker.zigbee/wiki/debug-messages-with-zigbee.0.info.debugmessages) to generate log messages when trying to change a state.

Post these change attempts as separate log snippets so we can try to see what is going on.

A.

**Comment by BenjaminHae** [comment]
For the first device, a relay:
```
2024-11-27 20:55:21.273 - warn: zigbee.0 (2981) ELEVATED: User stateChange zigbee.0.00124b0023a1addc.state {"val":true,"ack":false,"ts":1732737321270,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1732737321270}
2024-11-27 20:55:21.283 - warn: zigbee.0 (2981) ELEVATED Change state 'state' at device 0x00124b0023a1addc type 'ZB-SW01'
2024-11-27 20:55:21.290 - warn: zigbee.0 (2981) ELEVATED: Setting' converter to converter with key(s)'["state","on_time","off_wait_time"]}
2024-11-27 20:55:21.291 - warn: zigbee.0 (2981) ELEVATED: convert state, "ON", {} for device 0x00124b0023a1addc
2024-11-27 20:55:45.392 - warn: zigbee.0 (2981) ELEVATED: Zigbee Event of Type attributeReport from device "0x00124b0023a1addc", incoming event: {"type":"attributeReport","device":"0x00124b0023a1addc","endpoint":1,"data":{"onOff":0},"linkquality":0,"groupID":0,"cluster":"genOnOff"}
2024-11-27 20:55:45.431 - warn: zigbee.0 (2981) ELEVATED: Zigbee Event of Type attributeReport from device "0x00124b0023a1addc", incoming event: {"type":"attributeReport","device":"0x00124b0023a1addc","endpoint":1,"data":{"onOff":0},"linkquality":0,"groupID":0,"cluster":"genOnOff"}
2024-11-27 20:55:45.434 - warn: zigbee.0 (2981) ELEVATED: Zigbee Event of Type attributeReport from device "0x00124b0023a1addc", incoming event: {"type":"attributeReport","device":"0x00124b0023a1addc","endpoint":1,"data":{"onOff":0},"linkquality":0,"groupID":0,"cluster":"genOnOff"}
2024-11-27 20:55:45.437 - warn: zigbee.0 (2981) ELEVATED: Zigbee Event of Type attributeReport from device "0x00124b0023a1addc", incoming event: {"type":"attributeReport","device":"0x00124b0023a1addc","endpoint":1,"data":{"onOff":0},"linkquality":0,"groupID":0,"cluster":"genOnOff"}
2024-11-27 20:55:45.439 - warn: zigbee.0 (2981) ELEVATED: Zigbee Event of Type attributeReport from device "0x00124b0023a1addc", incoming event: {"type":"attributeReport","device":"0x00124b0023a1addc","endpoint":1,"data":{"onOff":0},"linkquality":0,"groupID":0,"cluster":"genOnOff"}
2024-11-27 20:55:45.442 - warn: zigbee.0 (2981) ELEVATED: Zigbee Event of Type attributeReport from device "0x00124b0023a1addc", incoming event: {"type":"attributeReport","device":"0x00124b0023a1addc","endpoint":1,"data":{"onOff":0},"linkquality":0,"groupID":0,"cluster":"genOnOff"}
2024-11-27 20:55:45.444 - warn: zigbee.0 (2981) ELEVATED: Zigbee Event of Type attributeReport from device "0x00124b0023a1addc", incoming event: {"type":"attributeReport","device":"0x00124b0023a1addc","endpoint":1,"data":{"onOff":0},"linkquality":0,"groupID":0,"cluster":"genOnOff"}
2024-11-27 20:55:45.447 - warn: zigbee.0 (2981) ELEVATED: Zigbee Event of Type attributeReport from device "0x00124b0023a1addc", incoming event: {"type":"attributeReport","device":"0x00124b0023a1addc","endpoint":1,"data":{"onOff":0},"linkquality":0,"groupID":0,"cluster":"genOnOff"}
2024-11-27 20:55:45.515 - warn: zigbee.0 (2981) ELEVATED publishToState: message received '{"state":"OFF"}' from device 00124b0023a1addc type 'ZB-SW01'
2024-11-27 20:55:45.516 - warn: zigbee.0 (2981) ELEVATED publishToState: value generated 'false' from device 00124b0023a1addc for 'On/off state of the switch'
```

Second device, a lighbulb:
```
2024-11-27 20:57:32.732 - warn: zigbee.0 (2981) ELEVATED: User stateChange zigbee.0.ec1bbdfffe95193a.state {"val":true,"ack":false,"ts":1732737452727,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1732737452727}
2024-11-27 20:57:32.817 - warn: zigbee.0 (2981) ELEVATED Change state 'state' at device 0xec1bbdfffe95193a type 'LED1837R5'
2024-11-27 20:57:32.826 - warn: zigbee.0 (2981) ELEVATED: Setting' converter to converter with key(s)'["state","brightness","brightness_percent","on_time"]}
2024-11-27 20:57:32.830 - warn: zigbee.0 (2981) ELEVATED: convert state, "ON", {"state":"ON","transition_time":10} for device 0xec1bbdfffe95193a
```
In both cases I only changed the state once, from false to true.

**Comment by asgothian** [comment]
I'll dig through the log and put up a test version with more logging. Will take til tomorrow evening though

**Comment by asgothian** [comment]
Please verify that both packets ( zigbee-herdsman and zigbee-herdsman-converters ) exist just once in the node-modules for iobroher (and not at in the global modules).

**Comment by BenjaminHae** [comment]
Does not look like it:
```
pi:/opt/iobroker$ npm list --depth=3 | grep zigbee
`-- iobroker.zigbee@1.10.13
  +-- zigbee-herdsman-converters@20.28.0
  | `-- zigbee-herdsman@2.1.4 deduped
  `-- zigbee-herdsman@2.1.4
pi:/opt/iobroker$ npm -g list --depth=3 | grep zigbee
iobroker@iobroker-pi:/opt/iobroker$ find . -iname "*zigbee*" -type d
./node_modules/zigbee-herdsman
./node_modules/zigbee-herdsman-converters
./node_modules/iobroker.zigbee
./iobroker-data/zigbee_0
./iobroker-data/files/zigbee.admin
./iobroker-data/zigbee_1
```

**Comment by BenjaminHae** [comment]
Another weird thing is when I start pairing, the states in `zigbee.0.info` do not change:  
![grafik](https://github.com/user-attachments/assets/2e64e39c-f95f-4fe3-a798-948704c20052)

**Comment by asgothian** [comment]
That is not weird, as it is tied to the response from the coordinator that the network is open. The lack of log entries seems to suggest that the data is never sent to the coordinator - I thought I caught all cases how this can happen, but I am still digging - it will take a few days for me to go through everything, sorry.

A.

**Comment by BenjaminHae** [comment]
Thank you for investing your time for this issue!

If there is any information I can provide or if there are any debugging steps I can take to assist you please let me know.

**Comment by BenjaminHae** [comment]
I've setup a new instance with a new coordinator. Everything works with that instance.

I've migrated all my devices to this new instance, so I can't take any debug steps anymore.

Thank you for your time.

**Comment by asgothian** [comment]
Thanks for the information. Is it another cc2531, or a more modern coordinator ?

**Comment by BenjaminHae** [comment]
It's cc2562p based. (So off 3.0)
