### ISSUE TITLE
Regelmäßiger Absturz Adapter wenn das Gerät "Fingerbot" hinzugefügt wird

### ISSUE THREAD

**Issue by andreashz** [ioBroker/ioBroker.zigbee#2334]
### describe the problem in Detail. What do you expect to happen ? What does happen ?

Seid einiger Zeit stürzt der Zigbee Adapter ab.  Dies ist mir nach dem letzten Update aufgefallen. 

Deaktiviere ich "**Tuya Zigbee fingerbot plus (EndDevice)**" läuft der Adapter korrekt.

Beschreibung:
Der Adapter geht **nur dann offline wenn ich den Fingerbot schalten** möchte. Im Gegensatz zu früher wird der Befehl auch nicht ausgeführt. Alle anderen Kommandos scheinen zu funkionieren und es erfolgt eine Reaktion in "msg_from_zigbee"
	

### Adapter version

1.10.13

### Coordinator firmware version

20240710

### Coordinator

SLZB-06, CC2652P

### Setup

LXC Container unter Proxmox

### Protocol of the error (as text, encapsulated in multiline code tags <>). Separate different occurrances into clearly split log sections

```
zigbee.2
	2024-12-30 11:59:00.546	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee.2
	2024-12-30 11:59:00.545	info	terminating
zigbee.2
	2024-12-30 11:59:00.066	error	Cannot read properties of undefined (reading 'includes')
zigbee.2
	2024-12-30 11:59:00.066	error	TypeError: Cannot read properties of undefined (reading 'includes') at /opt/iobroker/node_modules/iobroker.zigbee/main.js:726:31 at Array.forEach (<anonymous>) at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:652:23) at runNextTicks (node:internal/process/task_queues:60:5) at processImmediate (node:internal/timers:454:9)
zigbee.2
	2024-12-30 11:59:00.065	error	unhandled promise rejection: Cannot read properties of undefined (reading 'includes')
zigbee.2
	2024-12-30 11:59:00.065	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.2
	2024-12-30 11:59:00.046	info	Zigbee: disabling joining new devices.
zigbee.2
	2024-12-30 11:59:00.046	info	cleaned everything up...
zigbee.2
	2024-12-30 11:59:00.038	error	Cannot read properties of undefined (reading 'includes')
zigbee.2
	2024-12-30 11:59:00.038	error	TypeError: Cannot read properties of undefined (reading 'includes') at /opt/iobroker/node_modules/iobroker.zigbee/main.js:726:31 at Array.forEach (<anonymous>) at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:652:23)
zigbee.2
	2024-12-30 11:59:00.038	error	unhandled promise rejection: Cannot read properties of undefined (reading 'includes')
zigbee.2
	2024-12-30 11:59:00.037	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.2

```

```
	2024-12-30 11:58:34.406	info	debug devices set to []
zigbee.2
	2024-12-30 11:58:34.384	info	Zigbee started
zigbee.2
	2024-12-30 11:58:34.384	info	0xa4c138268c323f80 (addr 36327): WHD02 - Tuya Wall switch module (Router)
zigbee.2
	2024-12-30 11:58:34.383	info	0x84fd27fffe5f0217 (addr 54728): TS0121_plug - Tuya 10A UK or 16A EU smart plug (Router)
zigbee.2
	2024-12-30 11:58:34.382	info	0xb43522fffe754118 (addr 36585): E1603/E1702/E1708 - IKEA TRADFRI control outlet (Router)
zigbee.2
	2024-12-30 11:58:34.381	info	0xdc8e95fffe5d2ae6 (addr 14327): TO-Q-SY1-JZT - Tongou Din smart relay (with power monitoring via polling) (Router)
zigbee.2
	2024-12-30 11:58:34.380	info	0xa4c138e7dc85e089 (addr 27471): TS0601_soil - Tuya Soil sensor (EndDevice)
zigbee.2
	2024-12-30 11:58:34.379	info	0xa4c138a784c1023f (addr 27311): TS0001_fingerbot - Tuya Zigbee fingerbot plus (EndDevice)
zigbee.2
	2024-12-30 11:58:34.378	info	0xa4c138d59c26b27c (addr 51887): TS0601_soil - Tuya Soil sensor (EndDevice)
zigbee.2
	2024-12-30 11:58:34.373	info	Currently 7 devices are joined:
zigbee.2
	2024-12-30 11:58:34.145	info	--> transmitPower : high+
zigbee.2
	2024-12-30 11:58:34.139	info	Unable to disable LED, unsupported function.
zigbee.2
	2024-12-30 11:58:34.139	info	Coordinator firmware version: {"type":"zStack3x0","meta":{"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20240710}}
zigbee.2
	2024-12-30 11:58:32.906	info	Installed Version: iobroker.zigbee@1.10.13
zigbee.2
	2024-12-30 11:58:32.746	info	Starting Zigbee npm ...
zigbee.2
	2024-12-30 11:58:32.745	info	delete old Backup files. keep only last 10
zigbee.2
	2024-12-30 11:58:32.717	info	starting. Version 1.10.13 in /opt/iobroker/node_modules/iobroker.zigbee, node: v20.18.0, js-controller: 7.0.6
```

**Comment by asgothian** [comment]
When did you install the 1.10.13 ? The current GitHub version should have fixed this issue. Please install the 1.10.13 from today and test again.

A.

**Comment by andreashz** [comment]
Hi. I did reinstall version 1.10.13 just now -  but the driver is still crashing when I try to switch the "fingerbot"

**Comment by asgothian** [comment]
ok.. closing this
