### ISSUE TITLE
Please add support of GLEDOPTO GL-C-009 dimmer WW/CW

### ISSUE THREAD

**Issue by ericsboro** [ioBroker/ioBroker.zigbee#257]
here's what log shows:
error: zigbee.0 Unknown device model GL-C-009 emit event readRsp with data:{"cid":"genBasic","data":{"manufacturerName":"GLEDOPTO","modelId":"GL-C-009","powerSource":1}}
error: zigbee.0 Unknown device model GL-C-009 emit event devChange with data:{"cid":"genBasic","data":{"manufacturerName":"GLEDOPTO","modelId":"GL-C-009","powerSource":1}}

**Comment by ericsboro** [comment]
anyone :)
Please help :)

**Comment by asgothian** [comment]
Is this unit listed as supported in the zigbee2mqtt project ? I cannot find any reference to it in the source. Implementing it requires changes in the zigbee-shepherd-converters before we can add support to iobroker.

**Comment by ericsboro** [comment]
@asgothian 
many thanks for advise!
should i close this thread or confirm here after it's implemented in zigbee-shepherd-converters?

**Comment by asgothian** [comment]
Leave it open for now. I might take a look at the zigbee-shepherd-converter introduction - time allowing.

**Comment by asgothian** [comment]
Can you confirm that this unit can only control ww/cw LED strips, not RGB ?

**Comment by asgothian** [comment]
Fixed in my development branch. Please install from

`https://github.com/asgothian/ioBroker.zigbee/tarball/ecozy`
 and check if it works.
In order for this to work, you also need to install the zigbee-shepherd-converters from my repository.
`https://github.com/asgothian/zigbee-shepherd-converters`
Connect to your iobroker, navigate to the Folder
`/opt/iobroker/node_modules/iobroker.zigbee` 
and execute

`npm install git+https://git@github.com/asgothian/zigbee-shepherd-converters.git`
Note - remember to perform an "upload" after installing from GitHub.

**Comment by ericsboro** [comment]
> Can you confirm that this unit can only control ww/cw LED strips, not RGB ?

Yes, I confirm — it's now RGB.

I've tried to install everything as you advised — but it didn't work, unfortunately. zigbee adapter now starting after update/reinstall.

here's what log shows:

2019-03-23 17:29:45.237 - info: iobroker add zigbee --host iobroker
--
2019-03-23 17:29:46.312 - info: iobroker host.iobroker install adapter zigbee
2019-03-23 17:29:46.344 - info: iobroker got /opt/iobroker/node_modules/iobroker.zigbee/admin
2019-03-23 17:29:47.485 - info: iobroker upload [100] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/smarthomepty_plug.png img/smarthomepty_plug.png image/png
2019-03-23 17:29:48.161 - info: iobroker upload [90] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/plug.png img/plug.png image/png
2019-03-23 17:29:48.837 - info: iobroker upload [80] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/philips_hue_e14_ambiance.png img/philips_hue_e14_ambiance.png image/png
2019-03-23 17:29:49.504 - info: iobroker upload [70] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/ninja_plug.png img/ninja_plug.png image/png
2019-03-23 17:29:50.147 - info: iobroker upload [60] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/lightify-b40tw.png img/lightify-b40tw.png image/png
2019-03-23 17:29:50.871 - info: iobroker upload [50] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/ikea_gu10.png img/ikea_gu10.png image/png
2019-03-23 17:29:51.587 - info: iobroker upload [40] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/gld003z.png img/gld003z.png image/png
2019-03-23 17:29:52.320 - info: iobroker upload [30] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/cube.png img/cube.png image/png
2019-03-23 17:29:53.012 - info: iobroker upload [20] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/aqara_numan_body_sensor.png img/aqara_numan_body_sensor.png image/png
2019-03-23 17:29:53.081 - info: iobroker upload [19] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/aqara_bulb.png img/aqara_bulb.png image/png
2019-03-23 17:29:53.151 - info: iobroker upload [18] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/aqara.switch.png img/aqara.switch.png image/png
2019-03-23 17:29:53.218 - info: iobroker upload [17] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/TRADFRI.remote.control.png img/TRADFRI.remote.control.png image/png
2019-03-23 17:29:53.291 - info: iobroker upload [16] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/TRADFRI.bulb.E27.png img/TRADFRI.bulb.E27.png image/png
2019-03-23 17:29:53.365 - info: iobroker upload [15] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/FLOALT.panel.WS.png img/FLOALT.panel.WS.png image/png
2019-03-23 17:29:53.434 - info: iobroker upload [14] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/Eurotronic_Spirit_04.png img/Eurotronic_Spirit_04.png image/png
2019-03-23 17:29:53.514 - info: iobroker upload [13] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/86sw2.png img/86sw2.png image/png
2019-03-23 17:29:53.584 - info: iobroker upload [12] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/86sw1.png img/86sw1.png image/png
2019-03-23 17:29:53.654 - info: iobroker upload [11] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/86plug.png img/86plug.png image/png
2019-03-23 17:29:53.730 - info: iobroker upload [10] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/i18n/zh-cn/translations.json i18n/zh-cn/translations.json application/json
2019-03-23 17:29:53.786 - info: iobroker upload [9] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/i18n/ru/translations.json i18n/ru/translations.json application/json
2019-03-23 17:29:53.844 - info: iobroker upload [8] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/i18n/pt/translations.json i18n/pt/translations.json application/json
2019-03-23 17:29:53.900 - info: iobroker upload [7] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/i18n/pl/translations.json i18n/pl/translations.json application/json
2019-03-23 17:29:53.958 - info: iobroker upload [6] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/i18n/nl/translations.json i18n/nl/translations.json application/json
2019-03-23 17:29:54.016 - info: iobroker upload [5] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/i18n/it/translations.json i18n/it/translations.json application/json
2019-03-23 17:29:54.072 - info: iobroker upload [4] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/i18n/fr/translations.json i18n/fr/translations.json application/json
2019-03-23 17:29:54.130 - info: iobroker upload [3] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/i18n/es/translations.json i18n/es/translations.json application/json
2019-03-23 17:29:54.187 - info: iobroker upload [2] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/i18n/en/translations.json i18n/en/translations.json application/json
2019-03-23 17:29:54.372 - info: iobroker upload [1] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/i18n/de/translations.json i18n/de/translations.json application/json
2019-03-23 17:29:54.425 - info: iobroker upload [0] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/admin.js admin.js application/javascript
2019-03-23 17:29:54.607 - info: iobroker host.iobroker object system.adapter.zigbee created
2019-03-23 17:29:54.645 - info: iobroker host.iobroker create instance zigbee
2019-03-23 17:29:54.655 - info: iobroker host.iobroker object zigbee.0.info.groups created
2019-03-23 17:29:54.686 - info: iobroker host.iobroker object zigbee.0.info.pairingMessage created
2019-03-23 17:29:54.717 - info: iobroker host.iobroker object zigbee.0.info.pairingCountdown created
2019-03-23 17:29:54.753 - info: iobroker host.iobroker object zigbee.0.info.pairingMode created
2019-03-23 17:29:54.787 - info: iobroker host.iobroker object zigbee.0.info.connection created
2019-03-23 17:29:54.815 - info: iobroker host.iobroker object zigbee.0.info created
2019-03-23 17:29:54.853 - info: iobroker host.iobroker object system.adapter.zigbee.0.outputCount created
2019-03-23 17:29:54.887 - info: iobroker host.iobroker object system.adapter.zigbee.0.inputCount created
2019-03-23 17:29:54.922 - info: iobroker host.iobroker object system.adapter.zigbee.0.uptime created
2019-03-23 17:29:54.956 - info: iobroker host.iobroker object system.adapter.zigbee.0.memRss created
2019-03-23 17:29:54.992 - info: iobroker host.iobroker object system.adapter.zigbee.0.memHeapTotal created
2019-03-23 17:29:55.025 - info: iobroker host.iobroker object system.adapter.zigbee.0.memHeapUsed created
2019-03-23 17:29:55.058 - info: iobroker host.iobroker object system.adapter.zigbee.0.connected created
2019-03-23 17:29:55.091 - info: iobroker host.iobroker object system.adapter.zigbee.0.alive created
2019-03-23 17:29:55.134 - info: host.iobroker object change system.adapter.zigbee.0
2019-03-23 17:29:55.152 - info: host.iobroker instance system.adapter.zigbee.0 started with pid 20009
2019-03-23 17:29:55.162 - info: iobroker host.iobroker object system.adapter.zigbee.0 created
2019-03-23 17:29:55.178 - info: iobroker exit 0
2019-03-23 17:29:57.575 - error: Caught by controller[0]: /opt/iobroker/node_modules/iobroker.zigbee/lib/devstates.js:2672
2019-03-23 17:29:57.576 - error: Caught by controller[0]: ]
2019-03-23 17:29:57.577 - error: Caught by controller[0]: ^
2019-03-23 17:29:57.577 - error: Caught by controller[0]: SyntaxError: Unexpected token ]
2019-03-23 17:29:57.577 - error: Caught by controller[0]: at new Script (vm.js:79:7)
2019-03-23 17:29:57.577 - error: Caught by controller[0]: at createScript (vm.js:251:10)
2019-03-23 17:29:57.578 - error: Caught by controller[0]: at Object.runInThisContext (vm.js:303:10)
2019-03-23 17:29:57.578 - error: Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:657:28)
2019-03-23 17:29:57.578 - error: Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
2019-03-23 17:29:57.579 - error: Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:599:32)
2019-03-23 17:29:57.579 - error: Caught by controller[0]: at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
2019-03-23 17:29:57.579 - error: Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:530:3)
2019-03-23 17:29:57.579 - error: Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:637:17)
2019-03-23 17:29:57.580 - error: Caught by controller[0]: at require (internal/modules/cjs/helpers.js:22:18)
2019-03-23 17:29:57.580 - error: host.iobroker instance system.adapter.zigbee.0 terminated with code 1 ()
2019-03-23 17:29:57.580 - info: host.iobroker Restart adapter system.adapter.zigbee.0 because enabled

**Comment by asgothian** [comment]
Ok.. bug found.. please reinstall and restart.

A.

**Comment by ericsboro** [comment]
@asgothian 
you are genius! it works now!!! thanks a ton!!!

**Comment by asgothian** [comment]
Perfect.. i'll submit a pull request tomorrow to get it into the standard.
