### ISSUE TITLE
[testing herdsman] afapter restart when call some service

### ISSUE THREAD

**Issue by SchumyHao** [ioBroker/ioBroker.zigbee#408]
When I call set ikea light brightness to 0 in script-engin, zigbee adapter crash and restart

host.dockerhub-cn | 2019-11-09 01:40:39.337 | error | Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:68:7)
-- | -- | -- | --
host.dockerhub-cn | 2019-11-09 01:40:39.337 | error | Caught by controller[0]: at promise.then (/opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49)
host.dockerhub-cn | 2019-11-09 01:40:39.337 | error | Caught by controller[0]: at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
host.dockerhub-cn | 2019-11-09 01:40:39.336 | error | Caught by controller[0]: at client.get (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:475:17)
host.dockerhub-cn | 2019-11-09 01:40:39.336 | error | Caught by controller[0]: at adapter.getState (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:78:21)
host.dockerhub-cn | 2019-11-09 01:40:39.336 | error | Caught by controller[0]: at collectOptions.options (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:43:30)
host.dockerhub-cn | 2019-11-09 01:40:39.336 | error | Caught by controller[0]: at StatesController.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:110:37)
host.dockerhub-cn | 2019-11-09 01:40:39.335 | error | Caught by controller[0]: at Array.forEach (<anonymous>)
host.dockerhub-cn | 2019-11-09 01:40:39.335 | error | Caught by controller[0]: at stateModel.linkedStates.forEach (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:111:68)
host.dockerhub-cn | 2019-11-09 01:40:39.334 | error | Caught by controller[0]: ReferenceError: adapter is not defined
zigbee.0 | 2019-11-09 01:40:38.685 | info | (2421) Terminated (NO_ERROR): Without reason
zigbee.0 | 2019-11-09 01:40:38.684 | info | (2421) terminating
zigbee.0 | 2019-11-09 01:40:38.521 | info | (2421) Zigbee: disabling joining new devices.
zigbee.0 | 2019-11-09 01:40:38.519 | info | (2421) cleaned everything up...
zigbee.0 | 2019-11-09 01:40:38.517 | error | (2421) ReferenceError: adapter is not defined at stateModel.linkedStates.forEach (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:111:68) at Array.forEach (<anonymous>)
zigbee.0 | 2019-11-09 01:40:38.516 | error | (2421) uncaught exception: adapter is not defined

**Comment by SchumyHao** [comment]
Maybe this is a little mistake
I changed a little code in red block to fix this issue.
![image](https://user-images.githubusercontent.com/4982108/68524984-ec293780-0307-11ea-873f-69aa31807e00.png)

**Comment by SchumyHao** [comment]
PR created https://github.com/ioBroker/ioBroker.zigbee/pull/409
