### ISSUE TITLE
Add Request: Müller Licht  RGBW Strip

### ISSUE THREAD

**Issue by MikeEcho0815** [ioBroker/ioBroker.zigbee#421]
Maybe you could add the "Müller Licht" LED-Strip ioBroker logs this "new dev 0xccccccfffebb1133 54271 RGBW Lighting"

Thanx in advance

**Comment by arteck** [comment]
more infos plz like 
![grafik](https://user-images.githubusercontent.com/6681528/69081287-ec2ee300-0a3d-11ea-8cfe-429990af14ca.png)

**Comment by BBQ-90** [comment]
I'm interested, as well.
@arteck where do I find the needed info? in the Zigbee instance in ioBroker I can only see the following
![image](https://user-images.githubusercontent.com/57934168/69189714-2623e600-0b1f-11ea-886e-959ff24d77e6.png)

**Comment by arteck** [comment]
check my repo plz
https://github.com/arteck/ioBroker.zigbee/tarball/herdsman

**Comment by MikeEcho0815** [comment]
@arteck Thank you, for replying. Is there a short description, how I would install your repo over my existing Adapter?

**Comment by MikeEcho0815** [comment]
<img width="286" alt="mullerlicht_rgbw_strip" src="https://user-images.githubusercontent.com/45940028/69235606-15f91e80-0b92-11ea-9942-fbeb30b12bdd.PNG">
<img width="292" alt="zigbee_adapter" src="https://user-images.githubusercontent.com/45940028/69235612-198ca580-0b92-11ea-8ab7-ab1fc11a2bf8.PNG">

**Comment by MikeEcho0815** [comment]
![20191120_123540](https://user-images.githubusercontent.com/45940028/69235759-6cfef380-0b92-11ea-968a-4f2a9cf56c7e.jpg)

**Comment by MikeEcho0815** [comment]
Unfortunately i got the Adapter with 1.0.0a working just for a short time. Suddenly i am unable to assign a port to it. Deinstaslling and Reinstalling didn't work...

Going back to 0.11.5 works, though!

**Comment by MikeEcho0815** [comment]
> 
> 
> check my repo plz
> https://github.com/arteck/ioBroker.zigbee/tarball/herdsman

I tried your link :
https://github.com/arteck/ioBroker.zigbee/tarball/herdsman
After Installation my 2531 stopped working...

i also tried:
https://github.com/ioBroker/ioBroker.zigbee/tarball/herdsman
That worked kind of. ;) (Not all Devices where pairable or recognized)

**Comment by BBQ-90** [comment]
I tried the following Repo
https://github.com/ioBroker/ioBroker.zigbee/tarball/herdsman

Don't know what to do here, deleting the zigbee 11.5 adapter and installing the herdsman adapter from the repo above does not help. I cannot add devices and there are 2 dummy devices visible, furthermore a lot of connection problems in the log.

@MikeEcho0815 are there any dependencies to be updated? What did you do to get it working?

**Comment by BBQ-90** [comment]
Update:
* js-controller@2.1.0
* zigbee@1.0.0a
* node@10.17.0

I get the following errors when trying to pair the LED-Strip:

> 2019-11-24 11:54:46.757 - info: admin.0 (676) successful connection to socket.io from ::ffff:192.168.1.16
2019-11-24 11:54:49.134 - info: zigbee.0 (853) Zigbee: allowing new devices to join.
2019-11-24 11:54:57.806 - info: zigbee.0 (853) Starting interview of '0xccccccfffee2cac8'
2019-11-24 11:54:59.562 - error: zigbee.0 (853) Failed to execute LQI for '0x00158d0003275160'. "Error: AREQ - ZDO - mgmtLqiRsp after 10000ms\n at Timeout.object.timer.setTimeout [as _onTimeout] (/opt/iobroker/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)\n at ontimeout (timers.js:436:11)\n at tryOnTimeout (timers.js:300:5)\n at listOnTimeout (timers.js:263:5)\n at Timer.processTimers (timers.js:223:10)"
2019-11-24 11:55:08.612 - info: zigbee.0 (853) Successfully interviewed '0xccccccfffee2cac8', device has succesfully been paired
2019-11-24 11:55:09.866 - error: zigbee.0 (853) Failed to execute LQI for '0x00158d00032b2276'. "Error: AREQ - ZDO - mgmtLqiRsp after 10000ms\n at Timeout.object.timer.setTimeout [as _onTimeout] (/opt/iobroker/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)\n at ontimeout (timers.js:436:11)\n at tryOnTimeout (timers.js:300:5)\n at listOnTimeout (timers.js:263:5)\n at Timer.processTimers (timers.js:223:10)"
2019-11-24 11:55:50.188 - info: zigbee.0 (853) Zigbee: stop joining

Don't know what 0x00158d0003275160 and 0x00158d00032b2276 is 

The pairing log says no more than
>Pairing time left: 51
Device '0xccccccfffee2cac8' announced itself
Pairing time left: 52
Interview started: 0xccccccfffee2cac8
Pairing time left: 53

After this I got the following device in my list, but no objects for it
![image](https://user-images.githubusercontent.com/57934168/69494363-127bd500-0ebb-11ea-9c0d-2391d93df5ee.png)

Did I miss out on anything?
