### ISSUE TITLE
Can't upgrade

### ISSUE THREAD

**Issue by Meinsda** [ioBroker/ioBroker.zigbee#498]
Hello,

I want to upgrade the the newest zigbee adapter but while i upgrade the update i get a lot of messages like this one:
_npm install iobroker.zigbee@1.0.1 --loglevel error --prefix "/opt/iobroker" (System call)
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c: In function ‘strftimeFunc’:
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c:14234:27: warning: cast between incompatible function types from ‘int (*)(void *)’ to ‘void (*)(void *)’ [-Wcast-function-type] #define SQLITE_DYNAMIC   ((sqlite3_destructor_type)sqlite3MallocSize)                           ^Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c:22212:52: note: in expansion of macro ‘SQLITE_DYNAMIC’                       z==zBuf ? SQLITE_TRANSIENT : SQLITE_DYNAMIC);                                                    ^~~~~~~~~~~~~~
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c: In function ‘sqlite3ErrorWithMsg’:
Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c:14234:27: warning: cast between incompatible function types from ‘int (*)(void *)’ to ‘void (*)(void *)’ [-Wcast-function-type] #define SQLITE_DYNAMIC   ((sqlite3_destructor_type)sqlite3MallocSize)                           ^Release/obj/gen/sqlite-autoconf-3300100/sqlite3.c:30555:54: note: in expansion of macro ‘SQLITE_DYNAMIC’     sqlite3ValueSetStr(db->pErr, -1, z, SQLITE_UTF8, SQLITE_DYNAMIC);                                                      ^~~~~~~~~~~~~~_

After the upgrade it is not possible to start the adapter. Are there any depencies for this adpater?

Peter

**Comment by kirovilya** [comment]
there no errors in logs.
show full logs

**Comment by mickym2** [comment]
The upgrade to version 1.0.1 failed in the first installation as well:

`2020-01-29 08:43:23.469  - [32minfo[39m: host.MWHome iobroker Update "system.adapter.zigbee.0"
2020-01-29 08:43:24.415  - [32minfo[39m: host.MWHome iobroker upload [150] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/unknown.png img/unknown.png image/png
2020-01-29 08:43:27.534  - [32minfo[39m: host.MWHome iobroker upload [100] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/osram_g_spot.png img/osram_g_spot.png image/png
2020-01-29 08:43:27.656  - [31merror[39m: host.MWHome iobroker events.js:174      throw er; // Unhandled 'error' event      ^Error: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.zigbee/admin/img/osram_a60_rgbw.png'Emitted 'error' event at:    at lazyFs.open (internal/fs/streams.js:115:12)    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
2020-01-29 08:43:27.669  - [32minfo[39m: host.MWHome iobroker exit 1`

Reason seems to me - that a file at the end of the installation process was not found: osram_g_spot.png 

However - after I created accidently a new instance of the zigbee adapter, which I deleted afterwards - or there was some other self repairing mechanism - the adapter runs properly now. So may be it is only a minor bug in the installation script - with the osram*.png file

**Comment by Meinsda** [comment]
I do the same, after i install a new instance it works again. My errorlog looks like problems with the database.

**Comment by mickym2** [comment]
It seems with the installation of the new instance - the adapter automatically installed missing packages, which seems to be not available in the first trial:

`2020-01-29 08:53:06.016  -		error	: host.MWHome iobroker npm-install: Some packets could not be installed. Please install them manually
2020-01-29 08:53:06.916  -		info	: host.MWHome iobroker npm-install: upload [150] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/unknown.png img/unknown.png image/png
2020-01-29 08:53:09.836  -		info	: host.MWHome iobroker npm-install: upload [100] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/osram_g_spot.png img/osram_g_spot.png image/png
2020-01-29 08:53:10.478  -		info	: host.MWHome iobroker npm-install: upload [90] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/lumi_vibration.png img/lumi_vibration.png image/png
2020-01-29 08:53:11.125  -		info	: host.MWHome iobroker npm-install: upload [80] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/livolo.png img/livolo.png image/png
2020-01-29 08:53:11.726  -		info	: host.MWHome iobroker npm-install: upload [70] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/konke_kpft.png img/konke_kpft.png image/png
2020-01-29 08:53:12.309  -		info	: host.MWHome iobroker npm-install: upload [60] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/innr.png img/innr.png image/png
2020-01-29 08:53:12.889  -		info	: host.MWHome iobroker npm-install: upload [50] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/ikea_led1837r5.PNG img/ikea_led1837r5.PNG image/png
2020-01-29 08:53:13.500  -		info	: host.MWHome iobroker npm-install: upload [40] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/hs1sa.png img/hs1sa.png image/png
2020-01-29 08:53:14.085  -		info	: host.MWHome iobroker npm-install: upload [30] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/fnb56zsw01.png img/fnb56zsw01.png image/png
2020-01-29 08:53:14.677  -		info	: host.MWHome iobroker npm-install: upload [20] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/ctrl_neutral1.png img/ctrl_neutral1.png image/png
2020-01-29 08:53:14.734  -		info	: host.MWHome iobroker npm-install: upload [19] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/ctrl_ln2.png img/ctrl_ln2.png image/png
2020-01-29 08:53:14.792  -		info	: host.MWHome iobroker npm-install: upload [18] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/ctrl_ln1.png img/ctrl_ln1.png image/png
2020-01-29 08:53:14.850  -		info	: host.MWHome iobroker npm-install: upload [17] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/contact.png img/contact.png image/png
2020-01-29 08:53:14.908  -		info	: host.MWHome iobroker npm-install: upload [16] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/bitron_plug.png img/bitron_plug.png image/png
2020-01-29 08:53:14.970  -		info	: host.MWHome iobroker npm-install: upload [15] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/battery_v.png img/battery_v.png image/png
2020-01-29 08:53:15.028  -		info	: host.MWHome iobroker npm-install: upload [14] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/battery_p.png img/battery_p.png image/png
2020-01-29 08:53:15.087  -		info	: host.MWHome iobroker npm-install: upload [13] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/basiczbr3.png img/basiczbr3.png image/png
2020-01-29 08:53:15.145  -		info	: host.MWHome iobroker npm-install: upload [12] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/aqara_temperature_sensor.png img/aqara_temperature_sensor.png image/png
2020-01-29 08:53:15.203  -		info	: host.MWHome iobroker npm-install: upload [11] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/aqara_switch.png img/aqara_switch.png image/png
2020-01-29 08:53:15.260  -		info	: host.MWHome iobroker npm-install: upload [10] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/aqara_numan_body_sensor.png img/aqara_numan_body_sensor.png image/png
2020-01-29 08:53:15.319  -		info	: host.MWHome iobroker npm-install: upload [9] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/aqara_curtain.png img/aqara_curtain.png image/png
2020-01-29 08:53:15.381  -		info	: host.MWHome iobroker npm-install: upload [8] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/aqara_bulb.png img/aqara_bulb.png image/png
2020-01-29 08:53:15.439  -		info	: host.MWHome iobroker npm-install: upload [7] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/Ikea_fyrtur.png img/Ikea_fyrtur.png image/png
2020-01-29 08:53:15.498  -		info	: host.MWHome iobroker npm-install: upload [6] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/FLOALT.panel.WS.png img/FLOALT.panel.WS.png image/png
2020-01-29 08:53:15.556  -		info	: host.MWHome iobroker npm-install: upload [5] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/Eurotronic_Spirit_04.png img/Eurotronic_Spirit_04.png image/png
2020-01-29 08:53:15.614  -		info	: host.MWHome iobroker npm-install: upload [4] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/DIYRuZ.png img/DIYRuZ.png image/png
2020-01-29 08:53:15.672  -		info	: host.MWHome iobroker npm-install: upload [3] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/86sw2.png img/86sw2.png image/png
2020-01-29 08:53:15.730  -		info	: host.MWHome iobroker npm-install: upload [2] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/86sw1.png img/86sw1.png image/png
2020-01-29 08:53:15.789  -		info	: host.MWHome iobroker npm-install: upload [1] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/img/86plug.png img/86plug.png image/png
2020-01-29 08:53:15.847  -		info	: host.MWHome iobroker npm-install: upload [0] zigbee.admin /opt/iobroker/node_modules/iobroker.zigbee/admin/admin.js admin.js application/javascript
2020-01-29 08:53:15.959  -		info	: host.MWHome iobroker npm-install: host.MWHome object system.adapter.zigbee created/updated
2020-01-29 08:53:17.117  -		info	: host.MWHome iobroker npm-install: exit 0
2020-01-29 08:53:17.118  -		info	: host.MWHome startInstance system.adapter.zigbee.0: should start instance but disabled, re-enable
2020-01-29 08:53:17.121  -		info	: host.MWHome instance "system.adapter.zigbee.0" enabled via .alive
2020-01-29 08:53:17.137  -		info	: host.MWHome "system.adapter.zigbee.0" enabled
2020-01-29 08:53:17.153  -		info	: host.MWHome instance system.adapter.zigbee.0 started with pid 6735`

**Comment by arteck** [comment]
08:53:17.153 - info : host.MWHome instance system.adapter.zigbee.0 started with pid 6735

where is the problem ???

**Comment by Meinsda** [comment]
If you upgrade from a Version<1.0 to the newest it will not run. The Adapter don't work. So if you remove the adapter and install them again it works.

**Comment by mickym2** [comment]
> 08:53:17.153 - info : host.MWHome instance system.adapter.zigbee.0 started with pid 6735
> where is the problem ???

my problem is in my first posting. After I created a new instance - you see that the adapter installing missing files by itself and finally started without errors!!!

So the problem is my first post - and the second post shows what the adapter did to repair itself.
