### ISSUE TITLE
Failed to DeviceConfigure.onZigbeeStarted 

### ISSUE THREAD

**Issue by realwax** [ioBroker/ioBroker.zigbee#504]
Hallo,

Neue Fehlermeldung:

zigbee.0 | 2020-01-28 13:11:25.764 | error | at DeviceConfigure.onZigbeeStarted (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:39:26))
-- | -- | -- | --
zigbee.0 | 2020-01-28 13:11:25.764 | error | at DeviceConfigure.shouldConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:17:102)
zigbee.0 | 2020-01-28 13:11:25.764 | error | (729) Failed to DeviceConfigure.onZigbeeStarted (TypeError: Cannot read property 'configureKey' of undefined
zigbee.0 | 2020-01-28 13:16:05.020 | error | (729) Failed to DeviceConfigure.onZigbeeEvent (TypeError: Cannot read property 'configureKey' of undefined at DeviceConfigure.shouldConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDevi
-- | -- | -- | --

Bitte um Info inwiefern relevant, oder Aktion zu setzen ist.  

Danke

**Comment by realwax** [comment]
Habe es gelöst. Es war ein 0x00158d00028b3478 (addr 56970): ZNCZ02LM - Xiaomi Mi power plug ZigBee (Router) - der dies ausllöste. Ich habe das Gerät nicht aus der shepard.db genommen, aber dennoch neu angelernt. Das behob den Fehler. Ticket kann geschlossen werden und ist nur mehr FYI.
