### ISSUE TITLE
Can not delete divece

### ISSUE THREAD

**Issue by Maschler** [ioBroker/ioBroker.zigbee#589]
Hi,

here is another issue i have. When i try to delete the device, the following error appears:

```
zigbee.0 | 2020-04-11 10:24:35.480 | error | at Timer.processTimers (timers.js:223:10))
-- | -- | -- | --
zigbee.0 | 2020-04-11 10:24:35.480 | error | at listOnTimeout (timers.js:263:5)
zigbee.0 | 2020-04-11 10:24:35.480 | error | at tryOnTimeout (timers.js:300:5)
zigbee.0 | 2020-04-11 10:24:35.480 | error | at ontimeout (timers.js:436:11)
zigbee.0 | 2020-04-11 10:24:35.480 | error | at Timeout.object.timer.setTimeout [as _onTimeout] (/opt/iobroker/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
zigbee.0 | 2020-04-11 10:24:35.480 | error | (26681) Failed to do action 0xd0cf5efffe2e557a TRADFRI wireless dimmer,  attempt 1 (Error: AREQ - ZDO - mgmtLeaveRsp after 10000ms
zigbee.0 | 2020-04-11 10:24:25.475 | info | (26681) Do action on 0xd0cf5efffe2e557a TRADFRI wireless dimmer
```

**Comment by captchaos99** [comment]
Same here......but found a workaround for me:

cd /opt/iobroker
sudo iobroker stop
cd ~
sudo chmod 777 /opt/iobroker
sudo chown -R iobroker /opt/iobroker
cd /opt/iobroker
sudo iobroker restart

after that you cant delete the device.
im sure its just an access problem.
never tryed the install-fixer (who sets new rights too) but if someone do could give me feedback.
Thank u :)
(sry for bad english :( )
