### ISSUE TITLE
FYRTUR-Rollos lassen sich nach Reboot nicht mehr steuern

### ISSUE THREAD

**Issue by DerMario82** [ioBroker/ioBroker.zigbee#590]
Hi, ich habe 2 Ikea FYRTUR-Rollos in iobroker eingebunden, die funktionieren auch soweit - allerdings immer nur solange, bis der Raspberry (ist ein 3B) neustartet.
Die Rollos sind noch erreichbar und senden ihre LinkQuality - allerdings bekomme ich
einen timeout-Fehler, sobald ich eine geänderte Position senden will:

`
zigbee.0 | 2020-04-11 11:26:25.104 | error | at rejected (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65)
-- | -- | -- | --
zigbee.0 | 2020-04-11 11:26:25.104 | error | at Generator.throw (<anonymous>)
zigbee.0 | 2020-04-11 11:26:25.104 | error | at Endpoint.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:349:23)
zigbee.0 | 2020-04-11 11:26:25.104 | error | (1286) Error on send command to 0x680ae2fffe11cec6. Error: Error: Command 0x680ae2fffe11cec6/1 closuresWindowCovering.goToLiftPercentage({"percentageliftvalue":10}, {"timeout":6000,"manufacturerCode"
`

Dann muss ich die Rollos resetten (beide Knöpfe 5 sec), neu pairen, und sobald sie sich mit
"Device announced itself..." melden, funktionieren sie wieder bis zum Neustart. Alle anderen zigbee-Geräte funktionieren weiterhin.
(tritt nur bei einem kompletten Reboot auf, zigbee-Adapter restart und iobroker restart geht).

Was ich bereits alles probiert habe:
- Alle Zigbee-Geräte gelöscht
- Stick Hard-Reset
- Zigbee Instanz gelöscht + Adapter deinstalliert
-/opt/iobroker/iobroker-data/zigbee_0 gelöscht
- Adapter neuinstalliert (auch mal manuell über git)
- kompletten Zigbee-Stick getauscht (CC2531 auf CC2538)
- Firmwareupdate gesucht über die neue Funktion in der 1.0.4

Leider alles ohne Erfolg...

**Comment by Sacred-Shadow** [comment]
Hast auch einfach mal länger gewartet, ob die Rollos dann die Verbindung wieder herstellen?

**Comment by DerMario82** [comment]
Ja, müssen leider immer wieder neue gepairt werden :( Ziel war es eigentlich, das die Rollos bei Sonnenuntergrang runtergehen und morgens wieder hoch - leider muss ich meinen Raspi jede Nacht automatisch neustarten, weil sich sonst alles nach 2-3 Tagen aufhängt und nix mehr geht :/

**Comment by HansMaier** [comment]
Ich habe denke ich das gleiche oder zumindest ein sehr ähnliches Problem.
Ich habe 4 FYRTUR, aber bei mir ist nicht mal ein reset notwending, es funktioniert einige Tage lang und irgendwann fällt eins aus. Wenn man weiter wartet ist dann irgendwann das nächste dran. Die Fehlermeldung ist bei mir die gleiche wie oben erwähnt. 
Was ich nicht ganz verstehe, es klingt bei der Fehlermeldung ja so, als gäbe es ein Timeout beim senden des Befehls an das Rollo, jedoch ist das Rollo nicht offline (schaut zumindest so aus):
Available=true
link_quality=60

Ich hatte auch zuerst den CC2531 und bin dann auf den CC2538 gewechselt, weil ich schon über 20 Geräte im Netzwerk habe und dachte, es könnte daran liegen. Leider hat das nichts gebracht.

Habe den Adapter momentan auf 1.0.4
Generell habe ich noch nicht sonderlich viel Erfahrung mit Zigbee, aber als mein System aufgesetzt habe, hatte ich noch den Shepherd Converter und mit diesem Converter ist mir kein Problem aufgefallen. Es kam aber recht schnell das Update auf Herdsman, also könnte das Problem auch dort bestehen und ich habe es nicht bemerkt.
Ein Downgrade könnte vielleicht mal ein Versuch wert sein.

**Comment by allofmex** [comment]
Was habt ihr sonst für Geräte im Netz? Ich hatte Schwierigkeiten solange ich Osram smart Plugs und Müller Licht Lampen genutzt habe. Die scheinen andere Geräte aus dem Netz geworfen zu haben..

**Comment by Sacred-Shadow** [comment]
Also ich hab nen breiten Mix und die Smart Plugs sind auch dabei, passiert aber nix derartiges.

**Comment by HansMaier** [comment]
Ich habe
- 1 osram lampe
- ein paar Innr smart plugs
- 2 mueller licht tint controller

Die osram Lampe wird auch über normale lichtschalter geschalten, ist also größtenteils ohne strom.

Ich versuche es mal ohne die osram, mal schauen ob es dann besser klappt, Danke

**Comment by DerMario82** [comment]
Ich hatte ja schon probiert alles neu einzurichten, das Problem tritt auch auf wenn ein Rollo das einzige Gerät im Netz ist...

**Comment by HansMaier** [comment]
Ich habe mir btw vor paar Monaten auch extra das Ikea Gateway geholt und damit ein Firmware Update aller Rollos durchgeführt, hatte leider auch nix gebracht

**Comment by DerMario82** [comment]
Blöd das das so ein unlösbares Problem ist 👎🏻 Weiss jemand, wie man den Pairing-Mode über einen Button aktivieren kann, das man nicht jedes Mal in die iobroker-Oberfläche rein muss? Würde mir die Funktion dann auf einen zigbee-Button legen. Bei den Objekten unter Info den ParingMode auf true zu setzen, funktioniert leider nicht....
