### ISSUE TITLE
ZigBee-Adapter bleibt rot

### ISSUE THREAD

**Issue by jonas0806** [ioBroker/ioBroker.zigbee#60]
Hallo,

beim start des Adapters, bleibt dieser rot und wirft einige Fehler.

Als Hardware ist ein Raspberry 3 und der geflashte CC253 im Einsatz.

Hier der entsprechende Teil des Log-Files:
`.adapter.zigbee.0 because enabled
2018-09-27 17:59:46.471  - info: host.ioBroker-RasPi instance system.adapter.zigbee.0 started with pid 23382
2018-09-27 17:59:47.536  - error: Caught by controller[0]: /opt/iobroker/node_modules/bindings/bindings.js:96
2018-09-27 17:59:47.536  - error: Caught by controller[0]:   throw err
2018-09-27 17:59:47.536  - error: Caught by controller[0]:   ^
2018-09-27 17:59:47.536  - error: Caught by controller[0]: Error: Could not locate the bindings file. Tried:
2018-09-27 17:59:47.536  - error: Caught by controller[0]:  → /opt/iobroker/node_modules/serialport/build/serialport.node
2018-09-27 17:59:47.536  - error: Caught by controller[0]:  → /opt/iobroker/node_modules/serialport/build/Debug/serialport.node
2018-09-27 17:59:47.536  - error: Caught by controller[0]:  → /opt/iobroker/node_modules/serialport/build/Release/serialport.node
2018-09-27 17:59:47.537  - error: Caught by controller[0]:  → /opt/iobroker/node_modules/serialport/out/Debug/serialport.node
2018-09-27 17:59:47.537  - error: Caught by controller[0]:  → /opt/iobroker/node_modules/serialport/Debug/serialport.node
2018-09-27 17:59:47.537  - error: Caught by controller[0]:  → /opt/iobroker/node_modules/serialport/out/Release/serialport.node
2018-09-27 17:59:47.538  - error: Caught by controller[0]:  → /opt/iobroker/node_modules/serialport/Release/serialport.node
2018-09-27 17:59:47.538  - error: Caught by controller[0]:  → /opt/iobroker/node_modules/serialport/build/default/serialport.node
2018-09-27 17:59:47.538  - error: Caught by controller[0]:  → /opt/iobroker/node_modules/serialport/compiled/8.11.4/linux/arm/serialport.node
2018-09-27 17:59:47.538  - error: Caught by controller[0]:     at bindings (/opt/iobroker/node_modules/bindings/bindings.js:93:9)
2018-09-27 17:59:47.538  - error: Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/serialport/lib/bindings/linux.js:2:36)
2018-09-27 17:59:47.538  - error: Caught by controller[0]:     at Module._compile (module.js:652:30)
2018-09-27 17:59:47.538  - error: Caught by controller[0]:     at Object.Module._extensions..js (module.js:663:10)
2018-09-27 17:59:47.538  - error: Caught by controller[0]:     at Module.load (module.js:565:32)
2018-09-27 17:59:47.538  - error: Caught by controller[0]:     at tryModuleLoad (module.js:505:12)
2018-09-27 17:59:47.538  - error: Caught by controller[0]:     at Function.Module._load (module.js:497:3)
2018-09-27 17:59:47.538  - error: Caught by controller[0]:     at Module.require (module.js:596:17)
2018-09-27 17:59:47.539  - error: Caught by controller[0]:     at require (internal/module.js:11:18)
2018-09-27 17:59:47.539  - error: Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/serialport/lib/bindings/auto-detect.js:16:22)
2018-09-27 17:59:47.539  - error: host.ioBroker-RasPi instance system.adapter.zigbee.0 terminated with code 1 ()
2018-09-27 17:59:47.539  - info: host.ioBroker-RasPi Restart adapter system.adapter.zigbee.0 because enabled
`

Kann mir jemand sagen, woran das liegt? COM-Port ist angegeben.

Gruß Jonas

**Comment by arteck** [comment]
da stimmt was nicht mit der installtion des adapters.. nimm bitte mal den aus DEV

**Comment by arteck** [comment]
Version 0.7.3 ist da

**Comment by hdxbrain** [comment]
Bekomme auch solche Fehlermeldungen und der Adapter bleibt gelb oder rot

**Comment by arteck** [comment]
probiert mal mein repo https://github.com/arteck/ioBroker.zigbee

**Comment by flubb86** [comment]
Hallo, habe ein ähnliches Problem und daher einfach mal dein repo ausprobiert, jedoch läuft es damit leider auch nicht:

> zigbee.0 | 2019-01-25 21:05:28.824 | error | Error while starting zigbee-shepherd!. Error: request timeout
> -- | -- | -- | --
> zigbee.0 | 2019-01-25 21:05:20.843 | info | Starting zigbee-shepherd
> zigbee.0 | 2019-01-25 21:04:20.704 | info | Error while starting zigbee-shepherd, attemping to fix... (takes 60 seconds)
> zigbee.0 | 2019-01-25 21:04:17.708 | info | Queue is: true
> zigbee.0 | 2019-01-25 21:04:17.707 | info | Start on port: /dev/ttyACM0 with panID 6754 channel 11
> zigbee.0 | 2019-01-25 21:04:17.705 | info | starting. Version 0.8.2-a in /opt/iobroker/node_modules/iobroker.zigbee, node: v8.15.0

Jemand eine Idee woran es liegen könnte?

**Comment by arteck** [comment]
der cc2531 wird nicht gefunden

**Comment by k2dp2k** [comment]
@arteck hab den gleichen Fehler auf nem rock64 der Stick wird erkannt, aber sobald dieser was ausführen soll schmiert der Adapter ab. Berechtigungen passen, Adapter egal welche Version zeigt das gleiche Verhalten. Kann es sein das der Stick von Armbian standardmäßig mit dem falschen Treiber versorgt wird? Vielleicht hast du ja noch eine Idee, bin mit meinem Latein am Ende...

**Comment by EliasKotlyar** [comment]
Ich hatte denselben Fehler( error: Caught by controller[0]: /opt/iobroker/node_modules/bindings/bindings.js:96)  auf einem Olimexino A20 mit Armbian drauf. Gelöst habe ich es folgendermaßen. Es hat sich rausgestellt, das die serialport-library nicht durchkompiliert. Lösung:
 Vorher mit "sudo npm install serialport --unsafe-perm --build-from-source" probieren, damit sieht man ob der serialport durchkompiliert. Falls nicht, entsprechende Packete nachinstallieren(findet man durch google, bei mir wars apt-get install python-dev). Erst danach den Iobroker installieren.

**Comment by Apollon77** [comment]
>  Erst danach den Iobroker installieren.
Das sollte nicht nötig sein. Falls etwas nicht korrekt installiertz ist hilft ggf ein "npm rebuild"
