### ISSUE TITLE
Innr SP 120: Failed to configure

### ISSUE THREAD

**Issue by vain90** [ioBroker/ioBroker.zigbee#621]
Hallo,

I have two Innr SP 120 in use.
So far they work without problems. But I get some errors in the Zigbee log.

Adapter Version: 1.1.1

When I start the Zigbee adapter, I get the following errors several times:
```
zigbee.0	2020-05-05 13:51:41.443	error	(11410) Failed to configure 0x00158d0003891684 SP 120, attempt 5 (Error: Read 0x00158d0003891684/1 haElectricalMeasurement(["acVoltageMultiplier","acVoltageDivisor","acCurrentMultiplier"], {"timeout":
zigbee.0	2020-05-05 13:51:40.987	info	(11410) Configuring 0x00158d0003891684 SP 120
zigbee.0	2020-05-05 13:51:39.453	error	(11410) Failed to configure 0x00158d0003891684 SP 120, attempt 4 (Error: Read 0x00158d0003891684/1 haElectricalMeasurement(["acVoltageMultiplier","acVoltageDivisor","acCurrentMultiplier"], {"timeout":
zigbee.0	2020-05-05 13:51:38.993	info	(11410) Configuring 0x00158d0003891684 SP 120
zigbee.0	2020-05-05 13:51:38.303	error	(11410) Failed to configure 0x00158d0003894408 SP 120, attempt 2 (Error: Read 0x00158d0003894408/1 haElectricalMeasurement(["acVoltageMultiplier","acVoltageDivisor","acCurrentMultiplier"], {"timeout":
zigbee.0	2020-05-05 13:51:37.921	info	(11410) Configuring 0x00158d0003894408 SP 120
zigbee.0	2020-05-05 13:51:37.533	error	(11410) Failed to configure 0x00158d0003891684 SP 120, attempt 3 (Error: Read 0x00158d0003891684/1 haElectricalMeasurement(["acVoltageMultiplier","acVoltageDivisor","acCurrentMultiplier"], {"timeout":
zigbee.0	2020-05-05 13:51:37.001	info	(11410) Configuring 0x00158d0003891684 SP 120
zigbee.0	2020-05-05 13:51:35.695	error	(11410) Failed to configure 0x00158d0003891684 SP 120, attempt 2 (Error: Read 0x00158d0003891684/1 haElectricalMeasurement(["acVoltageMultiplier","acVoltageDivisor","acCurrentMultiplier"], {"timeout":
zigbee.0	2020-05-05 13:51:26.005	info	(11410) Configuring 0x00158d0003891684 SP 120
zigbee.0	2020-05-05 13:51:24.183	error	(11410) Failed to configure 0x00158d0003894408 SP 120, attempt 1 (Error: Read 0x00158d0003894408/1 haElectricalMeasurement(["acVoltageMultiplier","acVoltageDivisor","acCurrentMultiplier"], {"timeout":
zigbee.0	2020-05-05 13:51:22.233	info	(11410) Configuring 0x00158d0003894408 SP 120
zigbee.0	2020-05-05 13:51:22.233	error	(11410) Failed to configure 0x00158d0003891684 SP 120, attempt 1 (Error: Read 0x00158d0003891684/1 haElectricalMeasurement(["acVoltageMultiplier","acVoltageDivisor","acCurrentMultiplier"], {"timeout":
zigbee.0	2020-05-05 13:51:21.654	info	(11410) Zigbee started
```

The following lines appear a short moment later:

```
zigbee.0	2020-05-05 13:52:34.077	error	at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58))
zigbee.0	2020-05-05 13:52:34.077	error	at Generator.next (<anonymous>)
zigbee.0	2020-05-05 13:52:34.077	error	at Endpoint.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:182:23)
zigbee.0	2020-05-05 13:52:34.077	error	(11410) Failed to configure 0x00158d0003894408 SP 120, attempt 5 (Error: Read 0x00158d0003894408/1 haElectricalMeasurement(["acVoltageMultiplier","acVoltageDivisor","acCurrentMultiplier"], {"timeout"
zigbee.0	2020-05-05 13:52:33.733	info	(11410) Configuring 0x00158d0003894408 SP 120
zigbee.0	2020-05-05 13:52:16.114	error	at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58))
zigbee.0	2020-05-05 13:52:16.114	error	at Generator.next (<anonymous>)
zigbee.0	2020-05-05 13:52:16.114	error	at Endpoint.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:182:23)
zigbee.0	2020-05-05 13:52:16.114	error	(11410) Failed to configure 0x00158d0003894408 SP 120, attempt 4 (Error: Read 0x00158d0003894408/1 haElectricalMeasurement(["acVoltageMultiplier","acVoltageDivisor","acCurrentMultiplier"], {"timeout"
zigbee.0	2020-05-05 13:52:15.742	info	(11410) Configuring 0x00158d0003894408 SP 120
```
In addition, the plug has no picture in my network map. I've already done an upload.
As already written, it works without problems. Also the performance measurement!

Thanks in advance.
Best regards

**Comment by arteck** [comment]
which coordinator and which firmware you have?

**Comment by vain90** [comment]
Oh sorry,
I use a CC1352P-2

I'm currently using CC1352P_2_20200417
The problem was also present in the CC1352P_2_20191106.

**Comment by vain90** [comment]
Please reopen this issue. This issue isn't fixed yet.
