### ISSUE TITLE
Some Errors during Pairing Process.

### ISSUE THREAD

**Issue by Beliar-666** [ioBroker/ioBroker.zigbee#624]
Hello, with some Hardware i got Errors. Osram Smart+ Motion Sensors won´t pair correct. They appear in the List, But they have no function, also an Error during Pairing appears. Also some Ligthbulbs and the Osram Smart+ Socket gives errors. The socket and the bulbs have function, but the Socket switches on and off without doing anything. 

`Device '0x7cb03eaa0a01891a' announced itself
Error: Failed to configure 0x000d6f000fbfacbf Motion Sensor-A, attempt 4 (Error: ConfigureReporting 0x000d6f000fbfacbf/1 msTemperatureMeasurement([{"attribute":"measuredValue","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":25}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'INVALID_DATA_TYPE')
    at Endpoint.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58)). undefined
Error: Failed to configure 0x00158d0001fdde6d ZBT-DimmableLight, attempt 3 (Error: ConfigureReporting 0x00158d0001fdde6d/1 genOnOff([{"attribute":"onOff","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":0}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'INVALID_DATA_TYPE')
    at Endpoint.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58)). undefined
Error: Failed to configure 0x000d6f000fbfacbf Motion Sensor-A, attempt 3 (Error: ConfigureReporting 0x000d6f000fbfacbf/1 msTemperatureMeasurement([{"attribute":"measuredValue","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":25}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'INVALID_DATA_TYPE')
    at Endpoint.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58)). undefined
Error: Failed to configure 0x000d6f000fbfacbf Motion Sensor-A, attempt 2 (Error: ConfigureReporting 0x000d6f000fbfacbf/1 msTemperatureMeasurement([{"attribute":"measuredValue","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":25}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'INVALID_DATA_TYPE')
    at Endpoint.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58)). undefined
Error: Failed to configure 0x000d6f000fbfacbf Motion Sensor-A, attempt 1 (Error: ConfigureReporting 0x000d6f000fbfacbf/1 msTemperatureMeasurement([{"attribute":"measuredValue","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":25}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'INVALID_DATA_TYPE')
    at Endpoint.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58)). undefined
Error: Failed to configure 0x000d6f000fbf76e4 Motion Sensor-A, attempt 4 (Error: ConfigureReporting 0x000d6f000fbf76e4/1 msTemperatureMeasurement([{"attribute":"measuredValue","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":25}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'INVALID_DATA_TYPE')
    at Endpoint.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58)). undefined
Error: Failed to configure 0x000d6f000fbf76e4 Motion Sensor-A, attempt 3 (Error: ConfigureReporting 0x000d6f000fbf76e4/1 msTemperatureMeasurement([{"attribute":"measuredValue","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":25}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'INVALID_DATA_TYPE')
    at Endpoint.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58)). undefined
Error: Failed to configure 0x00158d0001fdde6d ZBT-DimmableLight, attempt 2 (Error: ConfigureReporting 0x00158d0001fdde6d/1 genOnOff([{"attribute":"onOff","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":0}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'INVALID_DATA_TYPE')
    at Endpoint.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58)). undefined
Error: Failed to configure 0x000d6f000fbf76e4 Motion Sensor-A, attempt 2 (Error: ConfigureReporting 0x000d6f000fbf76e4/1 msTemperatureMeasurement([{"attribute":"measuredValue","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":25}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'INVALID_DATA_TYPE')
    at Endpoint.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58)). undefined
Error: Failed to configure 0x000d6f000fbf76e4 Motion Sensor-A, attempt 1 (Error: ConfigureReporting 0x000d6f000fbf76e4/1 msTemperatureMeasurement([{"attribute":"measuredValue","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":25}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'INVALID_DATA_TYPE')
    at Endpoint.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)`

`Error: Failed to configure 0x00158d0001fdde6d ZBT-DimmableLight, attempt 1 (Error: ConfigureReporting 0x00158d0001fdde6d/1 genOnOff([{"attribute":"onOff","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":0}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'INVALID_DATA_TYPE')
    at Endpoint.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58)). undefined
Device '0x7cb03eaa0a01891a' announced itself
Error: Failed to configure 0x000d6f000fbfacbf Motion Sensor-A, attempt 1 (Error: ConfigureReporting 0x000d6f000fbfacbf/1 msTemperatureMeasurement([{"attribute":"measuredValue","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":25}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'INVALID_DATA_TYPE')
    at Endpoint.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58)). undefined
Error: Failed to configure 0x00158d0001fdde6d ZBT-DimmableLight, attempt 1 (Error: ConfigureReporting 0x00158d0001fdde6d/1 genOnOff([{"attribute":"onOff","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":0}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'INVALID_DATA_TYPE')
    at Endpoint.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58)). undefined
Error: Failed to configure 0x00158d0001fdde6d ZBT-DimmableLight, attempt 1 (Error: ConfigureReporting 0x00158d0001fdde6d/1 genOnOff([{"attribute":"onOff","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":0}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'INVALID_DATA_TYPE')
    at Endpoint.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58)). undefined
Error: Failed to configure 0x00158d0001fdde6d ZBT-DimmableLight, attempt 1 (Error: ConfigureReporting 0x00158d0001fdde6d/1 genOnOff([{"attribute":"onOff","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":0}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'INVALID_DATA_TYPE')
    at Endpoint.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58)). undefined
Device '0x7cb03eaa0a01891a' announced itself
Error: Failed to configure 0x00158d0001fdde6d ZBT-DimmableLight, attempt 2 (Error: ConfigureReporting 0x00158d0001fdde6d/1 genOnOff([{"attribute":"onOff","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":0}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'INVALID_DATA_TYPE')
    at Endpoint.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58)). undefined
Error: Failed to configure 0x00158d0001fdde6d ZBT-DimmableLight, attempt 1 (Error: ConfigureReporting 0x00158d0001fdde6d/1 genOnOff([{"attribute":"onOff","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":0}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'INVALID_DATA_TYPE')
    at Endpoint.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58)). undefined
Device '0x7cb03eaa0a01891a' announced itself`

IoB Log Errors: 
`
Zigbee.0 | 2020-05-07 01:23:22.189 | debug | (26417) Received Zigbee message from '0x000d6f000fbfacbf', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"manufacturerCode":4174,"imageType":48,"fileVersion":50333774
-- | -- | -- | --
zigbee.0 | 2020-05-07 01:23:22.188 | debug | (26417) handleMessage. {"type":"commandQueryNextImageRequest","device":{"ID":19,"_type":"EndDevice","_ieeeAddr":"0x000d6f000fbfacbf","_networkAddress":25567,"_manufacturerID":4174,"_endpoints":[{"ID"
zigbee.0 | 2020-05-07 01:23:20.483 | error | at fulfilled (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58))
zigbee.0 | 2020-05-07 01:23:20.483 | error | at Generator.next (<anonymous>)
zigbee.0 | 2020-05-07 01:23:20.483 | error | at Endpoint.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
zigbee.0 | 2020-05-07 01:23:20.483 | error | (26417) Failed to configure 0x00158d0001fdde6d ZBT-DimmableLight, attempt 1 (Error: ConfigureReporting 0x00158d0001fdde6d/1 genOnOff([{"attribute":"onOff","minimumReportInterval":0,"maximumReportInte
zigbee.0 | 2020-05-07 01:23:19.776 | info | (26417) Configuring 0x00158d0001fdde6d ZBT-DimmableLight
zigbee.0 | 2020-05-07 01:23:19.775 | debug | (26417) No converter available for '4713407' with cluster 'genOta' and type 'commandQueryNextImageRequest'

`

Also i can not delete some Devices. and my Network shows everything red without connections, but the most Hardware works.

Using 1.1.1 with Conbee2

**Comment by arteck** [comment]
Conbee2 is only alpha supported
