### ISSUE TITLE
Osram Motion Sensor

### ISSUE THREAD

**Issue by hoepps2802** [ioBroker/ioBroker.zigbee#645]
Hello 

when i will pair the Osram Motion sensor i get this 

Error: Failed to configure 0x000d6f000f77a794 Motion Sensor-A, attempt 5 (Error: ConfigureReporting 0x000d6f000f77a794/1 genPowerCfg([{"attribute":"batteryPercentageRemaining","minimumReportInterval":3600,"maximumReportInterval":62000,"reportableChange":0}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58)). undefined
Error: Failed to configure 0x000d6f000f77a794 Motion Sensor-A, attempt 4 (Error: ConfigureReporting 0x000d6f000f77a794/1 genPowerCfg([{"attribute":"batteryPercentageRemaining","minimumReportInterval":3600,"maximumReportInterval":62000,"reportableChange":0}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58)). undefined
Error: Failed to configure 0x000d6f000f77a794 Motion Sensor-A, attempt 3 (Error: ConfigureReporting 0x000d6f000f77a794/1 genPowerCfg([{"attribute":"batteryPercentageRemaining","minimumReportInterval":3600,"maximumReportInterval":62000,"reportableChange":0}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58)). undefined
Error: Failed to configure 0x000d6f000f77a794 Motion Sensor-A, attempt 2 (Error: ConfigureReporting 0x000d6f000f77a794/1 genPowerCfg([{"attribute":"batteryPercentageRemaining","minimumReportInterval":3600,"maximumReportInterval":62000,"reportableChange":0}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58)). undefined

I still pair one off the Motion sensor, but with earlyer version off Zigbee adapter

node.js 10.20.1
NPM 6.14.4
JS Controller 2.2.9
Zigbee Adapter 1.1.1

**Comment by Sacred-Shadow** [comment]
Something is wrong, mine does not transmit the battery level.
Can you please see which model you have there?

![grafik](https://user-images.githubusercontent.com/61997661/83250289-2ffe6400-a1a8-11ea-9731-ae6c8b0c6c82.png)


    model:AC01353010G
    vendor:OSRAM
    description:SMART+ Motion Sensor
    supports:occupancy, tamper and temperature

**Comment by hoepps2802** [comment]
Hi, i have the same one

**Comment by arteck** [comment]
> 
> 
> Something is wrong, mine does not transmit the battery level.
> Can you please see which model you have there?
> 
> ![grafik](https://user-images.githubusercontent.com/61997661/83250289-2ffe6400-a1a8-11ea-9731-ae6c8b0c6c82.png)
> 
> ```
> model:AC01353010G
> vendor:OSRAM
> description:SMART+ Motion Sensor
> supports:occupancy, tamper and temperature
> ```

this is true .. battery is not transmitted from device

**Comment by hoepps2802** [comment]
Hello

i use C2531 firmeware 20190608

i have the same device , paired long time ago, without an error

**Comment by hoepps2802** [comment]
Why, you close it? I still  have the error
