### ISSUE TITLE
Green power - senic friends of hue smart switch support

### ISSUE THREAD

**Issue by kuersche1337** [ioBroker/ioBroker.zigbee#670]
Hi, 

I'm failing on pairing my senic friend of hue smart switch. When I press ANY button on the switch, I get the following error and the zigbee adapter restarts.

```
2020-06-09 18:45:25.019 - error: zigbee.0 (17111) uncaught exception: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
2020-06-09 18:45:25.021 - error: zigbee.0 (17111) TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
at Cipheriv.update (internal/crypto/cipher.js:155:11)
at GreenPower.encryptSecurityKey (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/greenPower.js:50:34)
at GreenPower. (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/greenPower.js:57:34)
at Generator.next ()
at /opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/greenPower.js:8:71
at new Promise ()
at __awaiter (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/greenPower.js:4:12)
at GreenPower.onZclGreenPowerData (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/greenPower.js:54:16)
at Controller. (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/controller.js:405:37)
at Generator.next ()
```

First, it looked to me like a problem with the herdsman, so I reported an issue there, but so far nobody could help me. https://github.com/Koenkk/zigbee-herdsman/issues/187

I'm really deperate and would appreciate any help I can get!

Thanks
Alex

**Comment by kuersche1337** [comment]
Nobody can help me with this?

**Comment by kuersche1337** [comment]
-.- So nobody has any experience with this kind of switch?

**Comment by kuersche1337** [comment]
I'm closing this, because I finally could pair the device.
The solution for me was to pair the switch to a hue bridge first und then deleting it from there.

Afterwards I could pair it with the iobroker. I followed the advices here: https://www.zigbee2mqtt.io/devices/GreenPower_7.html

Now I have the error 
`(13213) Device 0x000000000171cfa9 "GreenPower_2" not described in statesMapping.`
but that shall not be discussed here.

kuersche
