### ISSUE TITLE
Devices can't be deleted

### ISSUE THREAD

**Issue by Grothesk242** [ioBroker/ioBroker.zigbee#676]
Trying to delete two IKEA Remote Controls. 

```
2020-06-28 19:56:43.372  - error: zigbee.0 (892) Failed to do action 0x000b57fffed28901 TRADFRI remote control, attempt 2 (TypeError: Cannot read property 'stack' of undefined
    at Object.action (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:360:69)
    at async DelayedAction.doActions (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDelayedAction.js:111:21))
2020-06-28 19:56:43.374  - info: zigbee.0 (892) Do action on 0x000b57fffed28901 TRADFRI remote control
2020-06-28 19:57:35.379  - error: zigbee.0 (892) Failed to do action 0xd0cf5efffeec84cc TRADFRI remote control, attempt 2 (TypeError: Cannot read property 'stack' of undefined
    at Object.action (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:360:69)
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:62:5)
    at processTimers (internal/timers.js:489:9)
    at async DelayedAction.doActions (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDelayedAction.js:111:21))
2020-06-28 19:57:43.379  - error: zigbee.0 (892) Failed to do action 0x000b57fffed28901 TRADFRI remote control, attempt 2 (TypeError: Cannot read property 'stack' of undefined
    at Object.action (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:360:69)
    at async DelayedAction.doActions (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDelayedAction.js:111:21))
```

**Comment by MrThreesome** [comment]
Same error here when clicking multiple on delete. Just click one time and wait
