### ISSUE TITLE
Cannot add devices to group

### ISSUE THREAD

**Issue by OXERY** [ioBroker/ioBroker.zigbee#679]
Hi there,

when I want to add devices to old/newly created groups, the Zigbee Adapter restarts because of following errors:

`2020-06-30 21:06:11.451 - error: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().`
`2020-06-30 21:06:11.452 - error: zigbee.0 (22487) unhandled promise rejection: Command 0x000b57fffeb1d9e3/1 genGroups.removeAll({}, {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Data request failed with error: 'MAC no ack' (233))`
`2020-06-30 21:06:11.452 - error: zigbee.0 (22487) Error: Command 0x000b57fffeb1d9e3/1 genGroups.removeAll({}, {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Data request failed with error: 'MAC no ack' (233))`

I'm using Adapter version 1.1.1 and a Zigbee stick as coordinator with following details: `{"type":"zStack30x","meta":{"transportrev":2,"product":2,"majorrel":2,"minorrel":7,"maintrel":2,"revision":20200327}}`, CC2538 + CC2592

**Comment by MrThreesome** [comment]
Some problem here if one of the devices is not available:

`2020-07-28 23:00:39.133  - info: zigbee.0 (9484) 0x00158d0004624e0e (addr 44142): 798.15 - Paulmann SmartHome Zigbee Pendulum Light Aptare (Router)
2020-07-28 23:00:39.137  - info: zigbee.0 (9484) Zigbee started
2020-07-28 23:03:33.591  - error: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2020-07-28 23:03:33.594  - error: zigbee.0 (9484) unhandled promise rejection: Command 0x00158d0004624e0e/1 genGroups.removeAll({}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Error: Data request failed with error: 'No network route' (205))
2020-07-28 23:03:33.600  - error: zigbee.0 (9484) Error: Command 0x00158d0004624e0e/1 genGroups.removeAll({}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Error: Data request failed with error: 'No network route' (205))
    at Endpoint.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:365:23)
    at Generator.throw (<anonymous>)
    at rejected (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65)
2020-07-28 23:03:33.604  - info: zigbee.0 (9484) cleaned everything up...
2020-07-28 23:03:33.612  - info: zigbee.0 (9484) Zigbee: disabling joining new devices.
2020-07-28 23:03:34.133  - info: zigbee.0 (9484) terminating
2020-07-28 23:03:34.136  - info: zigbee.0 (9484) Terminated (NO_ERROR): Without reason
2020-07-28 23:03:34.686  - info: host.ioBroker-RasPi instance system.adapter.zigbee.0 terminated with code 0 (NO_ERROR)
2020-07-28 23:03:34.688  - info: host.ioBroker-RasPi Restart adapter system.adapter.zigbee.0 because enabled
2020-07-28 23:04:04.719  - info: host.ioBroker-RasPi instance system.adapter.zigbee.0 started with pid 9719
2020-07-28 23:04:07.241  - info: zigbee.0 (9719) starting. **Version 1.1.2** in /opt/iobroker/node_modules/iobroker.zigbee, **node: v12.18.3, js-controller: 3.1.6**
2020-07-28 23:04:07.287  - info: zigbee.0 (9719) Starting Zigbee...
2020-07-28 23:04:09.155  - info: zigbee.0 (9719) Coordinator firmware version: {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}
2020-07-28 23:04:09.176  - info: zigbee.0 (9719)   --> transmitPower : normal
2020-07-28 23:04:09.225  - info: zigbee.0 (9719) Currently 32 devices are joined:
`
