### ISSUE TITLE
ERROR: Adpater chrashes while adding new device

### ISSUE THREAD

**Issue by Hesse-Bub** [ioBroker/ioBroker.zigbee#712]
The adapter crashes while trying to add Blitzwolf BW-IS4 Temp/Humidity Sensor (Tuya TS0201)

I tried with different versions of the Adapter (1.1.1, 1.1.2 and also the new 1.1.3 from github)

Coordinator:  CC2538+CC2592 PA ("type":"zStack30x","meta":{"transportrev":2,"product":2,"majorrel":2,"minorrel":7,"maintrel":2,"revision":20200327)

Debug LOG:
`2020-08-03 08:17:54.232 - debug: zigbee.0 (3560) Wrong device ec1bbdfffe70b2db null
2020-08-03 08:17:54.236 - debug: zigbee.0 (3560) Wrong device ec1bbdfffe70b2db null
2020-08-03 08:17:54.717 - info: zigbee.0 (3560) terminating
2020-08-03 08:17:54.718 - info: zigbee.0 (3560) Terminated (NO_ERROR): Without reason
2020-08-03 08:17:54.804 - debug: zigbee.0 (3560) handleMessage. {"type":"attributeReport","device":{"ID":13,"_type":"EndDevice","_ieeeAddr":"0xec1bbdfffe70b2db","_networkAddress":3186,"_manufacturerID":4098,"_endpoints":[{"ID":1,"profileID":260,"deviceID":770,"inputClusters":[0,1,1026,1029],"outputClusters":[25],"deviceNetworkAddress":3186,"deviceIeeeAddress":"0xec1bbdfffe70b2db","clusters":{"genBasic":{"attributes":{"modelId":"TS0201","manufacturerName":"_TYZB01_hjsgdkfl","powerSource":3,"zclVersion":3,"appVersion":65}},"msTemperatureMeasurement":{"attributes":{"measuredValue":3000}},"msRelativeHumidity":{"attributes":{"measuredValue":8880}},"genPowerCfg":{"attributes":{"batteryVoltage":31,"batteryPercentageRemaining":200}}},"_binds":[]}],"_manufacturerName":"_TYZB01_hjsgdkfl","_powerSource":"Battery","_modelID":"TS0201","_applicationVersion":65,"_zclVersion":3,"_interviewCompleted":false,"_interviewing":true,"meta":{},"_lastSeen":1596435474803},"endpoint":"[Circular]","data":{"batteryPercentageRemaining":200,"batteryVoltage":31},"linkquality":120,"groupID":0,"cluster":"genPowerCfg","meta":{"zclTransactionSequenceNumber":25,"manufacturerCode":null,"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":false,"reservedBits":0}}}
2020-08-03 08:17:54.805 - debug: zigbee.0 (3560) Received Zigbee message from '0xec1bbdfffe70b2db', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":200,"batteryVoltage":31}' from endpoint 1 with groupID 0
2020-08-03 08:17:54.806 - debug: zigbee.0 (3560) Type attributeReport device {"type":"device","device":{"ID":13,"_type":"EndDevice","_ieeeAddr":"0xec1bbdfffe70b2db","_networkAddress":3186,"_manufacturerID":4098,"_endpoints":[{"ID":1,"profileID":260,"deviceID":770,"inputClusters":[0,1,1026,1029],"outputClusters":[25],"deviceNetworkAddress":3186,"deviceIeeeAddress":"0xec1bbdfffe70b2db","clusters":{"genBasic":{"attributes":{"modelId":"TS0201","manufacturerName":"_TYZB01_hjsgdkfl","powerSource":3,"zclVersion":3,"appVersion":65}},"msTemperatureMeasurement":{"attributes":{"measuredValue":3000}},"msRelativeHumidity":{"attributes":{"measuredValue":8880}},"genPowerCfg":{"attributes":{"batteryVoltage":31,"batteryPercentageRemaining":200}}},"_binds":[]}],"_manufacturerName":"_TYZB01_hjsgdkfl","_powerSource":"Battery","_modelID":"TS0201","_applicationVersion":65,"_zclVersion":3,"_interviewCompleted":false,"_interviewing":true,"meta":{},"_lastSeen":1596435474803},"mapped":{"zigbeeModel":["TS0201"],"model":"TS0201","vendor":"TuYa","description":"Temperature & humidity sensor with display","supports":"temperature and humidity","fromZigbee":[{"cluster":"genPowerCfg","type":["attributeReport","readResponse"]},{"cluster":"msTemperatureMeasurement","type":["attributeReport","readResponse"]},{"cluster":"msRelativeHumidity","type":["attributeReport","readResponse"]}],"toZigbee":[]},"name":"0xec1bbdfffe70b2db"} incoming event: {"type":"attributeReport","device":{"ID":13,"_type":"EndDevice","_ieeeAddr":"0xec1bbdfffe70b2db","_networkAddress":3186,"_manufacturerID":4098,"_endpoints":[{"ID":1,"profileID":260,"deviceID":770,"inputClusters":[0,1,1026,1029],"outputClusters":[25],"deviceNetworkAddress":3186,"deviceIeeeAddress":"0xec1bbdfffe70b2db","clusters":{"genBasic":{"attributes":{"modelId":"TS0201","manufacturerName":"_TYZB01_hjsgdkfl","powerSource":3,"zclVersion":3,"appVersion":65}},"msTemperatureMeasurement":{"attributes":{"measuredValue":3000}},"msRelativeHumidity":{"attributes":{"measuredValue":8880}},"genPowerCfg":{"attributes":{"batteryVoltage":31,"batteryPercentageRemaining":200}}},"_binds":[]}],"_manufacturerName":"_TYZB01_hjsgdkfl","_powerSource":"Battery","_modelID":"TS0201","_applicationVersion":65,"_zclVersion":3,"_interviewCompleted":false,"_interviewing":true,"meta":{},"_lastSeen":1596435474803},"endpoint":"[Circular]","data":{"batteryPercentageRemaining":200,"batteryVoltage":31},"linkquality":120,"groupID":0,"cluster":"genPowerCfg","meta":{"zclTransactionSequenceNumber":25,"manufacturerCode":null,"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":false,"reservedBits":0}}}
2020-08-03 08:17:54.807 - debug: zigbee.0 (3560) Publish available for 0xec1bbdfffe70b2db = true
2020-08-03 08:17:54.812 - debug: zigbee.0 (3560) Wrong device ec1bbdfffe70b2db null
2020-08-03 08:17:54.813 - error: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2020-08-03 08:17:54.813 - error: zigbee.0 (3560) unhandled promise rejection: Cannot read property 'hasOwnProperty' of undefined
2020-08-03 08:17:54.814 - error: zigbee.0 (3560) TypeError: Cannot read property 'hasOwnProperty' of undefined
at Object.convert (/opt/iobroker/node_modules/zigbee-herdsman-converters/converters/fromZigbee.js:384:32)
at stController.collectOptions (/opt/iobroker/node_modules/iobroker.zigbee/main.js:270:43)
at StatesController.collectOptions (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:77:19)
at process._tickCallback (internal/process/next_tick.js:68:7)
2020-08-03 08:17:54.815 - debug: zigbee.0 (3560) Wrong device ec1bbdfffe70b2db null
2020-08-03 08:17:55.238 - info: host.iobroker instance system.adapter.zigbee.0 terminated with code 0 (NO_ERROR)
2020-08-03 08:17:55.240 - info: host.iobroker Restart adapter system.adapter.zigbee.0 because enabled
2020-08-03 08:18:25.253 - info: host.iobroker instance system.adapter.zigbee.0 started with pid 3577:`

**Comment by Hesse-Bub** [comment]
This seems to be fixed in herdsman converter 12.0.153

https://github.com/Koenkk/zigbee2mqtt/issues/4003

https://github.com/Koenkk/zigbee-herdsman-converters/commit/848c51a4c3e5dc28f511d2c69b2bd579bb0acfcb

Is it possible to change the Version at least to 12.0.153?

**Comment by kirovilya** [comment]
updated. install from github and check

**Comment by Hesse-Bub** [comment]
Thank you, this is working now :)

It also shows now the battery status of the device ... perfect
