### ISSUE TITLE
error: zigbee.0 (2316) Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'

### ISSUE THREAD

**Issue by PierreLovoo** [ioBroker/ioBroker.zigbee#722]
I had the issue, that running my CC2531 on my Raspberry worked great. From on day to another, the adapter stayed "yellow". Did a complete re-install of IOBroker and the Zigbee-Adapter. Still resulting in:

`2020-08-10 12:45:47.997 - info: zigbee.0 (2457) Starting Zigbee...
2020-08-10 12:45:55.382 - error: zigbee.0 (2457) Failed to start Zigbee
2020-08-10 12:45:55.385 - error: zigbee.0 (2457) Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
at ZStackAdapter. (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:72:23)
at Generator.throw ()
at rejected (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:6:65)
2020-08-10 12:46:05.387 - info: zigbee.0 (2457) Try to reconnect. 1 attempts left
2020-08-10 12:46:05.389 - info: zigbee.0 (2457) Starting Zigbee...
2020-08-10 12:46:05.639 - error: zigbee.0 (2457) Failed to start Zigbee
2020-08-10 12:46:05.641 - error: zigbee.0 (2457) Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
at Znp. (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:113:32)
at Generator.next ()
at /opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:8:71
at new Promise ()
at __awaiter (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:4:12)
at SerialPort.serialPort.open (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:111:49)
at SerialPort._error (/opt/iobroker/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
at binding.open.then.err (/opt/iobroker/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12)`

Also double-checked an `ls -la /dev/serial/by-id` gives me `usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B000BE88081-if00` so I entered `/dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B000BE88081-if00` as COMPORT-Name in the Settings. 

Tried with 1.2 and 1.0.4 :-( And also tried setting CCCCCCCCCCCCCCCC as ExtPanID. Not working. 

Any Ideas? Software- or Hardware-Issue?

**Comment by kirovilya** [comment]
try to unplug and plug stick again.

**Comment by PierreLovoo** [comment]
Tried that already several times. :-D Also tried different USB-Ports. 
What does "SRSP - SYS" mean in this case? Could it also be a Hardware-Issue? Read across the net, that a lot of people having same issues. But yeah, maybe it is just an issue of low-end-hardware. 

Ordered a new Stick and will check if it is working then. 

Thanks anyway for your support and this great adapter!

**Comment by kirovilya** [comment]
`SYS - ping` mean first request after connect to port https://github.com/Koenkk/zigbee-herdsman/blob/master/src/adapter/z-stack/adapter/zStackAdapter.ts#L85
I also sometimes see such an error when I reboot the adapter. It helps me to plug out and re-insert the stick.
try to reboot the PC completely

**Comment by agross** [comment]
I got out of this by reflashing the chip. There appear to be certain conditions that make the firmware go into an error state that you cannot get out by power-cycling the CC2531.

**Comment by sbormann** [comment]
same problem for me. i replaced my stick with a new one, now it is working again.
