### ISSUE TITLE
Tradfri control outlet E1603/E1702 crashes zigbee adapter

### ISSUE THREAD

**Issue by toltemp** [ioBroker/ioBroker.zigbee#765]
I am experiencing a problem with a brand new Ikea Tradfri outlet. Once the error pasted below happens the zigbee adapter does not control anything anymore. Restarting the adapter fails ("Resource temporarily unavailable Cannot lock port"). Only way to temporarily resolve is to unplug and replug the zigbee stick or restart the whole pi.

zigbee.0 | 2020-09-13 11:36:14.651 | error | at /opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:27:71
-- | -- | -- | --
zigbee.0 | 2020-09-13 11:36:14.651 | error | at Generator.next (<anonymous>)
zigbee.0 | 2020-09-13 11:36:14.651 | error | at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:298:50)
zigbee.0 | 2020-09-13 11:36:14.651 | error | at ZStackAdapter.dataRequest (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:705:16)
zigbee.0 | 2020-09-13 11:36:14.651 | error | at __awaiter (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:23:12)
zigbee.0 | 2020-09-13 11:36:14.651 | error | at new Promise (<anonymous>)
zigbee.0 | 2020-09-13 11:36:14.651 | error | at /opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:27:71
zigbee.0 | 2020-09-13 11:36:14.651 | error | at Generator.next (<anonymous>)
zigbee.0 | 2020-09-13 11:36:14.651 | error | at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:708:28)
zigbee.0 | 2020-09-13 11:36:14.651 | error | at Znp.request (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:273:19)
zigbee.0 | 2020-09-13 11:36:14.651 | error | (1810) Error on send command to 0x086bd7fffeXXXXXX. Error: Error: Command 0x086bd7fffeXXXXXX/1 closuresWindowCovering.goToLiftPercentage({"percentageliftvalue"

<img width="253" alt="image" src="https://user-images.githubusercontent.com/47525161/93015223-e6e7e980-f5b7-11ea-88f3-7625de6b3687.png">

**Comment by asgothian** [comment]
can you put the adapter in debug, check the Box "zigbee herdsman debug info" in the adapter configuration and post the last 10 to 15 messages before the error occurs ? That way we can try to trace the error back to the Source

Also - when pasting log information, please download the log and paste the information from the raw log, not from what is visible in the admin. The most interesting line (the one with the error) is incomplete.

A.

**Comment by vitalij82** [comment]
I have similar Problems after update to 1.2.1
Hier ist some ErrorLogs:

2020-10-03 08:52:37.855 - error: zigbee.0 (27311) Error on send command to 0x00124b001f7a9475. Error: Error: Command 0x00124b001f7a9475/11 genLevelCtrl.moveToLevelWithOnOff({"level":76,"transtime":0}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'undefined' (26))
--
at ZStackAdapter. (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:657:27)
at Generator.next ()
at fulfilled (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
2020-10-03 08:52:38.619 - error: zigbee.0 (27311) Error on send command to 0x00124b001f7a9475. Error: Error: Command 0x00124b001f7a9475/11 genLevelCtrl.moveToLevelWithOnOff({"level":50,"transtime":0}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'undefined' (26))
at ZStackAdapter. (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:657:27)
at Generator.next ()
at fulfilled (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
2020-10-03 09:06:00.105 - info: host.raspberrypi instance system.adapter.yr.0 started with pid 23807
2020-10-03 09:06:03.335 - info: yr.0 (23807) starting. Version 2.0.3 in /opt/iobroker/node_modules/iobroker.yr, node: v12.18.4, js-controller: 3.1.6

**Comment by asgothian** [comment]
- Is this also linked to an Ikea Tradfri outlet ?
- can you please put the log snippets in code tags, it is very hard to read otherwise.
- does the adapter restart or just report an error ?
