### ISSUE TITLE
Groups' states are not writable

### ISSUE THREAD

**Issue by A4E** [ioBroker/ioBroker.zigbee#781]
Running iobroker.zigbee 1.2.1 (installed from GitHub) on js-controller 3.1.6 (Windows, NodeJS 10.17.0), iobroker.javascript 4.8.2 getting errors like this when trying to modify any Zigbee group state:

```
zigbee.0 (3976) Error on send command to 6. Error: TypeError: definition is not iterable
    at Object.getMetaValue (C:\iobroker\iobroker\node_modules\zigbee-herdsman-converters\converters\utils.js:251:34)
    at Object.convertSet (C:\iobroker\iobroker\node_modules\zigbee-herdsman-converters\converters\toZigbee.js:485:49)
    at stateList.forEach (C:\iobroker\iobroker\node_modules\iobroker.zigbee\main.js:373:48)
    at Array.forEach (<anonymous>)
    at Zigbee.publishFromState (C:\iobroker\iobroker\node_modules\iobroker.zigbee\main.js:317:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by A4E** [comment]
It is interesting that setting colortemp to group raises the same error, but color temperature actually changes

**Comment by A4E** [comment]
Thanks, all working now
