### ISSUE TITLE
Heiman Smoke Detectors HS1SA incorrectly recognised as HS3SA - config error messages

### ISSUE THREAD

**Issue by martinschm** [ioBroker/ioBroker.zigbee#802]
Hi,

I paired a Heiman HS**1**SA smoke detector and the device is shown as a HS**3**SA in the adapter configuration

![image](https://user-images.githubusercontent.com/39886158/94849444-b8766500-0425-11eb-8d89-d6dfd53b238e.png)

Additionally I get this error message:
2020-10-01 20:20:02.431 - error: zigbee.0 (1160) DeviceConfigure failed 0x00158d0004b487d4 SmokeSensor-N-3.0, attempt 1 (Error: Bind 0x00158d0004b487d4/1 genPowerCfg from '0x00124b001caab658/1' failed (AREQ - ZDO - bindRsp after 10000ms)

**Comment by martinschm** [comment]
Maybe this helps as well


2020-10-01 20:18:15.520 - info: zigbee.0 (1131) Starting interview of '0x00158d0004b487d4'
--
2020-10-01 20:18:41.818 - info: zigbee.0 (1131) Successfully interviewed '0x00158d0004b487d4', device has succesfully been paired
2020-10-01 20:18:41.819 - info: zigbee.0 (1131) Device '0x00158d0004b487d4' is supported, identified as: HEIMAN Smoke detector (HS3SA)
2020-10-01 20:18:41.821 - info: zigbee.0 (1131) Configuring 0x00158d0004b487d4 SmokeSensor-N-3.0
2020-10-01 20:18:59.874 - info: zigbee.0 (1131) Zigbee: stop joining
2020-10-01 20:19:17.396 - error: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2020-10-01 20:19:17.397 - error: zigbee.0 (1131) unhandled promise rejection: Command 0x00158d0004b487d4/1 ssIasZone.enrollRsp({"enrollrspcode":0,"zoneid":23}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'No network route' (205))
2020-10-01 20:19:17.398 - error: zigbee.0 (1131) Error: Command 0x00158d0004b487d4/1 ssIasZone.enrollRsp({"enrollrspcode":0,"zoneid":23}, {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Data request failed with error: 'No network route' (205))
at ZStackAdapter. (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:309:27)
at Generator.next ()
at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:24:58)
2020-10-01 20:19:17.399 - info: zigbee.0 (1131) cleaned everything up...
2020-10-01 20:19:17.401 - info: zigbee.0 (1131) Zigbee: disabling joining new devices.

**Comment by martinschm** [comment]
I paired a few more devices. They are all labelled as HS1SA-E (Zigbee 3.0 version) which is supported by Zigbee2Mqtt (https://www.zigbee2mqtt.io/devices/HS1SA-M.html) but they are all recognised as MS3SA devices

**Comment by asgothian** [comment]
- The Error you posted refers to the smoke detector not actually being known to the network (No network route), i.e. the coordinator does not know where to send the request to. The "unhandled promise rejection" part will be fixed to ensure the adapter does not crash, but if the underlying condition (No network route) remains the unit may still not operate as desired.
- The Smoke detector is referenced as HS3SA because the device reports a string which is mapped to the HS3SA model to the zigbee network. (SmokeSensor-N-3.0). This needs to be corrected in the zigbee_herdsman_converters. Please open an issue there (https://github.com/Koenkk/zigbee-herdsman-converters)

**Comment by martinschm** [comment]
Hi @asgothian ,

thanks for the quick reply. Will take another go in a few minutes trying to integrate those two "unwilling" smoke detectors.

Thanks for taking care of the "unhandled promise rejection", and of course I understand that the error will still occur if there is a network problem.

Regarding the mapping, I created an issue on the herdsman-converter github: https://github.com/Koenkk/zigbee-herdsman-converters/issues/1632

**Comment by martinschm** [comment]
I tried to add the two "unwilling" smoke detectors and saw in the log that there are entries for already integrated smoke detectors as well:

`
zigbee.0 | 2020-10-06 12:50:58.909 | error | (3986468) DeviceConfigure failed 0x00158d0004fcf946 SmokeSensor-N-3.0, attempt 1 (Error: Bind 0x00158d0004fcf946/1 genPowerCfg from '0x00124b001caab658/1' failed (AREQ - ZDO - bindRsp after 10000ms)
-- | -- | -- | --
zigbee.0 | 2020-10-06 12:50:48.861 | info | (3986468) Configuring 0x00158d0004fcf946 SmokeSensor-N-3.0
`

Is this related to the smoke detector being recognised as a different device (HS3SA instead of HS1SA)? 
I was surprised to see that there was an attempt to configre the device which seems to be added correctly already.
![image](https://user-images.githubusercontent.com/39886158/95193513-36df5800-07d4-11eb-9ae9-e9baccf64968.png)

**Comment by asgothian** [comment]
Possibly, yes. It depends if the device with that ID is a HS1SA or a HS3SA. They differ in how they are supposed to be configured, so if the device is wrongly identified, it will not accept the configuration attempt.

A.
