### ISSUE TITLE
Support for Dimmer TS110F and Relay/Switch TYZB01

### ISSUE THREAD

**Issue by FotoFieber** [ioBroker/ioBroker.zigbee#820]
The switch (1 gang) is mapped to a ZM-L03E-Z (a 3 button switch) and can be used with this mapping. But I get errors:

```
zigbee.0 | 2020-10-20 08:28:16.118 | error | at async DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:105:17))
-- | -- | -- | --
zigbee.0 | 2020-10-20 08:28:16.118 | error | at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices.js:9530:19)
zigbee.0 | 2020-10-20 08:28:16.118 | error | at bind (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices.js:43:24)
zigbee.0 | 2020-10-20 08:28:16.118 | error | (605) DeviceConfigure failed 0x842e14fffee0d70d TS0003, attempt 5 (TypeError: Cannot read property 'bind' of undefined
```

The dimmer is shown in the ^Geräte' tab with a '?' icon. Under information, the type of the device seems correct. But no objects are created. Learning it, I got following Log:
```zigbee.0	2020-10-20 08:08:05.569	error	(605) Device 0xbc33acfffe6562ff "TS110F" not described in statesMapping.
zigbee.0	2020-10-20 08:08:05.230	error	at async DeviceConfigure.onZigbeeStarted (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:42:21))
zigbee.0	2020-10-20 08:08:05.230	error	at async DeviceConfigure.configure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:105:17)
zigbee.0	2020-10-20 08:08:05.230	error	at Object.configure (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices.js:9530:19)
zigbee.0	2020-10-20 08:08:05.230	error	at bind (/opt/iobroker/node_modules/zigbee-herdsman-converters/devices.js:43:24)
```

Here my system information:
Node.js v12.19.0
NPM 6.14.8
raspberrypi 3b+
zigbee adapter 1.2.1
admin 4.0.10

**Comment by FotoFieber** [comment]
Added dimmer with
`
    {
        models: ['TS110F'],
        icon: 'img/sunricher_dimmer.png',
        states: lightStates,
        linkedStates: [comb.brightnessAndState],
    },
`

Wrong ICON and only one dimmer but it seems to work for my purpose.

**Comment by FotoFieber** [comment]
The TS0003 model is used by different devices from different manufacturers. There is no easy fix for this, as the libraries the zibgee adapter is based on, don't support this.
