### ISSUE TITLE
ioBroker.zigbee Adapter crashes after some time of inactivity

### ISSUE THREAD

**Issue by Mr-Bubbles** [ioBroker/ioBroker.zigbee#845]
Hello,
I have a problem where the Adapter seems to hang when not being used for some time, for example first time use of a switch after some hours of no zigbee activity crashes the Adapter in iOBroker. After it restarts everything works fine until the next day.

I'm using:
iOBroker: 3.1.6 
Node-JS: 12.19.0
ioBroker.zigbee: 1.2.1 with a CC2531

```
info.0	2020-11-09 10:04:02.264	info	(2980) Popup news was read...
zigbee.0	2020-11-09 09:47:10.414	info	(3171) Zigbee started
zigbee.0	2020-11-09 09:47:10.414	info	(3171) 0x000d6ffffea83f84 (addr 51855): E1746 - IKEA TRADFRI signal repeater (Router)
zigbee.0	2020-11-09 09:47:10.413	info	(3171) 0xccccccfffee4d063 (addr 50850): E1743 - IKEA TRADFRI ON/OFF switch (EndDevice)
zigbee.0	2020-11-09 09:47:10.412	info	(3171) 0x000b57fffe32ac54 (addr 42654): E1524/E1810 - IKEA TRADFRI remote control (EndDevice)
zigbee.0	2020-11-09 09:47:10.410	info	(3171) Currently 3 devices are joined:
zigbee.0	2020-11-09 09:47:10.403	info	(3171) --> transmitPower : normal
zigbee.0	2020-11-09 09:47:10.394	info	(3171) Coordinator firmware version: {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}
zigbee.0	2020-11-09 09:47:08.448	info	(3171) Starting Zigbee...
zigbee.0	2020-11-09 09:47:08.430	info	(3171) starting. Version 1.2.1 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.19.0, js-controller: 3.1.6
host.iobroker	2020-11-09 09:47:06.877	info	instance system.adapter.zigbee.0 started with pid 3171
host.iobroker	2020-11-09 09:46:36.862	info	Restart adapter system.adapter.zigbee.0 because enabled
host.iobroker	2020-11-09 09:46:36.860	info	instance system.adapter.zigbee.0 terminated with code 0 (NO_ERROR)
zigbee.0	2020-11-09 09:46:36.344	info	(9075) Terminated (NO_ERROR): Without reason
zigbee.0	2020-11-09 09:46:36.343	info	(9075) terminating
zigbee.0	2020-11-09 09:46:36.089	info	(9075) Zigbee: disabling joining new devices.
zigbee.0	2020-11-09 09:46:36.089	info	(9075) cleaned everything up...
zigbee.0	2020-11-09 09:46:36.088	error	at Generator.next (<anonymous>)
zigbee.0	2020-11-09 09:46:36.088	error	at Controller.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/controller.js:426:37)
zigbee.0	2020-11-09 09:46:36.088	error	at GreenPower.onZclGreenPowerData (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/greenPower.js:66:16)
zigbee.0	2020-11-09 09:46:36.088	error	at __awaiter (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/greenPower.js:23:12)
zigbee.0	2020-11-09 09:46:36.088	error	at new Promise (<anonymous>)
zigbee.0	2020-11-09 09:46:36.088	error	at /opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/greenPower.js:27:71
zigbee.0	2020-11-09 09:46:36.088	error	at Generator.next (<anonymous>)
zigbee.0	2020-11-09 09:46:36.088	error	at GreenPower.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/greenPower.js:69:34)
zigbee.0	2020-11-09 09:46:36.088	error	at GreenPower.encryptSecurityKey (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/greenPower.js:62:34)
zigbee.0	2020-11-09 09:46:36.088	error	at Cipheriv.update (internal/crypto/cipher.js:155:11)
zigbee.0	2020-11-09 09:46:36.088	error	(9075) TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
zigbee.0	2020-11-09 09:46:36.088	error	(9075) unhandled promise rejection: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
Unhandled	2020-11-09 09:46:36.088	error	promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
info.0	2020-11-09 09:34:02.293	info	(2980) Popup news was read...```

**Comment by arteck** [comment]
stable is 1.3.1 ..plz install this version
