### ISSUE TITLE
 OSRAM Motion Sensor-A can not configure in 1.2.1

### ISSUE THREAD

**Issue by hoepps2802** [ioBroker/ioBroker.zigbee#846]
In Version 1.0.0 it still work

2020-11-09 20:48:45.842 - error: zigbee.0 (23983) Failed to interview '0x000d6f000fbf9d65', device has not succesfully been paired. undefined
--
2020-11-09 20:48:48.772 - info: zigbee.0 (23983) Configuring 0x000d6f000fbf9d65 Motion Sensor-A
2020-11-09 20:48:52.884 - error: zigbee.0 (23983) Failed to configure 0x000d6f000fbf9d65 Motion Sensor-A, attempt 1 (Error: ConfigureReporting 0x000d6f000fbf9d65/1 genPowerCfg([{"attribute":"batteryPercentageRemaining","minimumReportInterval":3600,"maximumReportInterval":62000,"reportableChange":0}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'UNSUPPORTED_ATTRIBUTE')
at Endpoint. (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
at Generator.next ()
at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58))
2020-11-09 20:48:53.889 - info: zigbee.0 (23983) Configuring 0x000d6f000fbf9d65 Motion Sensor-A
2020-11-09 20:48:57.936 - error: zigbee.0 (23983) Failed to configure 0x000d6f000fbf9d65 Motion Sensor-A, attempt 2 (Error: ConfigureReporting 0x000d6f000fbf9d65/1 genPowerCfg([{"attribute":"batteryPercentageRemaining","minimumReportInterval":3600,"maximumReportInterval":62000,"reportableChange":0}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'UNSUPPORTED_ATTRIBUTE')
at Endpoint. (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
at Generator.next ()
at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58))
2020-11-09 20:49:00.545 - info: zigbee.0 (23983) Configuring 0x000d6f000fbf9d65 Motion Sensor-A
2020-11-09 20:49:03.947 - error: zigbee.0 (23983) Failed to configure 0x000d6f000fbf9d65 Motion Sensor-A, attempt 3 (Error: ConfigureReporting 0x000d6f000fbf9d65/1 genPowerCfg([{"attribute":"batteryPercentageRemaining","minimumReportInterval":3600,"maximumReportInterval":62000,"reportableChange":0}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'UNSUPPORTED_ATTRIBUTE')
at Endpoint. (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
at Generator.next ()
at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58))
2020-11-09 20:49:29.954 - info: zigbee.0 (23983) Zigbee: stop joining
2020-11-09 20:49:30.193 - info: zigbee.0 (23983) Configuring 0x000d6f000fbf9d65 Motion Sensor-A
2020-11-09 20:49:34.237 - error: zigbee.0 (23983) Failed to configure 0x000d6f000fbf9d65 Motion Sensor-A, attempt 4 (Error: ConfigureReporting 0x000d6f000fbf9d65/1 genPowerCfg([{"attribute":"batteryPercentageRemaining","minimumReportInterval":3600,"maximumReportInterval":62000,"reportableChange":0}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'UNSUPPORTED_ATTRIBUTE')
at Endpoint. (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
at Generator.next ()
at fulfilled (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58))

**Comment by arteck** [comment]
install new version
