### ISSUE TITLE
Busch Jäger 6735/6736/6737 - Busch-Jaeger RM01 Brightness Error

### ISSUE THREAD

**Issue by Newan** [ioBroker/ioBroker.zigbee#854]
Hello,

in the new Version 1.3 the Brightness of the Busch Jäger not working

`
zigbee.0 | 2020-11-14 21:02:57.495 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
-- | -- | -- | --
zigbee.0 | 2020-11-14 21:02:57.495 | error | at runMicrotasks (<anonymous>)
zigbee.0 | 2020-11-14 21:02:57.495 | error | at /opt/iobroker/node_modules/iobroker.zigbee/main.js:373:48
zigbee.0 | 2020-11-14 21:02:57.495 | error | at Object.convertSet (/opt/iobroker/node_modules/zigbee-herdsman-converters/converters/toZigbee.js:2465:58)
zigbee.0 | 2020-11-14 21:02:57.495 | error | (12666) Error on send command to 0xd85def11a10046b1. Error: TypeError: Cannot read property 'convertSet' of undefined
`

I dont know where the Problem cames from, this Adapter oder the zigbee-herdsman-converters lib?

**Comment by Newan** [comment]
just for info, the function light_onoff_brightness works

**Comment by Newan** [comment]
Please Update to fix:

https://github.com/Koenkk/zigbee-herdsman-converters/commit/ab02e1f6c1ca39faecb9b1e4c7a336b993493240
