### ISSUE TITLE
Error in module, cause by double quote

### ISSUE THREAD

**Issue by modmax** [ioBroker/ioBroker.zigbee#918]
There is an error in the actual code, cause by a double quote, which leads to a compiler error.

`

2020-12-30 16:16:00.598  - error: host.tigger Caught by controller[0]: /work/iobroker/node_modules/iobroker.zigbee/lib/devices.js:390
--
2020-12-30 16:16:00.599  - error: host.tigger Caught by controller[0]:         models: ['WXKG02LM',''WXKG02LM_rev2'],
2020-12-30 16:16:00.599  - error: host.tigger Caught by controller[0]:                               ^^^^^^^^^^^^^
2020-12-30 16:16:00.599  - error: host.tigger Caught by controller[0]: SyntaxError: Unexpected identifier
2020-12-30 16:16:00.599  - error: host.tigger Caught by controller[0]:     at wrapSafe (internal/modules/cjs/loader.js:915:16)
2020-12-30 16:16:00.599  - error: host.tigger Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:963:27)
2020-12-30 16:16:00.599  - error: host.tigger Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2020-12-30 16:16:00.599  - error: host.tigger Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:863:32)
2020-12-30 16:16:00.599  - error: host.tigger Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2020-12-30 16:16:00.599  - error: host.tigger Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:887:19)
2020-12-30 16:16:00.600  - error: host.tigger Caught by controller[0]:     at require (internal/modules/cjs/helpers.js:74:18)
2020-12-30 16:16:00.600  - error: host.tigger Caught by controller[0]:     at Object. (/work/iobroker/node_modules/iobroker.zigbee/lib/commands.js:4:23)
2020-12-30 16:16:00.600  - error: host.tigger Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
2020-12-30 16:16:00.600  - error: host.tigger Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2020-12-30 16:16:00.600  - error: host.tigger instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
`

**Comment by o0shojo0o** [comment]
#919

**Comment by o0shojo0o** [comment]
Use the latest version from git, and check if your bug is fixed.
If the bug is fixed please close the issues.
