### ISSUE TITLE
Depencies unmet with a fresh install of V 1.4.2

### ISSUE THREAD

**Issue by Grothesk242** [ioBroker/ioBroker.zigbee#931]
When not installed 
```
npm list
```
ist clear. As soon as I install V 1.4.2 the dependencies get cluttered: 

```
npm ERR! peer dep missing: typedoc@>=0.19.0 < 0.20.0, required by typedoc-plugin-markdown@3.1.1
npm ERR! peer dep missing: typedoc@>=0.16.0, required by typedoc-plugin-no-inherit@1.2.0
npm ERR! peer dep missing: typedoc@>=0.16.0, required by typedoc-plugin-sourcefile-url@1.0.6
npm ERR! extraneous: @babel/cli@7.12.10 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@babel/cli
npm ERR! extraneous: @babel/preset-env@7.12.11 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@babel/preset-envnpm ERR! extraneous: @babel/preset-typescript@7.12.7 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@babel/preset-typescript
npm ERR! extraneous: @types/debounce@1.2.0 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@types/debounce
npm ERR! extraneous: @types/debug@4.1.5 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@types/debug
npm ERR! extraneous: @types/jest@26.0.19 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@types/jest
npm ERR! extraneous: @types/nedb@1.8.11 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@types/nedb
npm ERR! extraneous: @types/serialport@8.0.1 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@types/serialport
npm ERR! extraneous: @typescript-eslint/eslint-plugin@4.11.0 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@typescript-eslint/eslint-plugin
npm ERR! extraneous: @typescript-eslint/parser@4.11.0 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@typescript-eslint/parser
npm ERR! extraneous: eslint@7.16.0 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/eslint
npm ERR! extraneous: jest@26.6.3 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/jest
npm ERR! extraneous: typedoc-plugin-markdown@3.1.1 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/typedoc-plugin-markdown
npm ERR! extraneous: typedoc-plugin-no-inherit@1.2.0 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/typedoc-plugin-no-inherit
npm ERR! extraneous: typedoc-plugin-sourcefile-url@1.0.6 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/typedoc-plugin-sourcefile-url
npm ERR! extraneous: typescript@4.1.3 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/typescript
npm ERR! extraneous: eslint@7.16.0 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/eslint
npm ERR! extraneous: eslint-config-google@0.14.0 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/eslint-config-google
npm ERR! extraneous: eslint-plugin-jest@24.1.3 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/eslint-plugin-jest
npm ERR! extraneous: jest@26.6.3 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/jest
npm ERR! peer dep missing: typedoc@>=0.19.0 < 0.20.0, required by typedoc-plugin-markdown@3.1.0
npm ERR! peer dep missing: typedoc@>=0.16.0, required by typedoc-plugin-no-inherit@1.2.0
npm ERR! peer dep missing: typedoc@>=0.16.0, required by typedoc-plugin-sourcefile-url@1.0.6
npm ERR! extraneous: @babel/cli@7.12.8 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/@babel/cli
npm ERR! extraneous: @babel/preset-env@7.12.7 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/@babel/preset-env
npm ERR! extraneous: @babel/preset-typescript@7.12.7 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/@babel/preset-typescript
npm ERR! extraneous: @types/debounce@1.2.0 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/@types/debounce
npm ERR! extraneous: @types/debug@4.1.5 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/@types/debug
npm ERR! extraneous: @types/jest@26.0.18 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/@types/jest
npm ERR! extraneous: @types/nedb@1.8.11 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/@types/nedb
npm ERR! extraneous: @types/serialport@8.0.1 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/@types/serialport
npm ERR! extraneous: @typescript-eslint/eslint-plugin@4.9.1 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/@typescript-eslint/eslint-plugin
npm ERR! extraneous: @typescript-eslint/parser@4.9.1 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/@typescript-eslint/parser
npm ERR! extraneous: eslint@7.15.0 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/eslint
npm ERR! extraneous: jest@26.6.3 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/jest
npm ERR! extraneous: typedoc-plugin-markdown@3.1.0 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/typedoc-plugin-markdown
npm ERR! extraneous: typedoc-plugin-no-inherit@1.2.0 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/typedoc-plugin-no-inherit
npm ERR! extraneous: typedoc-plugin-sourcefile-url@1.0.6 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/typedoc-plugin-sourcefile-url
npm ERR! extraneous: typescript@4.1.2 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/typescript
```

This is 
```
 node -v && npm -v
v14.15.4
6.14.10
```

Is zigbee-herdsman and zigbee-herdsman-converters a little bit awkward in its depencies?

**Comment by Grothesk242** [comment]
When starting the adapter it issues these errors to the log file: 

```
2021-01-09 13:52:22.381  - info: zigbee.0 (1981) starting. Version 1.4.2 in /opt/iobroker/node_modules/iobroker.zigbee, node: v14.15.4, js-controller: 3.2.3
2021-01-09 13:52:25.020  - info: zigbee.0 (1981) Starting Zigbee  npm ...
2021-01-09 13:52:25.253  - info: zigbee.0 (1981) Installed Version: iobroker.zigbee@1.4.2
2021-01-09 13:52:36.399  - error: zigbee.0 (1981) Failed to start Zigbee
2021-01-09 13:52:36.400  - error: zigbee.0 (1981) TIMEOUT
2021-01-09 13:52:46.401  - info: zigbee.0 (1981) Try to reconnect. 1 attempts left
2021-01-09 13:52:46.402  - info: zigbee.0 (1981) Starting Zigbee  npm ...
2021-01-09 13:52:46.424  - info: zigbee.0 (1981) Installed Version: iobroker.zigbee@1.4.2
2021-01-09 13:52:46.568  - error: zigbee.0 (1981) Failed to start Zigbee
2021-01-09 13:52:46.569  - error: zigbee.0 (1981) Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at Driver.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:157:28)
    at Generator.next (<anonymous>)
    at /opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:4:12)
    at SerialPort.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/driver/driver.js:155:45)
    at SerialPort._error (/opt/iobroker/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
2021-01-09 13:52:47.516  - error: zigbee.0 (1981) uncaught exception: Port is not open
2021-01-09 13:52:47.517  - error: zigbee.0 (1981) Error: Port is not open
    at unixWrite (/opt/iobroker/node_modules/zigbee-herdsman/node_modules/@serialport/bindings/lib/unix-write.js:25:15)
    at async /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@serialport/bindings/lib/linux.js:72:7
2021-01-09 13:52:47.517  - error: zigbee.0 (1981) Port is not open
2021-01-09 13:52:47.594  - info: zigbee.0 (1981) cleaned everything up...
2021-01-09 13:52:47.597  - info: zigbee.0 (1981) Zigbee: disabling joining new devices.
2021-01-09 13:52:48.097  - info: zigbee.0 (1981) terminating
2021-01-09 13:52:48.098  - warn: zigbee.0 (1981) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-01-09 13:52:48.685  - error: host.raspberrypi instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-01-09 13:52:48.691  - info: host.raspberrypi Restart adapter system.adapter.zigbee.0 because enabled
```

**Comment by asgothian** [comment]
Zigbee-Herdsman, Zigbee-Herdsman-Converters and ioBroker.zigbee have not moved to Node 14 yet. It is unclear at this moment if all libraries and components in use support node 14.

Please downgrade to node 12.xx and verify if the error persists.

A.

**Comment by Grothesk242** [comment]
Still missing dependencies with nodeJS 12: 

```
npm ERR! peer dep missing: typedoc@>=0.19.0 < 0.20.0, required by typedoc-plugin-markdown@3.1.1
npm ERR! peer dep missing: typedoc@>=0.16.0, required by typedoc-plugin-no-inherit@1.2.0
npm ERR! peer dep missing: typedoc@>=0.16.0, required by typedoc-plugin-sourcefile-url@1.0.6
npm ERR! extraneous: @babel/cli@7.12.10 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@babel/cli
npm ERR! extraneous: @babel/preset-env@7.12.11 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@babel/preset-env
npm ERR! extraneous: @babel/preset-typescript@7.12.7 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@babel/preset-typescript
npm ERR! extraneous: @types/debounce@1.2.0 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@types/debounce
npm ERR! extraneous: @types/debug@4.1.5 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@types/debug
npm ERR! extraneous: @types/jest@26.0.19 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@types/jest
npm ERR! extraneous: @types/nedb@1.8.11 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@types/nedb
npm ERR! extraneous: @types/serialport@8.0.1 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@types/serialport
npm ERR! extraneous: @typescript-eslint/eslint-plugin@4.11.0 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@typescript-eslint/eslint-plugin
npm ERR! extraneous: @typescript-eslint/parser@4.11.0 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/@typescript-eslint/parser
npm ERR! extraneous: eslint@7.16.0 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/eslint
npm ERR! extraneous: jest@26.6.3 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/jest
npm ERR! extraneous: typedoc-plugin-markdown@3.1.1 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/typedoc-plugin-markdown
npm ERR! extraneous: typedoc-plugin-no-inherit@1.2.0 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/typedoc-plugin-no-inherit
npm ERR! extraneous: typedoc-plugin-sourcefile-url@1.0.6 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/typedoc-plugin-sourcefile-url
npm ERR! extraneous: typescript@4.1.3 /opt/iobroker/node_modules/zigbee-herdsman/node_modules/typescript
npm ERR! extraneous: eslint@7.16.0 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/eslint
npm ERR! extraneous: eslint-config-google@0.14.0 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/eslint-config-google
npm ERR! extraneous: eslint-plugin-jest@24.1.3 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/eslint-plugin-jest
npm ERR! extraneous: jest@26.6.3 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/jest
npm ERR! peer dep missing: typedoc@>=0.19.0 < 0.20.0, required by typedoc-plugin-markdown@3.1.0
npm ERR! peer dep missing: typedoc@>=0.16.0, required by typedoc-plugin-no-inherit@1.2.0
npm ERR! peer dep missing: typedoc@>=0.16.0, required by typedoc-plugin-sourcefile-url@1.0.6
npm ERR! extraneous: @babel/cli@7.12.8 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/@babel/cli
npm ERR! extraneous: @babel/preset-env@7.12.7 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/@babel/preset-env
npm ERR! extraneous: @babel/preset-typescript@7.12.7 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/@babel/preset-typescript
npm ERR! extraneous: @types/debounce@1.2.0 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/@types/debounce
npm ERR! extraneous: @types/debug@4.1.5 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/@types/debug
npm ERR! extraneous: @types/jest@26.0.18 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/@types/jest
npm ERR! extraneous: @types/nedb@1.8.11 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/@types/nedb
npm ERR! extraneous: @types/serialport@8.0.1 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/@types/serialport
npm ERR! extraneous: @typescript-eslint/eslint-plugin@4.9.1 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/@typescript-eslint/eslint-plugin
npm ERR! extraneous: @typescript-eslint/parser@4.9.1 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/@typescript-eslint/parser
npm ERR! extraneous: eslint@7.15.0 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/eslint
npm ERR! extraneous: jest@26.6.3 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/jest
npm ERR! extraneous: typedoc-plugin-markdown@3.1.0 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/typedoc-plugin-markdown
npm ERR! extraneous: typedoc-plugin-no-inherit@1.2.0 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/typedoc-plugin-no-inherit
npm ERR! extraneous: typedoc-plugin-sourcefile-url@1.0.6 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/typedoc-plugin-sourcefile-url
npm ERR! extraneous: typescript@4.1.2 /opt/iobroker/node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/typescript
pi@raspberrypi:/opt/iobroker $ nodejs -v && npm -v
v12.20.1
6.14.10
```

**Comment by asgothian** [comment]
The missing dependencies issues is for the Zigbee-herdsman-converters or the Zigbee-Herdsman project. 
It is not an issue which we will deal with in this project.

Does the adapter still crash when you started or does it run fine now?

A.

**Comment by Grothesk242** [comment]
I'm now running node15, dependencies are met, all adapters up and running.

**Comment by asgothian** [comment]
> I'm now running node15, dependencies are met, all adapters up and running.

This does not answer my question - did the adapter run with Node 12 ? As far as i understand it, Node14 will be the next supported release, and Node 16 after that, due to the support strategy with NodeJs.

A.
