### ISSUE TITLE
Error during start with a CC2531 using a rasperry pi

### ISSUE THREAD

**Issue by MartinSchlender** [ioBroker/ioBroker.zigbee#946]
Hi,
I have problem for quite some time now (running 1.3.1 right now) but the problem exists since the beginning.
If I reboot the system for any reason the zigbee adapter will not start (check the attached log). Another reboot usually helps but sometimes I have to shutdown, go powerless and restart to fix the issue. Any ideas what the reason could be?
Thanks Martin

Hi,
ich habe ein komische Problem mit meinem CC2531 am Raspberry pi.
Wenn ich das System mal ausschalte oder reboote ist es meist so, dass der Zigbee Adapter sich nicht starten läßt (siehe angehängtes Log). Ein erneuter Reboot behebt meist das Problem (manchmal auch erst runterfahren, kurz warten und dann nochmal starten). Irgend jemand eine Idee an was das liegen könnte?
Danke und Gruß
Martin

`

```
2021-01-21 21:08:33.862  - [32minfo[39m: zigbee.0 (1513) Starting Zigbee  npm ...
  | 2021-01-21 21:08:38.642  - [32minfo[39m: web.0 (1498) ==>Connected system.user.admin from ::ffff:192.168.0.50
  | 2021-01-21 21:08:38.752  - [32minfo[39m: web.0 (1498) <==Disconnect system.user.admin from ::ffff:192.168.0.50 vis.0
  | 2021-01-21 21:08:39.964  - [32minfo[39m: web.0 (1498) ==>Connected system.user.admin from ::ffff:192.168.0.50
  | 2021-01-21 21:08:53.773  - [31merror[39m: zigbee.0 (1513) Failed to start Zigbee
  | 2021-01-21 21:08:53.776  - [31merror[39m: zigbee.0 (1513) Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
  | at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
  | at Generator.throw (<anonymous>)
  | at rejected (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
  | 2021-01-21 21:09:03.777  - [32minfo[39m: zigbee.0 (1513) Try to reconnect. 1 attempts left
  | 2021-01-21 21:09:03.780  - [32minfo[39m: zigbee.0 (1513) Starting Zigbee  npm ...
  | 2021-01-21 21:09:04.029  - [31merror[39m: zigbee.0 (1513) Failed to start Zigbee
  | 2021-01-21 21:09:04.030  - [31merror[39m: zigbee.0 (1513) Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
  | at Znp.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:136:32)
  | at Generator.next (<anonymous>)
  | at /opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:27:71
  | at new Promise (<anonymous>)
  | at __awaiter (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:23:12)
  | at SerialPort.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:134:49)
  | at SerialPort._error (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
  | at /opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
  | 2021-01-21 21:09:21.782  - [32minfo[39m: host.raspberrypi stopInstance system.adapter.zigbee.0 (force=false, process=true)
  | 2021-01-21 21:09:21.791  - [32minfo[39m: host.raspberrypi stopInstance system.adapter.zigbee.0 send kill signal
  | 2021-01-21 21:09:21.798  - [32minfo[39m: zigbee.0 (1513) Got terminate signal TERMINATE_YOURSELF
  | 2021-01-21 21:09:21.800  - [32minfo[39m: zigbee.0 (1513) cleaned everything up...
  | 2021-01-21 21:09:21.806  - [32minfo[39m: zigbee.0 (1513) Zigbee: disabling joining new devices.
  | 2021-01-21 21:09:21.809  - [31merror[39m: zigbee.0 (1513) Failed to stop zigbee (TypeError: Cannot read property 'getEntries' of null
  | at Function.loadFromDatabaseIfNecessary (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/group.js:76:55)
  | at Function.all (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/group.js:88:15)
  | at Controller.databaseSave (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/controller.js:219:45)
  | at Controller.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/controller.js:200:18)
  | at Generator.next (<anonymous>)
  | at /opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/controller.js:27:71
  | at new Promise (<anonymous>)
  | at __awaiter (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/controller.js:23:12)
  | at Controller.stop (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/controller.js:199:16)
  | at ZigbeeController.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:308:33))
  | 2021-01-21 21:09:21.810  - [32minfo[39m: zigbee.0 (1513) terminating
  | 2021-01-21 21:09:21.812  - [32minfo[39m: zigbee.0 (1513) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
  | 2021-01-21 21:09:21.813  - [31merror[39m: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
  | 2021-01-21 21:09:21.814  - [31merror[39m: zigbee.0 (1513) unhandled promise rejection: Cannot read property 'getEntries' of null
  | 2021-01-21 21:09:21.818  - [31merror[39m: zigbee.0 (1513) TypeError: Cannot read property 'getEntries' of null
  | at Function.loadFromDatabaseIfNecessary (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/device.js:216:55)
  | at Function.all (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/model/device.js:236:16)
  | at Controller.getDevices (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/controller/controller.js:252:31)
  | at ZigbeeController.getClients (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:201:49)
  | at DeviceAvailability.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceAvailability.js:120:43)
  | at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:187:42)
  | at ZigbeeController.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:304:20)
  | at Zigbee.onUnload (/opt/iobroker/node_modules/iobroker.zigbee/main.js:450:41)
  | at Zigbee.emit (events.js:314:20)
  | at stop (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8270:22)

```
`

**Comment by asgothian** [comment]
- When you restart - do you go powerless or is it a powered restart ?
- Will it also occur on an attempt to restart just the zigbee adapter ?
- what happens if you first stop the zigbee adapter and then restart the pi ?
A.

**Comment by MartinSchlender** [comment]
Hi Asothian,

very good questions. 
> * When you restart - do you go powerless or is it a powered restart ?
Both. Last time I had the problem I was powerless to backup the SD card and after the power up the adapter didn´t start. A restart of the adapter doesn´t work then. The same error occurs time and again. Then I just did a sudo reboot.

> * Will it also occur on an attempt to restart just the zigbee adapter ?
If it runs once I can also restart the adapter - no problem.

> * what happens if you first stop the zigbee adapter and then restart the pi ?

Didn´t try that. So you suggest alwas before shutdown or sudo reboot to manualle stop the zigbee adapter first?
Thanks
Martin
