### ISSUE TITLE
Crash with 'Can not read getDevice of Null' after failed pairing

### ISSUE THREAD

**Issue by Garfonso** [ioBroker/ioBroker.zigbee#986]
Today I tried to pair a new device, which failed (probably because I accidentially reseted the device, when it already was trying to join the network). After the pairing timeout was done, I wanted to try again, but accidentially hit the wrong butto, the "touchlink" one... 

Since then the zigbee Adapter is in a restart loop with the following output:

```
2021-02-13 20:15:13.459  - info: zigbee.0 (612070) Zigbee: allowing new devices to join.
2021-02-13 20:15:29.479  - info: zigbee.0 (612070) Starting interview of '0x7cb03eaa0a0ba529'
2021-02-13 20:15:30.225  - warn: zigbee.0 (612070) Failed to ping 0x7cb03eaa00ad01d2 Plug 01
2021-02-13 20:15:30.315  - warn: zigbee.0 (612070) Device '0x7cb03eaa0a0ba529' announced itself
2021-02-13 20:15:40.765  - error: zigbee.0 (612070) Failed to interview '0x7cb03eaa0a0ba529', device has not succesfully been paired. undefined
2021-02-13 20:16:02.536  - warn: zigbee.0 (612070) Failed to ping 0x001788010416a250 LCT015
2021-02-13 20:17:14.695  - info: zigbee.0 (612070) Zigbee: stop joining
2021-02-13 20:18:34.942  - info: zigbee.0 (612070) Zigbee: allowing new devices to join.
2021-02-13 20:18:34.943  - error: zigbee.0 (612070) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-02-13 20:18:34.943  - error: zigbee.0 (612070) unhandled promise rejection: Cannot execute command, in Inter-PAN mode
2021-02-13 20:18:34.943  - error: zigbee.0 (612070) Error: Cannot execute command, in Inter-PAN mode
    at ZStackAdapter.checkInterpanLock (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:879:19)
    at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:166:22)
    at /opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:27:71
    at __awaiter (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:23:12)
    at Object.func (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:165:44)
    at Queue.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/utils/queue.js:29:46)
    at /opt/iobroker/node_modules/zigbee-herdsman/dist/utils/queue.js:8:71
2021-02-13 20:18:34.944  - error: zigbee.0 (612070) Cannot execute command, in Inter-PAN mode
2021-02-13 20:18:34.947  - info: zigbee.0 (612070) cleaned everything up...
2021-02-13 20:18:34.947  - info: zigbee.0 (612070) Zigbee: disabling joining new devices.
2021-02-13 20:18:35.002  - error: zigbee.0 (612070) Failed to stop zigbee (Error: Cannot execute command, in Inter-PAN mode
    at ZStackAdapter.checkInterpanLock (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:879:19)
    at ZStackAdapter.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:452:22)
    at /opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:27:71
    at __awaiter (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:23:12)
    at Object.func (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:451:45)
    at Queue.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/utils/queue.js:29:46)
    at /opt/iobroker/node_modules/zigbee-herdsman/dist/utils/queue.js:8:71)
2021-02-13 20:18:35.002  - info: zigbee.0 (612070) terminating
2021-02-13 20:18:35.003  - warn: zigbee.0 (612070) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-02-13 20:18:35.724  - error: host.Server instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-02-13 20:18:35.724  - info: host.Server Restart adapter system.adapter.zigbee.0 because enabled
2021-02-13 20:19:05.731  - info: host.Server instance system.adapter.zigbee.0 started with pid 1974478
2021-02-13 20:19:06.136  - info: zigbee.0 (1974478) starting. Version 1.4.2 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.20.1, js-controller: 3.2.16
2021-02-13 20:19:06.174  - info: zigbee.0 (1974478) Starting Zigbee  npm ...
2021-02-13 20:19:06.225  - info: zigbee.0 (1974478) Installed Version: iobroker.zigbee@1.4.2
2021-02-13 20:19:07.943  - info: host.Server stopInstance system.adapter.zigbee.0 (force=false, process=true)
2021-02-13 20:19:07.945  - info: host.Server stopInstance system.adapter.zigbee.0 send kill signal
2021-02-13 20:19:07.945  - info: zigbee.0 (1974478) Got terminate signal TERMINATE_YOURSELF
2021-02-13 20:19:07.946  - info: zigbee.0 (1974478) cleaned everything up...
2021-02-13 20:19:07.948  - info: zigbee.0 (1974478) Zigbee: disabling joining new devices.
2021-02-13 20:19:07.949  - error: zigbee.0 (1974478) Failed to stop zigbee (TypeError: Cannot read property 'getEntries' of null
    at Function.loadFromDatabaseIfNecessary (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/group.js:76:55)
    at Function.all (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/group.js:88:15)
    at Controller.databaseSave (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/controller.js:222:45)
    at Controller.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/controller.js:203:18)
    at /opt/iobroker/node_modules/zigbee-herdsman/dist/controller/controller.js:27:71
    at __awaiter (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/controller.js:23:12)
    at Controller.stop (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/controller.js:202:16)
    at ZigbeeController.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:310:33))
2021-02-13 20:19:07.949  - info: zigbee.0 (1974478) terminating
2021-02-13 20:19:07.950  - info: zigbee.0 (1974478) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2021-02-13 20:19:07.950  - error: zigbee.0 (1974478) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-02-13 20:19:07.950  - error: zigbee.0 (1974478) unhandled promise rejection: Cannot read property 'getEntries' of null
2021-02-13 20:19:07.952  - error: zigbee.0 (1974478) TypeError: Cannot read property 'getEntries' of null
    at Function.loadFromDatabaseIfNecessary (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/device.js:216:55)
    at Function.all (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/device.js:236:16)
    at Controller.getDevices (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/controller.js:255:31)
    at ZigbeeController.getClients (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:203:49)
    at DeviceAvailability.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceAvailability.js:180:43)
    at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:189:42)
    at ZigbeeController.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:306:20)
    at Zigbee.onUnload (/opt/iobroker/node_modules/iobroker.zigbee/main.js:465:41)
2021-02-13 20:19:07.952  - error: zigbee.0 (1974478) Cannot read property 'getEntries' of null
2021-02-13 20:19:08.659  - info: host.Server instance system.adapter.zigbee.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2021-02-13 20:19:10.952  - info: host.Server instance system.adapter.zigbee.0 started with pid 1974492
2021-02-13 20:19:11.302  - info: zigbee.0 (1974492) starting. Version 1.4.2 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.20.1, js-controller: 3.2.16
2021-02-13 20:19:11.329  - info: zigbee.0 (1974492) Starting Zigbee  npm ...
2021-02-13 20:19:11.364  - info: zigbee.0 (1974492) Installed Version: iobroker.zigbee@1.4.2
2021-02-13 20:19:17.347  - error: zigbee.0 (1974492) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-02-13 20:19:17.347  - error: zigbee.0 (1974492) unhandled promise rejection: Cannot read property 'getDevice' of undefined
2021-02-13 20:19:17.348  - error: zigbee.0 (1974492) TypeError: Cannot read property 'getDevice' of undefined
    at Developer.sendToZigbee (/opt/iobroker/node_modules/iobroker.zigbee/lib/developer.js:103:49)
    at Developer.onMessage (/opt/iobroker/node_modules/iobroker.zigbee/lib/developer.js:46:26)
2021-02-13 20:19:17.348  - error: zigbee.0 (1974492) Cannot read property 'getDevice' of undefined
2021-02-13 20:19:17.352  - info: zigbee.0 (1974492) cleaned everything up...
2021-02-13 20:19:17.353  - info: zigbee.0 (1974492) Zigbee: disabling joining new devices.
2021-02-13 20:19:17.353  - error: zigbee.0 (1974492) Failed to stop zigbee (TypeError: Cannot read property 'getEntries' of null
    at Function.loadFromDatabaseIfNecessary (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/group.js:76:55)
    at Function.all (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/group.js:88:15)
    at Controller.databaseSave (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/controller.js:222:45)
    at Controller.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/controller.js:203:18)
    at /opt/iobroker/node_modules/zigbee-herdsman/dist/controller/controller.js:27:71
    at __awaiter (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/controller.js:23:12)
    at Controller.stop (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/controller.js:202:16)
    at ZigbeeController.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:310:33))
2021-02-13 20:19:17.354  - info: zigbee.0 (1974492) terminating
2021-02-13 20:19:17.354  - warn: zigbee.0 (1974492) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-02-13 20:19:17.354  - error: zigbee.0 (1974492) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-02-13 20:19:17.355  - error: zigbee.0 (1974492) unhandled promise rejection: Cannot read property 'getEntries' of null
2021-02-13 20:19:17.355  - error: zigbee.0 (1974492) TypeError: Cannot read property 'getEntries' of null
    at Function.loadFromDatabaseIfNecessary (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/device.js:216:55)
    at Function.all (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/device.js:236:16)
    at Controller.getDevices (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/controller.js:255:31)
    at ZigbeeController.getClients (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:203:49)
    at DeviceAvailability.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceAvailability.js:180:43)
    at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:189:42)
    at ZigbeeController.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:306:20)
    at Zigbee.onUnload (/opt/iobroker/node_modules/iobroker.zigbee/main.js:465:41)
2021-02-13 20:19:17.355  - error: zigbee.0 (1974492) Cannot read property 'getEntries' of null
2021-02-13 20:19:18.060  - error: host.Server instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-02-13 20:19:18.062  - info: host.Server Restart adapter system.adapter.zigbee.0 because enabled
2021-02-13 20:19:19.214  - info: host.Server "system.adapter.zigbee.0" disabled
2021-02-13 20:19:48.418  - error: zigbee.0 (1975237) adapter disabled
2021-02-13 20:19:48.421  - warn: zigbee.0 (1975237) Terminated (NO_ADAPTER_CONFIG_FOUND): Without reason
2021-02-13 20:19:49.138  - error: host.Server instance system.adapter.zigbee.0 terminated with code 3 (NO_ADAPTER_CONFIG_FOUND)
2021-02-13 20:19:49.138  - info: host.Server Do not restart adapter system.adapter.zigbee.0 because disabled or deleted
2021-02-13 20:20:00.034  - info: host.Server "system.adapter.zigbee.0" enabled
2021-02-13 20:20:00.042  - info: host.Server instance system.adapter.zigbee.0 started with pid 1975271
2021-02-13 20:20:00.390  - info: zigbee.0 (1975271) starting. Version 1.4.2 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.20.1, js-controller: 3.2.16
2021-02-13 20:20:00.412  - info: zigbee.0 (1975271) Starting Zigbee  npm ...
2021-02-13 20:20:00.450  - info: zigbee.0 (1975271) Installed Version: iobroker.zigbee@1.4.2
2021-02-13 20:20:05.693  - error: zigbee.0 (1975271) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-02-13 20:20:05.693  - error: zigbee.0 (1975271) unhandled promise rejection: Cannot read property 'getDevice' of undefined
2021-02-13 20:20:05.694  - error: zigbee.0 (1975271) TypeError: Cannot read property 'getDevice' of undefined
    at Developer.sendToZigbee (/opt/iobroker/node_modules/iobroker.zigbee/lib/developer.js:103:49)
    at Developer.onMessage (/opt/iobroker/node_modules/iobroker.zigbee/lib/developer.js:46:26)
2021-02-13 20:20:05.694  - error: zigbee.0 (1975271) Cannot read property 'getDevice' of undefined
2021-02-13 20:20:05.697  - info: zigbee.0 (1975271) cleaned everything up...
2021-02-13 20:20:05.698  - info: zigbee.0 (1975271) Zigbee: disabling joining new devices.
2021-02-13 20:20:05.699  - error: zigbee.0 (1975271) Failed to stop zigbee (TypeError: Cannot read property 'getEntries' of null
    at Function.loadFromDatabaseIfNecessary (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/group.js:76:55)
    at Function.all (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/group.js:88:15)
    at Controller.databaseSave (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/controller.js:222:45)
    at Controller.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/controller.js:203:18)
    at /opt/iobroker/node_modules/zigbee-herdsman/dist/controller/controller.js:27:71
    at __awaiter (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/controller.js:23:12)
    at Controller.stop (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/controller.js:202:16)
    at ZigbeeController.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:310:33))
2021-02-13 20:20:05.699  - info: zigbee.0 (1975271) terminating
2021-02-13 20:20:05.700  - warn: zigbee.0 (1975271) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-02-13 20:20:05.700  - error: zigbee.0 (1975271) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-02-13 20:20:05.700  - error: zigbee.0 (1975271) unhandled promise rejection: Cannot read property 'getEntries' of null
2021-02-13 20:20:05.700  - error: zigbee.0 (1975271) TypeError: Cannot read property 'getEntries' of null
    at Function.loadFromDatabaseIfNecessary (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/device.js:216:55)
    at Function.all (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/device.js:236:16)
    at Controller.getDevices (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/controller.js:255:31)
    at ZigbeeController.getClients (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:203:49)
    at DeviceAvailability.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceAvailability.js:180:43)
    at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:189:42)
    at ZigbeeController.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:306:20)
    at Zigbee.onUnload (/opt/iobroker/node_modules/iobroker.zigbee/main.js:465:41)
2021-02-13 20:20:05.701  - error: zigbee.0 (1975271) Cannot read property 'getEntries' of null
2021-02-13 20:20:06.396  - error: host.Server instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-02-13 20:20:06.396  - info: host.Server Restart adapter system.adapter.zigbee.0 because enabled
2021-02-13 20:20:06.396  - warn: host.Server Do not restart adapter system.adapter.zigbee.0 because restart loop detected
```

Might be related to #642

**Comment by asgothian** [comment]
There are a number of issues here. Please install the latest GitHub 1.4.3 version, then try again to start.

My expectation is that it will still not start, but the errors thrown should be limited to the relevant errors and not overshadowed by followup errors.

Afterwards, please unplug the zigbee coordinator, plug it back in and try again. It seems that the firmware is stuck in a loop and won't accept commands.

A.
